// MX-RUNTIME-01 runtime activation driver.
// Drives REAL platform HTTP endpoints (NOT raw SQL) to generate operational
// activity. ALL data is DEMO SEED: emails are @example.com, names prefixed
// "MX Demo". Idempotent: re-register collisions fall back to login.
//
// Usage: node runtime_driver.mjs <careerCount> <capadexCount> <compCount>
// Default: 100 50 20

const BASE = 'http://localhost:8080';
const [careerN, capadexN, compN] = [
  Number(process.argv[2] ?? 100),
  Number(process.argv[3] ?? 50),
  Number(process.argv[4] ?? 20),
];

const COMP_CODES = ['COG01','COG02','COM01','COM02','LEA01','EXE01','ADP01','ADP02','TEC01','EIQ01'];
const CONCERNS = ['exam stress','career confusion','low confidence','time management','peer pressure','focus problems'];
const PERSONAS = [['student',17],['student',20],['job_seeker',24],['career_seeker',29],['parent',41]];
const SKILLS = [['python','sql','excel'],['communication','leadership'],['java','spring'],['design','figma'],['marketing','seo']];

const rnd = (a) => a[Math.floor(Math.random() * a.length)];
const rint = (lo, hi) => lo + Math.floor(Math.random() * (hi - lo + 1));

function parseCookie(setCookie) {
  if (!setCookie) return '';
  return setCookie.split(',').map(c => c.split(';')[0].trim())
    .filter(c => c.includes('=')).join('; ');
}

async function reg(i) {
  const email = `mxrt_cand_${String(i).padStart(3,'0')}@example.com`;
  const [role, age] = rnd(PERSONAS);
  const body = { username: email, email, password: 'DemoSeed123!', fullName: `MX Demo Candidate ${i}`, role: role === 'student' ? 'career_seeker' : role };
  let r = await fetch(`${BASE}/api/register`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(body) });
  if (r.status === 400) {
    // already exists -> login
    r = await fetch(`${BASE}/api/login`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ username: email, password: 'DemoSeed123!' }) });
  }
  const cookie = parseCookie(r.headers.get('set-cookie'));
  const j = await r.json().catch(() => ({}));
  return { ok: r.ok, id: j.id, email, cookie, role, age };
}

async function saveProfile(c) {
  const skills = rnd(SKILLS);
  const body = { profile: {
    personal: { fullName: `MX Demo Candidate`, email: c.email, location: rnd(['Bengaluru','Mumbai','Delhi','Pune','Chennai']) },
    summary: 'Demo seed candidate profile generated by MX-RUNTIME-01 activation driver.',
    skills: { technical: skills },
    education: [{ degree: rnd(['BTech','BSc','BCom','MBA']), year: String(rint(2018,2025)) }],
    experience: [{ role: rnd(['Analyst','Engineer','Associate','Coordinator']), years: rint(0,6) }],
    projects: [{ name: 'Demo Project', impact: 'sample' }],
    source: 'Demo Seed',
  }};
  const r = await fetch(`${BASE}/api/cv/save-profile`, { method:'POST', headers:{'Content-Type':'application/json','Cookie':c.cookie}, body: JSON.stringify(body) });
  return r.ok;
}

async function addGoal(c) {
  const body = { title: rnd(['Become Data Scientist','Get promoted','Switch to Product','Improve communication']), description: 'Demo seed goal', deadline: '2026-12-31', category: 'career', source: 'Demo Seed' };
  const r = await fetch(`${BASE}/api/cv/goals`, { method:'POST', headers:{'Content-Type':'application/json','Cookie':c.cookie}, body: JSON.stringify(body) });
  return r.ok;
}

async function runCompetency(c) {
  const n = rint(5, 10);
  const scores = COMP_CODES.slice(0, n).map(code => ({ competencyCode: code, rawScore: rint(40,90), confidence: Math.round((0.6+Math.random()*0.4)*100)/100 }));
  const r1 = await fetch(`${BASE}/api/competency/run-assessment`, { method:'POST', headers:{'Content-Type':'application/json','Cookie':c.cookie}, body: JSON.stringify({ scores }) });
  const okScores = r1.ok;
  let okProfile = false;
  if (c.id) {
    const r2 = await fetch(`${BASE}/api/competency/profile/${c.id}`, { method:'POST', headers:{'Content-Type':'application/json','Cookie':c.cookie}, body: JSON.stringify({ currentRole: rnd(['Analyst','Engineer','Associate']), targetRole: rnd(['Data Scientist','Manager','Lead']), industry: 'Tech', careerStage: 'early', experienceYears: rint(0,6), tenureMonths: rint(3,48) }) });
    okProfile = r2.ok;
  }
  return { okScores, okProfile };
}

async function capadexCycle(guestEmail) {
  const concern = rnd(CONCERNS);
  const [, age] = rnd(PERSONAS);
  const start = await fetch(`${BASE}/api/capadex/session/start`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ concern_name: concern, user_age: age, guest_email: guestEmail }) });
  if (!start.ok) return { ok:false, stage:'start', status:start.status };
  const s = await start.json();
  const sid = s.session_id;
  const items = (s.questions || s.items || []);
  if (!sid || items.length === 0) return { ok:false, stage:'no_items' };
  const responses = items.map(q => ({ item_id: q.id || q.item_id, response_value: rint(1,5), response_time_ms: rint(1500,9000) }));
  const resp = await fetch(`${BASE}/api/capadex/session/${sid}/respond`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ responses }) });
  if (!resp.ok) return { ok:false, stage:'respond', status:resp.status };
  const comp = await fetch(`${BASE}/api/capadex/session/${sid}/complete`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({}) });
  if (!comp.ok) return { ok:false, stage:'complete', status:comp.status };
  return { ok:true, sid };
}

(async () => {
  const t0 = Date.now();
  const stats = { registered:0, profiles:0, goals:0, capadex:0, capadexFail:0, compScores:0, compProfiles:0 };
  const candidates = [];

  process.stdout.write(`[career] registering+profiling ${careerN} candidates...\n`);
  for (let i = 1; i <= careerN; i++) {
    const c = await reg(i);
    if (!c.ok && !c.id) { continue; }
    candidates.push(c);
    stats.registered++;
    if (await saveProfile(c)) stats.profiles++;
    if (await addGoal(c)) stats.goals++;
    if (i % 25 === 0) process.stdout.write(`  ..${i}\n`);
  }

  process.stdout.write(`[competency] ${compN} assessments...\n`);
  for (let i = 0; i < Math.min(compN, candidates.length); i++) {
    const r = await runCompetency(candidates[i]);
    if (r.okScores) stats.compScores++;
    if (r.okProfile) stats.compProfiles++;
  }

  process.stdout.write(`[capadex] ${capadexN} assessment completions...\n`);
  for (let i = 0; i < capadexN; i++) {
    const guest = candidates[i]?.email; // tie first N to candidates for identity linkage
    const r = await capadexCycle(guest);
    if (r.ok) stats.capadex++; else { stats.capadexFail++; if (stats.capadexFail <= 3) process.stdout.write(`  capadex fail: ${JSON.stringify(r)}\n`); }
    if ((i+1) % 25 === 0) process.stdout.write(`  ..${i+1}\n`);
  }

  stats.elapsedSec = Math.round((Date.now()-t0)/1000);
  process.stdout.write('\nRESULT ' + JSON.stringify(stats) + '\n');
})();
