/**
 * Clarity-question → master-bridge-tag classifier (shared, pure).
 *
 * Single source of truth for deriving `master_bridge_tag` from a clarity row's
 * `concern_id_prefix` (+ concern text fallback). Ports the resolution cascade
 * from `scripts/audit_clarity_questions.py` so the import route and the backfill
 * script land on byte-identical buckets as the offline audit pipeline.
 *
 * Resolution order (high → low precision):
 *   1. curated `PREFIX_TO_MASTER_BRIDGE[prefix]`           — high precision
 *   2. token-heuristic of concern text vs master vocab     — last resort
 *   3. 'UNMAPPED' sentinel                                 — admin curates later
 *
 * The resulting tag is the column the DB joins on:
 *   capadex_clarity_questions.master_bridge_tag = capadex_concerns_master.relational_bridge_tag
 */
import type { Pool } from 'pg';

export const UNMAPPED = 'UNMAPPED';

// Curated prefix → master bridge tag map. Mirrors PREFIX_TO_MASTER_BRIDGE in
// scripts/audit_clarity_questions.py — keep the two in lockstep.
export const PREFIX_TO_MASTER_BRIDGE: Record<string, string> = {
  // Career & employability cluster
  CAREER: 'CAREER_READINESS', CAR: 'CAREER_READINESS',
  CAREERVISION: 'CAREER_READINESS', CAREERUNCERT: 'CAREER_READINESS',
  CAREERCLAR: 'CAREER_READINESS', CAREERDIR: 'CAREER_READINESS',
  CAREERPLAN: 'CAREER_READINESS', CAREERCHOICE: 'CAREER_READINESS',
  CAREERAMB: 'CAREER_READINESS',
  CAREERTRANS: 'CAREER_GROWTH', CAREERPROG: 'CAREER_GROWTH',
  CAREERPIVOT: 'CAREER_GROWTH', CAREERREINVENT: 'CAREER_GROWTH',
  CAREERREBOUND: 'CAREER_GROWTH', CAREERSTAB: 'CAREER_GROWTH',
  CAREERGAP: 'CAREER_GROWTH', CAREERHARM: 'CAREER_GROWTH',
  CAREERP: 'CAREER_GROWTH', REINVENT: 'CAREER_GROWTH',
  REIN: 'CAREER_GROWTH', RESTART: 'CAREER_GROWTH',
  TRANSITION: 'CAREER_GROWTH', TRANS: 'CAREER_GROWTH',
  TRANSFER: 'CAREER_GROWTH', PIVOT: 'CAREER_GROWTH',
  REENTRY: 'CAREER_GROWTH', GROWTH: 'CAREER_GROWTH',
  REAPPLY: 'CAREER_GROWTH', REATTEMPT: 'CAREER_GROWTH',
  HR: 'CAREER_READINESS', EMP: 'EMPLOYABILITY',
  INTERVIEW: 'EMPLOYABILITY', INT: 'EMPLOYABILITY',
  INTERVIEWCONF: 'EMPLOYABILITY', IMPOSTERINT: 'EMPLOYABILITY',
  MOCK: 'EMPLOYABILITY', MOCKCONF: 'EMPLOYABILITY',
  JOB: 'EMPLOYABILITY', JOBSEARCH: 'EMPLOYABILITY',
  JOBDELAY: 'EMPLOYABILITY', PLACEMENT: 'EMPLOYABILITY',
  PLACE: 'EMPLOYABILITY', PLACEREJ: 'EMPLOYABILITY',
  PLAC: 'EMPLOYABILITY', OFFERDELAY: 'EMPLOYABILITY',
  EMPREAD: 'EMPLOYABILITY', HIRING: 'EMPLOYABILITY',
  FIRSTJOB: 'EMPLOYABILITY', UNEMP: 'EMPLOYABILITY',
  LAYOFF: 'EMPLOYABILITY', REJ: 'EMOTIONAL_RECOVERY',
  REJECTION: 'EMOTIONAL_RECOVERY', REC: 'EMOTIONAL_RECOVERY',
  RECOVERY: 'EMOTIONAL_RECOVERY', RECOV: 'EMOTIONAL_RECOVERY',
  RECOVER: 'EMOTIONAL_RECOVERY', TOXRECOV: 'EMOTIONAL_RECOVERY',

  // Competency & employability skills
  COMP: 'COMPETENCY_DEVELOPMENT', COMPETENCE: 'COMPETENCY_DEVELOPMENT',
  COMPETITION: 'COMPETENCY_DEVELOPMENT', COMPIND: 'COMPETENCY_DEVELOPMENT',
  SKILL: 'COMPETENCY_DEVELOPMENT', SKL: 'COMPETENCY_DEVELOPMENT',
  SKILLGAP: 'COMPETENCY_DEVELOPMENT', SKILLOBSO: 'COMPETENCY_DEVELOPMENT',
  SKILLPRESS: 'COMPETENCY_DEVELOPMENT', OBSOLETE: 'COMPETENCY_DEVELOPMENT',
  AI: 'COMPETENCY_DEVELOPMENT', TECH: 'COMPETENCY_DEVELOPMENT',
  TECHPRESS: 'COMPETENCY_DEVELOPMENT', TECHLEAD: 'COMPETENCY_DEVELOPMENT',
  MASTERY: 'COMPETENCY_DEVELOPMENT', PRACTICAL: 'COMPETENCY_DEVELOPMENT',
  ANALYTICS: 'COMPETENCY_DEVELOPMENT', CODE: 'COMPETENCY_DEVELOPMENT',
  PROBSOLVE: 'COMPETENCY_DEVELOPMENT',
  UNFAMPROB: 'COMPETENCY_DEVELOPMENT', PROFILE: 'COMPETENCY_DEVELOPMENT',
  PROF: 'COMPETENCY_DEVELOPMENT', ASSESS: 'COMPETENCY_DEVELOPMENT',
  APT: 'COMPETENCY_DEVELOPMENT',

  // Motivation, holistic, identity
  MOT: 'MOTIVATION_VALUES', MOTIV: 'MOTIVATION_VALUES',
  MOTFAIL: 'MOTIVATION_VALUES', OPT: 'MOTIVATION_VALUES',
  OPTIMISM: 'MOTIVATION_VALUES', HOPE: 'MOTIVATION_VALUES',
  AMBITION: 'MOTIVATION_VALUES', OUTCOME: 'MOTIVATION_VALUES',
  MOMENTUM: 'MOTIVATION_VALUES', ENERGY: 'MOTIVATION_VALUES',
  VAL: 'MOTIVATION_VALUES', EXTVAL: 'MOTIVATION_VALUES',
  EXTERNALVAL: 'MOTIVATION_VALUES',
  HOLISTIC: 'HOLISTIC_DEVELOPMENT', HOL: 'HOLISTIC_DEVELOPMENT',
  HOLISTICSTRAT: 'HOLISTIC_DEVELOPMENT', HOLISTICID: 'HOLISTIC_DEVELOPMENT',
  GROWTHSTABILITY: 'HOLISTIC_DEVELOPMENT', BAL: 'HOLISTIC_DEVELOPMENT',
  BALANCE: 'HOLISTIC_DEVELOPMENT', WORKLIFE: 'HOLISTIC_DEVELOPMENT',
  INSTBAL: 'HOLISTIC_DEVELOPMENT', WELL: 'HOLISTIC_DEVELOPMENT',
  WORKHOME: 'HOLISTIC_DEVELOPMENT', SPILL: 'HOLISTIC_DEVELOPMENT',
  IDENTITY: 'ACADEMIC_IDENTITY', LEARNIDENTITY: 'ACADEMIC_IDENTITY',
  LEADIDENTITY: 'ACADEMIC_IDENTITY', LEADPURPOSE: 'ACADEMIC_IDENTITY',

  // Emotional regulation / recovery / resilience
  EMO: 'EMOTIONAL_REGULATION', EMR: 'EMOTIONAL_REGULATION',
  EMC: 'EMOTIONAL_REGULATION', EMOPEER: 'EMOTIONAL_REGULATION',
  ANX: 'EMOTIONAL_REGULATION', ANXIETY: 'EMOTIONAL_REGULATION',
  ANXREV: 'EMOTIONAL_REGULATION', CAREANX: 'EMOTIONAL_REGULATION',
  FEAR: 'EMOTIONAL_REGULATION', FOF: 'EMOTIONAL_REGULATION',
  CAREERFEAR: 'EMOTIONAL_REGULATION', PANIC: 'EMOTIONAL_REGULATION',
  FRUST: 'EMOTIONAL_REGULATION', BURNOUT: 'EMOTIONAL_REGULATION',
  BURN: 'EMOTIONAL_REGULATION', BUR: 'EMOTIONAL_REGULATION',
  MULTIBURN: 'EMOTIONAL_REGULATION', PERFBURN: 'EMOTIONAL_REGULATION',
  LEADERBURN: 'EMOTIONAL_REGULATION', FATIGUE: 'EMOTIONAL_REGULATION',
  RES: 'EMOTIONAL_RECOVERY', RESILIENCE: 'EMOTIONAL_RECOVERY',
  ORGRES: 'EMOTIONAL_RECOVERY', REI: 'EMOTIONAL_RECOVERY',
  FAILURE: 'EMOTIONAL_RECOVERY', FAIL: 'EMOTIONAL_RECOVERY',
  EARLYFAIL: 'EMOTIONAL_RECOVERY', LFAIL: 'EMOTIONAL_RECOVERY',
  SURVIVE: 'EMOTIONAL_RECOVERY', RFS: 'EMOTIONAL_RECOVERY',

  // Confidence & self
  SELF: 'CONFIDENCE_SELF', SA: 'CONFIDENCE_SELF',
  SELFBELIEF: 'CONFIDENCE_SELF', SELFCONF: 'CONFIDENCE_SELF',
  SELFDOUBT: 'CONFIDENCE_SELF', SELFRELIANCE: 'CONFIDENCE_SELF',
  CONF: 'CONFIDENCE_SELF', CONFENV: 'CONFIDENCE_SELF',
  CONFIDENCE: 'CONFIDENCE_SELF', CONFIDENTCAP: 'CONFIDENCE_SELF',
  CONFPRO: 'CONFIDENCE_SELF', CONFSTRUG: 'CONFIDENCE_SELF',
  LOWCONF: 'CONFIDENCE_SELF', SALCONF: 'CONFIDENCE_SELF',
  STREAMCONF: 'CONFIDENCE_SELF', PROBCONF: 'CONFIDENCE_SELF',
  IMPOSTER: 'CONFIDENCE_SELF', TRUST: 'CONFIDENCE_SELF',

  // Comparison & social
  COMPARE: 'SOCIAL_EMOTIONAL', PEERCOMP: 'SOCIAL_EMOTIONAL',
  PEERCOMPARE: 'SOCIAL_EMOTIONAL', PEER: 'SOCIAL_EMOTIONAL',
  PARENTCOMP: 'SOCIAL_EMOTIONAL', ACADEMIC: 'SOCIAL_EMOTIONAL',
  AGECOMP: 'SOCIAL_EMOTIONAL', COMPARING: 'SOCIAL_EMOTIONAL',
  SOCIAL: 'SOCIAL_EMOTIONAL', SOE: 'SOCIAL_EMOTIONAL',

  // Stress & exam
  STRESS: 'EXAMINATION_STRESS', STR: 'EXAMINATION_STRESS',
  PRESS: 'EXAMINATION_STRESS', PRS: 'EXAMINATION_STRESS',
  TECHPRES: 'EXAMINATION_STRESS', RESULTPRESS: 'EXAMINATION_STRESS',
  ACADPRESS: 'EXAMINATION_STRESS', WORKPOL: 'EXAMINATION_STRESS',
  EXA: 'EXAMINATION_STRESS', EXAM: 'EXAMINATION_STRESS',
  BOARD: 'EXAMINATION_STRESS', RESULTPRES: 'EXAMINATION_STRESS',
  PREP: 'STRATEGIC_PREPARATION', STRAT: 'STRATEGIC_PREPARATION',
  TESTSTRAT: 'STRATEGIC_PREPARATION', STRATEGIC: 'STRATEGIC_PREPARATION',
  MULTIATTEMPT: 'STRATEGIC_PREPARATION', RANK: 'STRATEGIC_PREPARATION',
  CUTOFFREC: 'STRATEGIC_PREPARATION', FILTER: 'STRATEGIC_PREPARATION',
  REV: 'STRATEGIC_PREPARATION', MARKS: 'STRATEGIC_PREPARATION',

  // Discipline / habits / focus / lifestyle
  FOCUS: 'DISCIPLINE_HABITS', ATT: 'DISCIPLINE_HABITS',
  ATTSPAN: 'DISCIPLINE_HABITS', LIMITEDATT: 'DISCIPLINE_HABITS',
  DISTRACTION: 'DISCIPLINE_HABITS', CONCENTRATION: 'DISCIPLINE_HABITS',
  DISC: 'DISCIPLINE_HABITS', DISCIPLINE: 'DISCIPLINE_HABITS',
  SELFDISC: 'DISCIPLINE_HABITS', TIMEALLOC: 'DISCIPLINE_HABITS',
  TIME: 'DISCIPLINE_HABITS', PROCR: 'DISCIPLINE_HABITS',
  PROD: 'DISCIPLINE_HABITS', PRO: 'DISCIPLINE_HABITS',
  CONS: 'DISCIPLINE_HABITS', PERSIST: 'DISCIPLINE_HABITS',
  ENDURANCE: 'DISCIPLINE_HABITS', DIG: 'LIFESTYLE_PRESSURE',
  DIGIDISC: 'LIFESTYLE_PRESSURE', SCREEN: 'LIFESTYLE_PRESSURE',
  SHORTVID: 'LIFESTYLE_PRESSURE', SLEEP: 'LIFESTYLE_PRESSURE',
  HEALTH: 'LIFESTYLE_PRESSURE', AWB: 'LIFESTYLE_PRESSURE',
  LIFESTYLE: 'LIFESTYLE_PRESSURE',

  // Academic + thinking
  ACAD: 'ACADEMIC_COGNITIVE', ACA: 'ACADEMIC_COGNITIVE',
  ACADDECLINE: 'ACADEMIC_COGNITIVE', BACKLOG: 'ACADEMIC_COGNITIVE',
  CONCEPT: 'ACADEMIC_COGNITIVE', CONC: 'ACADEMIC_COGNITIVE',
  MEM: 'ACADEMIC_COGNITIVE', RECALL: 'ACADEMIC_COGNITIVE',
  ROTE: 'ACADEMIC_COGNITIVE', PRACTICE: 'ACADEMIC_COGNITIVE',
  MATHSCI: 'STEM_LEARNING', MATHREASON: 'STEM_LEARNING',
  STEM: 'STEM_LEARNING', THEOPROJ: 'STEM_LEARNING',
  DECISION: 'THINKING_QUALITY', DEC: 'THINKING_QUALITY',
  STREAM: 'THINKING_QUALITY', PARENTDEC: 'THINKING_QUALITY',
  UNCERT: 'THINKING_QUALITY', UNCERTLEAD: 'THINKING_QUALITY',
  UNPRED: 'THINKING_QUALITY', PROB: 'THINKING_QUALITY',
  NAV: 'THINKING_QUALITY', RISK: 'THINKING_QUALITY',

  // Leadership + ownership
  LEAD: 'LEADERSHIP_OWNERSHIP', LEADER: 'LEADERSHIP_OWNERSHIP',
  LEADWELL: 'LEADERSHIP_OWNERSHIP', LEADRESP: 'LEADERSHIP_OWNERSHIP',
  LEADUNCERT: 'LEADERSHIP_OWNERSHIP', LEADFAM: 'LEADERSHIP_OWNERSHIP',
  SELFLEAD: 'LEADERSHIP_OWNERSHIP', OWNERSHIP: 'LEADERSHIP_OWNERSHIP',
  RESPONSIBILITY: 'LEADERSHIP_OWNERSHIP', EXECUTION: 'LEADERSHIP_OWNERSHIP',
  ROLE: 'LEADERSHIP_OWNERSHIP',

  // Learning adaptability
  LEARN: 'LEARNING_ADAPTABILITY', LONGLRN: 'LEARNING_ADAPTABILITY',
  INSTLEARN: 'LEARNING_ADAPTABILITY', SDL: 'LEARNING_ADAPTABILITY',
  ADAPT: 'LEARNING_ADAPTABILITY', ADP: 'LEARNING_ADAPTABILITY',
  ADAPTIVE: 'LEARNING_ADAPTABILITY', SLOWPROG: 'LEARNING_ADAPTABILITY',
  PLATEAU: 'LEARNING_ADAPTABILITY', STAG: 'LEARNING_ADAPTABILITY',

  // Communication
  COMM: 'COMMUNICATION_EXPRESSION', COMMCAREER: 'COMMUNICATION_EXPRESSION',
  PUBSPEAK: 'COMMUNICATION_EXPRESSION', CONV: 'COMMUNICATION_EXPRESSION',

  // Adjustment / family / workplace
  FAM: 'ADJUSTMENT_COPING', FAMILY: 'ADJUSTMENT_COPING',
  FAMCAREER: 'ADJUSTMENT_COPING', FAMTRANS: 'ADJUSTMENT_COPING',
  PARENT: 'ADJUSTMENT_COPING', FIN: 'ADJUSTMENT_COPING',
  FINANCE: 'ADJUSTMENT_COPING', FINFAM: 'ADJUSTMENT_COPING',
  ECO: 'ADJUSTMENT_COPING', ECOSYS: 'ADJUSTMENT_COPING',
  WORK: 'WORKPLACE_ADAPTATION', WRK: 'WORKPLACE_ADAPTATION',
  WORKCOMP: 'WORKPLACE_ADAPTATION', WKCONFLICT: 'WORKPLACE_ADAPTATION',
  CONFLICT: 'WORKPLACE_ADAPTATION', PROBATION: 'WORKPLACE_ADAPTATION',
  CORP: 'WORKPLACE_ADAPTATION', CORPCULT: 'WORKPLACE_ADAPTATION',
  CULT: 'WORKPLACE_ADAPTATION', ENT: 'WORKPLACE_ADAPTATION',
  ENTERPRISE: 'WORKPLACE_ADAPTATION', CROSSIND: 'WORKPLACE_ADAPTATION',
  INDCARR: 'WORKPLACE_ADAPTATION', INDUSTRY: 'WORKPLACE_ADAPTATION',
  CAMPWORK: 'WORKPLACE_ADAPTATION', CAM: 'WORKPLACE_ADAPTATION',
  COLLEGE: 'WORKPLACE_ADAPTATION', SCHOOL: 'CLASSROOM_ENGAGEMENT',

  // Self-reflection / interest / strengths
  INTEREST: 'SELF_REFLECTION', STRENGTH: 'SELF_REFLECTION',
  REF: 'SELF_REFLECTION', VIS: 'SELF_REFLECTION',
  FUTURE: 'SELF_REFLECTION',

  // Long-tail concern families (3-letter-prefix taxonomy batch). Keyed by the
  // FULL concern_id prefix (AVOID/MULTITASK/...), not the truncated 3-char
  // concern_id_prefix column some imports ship (AVO/MUL/...).
  AAG: 'GOAL_ALIGNMENT', GOALALIGN: 'GOAL_ALIGNMENT',
  ABS: 'ACADEMIC_RISK',
  ADULT: 'MATURITY_DEVELOPMENT',
  ASR: 'CONFIDENCE_BUILDING',
  AVOID: 'PERSISTENCE_DEVELOPMENT',
  AWC: 'SELF_ACCEPTANCE', WEAKNESS: 'SELF_ACCEPTANCE',
  CDC: 'ATTENTION_REFLECTION', DIST: 'ATTENTION_REFLECTION',
  COLLAB: 'COLLABORATION_OWNERSHIP', GRP: 'COLLABORATION_OWNERSHIP',
  COMFORT: 'EXPLORATION_INHIBITION',
  CONCEPTGAP: 'LEARNING_AWARENESS',
  CONTASS: 'ASSESSMENT_INTELLIGENCE', TA: 'ASSESSMENT_INTELLIGENCE',
  CONVCAR: 'CAREER_AUTONOMY',
  CRED: 'PERSONAL_BRANDING',
  DQA: 'HELP_SEEKING',
  ECI: 'IDENTITY_CONFIDENCE',
  EVA: 'SELF_WORTH', OV: 'SELF_WORTH',
  FASTWORK: 'WORKPLACE_ADAPTATION',
  GDA: 'ANALYTICAL_DEVELOPMENT', QUANT: 'ANALYTICAL_DEVELOPMENT',
  GLOBALTEAM: 'INCLUSIVE_LEADERSHIP',
  IMPROVAREA: 'SELF_EVALUATION',
  IND: 'CAREER_TRANSITION', INDEP: 'DECISION_INDEPENDENCE',
  LIMBELIEF: 'GROWTH_MINDSET',
  LM: 'REFLECTIVE_LEARNING',
  MULTITASK: 'PRODUCTIVITY_REFLECTION',
  NETMENT: 'GROWTH_MENTORING',
  OAE: 'EXAM_READINESS', TIMEASSMT: 'EXAM_READINESS',
  PB: 'THINKING_QUALITY',
  PVH: 'PURPOSE_DISCOVERY',
  ROUT: 'ADJUSTMENT_COPING',
  SELFEXP: 'IDENTITY_EXPRESSION', SELFID: 'STRENGTH_DISCOVERY',
  SFS: 'ENGAGEMENT_MANAGEMENT',
  SYLLABUS: 'ACADEMIC_PLANNING', SYLLREV: 'STUDY_STRATEGY',
  TALENT: 'TALENT_DISCOVERY',
  USB: 'CAREER_EXPECTATIONS',
  VIVA: 'EXAMINATION_READINESS',
  WWS: 'ACADEMIC_PERFORMANCE',
};

const TOKEN_RE = /[A-Za-z0-9]+/g;
const STOPWORDS = new Set(['and', 'the', 'of', 'in', 'for', 'to', 'a', 'an', 'with', 'on', '&']);
const PREFIX_RE = /^([A-Z]+)_/;

/** Extract the leading uppercase prefix from a concern_id (`STD_001` → `STD`). */
export function extractPrefix(concernId: string): string {
  const m = PREFIX_RE.exec(String(concernId ?? '').toUpperCase());
  return m ? m[1] : 'UNKNOWN';
}

/**
 * Token-heuristic: scan concern text for any token that appears in a known
 * master bridge tag; return the tag with the most overlapping tokens (≥1).
 * Mirrors `_token_fallback_lookup` in the Python audit.
 */
export function tokenFallback(concernText: string, masterTags: Iterable<string>): string | null {
  if (!concernText) return null;
  const textTokens = new Set(
    (String(concernText).match(TOKEN_RE) ?? [])
      .filter(t => !STOPWORDS.has(t.toLowerCase()) && t.length > 2)
      .map(t => t.toUpperCase()),
  );
  if (textTokens.size === 0) return null;
  let best: string | null = null;
  let bestScore = 0;
  for (const tag of masterTags) {
    const tagTokens = new Set(tag.split('_'));
    let score = 0;
    for (const t of textTokens) if (tagTokens.has(t)) score += 1;
    if (score > bestScore) { best = tag; bestScore = score; }
  }
  return bestScore >= 1 ? best : null;
}

export interface ClarityRowKey {
  concernId?: string;
  concernIdPrefix?: string;
  concern?: string;
}

/**
 * Resolve `master_bridge_tag` for one clarity row.
 *   1. curated prefix lookup (prefix col, else extracted from concern_id)
 *   2. token-heuristic against the master vocabulary (when supplied)
 *   3. 'UNMAPPED'
 */
export function resolveMasterBridgeTag(row: ClarityRowKey, masterTags?: Iterable<string>): string {
  // The full first-token of concern_id (matches the Python audit's PREFIX_RE
  // extraction) is the reliable prefix. The stored concern_id_prefix column is
  // sometimes truncated to 3 chars (AVOID→AVO), padded (LM→LM_), or collided
  // (CONCEPTGAP/CONTASS/CONVCAR→CON) on import, so try the full prefix FIRST and
  // only fall back to the stored column when concern_id has no usable prefix.
  const fullPrefix = extractPrefix(String(row.concernId ?? ''));
  const rawCol = String(row.concernIdPrefix ?? '').trim().toUpperCase();
  const colPrefix = rawCol && rawCol !== 'UNKNOWN' ? rawCol : '';

  const curated =
    (fullPrefix !== 'UNKNOWN' ? PREFIX_TO_MASTER_BRIDGE[fullPrefix] : undefined) ??
    (colPrefix ? PREFIX_TO_MASTER_BRIDGE[colPrefix] : undefined);
  if (curated) return curated;

  if (masterTags) {
    const t = tokenFallback(String(row.concern ?? ''), masterTags);
    if (t) return t;
  }
  return UNMAPPED;
}

/**
 * Load the distinct master vocabulary (every relational_bridge_tag present in
 * capadex_concerns_master) so the token-heuristic only ever lands on a tag that
 * actually joins. Best-effort: returns an empty set on any error.
 */
export async function loadMasterVocabulary(pool: Pool): Promise<Set<string>> {
  try {
    // ORDER BY makes iteration order deterministic: tokenFallback keeps the
    // first max-overlap tag, so on a score tie the lexically-smallest tag wins
    // (stable across runs) rather than depending on row arrival order.
    const r = await pool.query(
      `SELECT DISTINCT relational_bridge_tag AS t FROM capadex_concerns_master
         WHERE relational_bridge_tag IS NOT NULL AND relational_bridge_tag <> ''
         ORDER BY 1`,
    );
    return new Set(r.rows.map((row: { t: string }) => String(row.t)));
  } catch {
    return new Set<string>();
  }
}
