import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const EXPORT_DIR = '/tmp/rf_exports';

function ensureExportDir(): void {
  if (!fs.existsSync(EXPORT_DIR)) fs.mkdirSync(EXPORT_DIR, { recursive: true });
}

export interface WhiteLabelConfig {
  org_name?: string;
  primary_color?: string;
  secondary_color?: string;
  accent_color?: string;
  report_header?: string;
  report_footer?: string;
  logo_url?: string;
}

// ── PDF ────────────────────────────────────────────────────────────────────

export function renderReportToPDF(report: Record<string, unknown>, wl?: WhiteLabelConfig): Promise<string> {
  ensureExportDir();
  const uuid = (report.report_uuid as string) ?? String(report.id ?? Date.now());
  const filePath = path.join(EXPORT_DIR, `rf_${uuid}.pdf`);

  const primary    = wl?.primary_color ?? '#6366f1';
  const orgName    = wl?.org_name ?? 'MetryxOne';
  const footerText = wl?.report_footer ?? 'This report is a developmental tool generated by MetryxOne Behavioural Intelligence Platform. Not for use in hiring or promotion decisions.';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margins: { top: 60, bottom: 80, left: 60, right: 60 },
      size: 'A4',
      info: {
        Title: `${String(report.report_type ?? 'Report').toUpperCase()} Report`,
        Author: orgName,
        Creator: 'MetryxOne Report Factory',
      },
    });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const pageW = doc.page.width - 120; // usable width

    // ── Header band ──────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 90).fill(primary);
    doc.fontSize(20).fillColor('#ffffff')
       .text(`${String(report.report_type ?? 'custom').toUpperCase()} REPORT`, 60, 28, { width: pageW });
    doc.fontSize(10).fillColor('rgba(255,255,255,0.8)')
       .text(`Generated ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })} · ${orgName}`, 60, 56, { width: pageW });
    doc.y = 110;

    // ── Utility helpers ────────────────────────────────────────────────
    const hr = () => {
      doc.moveDown(0.4);
      doc.moveTo(60, doc.y).lineTo(60 + pageW, doc.y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
      doc.moveDown(0.6);
    };

    const sectionTitle = (title: string) => {
      if (doc.y > 700) doc.addPage();
      doc.moveDown(0.5);
      doc.fontSize(13).fillColor(primary).text(title, 60, doc.y, { width: pageW });
      doc.moveDown(0.3);
    };

    const bodyText = (text: string) => {
      doc.fontSize(10).fillColor('#374151').text(text, 60, doc.y, { width: pageW, lineGap: 3 });
      doc.moveDown(0.7);
    };

    const bullet = (text: string, color: string) => {
      if (doc.y > 720) doc.addPage();
      const bx = 72; const tx = 88;
      doc.circle(bx, doc.y + 4, 3).fill(color);
      doc.fontSize(9).fillColor('#374151').text(text, tx, doc.y, { width: pageW - 28, lineGap: 2 });
      doc.moveDown(0.4);
    };

    // ── Report sections ────────────────────────────────────────────────
    const sections: Record<string, unknown>[] = (report.generated_content as any)?.sections ?? [];

    for (const sec of sections) {
      if (!sec || typeof sec !== 'object') continue;
      const s = sec as Record<string, unknown>;
      const type = String(s.type ?? '');

      if (type === 'header' || type === 'footer') continue;

      if (s.title) sectionTitle(String(s.title));

      switch (type) {
        case 'narrative': {
          if (s.text) bodyText(String(s.text));
          hr();
          break;
        }
        case 'insight': {
          const insights = (s.insights as any[]) ?? [];
          const SEVERITY_COLORS: Record<string, string> = {
            positive: '#10b981', info: '#6366f1', warning: '#f59e0b', critical: '#ef4444',
          };
          for (const ins of insights) {
            bullet(String(ins.text ?? ''), SEVERITY_COLORS[String(ins.severity ?? 'info')] ?? '#6366f1');
          }
          if (insights.length === 0) {
            doc.fontSize(9).fillColor('#9ca3af').text('No insights fired for this report.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'chart': {
          const resolved = s.resolved_data as any;
          if (resolved?.labels?.length) {
            // Render as a simple data table inside the PDF
            const labels: string[] = resolved.labels ?? [];
            const values: number[] = resolved.datasets?.[0]?.data ?? [];
            const maxVal = Math.max(...values.filter(Number.isFinite), 1);
            const barMaxW = pageW - 160;

            doc.fontSize(9).fillColor('#6b7280')
               .text(`Chart: ${String(s.title ?? '')}  ·  Data source: ${String((s.visualization as any)?.data_source ?? '')}`, 60, doc.y, { width: pageW });
            doc.moveDown(0.4);

            for (let i = 0; i < Math.min(labels.length, 15); i++) {
              if (doc.y > 710) doc.addPage();
              const val = Number.isFinite(values[i]) ? values[i] : 0;
              const barW = (val / maxVal) * barMaxW;
              const rowY = doc.y;
              doc.fontSize(8).fillColor('#374151').text(String(labels[i]).substring(0, 28), 60, rowY + 2, { width: 130 });
              doc.rect(200, rowY, barW, 10).fill(`${primary}55`);
              doc.rect(200, rowY, barW, 10).stroke(primary);
              doc.fontSize(8).fillColor('#374151').text(String(val), 204 + barW, rowY + 2, { width: 50 });
              doc.y = rowY + 16;
            }
          } else {
            doc.fontSize(9).fillColor('#9ca3af')
               .text(`[Chart: ${String((s.visualization as any)?.title ?? 'data pending')} — view in web report for rendered chart]`, 60, doc.y, { width: pageW, oblique: true });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'benchmark': {
          const results = (s.benchmark_results as any[]) ?? [];
          if (results.length) {
            for (const r of results) {
              if (doc.y > 720) doc.addPage();
              if (r.suppressed) {
                doc.fontSize(9).fillColor('#9ca3af')
                   .text(`${r.metric}: insufficient cohort data (k < ${r.min_cohort_size ?? 30})`, 60, doc.y, { width: pageW });
              } else {
                const pctLabel = r.percentile != null ? ` · ${r.percentile}th percentile` : '';
                const medianLabel = r.peer_median != null ? ` · Peer median: ${r.peer_median}` : '';
                doc.fontSize(9).fillColor('#374151')
                   .text(`${r.metric}: Your score ${r.user_score ?? 'N/A'}${medianLabel}${pctLabel} (cohort n=${r.cohort_size ?? '—'})`, 60, doc.y, { width: pageW, lineGap: 2 });
              }
              doc.moveDown(0.4);
            }
          } else {
            doc.fontSize(9).fillColor('#9ca3af').text('No benchmark data available.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'score': {
          const scores = (s.scores as any[]) ?? [];
          for (const sc of scores) {
            if (doc.y > 720) doc.addPage();
            doc.fontSize(10).fillColor('#374151')
               .text(`${sc.score_type}: ${sc.score} (${sc.band ?? '—'})`, 60, doc.y, { width: pageW });
            doc.moveDown(0.3);
          }
          hr();
          break;
        }
        case 'precise_competency': {
          // Task #135 — precise per-competency scores, clearly labelled
          // precise vs domain-proxy, falling back to domain when precise absent.
          const precise = (s.precise as any[]) ?? [];
          const domains = (s.domains as any[]) ?? [];
          const note = String(s.note ?? '');
          if (note) {
            doc.fontSize(8).fillColor('#9ca3af').text(note, 60, doc.y, { width: pageW, lineGap: 2, oblique: true });
            doc.moveDown(0.4);
          }
          if (precise.length) {
            doc.fontSize(9).fillColor('#10b981').text('Precise (measured per competency)', 60, doc.y, { width: pageW });
            doc.moveDown(0.2);
            for (const c of precise) {
              if (doc.y > 720) doc.addPage();
              const score = c.score == null ? '—' : Math.round(Number(c.score));
              const lvl = c.levelLabel ? ` · ${c.levelLabel}` : '';
              doc.fontSize(10).fillColor('#374151')
                 .text(`${c.name ?? c.code}: ${score}${score === '—' ? '' : ' / 100'}${lvl}`, 72, doc.y, { width: pageW - 12 });
              doc.moveDown(0.25);
            }
            doc.moveDown(0.2);
          }
          if (domains.length) {
            doc.fontSize(9).fillColor('#6366f1').text('Domain proxy (aggregate)', 60, doc.y, { width: pageW });
            doc.moveDown(0.2);
            for (const c of domains) {
              if (doc.y > 720) doc.addPage();
              const score = c.score == null ? '—' : Math.round(Number(c.score));
              doc.fontSize(10).fillColor('#374151')
                 .text(`${c.name ?? c.code}: ${score}${score === '—' ? '' : ' / 100'}`, 72, doc.y, { width: pageW - 12 });
              doc.moveDown(0.25);
            }
          }
          if (!precise.length && !domains.length) {
            doc.fontSize(9).fillColor('#9ca3af').text('No competency scores available.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
      }
    }

    // ── Footer ─────────────────────────────────────────────────────────
    const footerY = doc.page.height - 60;
    doc.moveTo(60, footerY - 8).lineTo(60 + pageW, footerY - 8).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    doc.fontSize(7).fillColor('#9ca3af')
       .text(footerText, 60, footerY, { width: pageW, align: 'center', lineGap: 2 });

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

// ── Invoice / GST document (Task #6) ─────────────────────────────────────────

export interface InvoiceSellerView {
  legal_name?: string | null;
  trade_name?: string | null;
  gstin?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  email?: string | null;
  phone?: string | null;
}

const DOC_TYPE_TITLE: Record<string, string> = {
  tax: 'TAX INVOICE', proforma: 'PROFORMA INVOICE', credit_note: 'CREDIT NOTE',
  debit_note: 'DEBIT NOTE', payment_receipt: 'PAYMENT RECEIPT', refund_receipt: 'REFUND RECEIPT',
};

function rupees(paise: number): string {
  const n = Number(paise) / 100;
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 2 }).format(n);
}

/**
 * Render an invoice/GST document to PDF (reuses the existing pdfkit stack). Returns the file path.
 * The layout is intentionally compliant-plain: seller block with GSTIN, buyer block, single-page
 * line-item table, GST breakdown (CGST+SGST or IGST), and totals.
 */
export function renderInvoiceToPDF(
  invoice: Record<string, any>,
  lineItems: Array<Record<string, any>>,
  seller: InvoiceSellerView,
  wl?: WhiteLabelConfig,
): Promise<string> {
  ensureExportDir();
  const safeNum = String(invoice.invoice_number ?? invoice.id ?? Date.now()).replace(/[^a-zA-Z0-9]/g, '_');
  const filePath = path.join(EXPORT_DIR, `inv_${safeNum}.pdf`);

  const primary = wl?.primary_color ?? '#344E86';
  const docType = String(invoice.doc_type ?? 'tax');
  const title = DOC_TYPE_TITLE[docType] ?? 'INVOICE';
  const orgName = seller.legal_name || wl?.org_name || 'MetryxOne';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margins: { top: 50, bottom: 60, left: 50, right: 50 },
      size: 'A4',
      info: { Title: `${title} ${invoice.invoice_number ?? ''}`.trim(), Author: orgName, Creator: 'MetryxOne Invoice Engine' },
    });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const left = 50;
    const pageW = doc.page.width - 100;
    const right = left + pageW;

    // ── Header band ──
    doc.rect(0, 0, doc.page.width, 80).fill(primary);
    doc.fontSize(20).fillColor('#ffffff').text(title, left, 24, { width: pageW });
    doc.fontSize(10).fillColor('rgba(255,255,255,0.85)')
       .text(`${invoice.invoice_number ?? ''}  ·  ${new Date(invoice.created_at ?? Date.now()).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`, left, 52, { width: pageW });
    doc.y = 100;

    // ── Seller / buyer blocks ──
    const blockTop = doc.y;
    const sellerLines = [
      orgName,
      seller.trade_name && seller.trade_name !== orgName ? seller.trade_name : null,
      seller.address_line1, seller.address_line2,
      [seller.city, seller.state, seller.pincode].filter(Boolean).join(', ') || null,
      seller.gstin ? `GSTIN: ${seller.gstin}` : 'GSTIN: not configured',
      seller.email ? `Email: ${seller.email}` : null,
      seller.phone ? `Phone: ${seller.phone}` : null,
    ].filter(Boolean) as string[];

    doc.fontSize(8).fillColor('#6b7280').text('SELLER', left, blockTop);
    doc.fontSize(9).fillColor('#111827').text(sellerLines.join('\n'), left, blockTop + 12, { width: pageW / 2 - 10, lineGap: 1.5 });

    const buyerLines = [
      invoice.customer_name || 'Customer',
      invoice.customer_email ? `Email: ${invoice.customer_email}` : null,
      invoice.buyer_gstin ? `GSTIN: ${invoice.buyer_gstin}` : null,
      invoice.place_of_supply ? `Place of supply (state code): ${invoice.place_of_supply}` : null,
    ].filter(Boolean) as string[];

    const buyerX = left + pageW / 2 + 10;
    doc.fontSize(8).fillColor('#6b7280').text('BILL TO', buyerX, blockTop);
    doc.fontSize(9).fillColor('#111827').text(buyerLines.join('\n'), buyerX, blockTop + 12, { width: pageW / 2 - 10, lineGap: 1.5 });

    doc.y = blockTop + 12 + Math.max(sellerLines.length, buyerLines.length) * 13 + 14;

    // ── Meta row ──
    const supplyLabel = invoice.supply_type === 'intra_state' ? 'Intra-state (CGST + SGST)'
      : invoice.supply_type === 'inter_state' ? 'Inter-state (IGST)' : 'GST not determined';
    doc.fontSize(8.5).fillColor('#374151')
       .text(`Document type: ${title}   ·   Supply: ${supplyLabel}   ·   GST rate: ${Number(invoice.gst_rate_pct ?? 0)}%`, left, doc.y, { width: pageW });
    doc.moveDown(0.8);

    // ── Line-item table ──
    const tY = doc.y;
    const colDesc = left, colHsn = left + 280, colQty = left + 350, colAmt = right - 110;
    doc.rect(left, tY, pageW, 20).fill('#f1f5f9');
    doc.fontSize(8.5).fillColor('#334155');
    doc.text('Description', colDesc + 6, tY + 6, { width: 270 });
    doc.text('HSN/SAC', colHsn, tY + 6, { width: 60 });
    doc.text('Qty', colQty, tY + 6, { width: 40 });
    doc.text('Amount', colAmt, tY + 6, { width: 104, align: 'right' });
    doc.y = tY + 24;

    for (const li of lineItems) {
      const rowY = doc.y;
      doc.fontSize(9).fillColor('#111827');
      doc.text(String(li.description ?? ''), colDesc + 6, rowY, { width: 270 });
      doc.text(String(li.hsn_sac ?? '—'), colHsn, rowY, { width: 60 });
      doc.text(String(Number(li.quantity ?? 1)), colQty, rowY, { width: 40 });
      doc.text(rupees(Number(li.amount_paise ?? 0)), colAmt, rowY, { width: 104, align: 'right' });
      doc.y = Math.max(doc.y, rowY + 16);
      doc.moveTo(left, doc.y).lineTo(right, doc.y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
      doc.moveDown(0.3);
    }

    // ── Totals ──
    doc.moveDown(0.5);
    const labelX = right - 250, valX = right - 110;
    const totalRow = (label: string, value: string, bold = false) => {
      const y = doc.y;
      doc.fontSize(bold ? 11 : 9.5).fillColor(bold ? primary : '#374151');
      doc.text(label, labelX, y, { width: 130 });
      doc.text(value, valX, y, { width: 110, align: 'right' });
      doc.moveDown(bold ? 0.5 : 0.35);
    };
    totalRow('Taxable value', rupees(Number(invoice.taxable_paise ?? 0)));
    if (invoice.supply_type === 'inter_state') {
      totalRow(`IGST (${Number(invoice.gst_rate_pct ?? 0)}%)`, rupees(Number(invoice.igst_paise ?? 0)));
    } else if (invoice.supply_type === 'intra_state') {
      totalRow(`CGST (${Number(invoice.gst_rate_pct ?? 0) / 2}%)`, rupees(Number(invoice.cgst_paise ?? 0)));
      totalRow(`SGST (${Number(invoice.gst_rate_pct ?? 0) / 2}%)`, rupees(Number(invoice.sgst_paise ?? 0)));
    } else {
      totalRow('GST', 'Not determined');
    }
    doc.moveTo(labelX, doc.y).lineTo(right, doc.y).strokeColor('#cbd5e1').lineWidth(0.8).stroke();
    doc.moveDown(0.3);
    totalRow('Total', rupees(Number(invoice.total_paise ?? 0)), true);

    if (invoice.notes) {
      doc.moveDown(0.8);
      doc.fontSize(8).fillColor('#6b7280').text('Notes', left, doc.y);
      doc.fontSize(9).fillColor('#374151').text(String(invoice.notes), left, doc.y + 2, { width: pageW });
    }

    if (invoice.supply_type === 'undetermined') {
      doc.moveDown(0.8);
      doc.fontSize(8).fillColor('#b45309')
         .text('GST could not be determined (seller and/or buyer state code missing). This document is not a compliant tax invoice until GST is resolved.', left, doc.y, { width: pageW, lineGap: 2 });
    }

    // ── Footer ──
    const footerY = doc.page.height - 50;
    doc.moveTo(left, footerY - 8).lineTo(right, footerY - 8).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    doc.fontSize(7).fillColor('#9ca3af')
       .text(`${orgName} · This is a computer-generated ${title.toLowerCase()}.`, left, footerY, { width: pageW, align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

// ── CSV ────────────────────────────────────────────────────────────────────

export function renderReportToCSV(report: Record<string, unknown>): string {
  const rows: string[] = [
    'report_uuid,report_type,section_key,content_type,content,severity,metric,user_score,peer_median,percentile,cohort_size',
  ];
  const uuid = String(report.report_uuid ?? report.id ?? '');
  const rtype = String(report.report_type ?? '');
  const esc = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;

  const sections: Record<string, unknown>[] = (report.generated_content as any)?.sections ?? [];
  for (const sec of sections) {
    if (!sec || typeof sec !== 'object') continue;
    const s = sec as Record<string, unknown>;
    const key = String(s.key ?? s.section_key ?? s.type ?? '');
    const type = String(s.type ?? '');

    if (type === 'narrative' && s.text) {
      rows.push([esc(uuid), esc(rtype), esc(key), esc('narrative'), esc(s.text), '', '', '', '', '', ''].join(','));
    }
    if (type === 'insight') {
      for (const ins of (s.insights as any[]) ?? []) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('insight'), esc(ins.text ?? ''), esc(ins.severity ?? 'info'), '', '', '', '', ''].join(','));
      }
    }
    if (type === 'benchmark') {
      for (const r of (s.benchmark_results as any[]) ?? []) {
        if (!r.suppressed) {
          rows.push([esc(uuid), esc(rtype), esc(key), esc('benchmark'), '', '', esc(r.metric ?? ''), esc(r.user_score ?? ''), esc(r.peer_median ?? ''), esc(r.percentile ?? ''), esc(r.cohort_size ?? '')].join(','));
        }
      }
    }
    if (type === 'precise_competency') {
      for (const c of (s.precise as any[]) ?? []) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('precise_competency'), esc(c.name ?? c.code ?? ''), esc(c.levelLabel ?? ''), esc(c.name ?? c.code ?? ''), esc(c.score ?? ''), '', '', ''].join(','));
      }
      for (const c of (s.domains as any[]) ?? []) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('domain_proxy'), esc(c.name ?? c.code ?? ''), '', esc(c.name ?? c.code ?? ''), esc(c.score ?? ''), '', '', ''].join(','));
      }
    }
    if (type === 'chart' && (s.resolved_data as any)?.labels) {
      const rd = s.resolved_data as any;
      const labels: string[] = rd.labels ?? [];
      const values: number[] = rd.datasets?.[0]?.data ?? [];
      for (let i = 0; i < labels.length; i++) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('chart_datapoint'), esc(labels[i]), '', esc(labels[i]), esc(values[i] ?? ''), '', '', ''].join(','));
      }
    }
  }
  return '\uFEFF' + rows.join('\n'); // UTF-8 BOM for Excel
}

// ── JSON ───────────────────────────────────────────────────────────────────

export function renderReportToJSON(report: Record<string, unknown>): string {
  return JSON.stringify({
    schema_version: '1.0',
    exported_at: new Date().toISOString(),
    report: {
      uuid: report.report_uuid,
      type: report.report_type,
      language: report.language,
      status: report.status,
      created_at: report.created_at,
      completed_at: report.completed_at,
      narrative_texts: report.narrative_texts ?? {},
      insights: report.insights ?? [],
      generated_content: report.generated_content ?? {},
      metadata: report.metadata ?? {},
    },
  }, null, 2);
}

// ── Utilities ──────────────────────────────────────────────────────────────

export function getExportFilePath(jobUuid: string, format: string): string {
  const ext = format === 'pdf' ? 'pdf' : format === 'csv' ? 'csv' : format === 'xlsx' ? 'csv' : 'json';
  return path.join(EXPORT_DIR, `rf_${jobUuid}.${ext}`);
}

export function getContentType(format: string): string {
  switch (format) {
    case 'pdf':  return 'application/pdf';
    case 'csv':  return 'text/csv; charset=utf-8';
    case 'json': return 'application/json';
    case 'xlsx': return 'text/csv; charset=utf-8'; // served as csv until xlsx lib added
    default:     return 'application/octet-stream';
  }
}
