import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const EXPORT_DIR = '/tmp/rf_exports';

function ensureExportDir(): void {
  if (!fs.existsSync(EXPORT_DIR)) fs.mkdirSync(EXPORT_DIR, { recursive: true });
}

export interface WhiteLabelConfig {
  org_name?: string;
  primary_color?: string;
  secondary_color?: string;
  accent_color?: string;
  report_header?: string;
  report_footer?: string;
  logo_url?: string;
}

// ── PDF ────────────────────────────────────────────────────────────────────

export function renderReportToPDF(report: Record<string, unknown>, wl?: WhiteLabelConfig): Promise<string> {
  ensureExportDir();
  const uuid = (report.report_uuid as string) ?? String(report.id ?? Date.now());
  const filePath = path.join(EXPORT_DIR, `rf_${uuid}.pdf`);

  const primary    = wl?.primary_color ?? '#6366f1';
  const orgName    = wl?.org_name ?? 'MetryxOne';
  const footerText = wl?.report_footer ?? 'This report is a developmental tool generated by MetryxOne Behavioural Intelligence Platform. Not for use in hiring or promotion decisions.';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margins: { top: 60, bottom: 80, left: 60, right: 60 },
      size: 'A4',
      info: {
        Title: `${String(report.report_type ?? 'Report').toUpperCase()} Report`,
        Author: orgName,
        Creator: 'MetryxOne Report Factory',
      },
    });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const pageW = doc.page.width - 120; // usable width

    // ── Header band ──────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 90).fill(primary);
    doc.fontSize(20).fillColor('#ffffff')
       .text(`${String(report.report_type ?? 'custom').toUpperCase()} REPORT`, 60, 28, { width: pageW });
    doc.fontSize(10).fillColor('rgba(255,255,255,0.8)')
       .text(`Generated ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })} · ${orgName}`, 60, 56, { width: pageW });
    doc.y = 110;

    // ── Utility helpers ────────────────────────────────────────────────
    const hr = () => {
      doc.moveDown(0.4);
      doc.moveTo(60, doc.y).lineTo(60 + pageW, doc.y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
      doc.moveDown(0.6);
    };

    const sectionTitle = (title: string) => {
      if (doc.y > 700) doc.addPage();
      doc.moveDown(0.5);
      doc.fontSize(13).fillColor(primary).text(title, 60, doc.y, { width: pageW });
      doc.moveDown(0.3);
    };

    const bodyText = (text: string) => {
      doc.fontSize(10).fillColor('#374151').text(text, 60, doc.y, { width: pageW, lineGap: 3 });
      doc.moveDown(0.7);
    };

    const bullet = (text: string, color: string) => {
      if (doc.y > 720) doc.addPage();
      const bx = 72; const tx = 88;
      doc.circle(bx, doc.y + 4, 3).fill(color);
      doc.fontSize(9).fillColor('#374151').text(text, tx, doc.y, { width: pageW - 28, lineGap: 2 });
      doc.moveDown(0.4);
    };

    // ── Report sections ────────────────────────────────────────────────
    const sections: Record<string, unknown>[] = (report.generated_content as any)?.sections ?? [];

    for (const sec of sections) {
      if (!sec || typeof sec !== 'object') continue;
      const s = sec as Record<string, unknown>;
      const type = String(s.type ?? '');

      if (type === 'header' || type === 'footer') continue;

      if (s.title) sectionTitle(String(s.title));

      switch (type) {
        case 'narrative': {
          if (s.text) bodyText(String(s.text));
          hr();
          break;
        }
        case 'insight': {
          const insights = (s.insights as any[]) ?? [];
          const SEVERITY_COLORS: Record<string, string> = {
            positive: '#10b981', info: '#6366f1', warning: '#f59e0b', critical: '#ef4444',
          };
          for (const ins of insights) {
            bullet(String(ins.text ?? ''), SEVERITY_COLORS[String(ins.severity ?? 'info')] ?? '#6366f1');
          }
          if (insights.length === 0) {
            doc.fontSize(9).fillColor('#9ca3af').text('No insights fired for this report.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'chart': {
          const resolved = s.resolved_data as any;
          if (resolved?.labels?.length) {
            // Render as a simple data table inside the PDF
            const labels: string[] = resolved.labels ?? [];
            const values: number[] = resolved.datasets?.[0]?.data ?? [];
            const maxVal = Math.max(...values.filter(Number.isFinite), 1);
            const barMaxW = pageW - 160;

            doc.fontSize(9).fillColor('#6b7280')
               .text(`Chart: ${String(s.title ?? '')}  ·  Data source: ${String((s.visualization as any)?.data_source ?? '')}`, 60, doc.y, { width: pageW });
            doc.moveDown(0.4);

            for (let i = 0; i < Math.min(labels.length, 15); i++) {
              if (doc.y > 710) doc.addPage();
              const val = Number.isFinite(values[i]) ? values[i] : 0;
              const barW = (val / maxVal) * barMaxW;
              const rowY = doc.y;
              doc.fontSize(8).fillColor('#374151').text(String(labels[i]).substring(0, 28), 60, rowY + 2, { width: 130 });
              doc.rect(200, rowY, barW, 10).fill(`${primary}55`);
              doc.rect(200, rowY, barW, 10).stroke(primary);
              doc.fontSize(8).fillColor('#374151').text(String(val), 204 + barW, rowY + 2, { width: 50 });
              doc.y = rowY + 16;
            }
          } else {
            doc.fontSize(9).fillColor('#9ca3af')
               .text(`[Chart: ${String((s.visualization as any)?.title ?? 'data pending')} — view in web report for rendered chart]`, 60, doc.y, { width: pageW, oblique: true });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'benchmark': {
          const results = (s.benchmark_results as any[]) ?? [];
          if (results.length) {
            for (const r of results) {
              if (doc.y > 720) doc.addPage();
              if (r.suppressed) {
                doc.fontSize(9).fillColor('#9ca3af')
                   .text(`${r.metric}: insufficient cohort data (k < ${r.min_cohort_size ?? 30})`, 60, doc.y, { width: pageW });
              } else {
                const pctLabel = r.percentile != null ? ` · ${r.percentile}th percentile` : '';
                const medianLabel = r.peer_median != null ? ` · Peer median: ${r.peer_median}` : '';
                doc.fontSize(9).fillColor('#374151')
                   .text(`${r.metric}: Your score ${r.user_score ?? 'N/A'}${medianLabel}${pctLabel} (cohort n=${r.cohort_size ?? '—'})`, 60, doc.y, { width: pageW, lineGap: 2 });
              }
              doc.moveDown(0.4);
            }
          } else {
            doc.fontSize(9).fillColor('#9ca3af').text('No benchmark data available.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'score': {
          const scores = (s.scores as any[]) ?? [];
          for (const sc of scores) {
            if (doc.y > 720) doc.addPage();
            doc.fontSize(10).fillColor('#374151')
               .text(`${sc.score_type}: ${sc.score} (${sc.band ?? '—'})`, 60, doc.y, { width: pageW });
            doc.moveDown(0.3);
          }
          hr();
          break;
        }
        case 'precise_competency': {
          // Task #135 — precise per-competency scores, clearly labelled
          // precise vs domain-proxy, falling back to domain when precise absent.
          const precise = (s.precise as any[]) ?? [];
          const domains = (s.domains as any[]) ?? [];
          const note = String(s.note ?? '');
          if (note) {
            doc.fontSize(8).fillColor('#9ca3af').text(note, 60, doc.y, { width: pageW, lineGap: 2, oblique: true });
            doc.moveDown(0.4);
          }
          if (precise.length) {
            doc.fontSize(9).fillColor('#10b981').text('Precise (measured per competency)', 60, doc.y, { width: pageW });
            doc.moveDown(0.2);
            for (const c of precise) {
              if (doc.y > 720) doc.addPage();
              const score = c.score == null ? '—' : Math.round(Number(c.score));
              const lvl = c.levelLabel ? ` · ${c.levelLabel}` : '';
              doc.fontSize(10).fillColor('#374151')
                 .text(`${c.name ?? c.code}: ${score}${score === '—' ? '' : ' / 100'}${lvl}`, 72, doc.y, { width: pageW - 12 });
              doc.moveDown(0.25);
            }
            doc.moveDown(0.2);
          }
          if (domains.length) {
            doc.fontSize(9).fillColor('#6366f1').text('Domain proxy (aggregate)', 60, doc.y, { width: pageW });
            doc.moveDown(0.2);
            for (const c of domains) {
              if (doc.y > 720) doc.addPage();
              const score = c.score == null ? '—' : Math.round(Number(c.score));
              doc.fontSize(10).fillColor('#374151')
                 .text(`${c.name ?? c.code}: ${score}${score === '—' ? '' : ' / 100'}`, 72, doc.y, { width: pageW - 12 });
              doc.moveDown(0.25);
            }
          }
          if (!precise.length && !domains.length) {
            doc.fontSize(9).fillColor('#9ca3af').text('No competency scores available.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          // Task #166 — mirror the in-app honest footnote (Task #160): name the
          // competencies measured in the broader assessment that aren't yet on
          // the precise scale, so the exported report doesn't look like results
          // silently vanished. Names only, never a fabricated score.
          const notOnScale = (s.notOnPreciseScale as any[]) ?? [];
          if (notOnScale.length) {
            if (doc.y > 700) doc.addPage();
            doc.moveDown(0.2);
            doc.fontSize(9).fillColor('#b45309')
               .text(`${notOnScale.length} of your competencies aren't on the precise scale yet`, 60, doc.y, { width: pageW });
            doc.moveDown(0.2);
            doc.fontSize(8).fillColor('#92400e').text(
              "These were measured in your broader assessment, but there isn't a genuine matching competency in our genome yet, so we don't show a precise score rather than fabricate one:",
              60, doc.y, { width: pageW, lineGap: 2 });
            doc.moveDown(0.2);
            const names = notOnScale.map((c) => String(c.name ?? c.code ?? '')).filter(Boolean).join(', ');
            doc.fontSize(9).fillColor('#374151').text(names, 72, doc.y, { width: pageW - 12 });
            doc.moveDown(0.4);
          }
          hr();
          break;
        }
      }
    }

    // ── Footer ─────────────────────────────────────────────────────────
    const footerY = doc.page.height - 60;
    doc.moveTo(60, footerY - 8).lineTo(60 + pageW, footerY - 8).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    doc.fontSize(7).fillColor('#9ca3af')
       .text(footerText, 60, footerY, { width: pageW, align: 'center', lineGap: 2 });

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

// ── Invoice / GST document (Task #6) ─────────────────────────────────────────

export interface InvoiceSellerView {
  legal_name?: string | null;
  trade_name?: string | null;
  gstin?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  email?: string | null;
  phone?: string | null;
}

const DOC_TYPE_TITLE: Record<string, string> = {
  tax: 'TAX INVOICE', proforma: 'PROFORMA INVOICE', credit_note: 'CREDIT NOTE',
  debit_note: 'DEBIT NOTE', payment_receipt: 'PAYMENT RECEIPT', refund_receipt: 'REFUND RECEIPT',
};

function rupees(paise: number): string {
  const n = Number(paise) / 100;
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 2 }).format(n);
}

/**
 * Render an invoice/GST document to PDF (reuses the existing pdfkit stack). Returns the file path.
 * The layout is intentionally compliant-plain: seller block with GSTIN, buyer block, single-page
 * line-item table, GST breakdown (CGST+SGST or IGST), and totals.
 */
export function renderInvoiceToPDF(
  invoice: Record<string, any>,
  lineItems: Array<Record<string, any>>,
  seller: InvoiceSellerView,
  wl?: WhiteLabelConfig,
): Promise<string> {
  ensureExportDir();
  const safeNum = String(invoice.invoice_number ?? invoice.id ?? Date.now()).replace(/[^a-zA-Z0-9]/g, '_');
  const filePath = path.join(EXPORT_DIR, `inv_${safeNum}.pdf`);

  const primary = wl?.primary_color ?? '#344E86';
  const docType = String(invoice.doc_type ?? 'tax');
  const title = DOC_TYPE_TITLE[docType] ?? 'INVOICE';
  const orgName = seller.legal_name || wl?.org_name || 'MetryxOne';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margins: { top: 50, bottom: 60, left: 50, right: 50 },
      size: 'A4',
      info: { Title: `${title} ${invoice.invoice_number ?? ''}`.trim(), Author: orgName, Creator: 'MetryxOne Invoice Engine' },
    });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const left = 50;
    const pageW = doc.page.width - 100;
    const right = left + pageW;

    // ── Header band ──
    doc.rect(0, 0, doc.page.width, 80).fill(primary);
    doc.fontSize(20).fillColor('#ffffff').text(title, left, 24, { width: pageW });
    doc.fontSize(10).fillColor('rgba(255,255,255,0.85)')
       .text(`${invoice.invoice_number ?? ''}  ·  ${new Date(invoice.created_at ?? Date.now()).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`, left, 52, { width: pageW });
    doc.y = 100;

    // ── Seller / buyer blocks ──
    const blockTop = doc.y;
    const sellerLines = [
      orgName,
      seller.trade_name && seller.trade_name !== orgName ? seller.trade_name : null,
      seller.address_line1, seller.address_line2,
      [seller.city, seller.state, seller.pincode].filter(Boolean).join(', ') || null,
      seller.gstin ? `GSTIN: ${seller.gstin}` : 'GSTIN: not configured',
      seller.email ? `Email: ${seller.email}` : null,
      seller.phone ? `Phone: ${seller.phone}` : null,
    ].filter(Boolean) as string[];

    doc.fontSize(8).fillColor('#6b7280').text('SELLER', left, blockTop);
    doc.fontSize(9).fillColor('#111827').text(sellerLines.join('\n'), left, blockTop + 12, { width: pageW / 2 - 10, lineGap: 1.5 });

    const buyerLines = [
      invoice.customer_name || 'Customer',
      invoice.customer_email ? `Email: ${invoice.customer_email}` : null,
      invoice.buyer_gstin ? `GSTIN: ${invoice.buyer_gstin}` : null,
      invoice.place_of_supply ? `Place of supply (state code): ${invoice.place_of_supply}` : null,
    ].filter(Boolean) as string[];

    const buyerX = left + pageW / 2 + 10;
    doc.fontSize(8).fillColor('#6b7280').text('BILL TO', buyerX, blockTop);
    doc.fontSize(9).fillColor('#111827').text(buyerLines.join('\n'), buyerX, blockTop + 12, { width: pageW / 2 - 10, lineGap: 1.5 });

    doc.y = blockTop + 12 + Math.max(sellerLines.length, buyerLines.length) * 13 + 14;

    // ── Meta row ──
    const supplyLabel = invoice.supply_type === 'intra_state' ? 'Intra-state (CGST + SGST)'
      : invoice.supply_type === 'inter_state' ? 'Inter-state (IGST)' : 'GST not determined';
    doc.fontSize(8.5).fillColor('#374151')
       .text(`Document type: ${title}   ·   Supply: ${supplyLabel}   ·   GST rate: ${Number(invoice.gst_rate_pct ?? 0)}%`, left, doc.y, { width: pageW });
    doc.moveDown(0.8);

    // ── Line-item table ──
    const tY = doc.y;
    const colDesc = left, colHsn = left + 280, colQty = left + 350, colAmt = right - 110;
    doc.rect(left, tY, pageW, 20).fill('#f1f5f9');
    doc.fontSize(8.5).fillColor('#334155');
    doc.text('Description', colDesc + 6, tY + 6, { width: 270 });
    doc.text('HSN/SAC', colHsn, tY + 6, { width: 60 });
    doc.text('Qty', colQty, tY + 6, { width: 40 });
    doc.text('Amount', colAmt, tY + 6, { width: 104, align: 'right' });
    doc.y = tY + 24;

    for (const li of lineItems) {
      const rowY = doc.y;
      doc.fontSize(9).fillColor('#111827');
      doc.text(String(li.description ?? ''), colDesc + 6, rowY, { width: 270 });
      doc.text(String(li.hsn_sac ?? '—'), colHsn, rowY, { width: 60 });
      doc.text(String(Number(li.quantity ?? 1)), colQty, rowY, { width: 40 });
      doc.text(rupees(Number(li.amount_paise ?? 0)), colAmt, rowY, { width: 104, align: 'right' });
      doc.y = Math.max(doc.y, rowY + 16);
      doc.moveTo(left, doc.y).lineTo(right, doc.y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
      doc.moveDown(0.3);
    }

    // ── Totals ──
    doc.moveDown(0.5);
    const labelX = right - 250, valX = right - 110;
    const totalRow = (label: string, value: string, bold = false) => {
      const y = doc.y;
      doc.fontSize(bold ? 11 : 9.5).fillColor(bold ? primary : '#374151');
      doc.text(label, labelX, y, { width: 130 });
      doc.text(value, valX, y, { width: 110, align: 'right' });
      doc.moveDown(bold ? 0.5 : 0.35);
    };
    totalRow('Taxable value', rupees(Number(invoice.taxable_paise ?? 0)));
    if (invoice.supply_type === 'inter_state') {
      totalRow(`IGST (${Number(invoice.gst_rate_pct ?? 0)}%)`, rupees(Number(invoice.igst_paise ?? 0)));
    } else if (invoice.supply_type === 'intra_state') {
      totalRow(`CGST (${Number(invoice.gst_rate_pct ?? 0) / 2}%)`, rupees(Number(invoice.cgst_paise ?? 0)));
      totalRow(`SGST (${Number(invoice.gst_rate_pct ?? 0) / 2}%)`, rupees(Number(invoice.sgst_paise ?? 0)));
    } else {
      totalRow('GST', 'Not determined');
    }
    doc.moveTo(labelX, doc.y).lineTo(right, doc.y).strokeColor('#cbd5e1').lineWidth(0.8).stroke();
    doc.moveDown(0.3);
    totalRow('Total', rupees(Number(invoice.total_paise ?? 0)), true);

    if (invoice.notes) {
      doc.moveDown(0.8);
      doc.fontSize(8).fillColor('#6b7280').text('Notes', left, doc.y);
      doc.fontSize(9).fillColor('#374151').text(String(invoice.notes), left, doc.y + 2, { width: pageW });
    }

    if (invoice.supply_type === 'undetermined') {
      doc.moveDown(0.8);
      doc.fontSize(8).fillColor('#b45309')
         .text('GST could not be determined (seller and/or buyer state code missing). This document is not a compliant tax invoice until GST is resolved.', left, doc.y, { width: pageW, lineGap: 2 });
    }

    // ── Footer ──
    const footerY = doc.page.height - 50;
    doc.moveTo(left, footerY - 8).lineTo(right, footerY - 8).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    doc.fontSize(7).fillColor('#9ca3af')
       .text(`${orgName} · This is a computer-generated ${title.toLowerCase()}.`, left, footerY, { width: pageW, align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

// ── CSV ────────────────────────────────────────────────────────────────────

export function renderReportToCSV(report: Record<string, unknown>): string {
  const rows: string[] = [
    'report_uuid,report_type,section_key,content_type,content,severity,metric,user_score,peer_median,percentile,cohort_size',
  ];
  const uuid = String(report.report_uuid ?? report.id ?? '');
  const rtype = String(report.report_type ?? '');
  const esc = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;

  const sections: Record<string, unknown>[] = (report.generated_content as any)?.sections ?? [];
  for (const sec of sections) {
    if (!sec || typeof sec !== 'object') continue;
    const s = sec as Record<string, unknown>;
    const key = String(s.key ?? s.section_key ?? s.type ?? '');
    const type = String(s.type ?? '');

    if (type === 'narrative' && s.text) {
      rows.push([esc(uuid), esc(rtype), esc(key), esc('narrative'), esc(s.text), '', '', '', '', '', ''].join(','));
    }
    if (type === 'insight') {
      for (const ins of (s.insights as any[]) ?? []) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('insight'), esc(ins.text ?? ''), esc(ins.severity ?? 'info'), '', '', '', '', ''].join(','));
      }
    }
    if (type === 'benchmark') {
      for (const r of (s.benchmark_results as any[]) ?? []) {
        if (!r.suppressed) {
          rows.push([esc(uuid), esc(rtype), esc(key), esc('benchmark'), '', '', esc(r.metric ?? ''), esc(r.user_score ?? ''), esc(r.peer_median ?? ''), esc(r.percentile ?? ''), esc(r.cohort_size ?? '')].join(','));
        }
      }
    }
    if (type === 'precise_competency') {
      for (const c of (s.precise as any[]) ?? []) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('precise_competency'), esc(c.name ?? c.code ?? ''), esc(c.levelLabel ?? ''), esc(c.name ?? c.code ?? ''), esc(c.score ?? ''), '', '', ''].join(','));
      }
      for (const c of (s.domains as any[]) ?? []) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('domain_proxy'), esc(c.name ?? c.code ?? ''), '', esc(c.name ?? c.code ?? ''), esc(c.score ?? ''), '', '', ''].join(','));
      }
    }
    if (type === 'chart' && (s.resolved_data as any)?.labels) {
      const rd = s.resolved_data as any;
      const labels: string[] = rd.labels ?? [];
      const values: number[] = rd.datasets?.[0]?.data ?? [];
      for (let i = 0; i < labels.length; i++) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('chart_datapoint'), esc(labels[i]), '', esc(labels[i]), esc(values[i] ?? ''), '', '', ''].join(','));
      }
    }
  }
  return '\uFEFF' + rows.join('\n'); // UTF-8 BOM for Excel
}

// ── JSON ───────────────────────────────────────────────────────────────────

export function renderReportToJSON(report: Record<string, unknown>): string {
  return JSON.stringify({
    schema_version: '1.0',
    exported_at: new Date().toISOString(),
    report: {
      uuid: report.report_uuid,
      type: report.report_type,
      language: report.language,
      status: report.status,
      created_at: report.created_at,
      completed_at: report.completed_at,
      narrative_texts: report.narrative_texts ?? {},
      insights: report.insights ?? [],
      generated_content: report.generated_content ?? {},
      metadata: report.metadata ?? {},
    },
  }, null, 2);
}

// ── HTML (standalone, branded — this IS the in-app preview) ──────────────────

function htmlEscape(v: unknown): string {
  return String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Inline horizontal SVG bar chart from resolved_data — never a blank chart. */
function svgBarChart(labels: string[], values: number[], primary: string, accent: string): string {
  const n = Math.min(labels.length, 20);
  if (n === 0) return '';
  const rowH = 26;
  const top = 8;
  const labelW = 180;
  const barAreaW = 360;
  const valW = 56;
  const width = labelW + barAreaW + valW;
  const height = top * 2 + n * rowH;
  const finite = values.filter((v) => Number.isFinite(v));
  const maxAbs = Math.max(1, ...finite.map((v) => Math.abs(v)));
  let rows = '';
  for (let i = 0; i < n; i++) {
    const v = Number.isFinite(values[i]) ? values[i] : 0;
    const w = (Math.abs(v) / maxAbs) * barAreaW;
    const y = top + i * rowH;
    const fill = v < 0 ? '#ef4444' : primary;
    rows +=
      `<text x="${labelW - 8}" y="${y + 16}" text-anchor="end" font-size="11" fill="#374151">${htmlEscape(
        labels[i].length > 30 ? labels[i].slice(0, 29) + '…' : labels[i],
      )}</text>` +
      `<rect x="${labelW}" y="${y + 5}" width="${Math.max(2, w)}" height="14" rx="3" fill="${fill}" opacity="0.85"></rect>` +
      `<text x="${labelW + Math.max(2, w) + 6}" y="${y + 16}" font-size="11" fill="#111827">${htmlEscape(
        Math.round(v * 10) / 10,
      )}</text>`;
  }
  return `<svg viewBox="0 0 ${width} ${height}" width="100%" preserveAspectRatio="xMinYMin meet" role="img" aria-label="bar chart" style="max-width:${width}px">${rows}</svg>`;
}

export function renderReportToHTML(report: Record<string, unknown>, wl?: WhiteLabelConfig): string {
  const primary = wl?.primary_color ?? '#1e3a5f';
  const secondary = wl?.secondary_color ?? '#2563eb';
  const accent = wl?.accent_color ?? '#10b981';
  const textColor = '#111827';
  const orgName = wl?.org_name ?? 'MetryxOne';
  const headerText = wl?.report_header ?? '';
  const footerText =
    wl?.report_footer ??
    'This report is a developmental tool generated by the MetryxOne Behavioural Intelligence Platform. Not for use in hiring or promotion decisions.';
  const logo = wl?.logo_url;

  const rtype = String(report.report_type ?? 'custom');
  const title = `${rtype.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())} Report`;
  const sections: Record<string, unknown>[] = (report.generated_content as any)?.sections ?? [];

  const SEVERITY_COLORS: Record<string, string> = {
    positive: '#10b981',
    info: secondary,
    warning: '#f59e0b',
    critical: '#ef4444',
  };

  const parts: string[] = [];
  for (const sec of sections) {
    if (!sec || typeof sec !== 'object') continue;
    const s = sec as Record<string, unknown>;
    const type = String(s.type ?? '');
    if (type === 'header' || type === 'footer') continue;
    const secTitle = s.title ? `<h2>${htmlEscape(s.title)}</h2>` : '';
    let body = '';

    if (type === 'narrative') {
      const isHonest = String(s.callout ?? '') === 'honest';
      const text = String(s.text ?? '')
        .split('\n')
        .map((line) => (line.trim() === '' ? '<br/>' : `<p>${htmlEscape(line)}</p>`))
        .join('');
      body = isHonest ? `<div class="callout honest">${text}</div>` : `<div class="prose">${text}</div>`;
    } else if (type === 'insight') {
      const insights = (s.insights as any[]) ?? [];
      if (insights.length) {
        body =
          '<ul class="insights">' +
          insights
            .map(
              (ins) =>
                `<li><span class="dot" style="background:${
                  SEVERITY_COLORS[String(ins.severity ?? 'info')] ?? secondary
                }"></span>${htmlEscape(ins.text ?? '')}</li>`,
            )
            .join('') +
          '</ul>';
      } else {
        body = '<div class="callout honest"><p>No insights fired for this report.</p></div>';
      }
    } else if (type === 'chart') {
      const rd = s.resolved_data as any;
      const labels: string[] = (rd?.labels ?? []).map((x: any) => String(x));
      const data: number[] = (rd?.datasets?.[0]?.data ?? []).map((x: any) => Number(x));
      const dataSrc = String((s.visualization as any)?.data_source ?? '');
      if (labels.length && data.length) {
        body =
          `<div class="chart">${svgBarChart(labels, data, primary, accent)}</div>` +
          (dataSrc ? `<p class="muted">Data source: ${htmlEscape(dataSrc)}</p>` : '');
      } else {
        body = '<div class="callout honest"><p>No chartable data is available for this visualization.</p></div>';
      }
    } else if (type === 'score') {
      const scores = (s.scores as any[]) ?? [];
      body =
        '<table class="data"><tbody>' +
        scores
          .map(
            (sc) =>
              `<tr><td>${htmlEscape(sc.score_type)}</td><td class="num">${htmlEscape(sc.score)}</td><td>${htmlEscape(
                sc.band ?? '—',
              )}</td></tr>`,
          )
          .join('') +
        '</tbody></table>';
    } else if (type === 'benchmark') {
      const results = (s.benchmark_results as any[]) ?? [];
      body = results.length
        ? '<table class="data"><tbody>' +
          results
            .map((r) =>
              r.suppressed
                ? `<tr><td>${htmlEscape(r.metric)}</td><td colspan="2" class="muted">insufficient cohort data (k &lt; ${htmlEscape(
                    r.min_cohort_size ?? 30,
                  )})</td></tr>`
                : `<tr><td>${htmlEscape(r.metric)}</td><td class="num">${htmlEscape(
                    r.user_score ?? 'N/A',
                  )}</td><td>${r.percentile != null ? htmlEscape(r.percentile) + 'th pct' : '—'}</td></tr>`,
            )
            .join('') +
          '</tbody></table>'
        : '<div class="callout honest"><p>No benchmark data available.</p></div>';
    } else if (type === 'precise_competency') {
      const precise = (s.precise as any[]) ?? [];
      const domains = (s.domains as any[]) ?? [];
      const note = String(s.note ?? '');
      const rows = (list: any[]) =>
        list
          .map(
            (c) =>
              `<tr><td>${htmlEscape(c.name ?? c.code)}</td><td class="num">${
                c.score == null ? '—' : Math.round(Number(c.score))
              }</td></tr>`,
          )
          .join('');
      body =
        (note ? `<p class="muted">${htmlEscape(note)}</p>` : '') +
        (precise.length ? `<h3 style="color:${accent}">Precise (per competency)</h3><table class="data"><tbody>${rows(precise)}</tbody></table>` : '') +
        (domains.length ? `<h3 style="color:${secondary}">Domain proxy</h3><table class="data"><tbody>${rows(domains)}</tbody></table>` : '') +
        (!precise.length && !domains.length ? '<div class="callout honest"><p>No competency scores available.</p></div>' : '');
    }

    parts.push(`<section class="card">${secTitle}${body}</section>`);
  }

  const generatedOn = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${htmlEscape(title)} · ${htmlEscape(orgName)}</title>
<style>
  :root { --primary:${primary}; --secondary:${secondary}; --accent:${accent}; --text:${textColor}; }
  * { box-sizing: border-box; }
  body { margin:0; font-family:${wl?.font_family ?? "'Inter','Segoe UI',system-ui,sans-serif"}; color:var(--text); background:#f3f4f6; line-height:1.55; }
  .page { max-width:880px; margin:0 auto; background:#fff; min-height:100vh; box-shadow:0 1px 4px rgba(0,0,0,.06); }
  header.brand { background:linear-gradient(135deg,var(--primary),var(--secondary)); color:#fff; padding:32px 48px; }
  header.brand .org { display:flex; align-items:center; gap:12px; font-size:13px; opacity:.9; letter-spacing:.04em; text-transform:uppercase; }
  header.brand .org img { height:28px; }
  header.brand h1 { margin:10px 0 4px; font-size:26px; font-weight:700; }
  header.brand .meta { font-size:12.5px; opacity:.85; }
  main { padding:24px 48px 8px; }
  .card { border:1px solid #e5e7eb; border-radius:10px; padding:18px 22px; margin:16px 0; }
  .card h2 { margin:0 0 10px; font-size:15px; color:var(--primary); border-bottom:2px solid #eef2f7; padding-bottom:7px; }
  .card h3 { font-size:12.5px; margin:12px 0 6px; }
  .prose p { margin:0 0 8px; font-size:13.5px; color:#374151; }
  .callout.honest { background:#fff8eb; border-left:4px solid #f59e0b; border-radius:6px; padding:12px 16px; }
  .callout.honest p { margin:0 0 6px; font-size:13px; color:#7c5e10; }
  ul.insights { list-style:none; margin:0; padding:0; }
  ul.insights li { display:flex; gap:9px; align-items:flex-start; font-size:13.5px; color:#374151; padding:5px 0; }
  ul.insights .dot { width:9px; height:9px; border-radius:50%; margin-top:6px; flex:0 0 auto; }
  .chart { margin:6px 0; }
  table.data { width:100%; border-collapse:collapse; font-size:13px; }
  table.data td { padding:6px 8px; border-bottom:1px solid #f1f5f9; }
  table.data td.num { text-align:right; font-variant-numeric:tabular-nums; font-weight:600; }
  .muted { color:#9ca3af; font-size:11.5px; }
  footer.brand { padding:20px 48px 32px; color:#9ca3af; font-size:11px; text-align:center; border-top:1px solid #eef2f7; margin-top:16px; }
</style>
</head>
<body>
  <div class="page">
    <header class="brand">
      <div class="org">${logo ? `<img src="${htmlEscape(logo)}" alt="${htmlEscape(orgName)}"/>` : ''}<span>${htmlEscape(orgName)}</span></div>
      <h1>${htmlEscape(title)}</h1>
      <div class="meta">Generated ${htmlEscape(generatedOn)}${headerText ? ' · ' + htmlEscape(headerText) : ''}</div>
    </header>
    <main>
      ${parts.join('\n      ')}
    </main>
    <footer class="brand">${htmlEscape(footerText)}</footer>
  </div>
</body>
</html>`;
}

// ── Utilities ──────────────────────────────────────────────────────────────

export function getExportFilePath(jobUuid: string, format: string): string {
  const ext = format === 'pdf' ? 'pdf' : format === 'csv' ? 'csv' : format === 'xlsx' ? 'csv' : 'json';
  return path.join(EXPORT_DIR, `rf_${jobUuid}.${ext}`);
}

export function getContentType(format: string): string {
  switch (format) {
    case 'pdf':  return 'application/pdf';
    case 'csv':  return 'text/csv; charset=utf-8';
    case 'json': return 'application/json';
    case 'xlsx': return 'text/csv; charset=utf-8'; // served as csv until xlsx lib added
    default:     return 'application/octet-stream';
  }
}
