import { query } from './client.js';

const ALL_MODULES = [
  // ── LBI™ Behavioural Assessment (5 tiers) ─────────────────────────────────
  { name: 'LBI Quick Scan', cat: 'LBI Behavioural Assessment', sub: 'Entry', seg: 'Classes 1–12', price: null, days: 7, qcount: 15, report: 'Basic', billing: 'one-time', desc: "A short 15-item snapshot of your child's core learning behaviours across attention, memory and self-regulation.", hi: ['15 assessment items','7-day access','Basic PDF report','Key strengths highlighted'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation'], rec: false, ord: 100 },
  { name: 'LBI Starter', cat: 'LBI Behavioural Assessment', sub: 'Starter', seg: 'Classes 3–8', price: 299, days: 30, qcount: 25, report: 'Basic', billing: 'one-time', desc: 'Entry-level LBI assessment mapping foundational learning behaviours with a simple parent-friendly report.', hi: ['25 assessment items','30-day access','Domain-wise breakdown','Parent summary report'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation','Social & Emotional Intelligence'], rec: false, ord: 101 },
  { name: 'LBI Core Assessment', cat: 'LBI Behavioural Assessment', sub: 'Core', seg: 'Classes 6–12', price: 799, days: 90, qcount: 45, report: 'Standard', billing: 'one-time', desc: 'Comprehensive LBI assessment covering 5 major behavioural domains with detailed insights and personalised recommendations.', hi: ['45 assessment items','90-day access','Detailed domain report','Personalised strategies','Study plan suggestions'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation','Social & Emotional Intelligence','Discipline, Habits & Commitment','Thinking Quality Profiling'], rec: true, ord: 102 },
  { name: 'LBI Full Profile', cat: 'LBI Behavioural Assessment', sub: 'Full', seg: 'Classes 6–12', price: 1499, days: 180, qcount: 80, report: 'Detailed', billing: 'one-time', desc: 'In-depth LBI profiling across all 10 domains. Includes a Behavioural Intelligence Score, growth tracking and a re-assessment after 90 days.', hi: ['80 assessment items','180-day access','All 10 LBI domains','Behavioural Intelligence Score','Re-assessment included','Peer benchmarking'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation','Social & Emotional Intelligence','Discipline, Habits & Commitment','Thinking Quality Profiling','Motivation, Values & Resilience','Optimism, Courage & Resilience','Lifestyle, Pressures & Environment'], rec: false, ord: 103 },
  { name: 'LBI Annual + Mentor', cat: 'LBI Behavioural Assessment', sub: 'Premium', seg: 'Classes 8–12', price: 2999, days: 365, qcount: 100, report: 'Comprehensive', billing: 'one-time', desc: 'Year-long behavioural intelligence programme with full LBI profiling, quarterly check-ins and 2 included mentor sessions.', hi: ['100 assessment items','1-year access','Quarterly re-assessments','2 mentor sessions included','Annual portfolio report','Priority support'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation','Social & Emotional Intelligence','Discipline, Habits & Commitment','Thinking Quality Profiling','Motivation, Values & Resilience','Lifestyle, Pressures & Environment','Emotional Self-Expression & Regulation'], rec: false, ord: 104 },

  // ── Exam Readiness (5 tiers) ───────────────────────────────────────────────
  { name: 'Exam Mini Check', cat: 'Exam Readiness', sub: 'Free', seg: 'Classes 9–12', price: null, days: 15, qcount: 20, report: 'Basic', billing: 'one-time', desc: 'Quick 20-item exam-readiness diagnostic. Get instant feedback on focus, stress and time-management readiness.', hi: ['20 assessment items','Instant digital report','Focus & stress snapshot','Free — no card needed'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation'], rec: false, ord: 200 },
  { name: 'Board Exam Sprint', cat: 'Exam Readiness', sub: 'Sprint', seg: 'Classes 10 & 12', price: 299, days: 30, qcount: 30, report: 'Basic', billing: 'one-time', desc: '30-day focused exam readiness programme for board exam candidates covering key cognitive and emotional preparedness domains.', hi: ['30 assessment items','30-day access','Board exam optimised','Domain-wise readiness score'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation','Discipline, Habits & Commitment'], rec: false, ord: 201 },
  { name: 'Exam Ready Pro', cat: 'Exam Readiness', sub: 'Pro', seg: 'Classes 9–12', price: 999, days: 90, qcount: 50, report: 'Standard', billing: 'one-time', desc: 'Comprehensive exam-readiness assessment with 50 items across 6 domains. Includes a detailed readiness report and personalised preparation strategies.', hi: ['50 assessment items','90-day access','6 readiness domains','Personalised prep plan','Progress tracking'], domains: ['Academic & Cognitive Efficiency','Mindset & Self-Regulation','Discipline, Habits & Commitment','Thinking Quality Profiling','Emotional Self-Expression & Regulation','Lifestyle, Pressures & Environment'], rec: true, ord: 202 },
  { name: 'NEET / JEE Elite', cat: 'Exam Readiness', sub: 'Competitive', seg: 'JEE / NEET Aspirants', price: 2499, days: 180, qcount: 90, report: 'Detailed', billing: 'one-time', desc: 'High-intensity exam readiness profiling for competitive entrance exam aspirants covering pressure management, cognitive load and resilience.', hi: ['90 assessment items','180-day access','Competitive exam benchmarks','Pressure management profiling','Weekly readiness check-ins','Peer percentile rank'], domains: ['Academic & Cognitive Efficiency','Thinking Quality Profiling','Emotional Self-Expression & Regulation','Mindset & Self-Regulation','Lifestyle, Pressures & Environment','Motivation, Values & Resilience'], rec: false, ord: 203 },
  { name: 'Annual Exam Pack', cat: 'Exam Readiness', sub: 'Annual', seg: 'Classes 9–12', price: 3999, days: 365, qcount: 120, report: 'Comprehensive', billing: 'one-time', desc: 'Full-year exam readiness programme tracking cognitive and behavioural readiness across all major examination seasons with quarterly reports.', hi: ['120 assessment items','1-year access','Quarterly readiness reports','Term-wise tracking','Mentor session included','Annual progress portfolio'], domains: ['Academic & Cognitive Efficiency','Thinking Quality Profiling','Emotional Self-Expression & Regulation','Mindset & Self-Regulation','Lifestyle, Pressures & Environment','Motivation, Values & Resilience','Discipline, Habits & Commitment'], rec: false, ord: 204 },

  // ── Career Compass™ / Career Intelligence (4 tiers) ────────────────────────
  { name: 'Career Spark', cat: 'Career Intelligence', sub: 'Free', seg: 'Classes 8–12', price: null, days: 30, qcount: 20, report: 'Basic', billing: 'one-time', desc: 'A free introductory career interest and strength mapping tool. Discover your top 3 career directions based on personality and learning style.', hi: ['20 items','Top 3 career matches','Interest & strength mapping','Free forever'], domains: ['Social & Emotional Intelligence','Motivation, Values & Resilience'], rec: false, ord: 300 },
  { name: 'Career Explorer', cat: 'Career Intelligence', sub: 'Explorer', seg: 'Classes 9–12', price: 499, days: 90, qcount: 40, report: 'Standard', billing: 'one-time', desc: 'A structured career discovery assessment matching student traits with 29+ career paths, including a domain compatibility matrix and subject-alignment guide.', hi: ['40 assessment items','90-day access','29+ career paths mapped','Subject alignment guide','Strengths & gaps report'], domains: ['Motivation, Values & Resilience','Social & Emotional Intelligence','Thinking Quality Profiling'], rec: false, ord: 301 },
  { name: 'Career Intelligence Pro', cat: 'Career Intelligence', sub: 'Pro', seg: 'Classes 10–12 & UG', price: 1499, days: 180, qcount: 70, report: 'Detailed', billing: 'one-time', desc: 'Deep career intelligence profiling covering cognitive, personality and interest domains with 50+ career options with fit scores and roadmaps.', hi: ['70 assessment items','180-day access','50+ career options with fit scores','Domain-wise competency map','Personalised roadmap','Peer benchmark data'], domains: ['Motivation, Values & Resilience','Social & Emotional Intelligence','Thinking Quality Profiling','Academic & Cognitive Efficiency','Adaptability & Integrity Management'], rec: true, ord: 302 },
  { name: 'Career Deep Dive + Mentor', cat: 'Career Intelligence', sub: 'Premium', seg: 'Classes 11–12 & UG', price: 3499, days: 365, qcount: 100, report: 'Comprehensive', billing: 'one-time', desc: 'The most comprehensive career intelligence programme combining deep psychometric assessment with 3 one-on-one career mentoring sessions and an annual portfolio.', hi: ['100 assessment items','1-year access','3 career mentor sessions','Annual career portfolio','100+ career paths analysed','University & stream guidance'], domains: ['Motivation, Values & Resilience','Social & Emotional Intelligence','Thinking Quality Profiling','Academic & Cognitive Efficiency','Adaptability & Integrity Management','Discipline, Habits & Commitment'], rec: false, ord: 303 },

  // ── Wellness Check-ins (4 tiers) ───────────────────────────────────────────
  { name: 'Wellness Snapshot', cat: 'Wellness', sub: 'Free', seg: 'Classes 6–12', price: null, days: 7, qcount: 10, report: 'Basic', billing: 'one-time', desc: 'A quick 10-item wellbeing check-in covering stress, mood and energy levels. Alerts parents if intervention is needed.', hi: ['10-item wellness check','Instant mood summary','Stress & energy levels','Parent alert if needed','Free access'], domains: ['Emotional Self-Expression & Regulation','Lifestyle, Pressures & Environment'], rec: false, ord: 400 },
  { name: 'Monthly Wellness Tracker', cat: 'Wellness', sub: 'Monthly', seg: 'Classes 6–12', price: 199, days: 30, qcount: 20, report: 'Basic', billing: 'subscription', desc: 'Monthly wellbeing programme with weekly check-ins tracking stress, burnout, sleep and social wellbeing. Generates a monthly wellness trend report.', hi: ['4 weekly check-ins','Burnout & stress tracking','Sleep quality indicator','Monthly trend report','Parent dashboard alerts'], domains: ['Emotional Self-Expression & Regulation','Lifestyle, Pressures & Environment','Mindset & Self-Regulation'], rec: false, ord: 401 },
  { name: 'Term Wellness Programme', cat: 'Wellness', sub: 'Term', seg: 'Classes 6–12', price: 499, days: 90, qcount: 40, report: 'Standard', billing: 'one-time', desc: 'Full-term wellness monitoring with fortnightly check-ins, burnout screening and a term-end wellness summary report.', hi: ['6 fortnightly check-ins','Burnout screening','Term wellness report','Personalised coping strategies','Parent & teacher summary'], domains: ['Emotional Self-Expression & Regulation','Lifestyle, Pressures & Environment','Mindset & Self-Regulation','Optimism, Courage & Resilience'], rec: true, ord: 402 },
  { name: 'Annual Wellness Plan', cat: 'Wellness', sub: 'Annual', seg: 'Classes 6–12', price: 999, days: 365, qcount: 80, report: 'Detailed', billing: 'one-time', desc: 'Year-round wellbeing support with monthly check-ins, quarterly trend analysis, a yearly wellness portfolio and access to a crisis-alert system.', hi: ['12 monthly check-ins','Quarterly trend analysis','Annual wellness portfolio','Crisis-alert system','School-dashboard integration','Parent coaching notes'], domains: ['Emotional Self-Expression & Regulation','Lifestyle, Pressures & Environment','Mindset & Self-Regulation','Optimism, Courage & Resilience','Social & Emotional Intelligence'], rec: false, ord: 403 },

  // ── Mentor Matching (4 tiers) ─────────────────────────────────────────────
  { name: 'Mentor Trial Session', cat: 'Mentor Matching', sub: 'Trial', seg: 'All Students', price: 299, days: 7, qcount: 0, report: 'Session', billing: 'one-time', desc: 'One 45-minute introductory session with a matched mentor — subject tutor or psychological counsellor. No commitment required.', hi: ['1 x 45-min session','7-day booking window','Subject tutor or counsellor','No auto-renewal'], domains: [], rec: false, ord: 500 },
  { name: 'Mentor Starter Bundle', cat: 'Mentor Matching', sub: 'Starter', seg: 'All Students', price: 799, days: 30, qcount: 0, report: 'Session', billing: 'one-time', desc: '3 one-on-one mentor sessions over 30 days. Choose from subject experts, counsellors or career coaches.', hi: ['3 x 60-min sessions','30-day access','Choose mentor type','Session summary notes','Flexible scheduling'], domains: [], rec: false, ord: 501 },
  { name: 'Mentor Growth Bundle', cat: 'Mentor Matching', sub: 'Growth', seg: 'All Students', price: 1499, days: 60, qcount: 0, report: 'Session', billing: 'one-time', desc: '6 mentor sessions over 60 days. Includes a pre-session diagnostic assessment and post-programme progress note.', hi: ['6 x 60-min sessions','60-day access','Pre-session assessment','Progress note at end','Priority mentor matching'], domains: [], rec: true, ord: 502 },
  { name: 'Mentor Premium Bundle', cat: 'Mentor Matching', sub: 'Premium', seg: 'All Students', price: 2999, days: 120, qcount: 0, report: 'Session', billing: 'one-time', desc: '12 mentor sessions over 4 months with a dedicated assigned mentor, bi-weekly progress reviews and a complete mentoring portfolio.', hi: ['12 x 60-min sessions','4-month programme','Dedicated mentor assigned','Bi-weekly progress reviews','Mentoring portfolio','Parent progress briefings'], domains: [], rec: false, ord: 503 },

  // ── Competency Assessment — Professional (7 plans) ────────────────────────
  { name: 'Mini Assessment', cat: 'Competency Assessment', sub: 'Entry', seg: 'Professionals & Institutions', price: 299, days: 7, qcount: 20, report: 'Basic', billing: 'one-time', desc: 'A 20-item professional competency snapshot across 3 core domains. Ideal for pre-screening and quick capability checks.', hi: ['20 assessment items','7-day access','3 competency domains','Basic competency report'], domains: ['Cognitive Competencies','Communication Competencies','Leadership Competencies'], rec: false, ord: 600 },
  { name: 'Focus & Clarity Check', cat: 'Competency Assessment', sub: 'Entry', seg: 'Professionals & Institutions', price: 299, days: 90, qcount: 30, report: 'Basic', billing: 'one-time', desc: 'A focused competency assessment for cognitive clarity and decision-making. Used widely in hiring screening and development programmes.', hi: ['30 assessment items','90-day access','Decision-making profiling','Focus & clarity score'], domains: ['Cognitive Competencies','Emotional Intelligence Competencies'], rec: false, ord: 601 },
  { name: 'EXAM READY™', cat: 'Competency Assessment', sub: 'Standard', seg: 'Professionals & Institutions', price: 999, days: 30, qcount: 40, report: 'Standard', billing: 'one-time', desc: 'Standard professional competency assessment covering 5 key domains. Benchmarked against industry norms with a percentile report.', hi: ['40 assessment items','30-day access','5 competency domains','Industry benchmark report','Percentile ranking'], domains: ['Cognitive Competencies','Communication Competencies','Leadership Competencies','Emotional Intelligence Competencies','Interpersonal Competencies'], rec: true, ord: 602 },
  { name: 'Exam Season Booster', cat: 'Competency Assessment', sub: 'Booster', seg: 'Professionals & Institutions', price: 699, days: 180, qcount: 60, report: 'Standard', billing: 'one-time', desc: 'Targeted competency booster for high-demand periods — 60 items across thinking quality and self-regulation domains.', hi: ['60 assessment items','180-day access','Thinking quality focus','Self-regulation profiling','Development tips included'], domains: ['Cognitive Competencies','Emotional Intelligence Competencies','Interpersonal Competencies'], rec: false, ord: 603 },
  { name: 'Annual Core LBI', cat: 'Competency Assessment', sub: 'Annual', seg: 'Professionals & Institutions', price: 1499, days: 365, qcount: 120, report: 'Detailed', billing: 'one-time', desc: 'Full-year competency programme covering 8 domains with semi-annual re-assessments, peer benchmarking and a development roadmap.', hi: ['120 assessment items','1-year access','8 competency domains','Semi-annual re-assessment','Peer benchmark data','Development roadmap'], domains: ['Cognitive Competencies','Communication Competencies','Leadership Competencies','Emotional Intelligence Competencies','Interpersonal Competencies','Integrity & Ethics','Adaptability Competencies','Strategic Thinking'], rec: true, ord: 604 },
  { name: 'High-Pressure Premium', cat: 'Competency Assessment', sub: 'Premium', seg: 'Professionals & Institutions', price: 2999, days: 365, qcount: 180, report: 'Comprehensive', billing: 'one-time', desc: 'Comprehensive competency profiling across all 19 domains. Designed for leadership assessment, succession planning and high-potential identification.', hi: ['180 assessment items','1-year access','All 19 competency domains','Comprehensive leadership profile','Succession planning report','2 debrief sessions'], domains: ['Cognitive Competencies','Communication Competencies','Leadership Competencies','Emotional Intelligence Competencies','Interpersonal Competencies','Integrity & Ethics','Adaptability Competencies','Strategic Thinking','Innovation Competencies','Resilience Competencies'], rec: false, ord: 605 },
  { name: 'Post-Exam Transition Check', cat: 'Competency Assessment', sub: 'Transition', seg: 'Professionals & Institutions', price: 499, days: 120, qcount: 45, report: 'Standard', billing: 'one-time', desc: 'Post-assessment transition check for candidates moving between roles or programmes. Maps adaptability and motivation readiness.', hi: ['45 assessment items','120-day access','Transition readiness score','Adaptability profiling','Motivation mapping'], domains: ['Adaptability Competencies','Integrity & Ethics','Resilience Competencies'], rec: false, ord: 606 },
];

async function main() {
  let inserted = 0;
  let skipped = 0;

  for (const m of ALL_MODULES) {
    const { rows: existing } = await query(
      `SELECT 1 FROM subscription_packages WHERE product_name = $1`,
      [m.name]
    );
    if (existing.length > 0) {
      skipped++;
      continue;
    }

    await query(
      `INSERT INTO subscription_packages
        (product_name, category, subcategory, student_segment,
         price, validity_days, question_count, report_type, billing_type,
         description, highlights, domains_covered,
         is_recommended, sort_order, is_active, pkg_status,
         difficulty_distribution, question_draw_mode)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
               true, 'active', '{"easy":30,"medium":50,"hard":20}'::jsonb, 'weighted')`,
      [
        m.name, m.cat, m.sub, m.seg,
        m.price ?? null, m.days, m.qcount, m.report, m.billing,
        m.desc, m.hi, m.domains,
        m.rec, m.ord,
      ]
    );
    inserted++;
    process.stdout.write('.');
  }

  console.log(`\nDone: inserted=${inserted}, skipped=${skipped}, total=${ALL_MODULES.length}`);
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
