export interface ConcernOption {
  value: string;
  label: string;
}

export interface ConcernQuestion {
  id: number;
  text: string;
  domain: string;
  domainLabel: string;
  tip: string;
}

type PersonaKey = 'student' | 'teacher' | 'campus' | 'jobseeker' | 'parent' | 'professional';

export const CONCERN_OPTIONS: Record<PersonaKey, ConcernOption[]> = {
  student: [
    { value: 'exam_anxiety',    label: 'Exam Anxiety & Pressure' },
    { value: 'focus',           label: 'Focus & Concentration' },
    { value: 'motivation',      label: 'Motivation & Procrastination' },
    { value: 'retention',       label: 'Memory & Retention' },
  ],
  teacher: [
    { value: 'engagement',      label: 'Low Classroom Engagement' },
    { value: 'behaviour',       label: 'Disruptive Student Behaviour' },
    { value: 'learning_gaps',   label: 'Learning Gaps & Mixed Abilities' },
    { value: 'burnout',         label: 'Workload & Teacher Burnout' },
  ],
  campus: [
    { value: 'placement',       label: 'Placement & Interview Readiness' },
    { value: 'communication',   label: 'Communication & Soft Skills' },
    { value: 'confidence',      label: 'Confidence & Self-Doubt' },
    { value: 'time',            label: 'Time & Priority Management' },
  ],
  jobseeker: [
    { value: 'interview',       label: 'Interview Performance' },
    { value: 'career_change',   label: 'Career Change / Pivot' },
    { value: 'confidence',      label: 'Confidence & Self-Presentation' },
    { value: 'skill_gap',       label: 'Skill Gaps & Upskilling' },
  ],
  parent: [
    { value: 'performance',     label: 'Academic Performance Concerns' },
    { value: 'stress',          label: 'Exam Stress & Anxiety' },
    { value: 'distraction',     label: 'Distraction & Screen Time' },
    { value: 'motivation',      label: 'Lack of Motivation to Study' },
  ],
  professional: [
    { value: 'leadership',      label: 'Leadership & Managing People' },
    { value: 'growth',          label: 'Career Growth & Stagnation' },
    { value: 'conflict',        label: 'Conflict & Difficult Conversations' },
    { value: 'burnout',         label: 'Burnout & Pressure Management' },
  ],
};

export const CONCERN_QUESTIONS: Record<PersonaKey, Record<string, ConcernQuestion[]>> = {
  student: {
    exam_anxiety: [
      { id: 1, text: "feel physically calm — no racing heart or shaky hands — when an exam begins.", domain: "exam_physiology", domainLabel: "Physical Exam Response", tip: "Physical symptoms are the first lever to address; calm body → calm mind." },
      { id: 2, text: "recall information during exams that I knew well during revision.", domain: "recall_under_pressure", domainLabel: "Recall Under Pressure", tip: "Retrieval under stress is trainable through timed practice tests." },
      { id: 3, text: "manage my time within the exam — I don't panic about running out of time.", domain: "time_pressure", domainLabel: "Time Pressure Management", tip: "Students who time-plan before writing score 18% higher on average." },
      { id: 4, text: "start answering confidently rather than freezing or leaving questions blank.", domain: "exam_confidence", domainLabel: "Exam Initiation Confidence", tip: "Starting with known questions builds momentum and reduces freeze." },
      { id: 5, text: "avoid catastrophising ('I'll fail everything') before or during a test.", domain: "catastrophising", domainLabel: "Negative Thought Control", tip: "Cognitive reframing reduces test anxiety by up to 22%." },
      { id: 6, text: "sleep well the night before an exam rather than lying awake worrying.", domain: "pre_exam_sleep", domainLabel: "Pre-Exam Sleep Quality", tip: "Poor pre-exam sleep reduces recall by up to 30%." },
      { id: 7, text: "recover quickly after a bad exam rather than letting it affect the next one.", domain: "post_exam_recovery", domainLabel: "Post-Exam Recovery", tip: "Inter-exam recovery is the most underrated performance lever." },
      { id: 8, text: "feel equally prepared whether the exam is multiple-choice, written, or practical.", domain: "format_adaptability", domainLabel: "Format Adaptability", tip: "Format-specific practice dramatically reduces format-induced anxiety." },
      { id: 9, text: "trust my preparation going into an exam rather than second-guessing myself.", domain: "self_trust", domainLabel: "Preparation Self-Trust", tip: "Self-trust correlates at 0.61 with actual exam performance." },
      { id: 10, text: "find that my exam performance matches my actual level of understanding.", domain: "performance_gap", domainLabel: "Performance vs. Knowledge Gap", tip: "A large gap here often signals anxiety, not a knowledge deficit." },
    ],
    focus: [
      { id: 1, text: "can study for 45+ minutes without checking my phone or getting distracted.", domain: "sustained_focus", domainLabel: "Sustained Focus", tip: "Distraction-free deep work is the #1 study quality differentiator." },
      { id: 2, text: "re-focus quickly after an interruption — notification, noise, or family member.", domain: "refocus", domainLabel: "Refocus After Distraction", tip: "Average refocus time after a notification is 23 minutes." },
      { id: 3, text: "choose to study even when social media or entertainment feels more appealing.", domain: "impulse_control", domainLabel: "Impulse Control", tip: "Impulse control during study predicts academic rank better than IQ." },
      { id: 4, text: "create a structured, distraction-free study environment intentionally.", domain: "environment_design", domainLabel: "Study Environment Design", tip: "Environment design reduces willpower strain by 40%." },
      { id: 5, text: "notice when I've mentally drifted and bring myself back without frustration.", domain: "metacognition", domainLabel: "Metacognitive Awareness", tip: "Metacognition is the skill that separates A students from B students." },
      { id: 6, text: "feel mentally present and engaged during online classes or recorded lectures.", domain: "digital_attention", domainLabel: "Digital Attention Span", tip: "Online attention lasts 40% less time than in-person — by design." },
      { id: 7, text: "avoid multitasking while studying — no TV or music with lyrics in the background.", domain: "single_tasking", domainLabel: "Single-Task Focus", tip: "Multitasking reduces study retention by 25%." },
      { id: 8, text: "plan each study session with a clear topic, start, and end time.", domain: "session_planning", domainLabel: "Study Session Planning", tip: "Structured sessions produce 37% better outcomes than open-ended ones." },
      { id: 9, text: "feel a clear quality difference between focused vs. distracted study.", domain: "quality_awareness", domainLabel: "Focus Quality Awareness", tip: "Students who can feel the difference choose focus 2x more often." },
      { id: 10, text: "use techniques like Pomodoro or structured breaks to sustain focus over time.", domain: "focus_technique", domainLabel: "Focus Technique Use", tip: "Structured break users maintain output quality 3x longer." },
    ],
    motivation: [
      { id: 1, text: "can start studying even when I really don't feel like it.", domain: "initiation", domainLabel: "Study Initiation", tip: "Action precedes motivation — starting is the hardest step." },
      { id: 2, text: "study without needing external pressure like parent reminders or upcoming deadlines.", domain: "intrinsic_drive", domainLabel: "Intrinsic Drive", tip: "Intrinsic motivation predicts academic performance more strongly than study hours." },
      { id: 3, text: "have a personal, clear reason WHY I want to do well — beyond pleasing others.", domain: "purpose", domainLabel: "Sense of Purpose", tip: "Purpose-connected students study 2.3x more consistently." },
      { id: 4, text: "avoid comparing myself to peers in a way that discourages me.", domain: "comparison_resilience", domainLabel: "Comparison Resilience", tip: "Unhealthy comparison is the #1 self-reported demotivator in students." },
      { id: 5, text: "bounce back quickly after a disappointing grade without losing momentum.", domain: "setback_recovery", domainLabel: "Setback Recovery", tip: "Recovery speed post-setback predicts final grade improvement." },
      { id: 6, text: "feel genuinely excited about learning at least some of what I study.", domain: "subject_interest", domainLabel: "Subject Engagement", tip: "Even partial subject interest lifts overall study quality." },
      { id: 7, text: "celebrate progress and small wins rather than only the final result.", domain: "progress_celebration", domainLabel: "Progress Recognition", tip: "Progress-focused students burn out 60% less often." },
      { id: 8, text: "set meaningful short-term goals that keep me engaged week to week.", domain: "short_term_goals", domainLabel: "Short-Term Goal Setting", tip: "Weekly micro-goals increase task completion by 28%." },
      { id: 9, text: "push through boring or difficult topics without giving up.", domain: "persistence", domainLabel: "Academic Persistence", tip: "Persistence through difficulty is the strongest predictor of mastery." },
      { id: 10, text: "believe that my effort directly leads to improvement — hard work pays off.", domain: "effort_belief", domainLabel: "Effort-Outcome Belief", tip: "Effort belief (growth mindset) predicts GPA improvement over 2 years." },
    ],
    retention: [
      { id: 1, text: "recall key concepts from last week's lesson without needing to re-read notes.", domain: "long_term_retention", domainLabel: "Long-Term Retention", tip: "Without active recall, 70% of new content is forgotten within 24 hours." },
      { id: 2, text: "use active recall — self-testing or flashcards — rather than just re-reading.", domain: "active_recall", domainLabel: "Active Recall Practice", tip: "Active recall improves long-term retention by 50% vs. passive review." },
      { id: 3, text: "space my revision over multiple days rather than cramming the night before.", domain: "spaced_repetition", domainLabel: "Spaced Repetition", tip: "Spacing effect is the most evidence-backed learning strategy available." },
      { id: 4, text: "connect new information to concepts I already understand.", domain: "schema_building", domainLabel: "Schema Building", tip: "Connected knowledge is 3x more retrievable under exam conditions." },
      { id: 5, text: "teach or explain a concept to someone else to test my understanding.", domain: "elaborative_interrogation", domainLabel: "Elaborative Understanding", tip: "Teaching is the deepest form of learning — it exposes hidden gaps." },
      { id: 6, text: "identify what I don't know (gaps) rather than only revising comfortable topics.", domain: "gap_identification", domainLabel: "Learning Gap Awareness", tip: "Revising gaps yields 4x more exam score improvement than revising known material." },
      { id: 7, text: "write summaries in my own words rather than copying from a textbook.", domain: "paraphrasing", domainLabel: "Paraphrasing & Synthesis", tip: "Own-words summarising is strongly linked to deep comprehension." },
      { id: 8, text: "use diagrams, mind maps, or visual notes to organise information for recall.", domain: "visual_memory", domainLabel: "Visual Memory Strategies", tip: "Dual-coding (words + visuals) improves recall by 65%." },
      { id: 9, text: "revise topics at increasing intervals to build durable long-term memory.", domain: "spacing", domainLabel: "Memory Spacing Strategy", tip: "Spaced learners retain 80% at 30 days vs. 20% for massed learners." },
      { id: 10, text: "feel confident that what I study will actually be retrievable during the exam.", domain: "retrieval_confidence", domainLabel: "Retrieval Confidence", tip: "Retrieval confidence — not coverage — predicts exam performance." },
    ],
  },

  teacher: {
    engagement: [
      { id: 1, text: "structure lessons with activities that require active student participation, not just listening.", domain: "active_design", domainLabel: "Active Lesson Design", tip: "Active participation raises concept retention by 55% vs. passive listening." },
      { id: 2, text: "notice when students have disengaged and immediately have a strategy ready.", domain: "disengagement_detection", domainLabel: "Disengagement Detection", tip: "Average teachers detect disengagement 11 minutes after it starts." },
      { id: 3, text: "use varied teaching methods — discussion, demonstration, group work — within a single lesson.", domain: "methodology_variety", domainLabel: "Teaching Method Variety", tip: "Method-variety reduces attention fatigue by 40%." },
      { id: 4, text: "connect lesson content to real-world examples students genuinely care about.", domain: "relevance", domainLabel: "Curriculum Relevance", tip: "Perceived relevance is the single strongest engagement predictor." },
      { id: 5, text: "ask open-ended questions that generate genuine discussion rather than yes/no answers.", domain: "questioning", domainLabel: "Quality Questioning", tip: "Higher-order questions increase student talk-time 3x." },
      { id: 6, text: "give students some choice in how they demonstrate their learning.", domain: "student_choice", domainLabel: "Student Autonomy", tip: "Perceived autonomy raises student motivation by 31%." },
      { id: 7, text: "read the room and adjust the energy level of the class when it drops.", domain: "classroom_energy", domainLabel: "Energy Management", tip: "Energy-responsive teachers retain attention 25 minutes longer per lesson." },
      { id: 8, text: "track which students are consistently disengaged and take targeted individual action.", domain: "individual_monitoring", domainLabel: "Individual Engagement Tracking", tip: "Individual-level intervention is 4x more effective than group intervention." },
      { id: 9, text: "use student feedback to improve how I teach, not only how they perform.", domain: "teacher_feedback", domainLabel: "Student-to-Teacher Feedback", tip: "Teachers who actively seek feedback improve 2x faster." },
      { id: 10, text: "feel that most students leave each lesson having genuinely engaged with the content.", domain: "lesson_impact", domainLabel: "Lesson Impact Confidence", tip: "Teacher-reported lesson impact correlates strongly with student outcomes." },
    ],
    behaviour: [
      { id: 1, text: "establish and consistently enforce clear classroom rules and expectations.", domain: "rules", domainLabel: "Rule Clarity & Consistency", tip: "Consistent enforcement reduces incidents by 34% within 4 weeks." },
      { id: 2, text: "address disruptive behaviour calmly without escalating the situation.", domain: "de_escalation", domainLabel: "Behaviour De-escalation", tip: "Calm responses reduce re-escalation by 60% compared to reactive responses." },
      { id: 3, text: "understand the underlying reason behind a student's disruptive behaviour.", domain: "root_cause", domainLabel: "Root Cause Awareness", tip: "Most disruptive behaviour has a trigger — addressing it stops recurrence." },
      { id: 4, text: "build strong enough relationships that behavioural incidents reduce over time.", domain: "relationship", domainLabel: "Teacher-Student Relationship", tip: "Strong teacher-student relationships reduce incidents by 46%." },
      { id: 5, text: "use proactive strategies — seating plans, structured tasks — to prevent disruption.", domain: "prevention", domainLabel: "Proactive Behaviour Management", tip: "Prevention-focused classrooms have 50% fewer incidents." },
      { id: 6, text: "apply consequences consistently, regardless of which student is involved.", domain: "consistency", domainLabel: "Consequence Consistency", tip: "Inconsistency is the #1 reason students test boundaries repeatedly." },
      { id: 7, text: "involve parents or support staff at the right moment — not too late or too early.", domain: "escalation_timing", domainLabel: "Escalation Timing", tip: "Timely escalation prevents 70% of chronic behaviour patterns." },
      { id: 8, text: "distinguish between students who are defiant versus those who are struggling and acting out.", domain: "behaviour_differentiation", domainLabel: "Behaviour Differentiation", tip: "Correct differentiation leads to the right intervention 90% of the time." },
      { id: 9, text: "maintain classroom authority without resorting to threats or raised voice.", domain: "authority", domainLabel: "Low-Stress Authority", tip: "Low-stress authority is the hallmark of the most effective classroom managers." },
      { id: 10, text: "feel confident managing a class that includes students with known behavioural challenges.", domain: "inclusive_management", domainLabel: "Inclusive Classroom Management", tip: "Inclusive management skill predicts long-term teaching satisfaction." },
    ],
    learning_gaps: [
      { id: 1, text: "quickly identify which specific concepts students have misunderstood before moving on.", domain: "diagnostic", domainLabel: "Rapid Misconception Diagnosis", tip: "Early diagnosis prevents misconceptions from compounding over weeks." },
      { id: 2, text: "differentiate instruction so both struggling and advanced students are appropriately challenged.", domain: "differentiation", domainLabel: "Instructional Differentiation", tip: "Differentiated classrooms improve outcomes for all learners by 28%." },
      { id: 3, text: "adapt my pace when I notice a significant portion of the class hasn't grasped a concept.", domain: "pacing", domainLabel: "Adaptive Pacing", tip: "Pace adaptation is linked to 22% better end-of-term results." },
      { id: 4, text: "use formative checks — exit tickets, quick quizzes — to gauge understanding during the lesson.", domain: "formative", domainLabel: "Formative Assessment Use", tip: "Formative assessment doubles learning gains compared to summative-only." },
      { id: 5, text: "ensure students who fall behind have a clear, actionable path to catch up.", domain: "catch_up", domainLabel: "Learning Catch-Up Planning", tip: "Structured catch-up plans reduce chronic underperformance by 38%." },
      { id: 6, text: "create small-group support within the class without making struggling students feel singled out.", domain: "group_support", domainLabel: "Discreet Group Support", tip: "Discreet differentiation preserves student dignity and motivation." },
      { id: 7, text: "address foundational gaps in a topic before teaching the next concept.", domain: "sequencing", domainLabel: "Curriculum Sequencing", tip: "Gap-aware sequencing prevents 60% of chronic learning failure patterns." },
      { id: 8, text: "track individual student progress across the term and act on patterns I notice.", domain: "tracking", domainLabel: "Individual Progress Tracking", tip: "Data-informed teachers close learning gaps 2x faster." },
      { id: 9, text: "adjust my explanation style when my current approach isn't landing for most students.", domain: "explanation_flexibility", domainLabel: "Explanation Flexibility", tip: "Multi-modal explanation reduces misconception rates by 45%." },
      { id: 10, text: "design revision activities that target known gaps rather than covering everything again.", domain: "targeted_revision", domainLabel: "Targeted Revision Design", tip: "Targeted revision is 3x more efficient than blanket review." },
    ],
    burnout: [
      { id: 1, text: "manage my marking load without it consistently bleeding into evenings and weekends.", domain: "workload", domainLabel: "Marking & Workload Boundaries", tip: "Chronic overwork is the #1 predictor of teacher attrition." },
      { id: 2, text: "feel energised and motivated when I walk into the classroom most days.", domain: "teaching_energy", domainLabel: "Teaching Energy", tip: "Teaching energy is contagious — it directly shapes student engagement." },
      { id: 3, text: "set clear boundaries between work and personal time and actually protect them.", domain: "boundaries", domainLabel: "Work-Life Boundary Protection", tip: "Boundary-setting is the most protective factor against educator burnout." },
      { id: 4, text: "feel that administrative demands don't consistently overshadow actual teaching.", domain: "admin_balance", domainLabel: "Admin vs. Teaching Balance", tip: "Teachers who feel admin overwhelmed report burnout 2x more often." },
      { id: 5, text: "manage emotionally draining classroom situations without taking them home.", domain: "emotional_protection", domainLabel: "Emotional Boundary Setting", tip: "Emotional compartmentalisation is teachable and dramatically improves wellbeing." },
      { id: 6, text: "feel supported by school leadership when I raise concerns about workload or wellbeing.", domain: "institutional_support", domainLabel: "Institutional Support", tip: "Leadership support is the #1 factor in teacher retention beyond pay." },
      { id: 7, text: "reflect on what is going well in my teaching, not only the challenges.", domain: "positive_reflection", domainLabel: "Positive Teaching Reflection", tip: "Positive reflection practice reduces burnout symptoms by 29%." },
      { id: 8, text: "plan lessons efficiently without it consuming disproportionate time each week.", domain: "planning_efficiency", domainLabel: "Lesson Planning Efficiency", tip: "Planning efficiency separates sustainable from exhausted teachers." },
      { id: 9, text: "feel that my contribution to student growth is visible and acknowledged.", domain: "recognition", domainLabel: "Professional Recognition", tip: "Recognised teachers are 3x more likely to stay in the profession." },
      { id: 10, text: "have a peer or mentor I can speak to honestly about the real challenges of the job.", domain: "peer_support", domainLabel: "Peer & Mentor Support", tip: "Peer support networks halve the risk of first-5-year attrition." },
    ],
  },

  campus: {
    placement: [
      { id: 1, text: "confidently deliver a structured, memorable 1-minute self-introduction.", domain: "self_intro", domainLabel: "Self-Introduction Confidence", tip: "The first 60 seconds determine how interviewers frame everything that follows." },
      { id: 2, text: "handle HR questions — strengths, weaknesses, situational — without blanking.", domain: "hr_questions", domainLabel: "HR Question Handling", tip: "Preparation with STAR examples reduces blank-out by 70%." },
      { id: 3, text: "research companies thoroughly before applying and tailor each application.", domain: "company_research", domainLabel: "Pre-Placement Research", tip: "Tailored applications are 40% more likely to convert to interviews." },
      { id: 4, text: "perform consistently in group discussions and personal interviews without freezing.", domain: "gd_pi", domainLabel: "Group Discussion & PI Performance", tip: "GD performance is the most differentiating placement stage." },
      { id: 5, text: "maintain a professional LinkedIn profile that reflects my actual capability.", domain: "digital_presence", domainLabel: "Digital Professional Presence", tip: "70% of recruiters check LinkedIn before shortlisting." },
      { id: 6, text: "handle placement rejection without losing confidence in subsequent attempts.", domain: "rejection_resilience", domainLabel: "Rejection Resilience", tip: "Placement success correlates with number of attempts — persistence wins." },
      { id: 7, text: "demonstrate relevant technical or domain knowledge at the right moments.", domain: "domain_knowledge", domainLabel: "Domain Knowledge Display", tip: "Domain credibility is the #1 factor beyond communication in tech placements." },
      { id: 8, text: "manage the stress of multiple simultaneous placement processes effectively.", domain: "process_stress", domainLabel: "Placement Process Stress", tip: "Multi-process stress management separates top performers from average ones." },
      { id: 9, text: "communicate clearly in written form — emails, cover letters, responses.", domain: "written_comm", domainLabel: "Written Communication", tip: "Written clarity is increasingly tested across placement stages." },
      { id: 10, text: "make a strong positive impression in the first 5 minutes of any interaction.", domain: "first_impression", domainLabel: "First Impression Management", tip: "First impressions lock in within 7 seconds and are highly resistant to change." },
    ],
    communication: [
      { id: 1, text: "express ideas clearly in group presentations without losing my train of thought.", domain: "presentation", domainLabel: "Presentation Clarity", tip: "Structure is the #1 differentiator in campus presentations." },
      { id: 2, text: "listen actively and build on others' points in discussions rather than waiting for my turn.", domain: "active_listening", domainLabel: "Active Listening", tip: "Active listeners are perceived as 40% more credible in professional settings." },
      { id: 3, text: "adjust how I communicate based on the audience — professor, peer, or industry professional.", domain: "audience_adaptation", domainLabel: "Audience Adaptation", tip: "Audience adaptation is the most valued communication skill by employers." },
      { id: 4, text: "handle nerves confidently when speaking in front of a group of 10+ people.", domain: "speaking_nerves", domainLabel: "Public Speaking Confidence", tip: "Public speaking confidence is the #1 soft skill gap in campus hires." },
      { id: 5, text: "participate confidently in class discussions rather than staying silent.", domain: "class_participation", domainLabel: "Class Participation Confidence", tip: "In-class participation builds the muscle used in professional settings." },
      { id: 6, text: "write professional emails and reports that are clear, concise, and well-structured.", domain: "written_prof", domainLabel: "Professional Writing", tip: "Professional writing quality signals attention to detail and intelligence." },
      { id: 7, text: "ask questions in professional settings without feeling I'll be judged negatively.", domain: "question_confidence", domainLabel: "Question Confidence", tip: "Asking questions is strongly correlated with being seen as engaged and curious." },
      { id: 8, text: "give feedback to peers constructively without making them feel criticised.", domain: "peer_feedback", domainLabel: "Peer Feedback Skills", tip: "Feedback skills in campus predict feedback effectiveness as a manager." },
      { id: 9, text: "navigate disagreements in group projects without it becoming personal.", domain: "conflict_comm", domainLabel: "Conflict Communication", tip: "Conflict navigation is tested in most assessment centres for campus roles." },
      { id: 10, text: "come across as credible and confident even when I'm uncertain about a topic.", domain: "credibility", domainLabel: "Credibility Under Uncertainty", tip: "Composure under uncertainty is the hallmark of high-potential hires." },
    ],
    confidence: [
      { id: 1, text: "believe that I am as capable as other students being placed from my college.", domain: "peer_comparison", domainLabel: "Peer Capability Belief", tip: "Comparison-driven self-doubt reduces interview performance by up to 15%." },
      { id: 2, text: "walk into a new situation — interview, networking event — without significant self-doubt.", domain: "new_situation", domainLabel: "New Situation Confidence", tip: "Situational confidence is trainable through deliberate exposure." },
      { id: 3, text: "advocate for myself — ask for what I need in academic or professional settings.", domain: "self_advocacy", domainLabel: "Self-Advocacy", tip: "Self-advocacy is the most underrated campus skill for career success." },
      { id: 4, text: "view failures and setbacks as temporary and useful, not as proof I'm not good enough.", domain: "failure_framing", domainLabel: "Failure Framing", tip: "Failure reframing is the core cognitive skill behind resilient performers." },
      { id: 5, text: "share my opinion even when I think it might be unpopular or partly wrong.", domain: "opinion_sharing", domainLabel: "Opinion Confidence", tip: "Campus students who speak up in groups are shortlisted 2x more." },
      { id: 6, text: "maintain my confidence across the long, uncertain placement process.", domain: "sustained_confidence", domainLabel: "Sustained Confidence", tip: "Confidence durability — not peak confidence — predicts placement outcome." },
      { id: 7, text: "take on responsibilities and projects that stretch beyond my comfort zone.", domain: "stretch", domainLabel: "Comfort Zone Expansion", tip: "High-potential hires consistently seek stretch, not safety." },
      { id: 8, text: "prepare for high-stakes moments without over-preparing from a place of fear.", domain: "healthy_prep", domainLabel: "Healthy Preparation", tip: "Fear-based over-preparation raises anxiety without improving performance." },
      { id: 9, text: "feel proud of my academic and personal journey without minimising my achievements.", domain: "self_pride", domainLabel: "Self-Worth Recognition", tip: "Students who own their story communicate it 3x more effectively." },
      { id: 10, text: "recover quickly from a poor performance — bad mock, failed GD — and re-engage.", domain: "performance_recovery", domainLabel: "Performance Recovery", tip: "Recovery speed after setbacks is the strongest predictor of placement success." },
    ],
    time: [
      { id: 1, text: "balance academics, placement prep, extracurriculars, and personal life without constant stress.", domain: "life_balance", domainLabel: "Multi-Domain Balance", tip: "Perceived balance — not actual hours — predicts performance across domains." },
      { id: 2, text: "plan my week in advance and stick to it most of the time.", domain: "weekly_planning", domainLabel: "Weekly Planning", tip: "Weekly planning reduces decision fatigue by 30% across the week." },
      { id: 3, text: "say no to low-value activities to protect time for what matters most.", domain: "saying_no", domainLabel: "Saying No", tip: "The ability to say no is the highest-leverage time management skill." },
      { id: 4, text: "avoid procrastinating on important tasks until the last minute.", domain: "procrastination", domainLabel: "Procrastination Control", tip: "Procrastination costs an average campus student 3 hours of productive time daily." },
      { id: 5, text: "feel in control of my schedule rather than constantly reacting to what's urgent.", domain: "proactive_schedule", domainLabel: "Proactive Scheduling", tip: "Proactive scheduling is linked to 28% lower stress during placement season." },
      { id: 6, text: "estimate how long tasks will take accurately and plan accordingly.", domain: "time_estimation", domainLabel: "Time Estimation Accuracy", tip: "Planning fallacy — underestimating task time — derails 60% of campus planners." },
      { id: 7, text: "protect specific deep-work blocks that others respect and don't interrupt.", domain: "deep_work", domainLabel: "Deep Work Protection", tip: "Even 90 minutes of protected deep work daily doubles output quality." },
      { id: 8, text: "make progress on long-term goals even during a busy, chaotic week.", domain: "long_term_progress", domainLabel: "Long-Term Progress Maintenance", tip: "Small daily actions on long-term goals outperform sprint-based efforts." },
      { id: 9, text: "review what didn't get done and adjust my plan without spiralling into guilt.", domain: "plan_review", domainLabel: "Plan Review & Adjustment", tip: "Weekly reflection is the keystone habit of high-performers." },
      { id: 10, text: "avoid checking my phone unnecessarily during dedicated study or work periods.", domain: "phone_discipline", domainLabel: "Phone Discipline", tip: "Phone within arm's reach reduces cognitive capacity by 10% even when unused." },
    ],
  },

  jobseeker: {
    interview: [
      { id: 1, text: "answer 'Tell me about yourself' in a way that is structured, memorable, and genuine.", domain: "self_intro", domainLabel: "Self-Introduction Quality", tip: "A strong 90-second intro sets the interview tone and is rarely corrected." },
      { id: 2, text: "prepare specific STAR-format examples for competency-based questions in advance.", domain: "star_prep", domainLabel: "STAR Preparation Quality", tip: "Candidates with 5+ STAR examples prepared convert interviews at 3x the rate." },
      { id: 3, text: "manage interview anxiety so it doesn't visibly affect the quality of my answers.", domain: "interview_anxiety", domainLabel: "Interview Anxiety Management", tip: "Controlled anxiety slightly improves performance — uncontrolled anxiety tanks it." },
      { id: 4, text: "research the company and role deeply enough to ask intelligent, specific questions.", domain: "company_research", domainLabel: "Pre-Interview Research", tip: "Good closing questions are cited by 72% of interviewers as a differentiator." },
      { id: 5, text: "answer 'What is your weakness?' in a way that is honest but not self-defeating.", domain: "weakness_answer", domainLabel: "Weakness Question Handling", tip: "Authentic weakness answers signal self-awareness — a top hiring criterion." },
      { id: 6, text: "maintain confident body language — eye contact, posture, voice — throughout.", domain: "body_language", domainLabel: "Interview Body Language", tip: "55% of interview impressions are formed through body language alone." },
      { id: 7, text: "handle curveball or pressure questions without losing composure.", domain: "pressure_questions", domainLabel: "Pressure Question Handling", tip: "Pressure questions simulate real workplace demands — poise here signals a lot." },
      { id: 8, text: "recover smoothly if I don't know an answer rather than shutting down.", domain: "recovery", domainLabel: "Answer Recovery", tip: "'I'll find that out' said confidently is more impressive than a wrong answer." },
      { id: 9, text: "follow up professionally after an interview with a thank-you or polite check-in.", domain: "follow_up", domainLabel: "Post-Interview Follow-Up", tip: "Follow-up converts borderline decisions in favour of the candidate 28% of the time." },
      { id: 10, text: "feel that my preparation level matches the demands of the roles I'm interviewing for.", domain: "prep_match", domainLabel: "Preparation Adequacy", tip: "Perceived preparation adequacy directly predicts interview confidence." },
    ],
    career_change: [
      { id: 1, text: "articulate clearly why I'm changing careers in a way that sounds strategic, not desperate.", domain: "change_narrative", domainLabel: "Career Change Narrative", tip: "A compelling pivot story reduces hiring bias by up to 35%." },
      { id: 2, text: "identify which of my existing skills transfer meaningfully to my target new role.", domain: "skill_transfer", domainLabel: "Transferable Skill Identification", tip: "Most career changers underestimate how transferable their skills are." },
      { id: 3, text: "fill the most critical skill gaps for my target industry within a realistic timeframe.", domain: "gap_filling", domainLabel: "Gap-Filling Strategy", tip: "Targeted gap-filling is 4x more effective than broad upskilling." },
      { id: 4, text: "network authentically with people in my target industry without it feeling transactional.", domain: "networking", domainLabel: "Target Industry Networking", tip: "70% of career pivot roles are filled through network referrals." },
      { id: 5, text: "handle any pay cut or status reset that may come with the career transition.", domain: "ego_management", domainLabel: "Transition Ego Management", tip: "Candidates who emotionally process the reset succeed in transitions 2x more." },
      { id: 6, text: "stay motivated across the longer job search that career pivots typically require.", domain: "pivot_motivation", domainLabel: "Pivot Motivation Durability", tip: "Career pivots take 40% longer on average — motivation durability is critical." },
      { id: 7, text: "position my past experience as an asset, not a liability, in the new field.", domain: "experience_framing", domainLabel: "Experience Repositioning", tip: "Cross-industry experience is often a unique competitive advantage — own it." },
      { id: 8, text: "decide which specific roles to target in the new field rather than applying broadly.", domain: "role_targeting", domainLabel: "Targeted Role Selection", tip: "Focused targeting produces 3x more responses than broad applications." },
      { id: 9, text: "manage the uncertainty of being a 'beginner' again without excessive self-doubt.", domain: "beginner_mindset", domainLabel: "Beginner Mindset", tip: "Comfort with beginner status is the #1 predictor of career change success." },
      { id: 10, text: "set a realistic timeline for my career pivot and track progress against it.", domain: "pivot_timeline", domainLabel: "Pivot Timeline Management", tip: "Milestoned timelines reduce anxiety and increase pivot completion rates." },
    ],
    confidence: [
      { id: 1, text: "believe I add genuine value to employers despite any gap in employment or career history.", domain: "value_belief", domainLabel: "Candidate Value Belief", tip: "Candidates who own their value communicate it 3x more effectively." },
      { id: 2, text: "maintain confidence across multiple rejections without withdrawing from the process.", domain: "rejection_resilience", domainLabel: "Rejection Resilience", tip: "Most successful hires come after 8+ rejections — resilience is the differentiator." },
      { id: 3, text: "present my experience confidently even when I feel others may be more qualified.", domain: "self_presentation", domainLabel: "Self-Presentation Confidence", tip: "Perceived confidence influences hiring decisions independently of qualifications." },
      { id: 4, text: "negotiate salary without accepting the first offer out of discomfort or fear.", domain: "negotiation", domainLabel: "Salary Negotiation Confidence", tip: "Only 37% of candidates negotiate — those who do earn 7–10% more on average." },
      { id: 5, text: "reach out to strangers or attend networking events without excessive anxiety.", domain: "outreach_confidence", domainLabel: "Outreach Confidence", tip: "Cold outreach confidence is the most high-leverage job search skill." },
      { id: 6, text: "comfortably say 'I don't know but I will find out' in an interview.", domain: "uncertainty_comfort", domainLabel: "Uncertainty Comfort", tip: "Interviewers prefer honest uncertainty over confident wrong answers." },
      { id: 7, text: "avoid catastrophising after a bad interview — 'I'll never get a job' thinking.", domain: "catastrophising", domainLabel: "Catastrophising Control", tip: "Catastrophising is the primary driver of premature job search abandonment." },
      { id: 8, text: "celebrate interim progress — final round invites, positive feedback — not just offers.", domain: "progress_recognition", domainLabel: "Progress Recognition", tip: "Progress-aware candidates stay in the process 60% longer." },
      { id: 9, text: "accurately assess my own strengths without undervaluing them.", domain: "self_assessment", domainLabel: "Accurate Self-Assessment", tip: "Self-awareness and accurate self-assessment are the most valued leadership traits." },
      { id: 10, text: "stay consistent in my job search effort during weeks of silence from employers.", domain: "sustained_effort", domainLabel: "Sustained Search Effort", tip: "Consistent daily effort through silent periods is what separates successful searchers." },
    ],
    skill_gap: [
      { id: 1, text: "identify which specific skills are most critical for the roles I'm actually targeting.", domain: "skill_prioritisation", domainLabel: "Skill Prioritisation", tip: "Focusing on 2–3 critical gaps is 5x more effective than broad upskilling." },
      { id: 2, text: "learn new tools or technologies quickly enough to apply them in a real work context.", domain: "tech_agility", domainLabel: "Technology Agility", tip: "Tech agility is the most in-demand skill across all sectors in 2025." },
      { id: 3, text: "build visible proof of my new skills — projects, portfolio, certifications — for employers.", domain: "skill_visibility", domainLabel: "Skill Visibility", tip: "Demonstrated skills convert 3x better than claimed ones on a resume." },
      { id: 4, text: "follow a structured upskilling plan consistently, not just when motivation is high.", domain: "learning_consistency", domainLabel: "Upskilling Consistency", tip: "Consistent learners close the same gap in 40% of the time." },
      { id: 5, text: "choose the right learning resources rather than wasting time on low-quality content.", domain: "resource_quality", domainLabel: "Learning Resource Selection", tip: "Resource quality accounts for 60% of variance in learning speed." },
      { id: 6, text: "apply what I'm learning immediately in practice rather than just consuming content.", domain: "applied_learning", domainLabel: "Applied Learning", tip: "Practical application within 24 hours raises retention from 10% to 75%." },
      { id: 7, text: "balance active job searching with consistent skill development — without dropping either.", domain: "parallel_growth", domainLabel: "Parallel Growth", tip: "Skills developed during the job search directly improve interview quality." },
      { id: 8, text: "benchmark my current skill level honestly against what employers actually expect.", domain: "honest_benchmark", domainLabel: "Honest Benchmarking", tip: "Honest self-benchmarking reduces wasted applications by 40%." },
      { id: 9, text: "avoid 'learning paralysis' — starting many courses without completing any.", domain: "learning_completion", domainLabel: "Learning Completion Rate", tip: "Course completion rate is a direct signal of follow-through to employers." },
      { id: 10, text: "seek feedback on my work or output to know whether my skills are genuinely improving.", domain: "skill_feedback", domainLabel: "Skill Development Feedback", tip: "External feedback is the fastest accelerator of skill growth." },
    ],
  },

  parent: {
    performance: [
      { id: 1, text: "is performing at or near their potential based on the effort they actually put in.", domain: "effort_output", domainLabel: "Effort vs. Output Alignment", tip: "A large effort-output gap often signals learning style mismatch, not ability." },
      { id: 2, text: "has a consistent study routine that supports their academic performance.", domain: "study_routine", domainLabel: "Study Routine Consistency", tip: "Routine consistency predicts academic improvement more than study duration." },
      { id: 3, text: "understands subject content well enough to explain it in their own words.", domain: "comprehension", domainLabel: "Subject Comprehension Depth", tip: "Paraphrase ability is the most reliable indicator of true understanding." },
      { id: 4, text: "asks for help when struggling rather than going silent and falling further behind.", domain: "help_seeking", domainLabel: "Help-Seeking Behaviour", tip: "Help-seeking behaviour is the strongest predictor of academic recovery." },
      { id: 5, text: "performs consistently across subjects rather than having extreme highs and lows.", domain: "consistency", domainLabel: "Cross-Subject Consistency", tip: "Extreme variation signals a preference or environmental factor worth exploring." },
      { id: 6, text: "learns from errors in tests rather than repeating the same mistakes.", domain: "error_learning", domainLabel: "Error-Based Learning", tip: "Students who review errors improve 40% faster than those who don't." },
      { id: 7, text: "takes school assessments seriously and prepares adequately before each one.", domain: "assessment_seriousness", domainLabel: "Assessment Preparation Seriousness", tip: "Attitude toward assessments predicts grade trajectory more than baseline ability." },
      { id: 8, text: "is aware of their own academic strengths and what needs more attention.", domain: "self_awareness", domainLabel: "Academic Self-Awareness", tip: "Self-aware learners set more effective study priorities." },
      { id: 9, text: "responds well to encouragement and constructive feedback about their studies from me.", domain: "feedback_receptivity", domainLabel: "Feedback Receptivity", tip: "Receptivity to parental support is linked to stronger teacher-parent outcomes." },
      { id: 10, text: "shows gradual improvement over the term rather than stagnating or declining.", domain: "growth_trend", domainLabel: "Academic Growth Trend", tip: "Positive trajectory — not absolute level — is the most encouraging indicator." },
    ],
    stress: [
      { id: 1, text: "shows healthy physical signs — good appetite, regular sleep, normal energy — before exams.", domain: "physical_stress", domainLabel: "Physical Stress Indicators", tip: "Physical signals are the earliest detectable signs of exam-related distress." },
      { id: 2, text: "talks openly to me about how they're feeling in the lead-up to tests.", domain: "communication", domainLabel: "Exam Stress Communication", tip: "Open parent-child dialogue about stress halves its negative academic impact." },
      { id: 3, text: "can study productively in the days before an exam rather than shutting down.", domain: "productive_revision", domainLabel: "Pre-Exam Productive Revision", tip: "Shutdown before exams is an anxiety pattern, not a work-ethic one." },
      { id: 4, text: "avoids catastrophising — thinking 'I'll fail everything' — before or after a test.", domain: "catastrophising", domainLabel: "Catastrophising Pattern", tip: "Cognitive catastrophising in children responds well to structured reframing." },
      { id: 5, text: "recovers emotionally after a disappointing result within a reasonable time.", domain: "result_recovery", domainLabel: "Post-Result Emotional Recovery", tip: "Recovery speed is a strong indicator of long-term academic resilience." },
      { id: 6, text: "manages the transition between consecutive exams without carrying stress from one to the next.", domain: "cross_exam_reset", domainLabel: "Inter-Exam Reset", tip: "Children who can reset between exams outperform those who cannot by 12%." },
      { id: 7, text: "maintains healthy study-rest balance during exam periods — doesn't study 12+ hours daily.", domain: "study_balance", domainLabel: "Study-Rest Balance", tip: "Sleep and rest are performance inputs, not rewards — this distinction matters." },
      { id: 8, text: "feels genuinely supported by me and school during high-pressure periods.", domain: "support_felt", domainLabel: "Perceived Support", tip: "Perceived support from parents is the #1 buffer against exam anxiety." },
      { id: 9, text: "approaches exams with belief in their preparation rather than fear of failure.", domain: "preparation_belief", domainLabel: "Preparation Belief", tip: "Preparation belief — not actual preparation — most strongly predicts exam performance." },
      { id: 10, text: "shows stable, consistent behaviour at home regardless of whether exams are near.", domain: "baseline_behaviour", domainLabel: "Baseline Emotional Stability", tip: "Exam-driven behavioural swings signal high anxiety and need early intervention." },
    ],
    distraction: [
      { id: 1, text: "puts away devices when it is time to study without me having to enforce it each time.", domain: "device_selfcontrol", domainLabel: "Device Self-Control", tip: "Self-initiated device control is 3x more durable than parent-enforced rules." },
      { id: 2, text: "has a consistent, quiet study space that minimises environmental distraction.", domain: "environment", domainLabel: "Study Environment Quality", tip: "Environment design reduces the need for willpower by 40%." },
      { id: 3, text: "sustains focus during homework for 20–30 minutes before taking a break.", domain: "focus_duration", domainLabel: "Sustained Homework Focus", tip: "Sustained focus duration is trainable in children through gradual extension." },
      { id: 4, text: "does not spend excessive time on social media or gaming during school days.", domain: "screen_time", domainLabel: "Healthy Screen Time", tip: "More than 3 hours of recreational screen time daily reduces academic output by 20%." },
      { id: 5, text: "responds positively when I ask them to put away distractions — without significant conflict.", domain: "compliance", domainLabel: "Distraction Compliance", tip: "Conflict around device limits is normal — the skill is in reducing escalation." },
      { id: 6, text: "understands and takes seriously the impact distraction has on their own learning.", domain: "impact_awareness", domainLabel: "Distraction Impact Awareness", tip: "Children who understand the impact self-regulate 2x more effectively." },
      { id: 7, text: "follows a homework or study schedule without needing to be reminded every day.", domain: "schedule_adherence", domainLabel: "Study Schedule Adherence", tip: "Consistent schedule adherence predicts long-term academic performance." },
      { id: 8, text: "prioritises completing learning tasks over entertainment during study time.", domain: "learning_priority", domainLabel: "Learning vs. Entertainment Priority", tip: "Prioritisation is a value — it is shaped by the home environment significantly." },
      { id: 9, text: "avoids multitasking — does not text or browse while revising.", domain: "multitasking", domainLabel: "Study Multitasking", tip: "Multitasking during study reduces content retention by 25%." },
      { id: 10, text: "recognises they feel clearer and more capable after focused study vs. distracted study.", domain: "self_recognition", domainLabel: "Focus vs. Distraction Self-Awareness", tip: "Self-recognition of focus benefits is the strongest motivator of self-regulation." },
    ],
    motivation: [
      { id: 1, text: "initiates studying on their own, without me having to remind them daily.", domain: "initiation", domainLabel: "Study Initiation", tip: "Self-initiated study is associated with 34% stronger academic outcomes." },
      { id: 2, text: "shows genuine interest in at least some of what they study.", domain: "interest", domainLabel: "Subject Interest", tip: "Even partial subject interest lifts overall study quality significantly." },
      { id: 3, text: "has a reason they care about doing well that goes beyond avoiding trouble at home.", domain: "intrinsic_purpose", domainLabel: "Intrinsic Purpose", tip: "Intrinsic purpose is the most durable motivational fuel a child can have." },
      { id: 4, text: "sets their own study goals and feels personally accountable to them.", domain: "self_goals", domainLabel: "Self-Set Goals", tip: "Self-set goals are 2x more motivating than parent-assigned targets." },
      { id: 5, text: "responds positively to encouragement rather than dismissing or ignoring it.", domain: "encouragement_response", domainLabel: "Response to Encouragement", tip: "Receptivity to encouragement indicates healthy parental attachment." },
      { id: 6, text: "bounces back after setbacks — bad marks, difficult topics — without giving up.", domain: "academic_resilience", domainLabel: "Academic Resilience", tip: "Academic resilience is teachable and is the strongest predictor of long-term success." },
      { id: 7, text: "believes that hard work leads to improvement — that effort matters.", domain: "effort_belief", domainLabel: "Effort-Outcome Belief", tip: "Effort belief (growth mindset) is the core lever of academic motivation." },
      { id: 8, text: "talks about future goals or aspirations that are connected to academic effort.", domain: "future_orientation", domainLabel: "Future Orientation", tip: "Children with a vision of the future study with 40% more consistency." },
      { id: 9, text: "engages in self-directed learning beyond school — reading, curiosity, projects.", domain: "self_directed", domainLabel: "Self-Directed Learning", tip: "Self-directed learners in school become independent thinkers as adults." },
      { id: 10, text: "shows a general attitude of trying and persisting rather than giving up quickly.", domain: "growth_attitude", domainLabel: "Growth Mindset Indicators", tip: "Growth mindset is the single most predictive factor of academic improvement." },
    ],
  },

  professional: {
    leadership: [
      { id: 1, text: "set a clear team direction that members understand and can act on independently.", domain: "direction", domainLabel: "Strategic Direction Setting", tip: "Teams with clear direction outperform by 31% — clarity is a leadership output." },
      { id: 2, text: "delegate tasks based on team members' strengths and development needs, not convenience.", domain: "delegation", domainLabel: "Strength-Based Delegation", tip: "Strength-based delegation drives 23% higher team productivity." },
      { id: 3, text: "give feedback that visibly changes behaviour rather than just conveying information.", domain: "feedback_impact", domainLabel: "Behaviour-Changing Feedback", tip: "Effective feedback is specific, timely, and tied to observable outcomes." },
      { id: 4, text: "create an environment where team members feel safe to raise problems and bad news early.", domain: "psychological_safety", domainLabel: "Psychological Safety", tip: "Psychological safety is the #1 predictor of team innovation and performance." },
      { id: 5, text: "coach team members toward solutions rather than solving problems for them.", domain: "coaching", domainLabel: "Coaching vs. Solving", tip: "Coaching builds capability — solving builds dependency." },
      { id: 6, text: "manage poor performance directly and professionally rather than avoiding it.", domain: "performance_mgmt", domainLabel: "Performance Management Courage", tip: "Avoiding performance conversations is cited by 64% of employees as deeply demotivating." },
      { id: 7, text: "build a team culture that persists even when I'm not in the room.", domain: "culture", domainLabel: "Culture Building", tip: "Culture that depends on the leader's presence is not a culture — it is compliance." },
      { id: 8, text: "earn trust and respect through my actions, not just my title or position.", domain: "trust", domainLabel: "Trust Earned Through Action", tip: "Title-earned authority lasts months. Action-earned trust lasts careers." },
      { id: 9, text: "handle situations where a team member's personal issues are affecting team performance.", domain: "personal_support", domainLabel: "Personal-Professional Balance", tip: "Boundary-aware support distinguishes great leaders from merely competent ones." },
      { id: 10, text: "lead team meetings that are efficient and consistently produce clear, actionable outcomes.", domain: "meeting_leadership", domainLabel: "Meeting Leadership Effectiveness", tip: "Meeting quality is rated the #1 cultural indicator by high-performing teams." },
    ],
    growth: [
      { id: 1, text: "feel clear about where I want to be in my career 3–5 years from now.", domain: "career_vision", domainLabel: "Career Vision Clarity", tip: "Professionals with clear vision take more targeted, effective career actions." },
      { id: 2, text: "have regular, substantive conversations with my manager about my career development.", domain: "career_dialogue", domainLabel: "Career Development Dialogue", tip: "Development conversations quadruple promotion probability within 2 years." },
      { id: 3, text: "proactively seek out stretch projects and responsibilities beyond my current role.", domain: "stretch_seeking", domainLabel: "Stretch Opportunity Seeking", tip: "Stretch assignment experience is the #1 predictor of executive readiness." },
      { id: 4, text: "build skills that increase my value both in my current role and future roles.", domain: "skill_building", domainLabel: "Forward-Looking Skill Building", tip: "Future-relevant skills grow salary 15% faster over a 5-year period." },
      { id: 5, text: "feel my current role provides experiences that are developing my career.", domain: "role_development", domainLabel: "Role as Development Vehicle", tip: "When roles stop developing people, top performers leave within 18 months." },
      { id: 6, text: "take active steps to advance my career rather than waiting to be noticed.", domain: "proactive_career", domainLabel: "Proactive Career Management", tip: "Career proactivity doubles promotion speed compared to passive performance." },
      { id: 7, text: "build a professional network beyond my immediate team and organisation.", domain: "network", domainLabel: "Professional Network Building", tip: "75% of senior roles are filled through networks — not job boards." },
      { id: 8, text: "seek and act on feedback about how I'm perceived and what I need to develop.", domain: "feedback_seeking", domainLabel: "Development Feedback Seeking", tip: "Feedback-seeking professionals grow skills 2x faster than those who don't." },
      { id: 9, text: "balance delivering strong results in my current role with investing in my future growth.", domain: "current_vs_future", domainLabel: "Current vs. Future Investment Balance", tip: "Over-investing in the present stalls careers; balance is the key." },
      { id: 10, text: "feel energised and genuinely engaged by my work most days.", domain: "engagement", domainLabel: "Work Engagement", tip: "Sustained engagement is the clearest signal of career-role fit." },
    ],
    conflict: [
      { id: 1, text: "address conflict directly and early rather than avoiding it until it escalates.", domain: "early_address", domainLabel: "Early Conflict Addressing", tip: "Conflicts addressed within 48 hours resolve in 3x fewer interactions." },
      { id: 2, text: "have difficult conversations — performance, behaviour, disagreements — without damaging the relationship.", domain: "difficult_convos", domainLabel: "Relationship-Preserving Confrontation", tip: "The ability to confront without rupture is the defining mark of a senior leader." },
      { id: 3, text: "stay calm and constructive when I'm challenged or disagreed with in a meeting.", domain: "challenge_response", domainLabel: "Challenge Response", tip: "Composure under challenge raises perceived credibility by 40%." },
      { id: 4, text: "separate the person from the issue in a conflict — I don't make it personal.", domain: "depersonalisation", domainLabel: "Conflict Depersonalisation", tip: "Issue-focused conflict resolves 60% faster than person-focused conflict." },
      { id: 5, text: "genuinely understand the other person's perspective before advocating for my own.", domain: "empathy", domainLabel: "Conflict Empathy", tip: "Perspective-taking before advocating reduces conflict duration by 50%." },
      { id: 6, text: "professionally handle a peer or stakeholder who is being unreasonable or obstructive.", domain: "difficult_stakeholder", domainLabel: "Difficult Stakeholder Management", tip: "Stakeholder management under pressure is the #1 tested executive skill." },
      { id: 7, text: "express frustration directly and constructively rather than through passive-aggressive behaviour.", domain: "directness", domainLabel: "Constructive Directness", tip: "Passive aggression is 3x more corrosive to team trust than direct conflict." },
      { id: 8, text: "actively repair and rebuild relationships after a conflict has been resolved.", domain: "repair", domainLabel: "Post-Conflict Relationship Repair", tip: "Post-conflict repair converts adversaries into allies — most leaders skip it." },
      { id: 9, text: "disagree with my manager or senior leader effectively without damaging the relationship.", domain: "upward_conflict", domainLabel: "Managing Up in Conflict", tip: "Upward disagreement skill is the most career-limiting gap in talented professionals." },
      { id: 10, text: "believe that conflict, when handled well, consistently leads to better outcomes.", domain: "conflict_belief", domainLabel: "Productive Conflict Belief", tip: "Leaders who believe in productive conflict build 30% more innovative teams." },
    ],
    burnout: [
      { id: 1, text: "finish work at a reasonable time most days without it consistently spilling into evenings.", domain: "work_hours", domainLabel: "Work Hours Boundaries", tip: "Chronic overwork beyond 50 hours/week reduces productivity by 25%." },
      { id: 2, text: "feel genuinely refreshed after weekends and leave rather than dreading Monday.", domain: "rest_quality", domainLabel: "Rest & Recovery Quality", tip: "True rest — not just rest from office — is the most restorative recovery type." },
      { id: 3, text: "disconnect mentally from work during non-work time rather than constantly checking messages.", domain: "mental_disconnect", domainLabel: "Mental Disconnection", tip: "Always-on professionals are 2x more likely to burn out within 3 years." },
      { id: 4, text: "maintain consistent energy and enthusiasm for work across the full working week.", domain: "sustained_energy", domainLabel: "Sustained Work Energy", tip: "Energy management — not time management — is the key lever against burnout." },
      { id: 5, text: "recognise early burnout warning signs in myself — irritability, numbness, errors — and act.", domain: "self_awareness", domainLabel: "Burnout Early Warning Recognition", tip: "Early recognition reduces burnout severity by 60% compared to late-stage recognition." },
      { id: 6, text: "feel that my workload is manageable, not chronically overwhelming.", domain: "workload_manageability", domainLabel: "Workload Manageability", tip: "Sustained unmanageable workload is the primary structural cause of burnout." },
      { id: 7, text: "have genuine interests and activities outside work that actively restore my energy.", domain: "recovery_activities", domainLabel: "Recovery Activities", tip: "Active recovery is 3x more restorative than passive recovery (TV, scrolling)." },
      { id: 8, text: "say no to additional work when I'm already at capacity — without excessive guilt.", domain: "boundary_setting", domainLabel: "Boundary Setting Without Guilt", tip: "Guilt-free boundary setting is a learned skill — and the core of sustainable performance." },
      { id: 9, text: "feel that my effort is recognised and that my work genuinely matters.", domain: "recognition", domainLabel: "Work Meaning & Recognition", tip: "Lack of recognition doubles burnout risk, independent of workload." },
      { id: 10, text: "seek support — manager, mentor, HR, or therapist — when I notice I'm struggling.", domain: "help_seeking", domainLabel: "Help-Seeking for Wellbeing", tip: "Help-seeking is a sign of strength, not weakness — and dramatically shortens recovery." },
    ],
  },
};
