import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useToast } from "@/hooks/use-toast";
import { Plus, FileText, Clock, CheckCircle, XCircle, AlertCircle, Calendar, Target, Eye, ThumbsUp, ThumbsDown, Send, Users, GraduationCap } from "lucide-react";

interface Test {
  id: string;
  testCode: string;
  testName: string;
  testType: string;
  duration: number;
  totalMarks: number;
  passingMarks: number;
  workflowStatus: string;
  isAutoGenerated: boolean;
  createdAt: string;
  createdBy: string;
}

interface Props {
  instituteId: string;
  instituteName: string;
  userRole: 'superadmin' | 'teacher' | 'admin';
}

export function InstituteTestWorkflow({ instituteId, instituteName, userRole }: Props) {
  const { toast } = useToast();
  
  const [tests, setTests] = useState<Test[]>([]);
  const [pendingApprovalTests, setPendingApprovalTests] = useState<Test[]>([]);
  const [selectedTest, setSelectedTest] = useState<Test | null>(null);
  const [isReviewOpen, setIsReviewOpen] = useState(false);
  const [reviewComments, setReviewComments] = useState('');
  const [isAssignOpen, setIsAssignOpen] = useState(false);
  const [selectedBatch, setSelectedBatch] = useState('');
  const [assignStartDate, setAssignStartDate] = useState('');
  const [assignEndDate, setAssignEndDate] = useState('');
  
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState(false);
  
  useEffect(() => {
    fetchTests();
    if (userRole === 'superadmin' || userRole === 'admin') {
      fetchPendingApprovalTests();
    }
  }, [instituteId, userRole]);
  
  const fetchTests = async () => {
    try {
      const response = await fetch('/api/tests/my-tests', {
        credentials: 'include'
      });
      if (response.ok) {
        const data = await response.json();
        setTests(data);
      }
    } catch (error) {
      console.error('Failed to fetch tests:', error);
    }
    setLoading(false);
  };
  
  const fetchPendingApprovalTests = async () => {
    try {
      const response = await fetch(`/api/institute/${instituteId}/tests/pending-approval`, {
        credentials: 'include'
      });
      if (response.ok) {
        const data = await response.json();
        setPendingApprovalTests(data);
      }
    } catch (error) {
      console.error('Failed to fetch pending tests:', error);
    }
  };
  
  const submitForReview = async (testId: string) => {
    setProcessing(true);
    try {
      const response = await fetch(`/api/tests/${testId}/submit-for-review`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ comments: 'Submitted for review' })
      });
      
      if (response.ok) {
        toast({ title: 'Success', description: 'Test submitted for review' });
        fetchTests();
      }
    } catch (error) {
      toast({ title: 'Error', description: 'Failed to submit for review', variant: 'destructive' });
    }
    setProcessing(false);
  };
  
  const approveTest = async () => {
    if (!selectedTest) return;
    
    setProcessing(true);
    try {
      const response = await fetch(`/api/tests/${selectedTest.id}/approve`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ comments: reviewComments })
      });
      
      if (response.ok) {
        toast({ title: 'Success', description: 'Test approved successfully' });
        setIsReviewOpen(false);
        setReviewComments('');
        fetchTests();
        fetchPendingApprovalTests();
      }
    } catch (error) {
      toast({ title: 'Error', description: 'Failed to approve test', variant: 'destructive' });
    }
    setProcessing(false);
  };
  
  const rejectTest = async () => {
    if (!selectedTest) return;
    if (!reviewComments.trim()) {
      toast({ title: 'Error', description: 'Please provide rejection reason', variant: 'destructive' });
      return;
    }
    
    setProcessing(true);
    try {
      const response = await fetch(`/api/tests/${selectedTest.id}/reject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ comments: reviewComments })
      });
      
      if (response.ok) {
        toast({ title: 'Success', description: 'Test rejected' });
        setIsReviewOpen(false);
        setReviewComments('');
        fetchTests();
        fetchPendingApprovalTests();
      }
    } catch (error) {
      toast({ title: 'Error', description: 'Failed to reject test', variant: 'destructive' });
    }
    setProcessing(false);
  };
  
  const assignTest = async () => {
    if (!selectedTest) return;
    
    setProcessing(true);
    try {
      const response = await fetch(`/api/tests/${selectedTest.id}/assign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          batchId: selectedBatch || undefined,
          startDate: assignStartDate || undefined,
          endDate: assignEndDate || undefined
        })
      });
      
      if (response.ok) {
        toast({ title: 'Success', description: 'Test assigned successfully' });
        setIsAssignOpen(false);
        fetchTests();
      }
    } catch (error) {
      toast({ title: 'Error', description: 'Failed to assign test', variant: 'destructive' });
    }
    setProcessing(false);
  };
  
  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'Draft':
        return <Badge variant="outline" className="bg-gray-100 text-gray-700">Draft</Badge>;
      case 'Pending Review':
        return <Badge variant="outline" className="bg-yellow-100 text-yellow-700">Pending Review</Badge>;
      case 'Approved':
        return <Badge variant="outline" className="bg-teal-100 text-teal-700">Approved</Badge>;
      case 'Rejected':
        return <Badge variant="outline" className="bg-red-100 text-red-700">Rejected</Badge>;
      case 'Assigned':
        return <Badge variant="outline" className="bg-blue-100 text-blue-700">Assigned</Badge>;
      default:
        return <Badge variant="outline">{status}</Badge>;
    }
  };
  
  const canApprove = userRole === 'superadmin' || userRole === 'admin';
  
  return (
    <div className="space-y-6" data-testid="institute-test-workflow">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-[#0B3C5D]" data-testid="workflow-title">
            Test Management - {instituteName}
          </h2>
          <p className="text-sm text-muted-foreground">Create, review, approve, and assign tests</p>
        </div>
      </div>
      
      <Tabs defaultValue="my-tests" className="w-full">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="my-tests" className="flex items-center gap-2" data-testid="tab-my-tests">
            <FileText className="h-4 w-4" />
            My Tests ({tests.length})
          </TabsTrigger>
          {canApprove && (
            <TabsTrigger value="pending-approval" className="flex items-center gap-2" data-testid="tab-pending-approval">
              <AlertCircle className="h-4 w-4" />
              Pending Approval ({pendingApprovalTests.length})
            </TabsTrigger>
          )}
        </TabsList>
        
        <TabsContent value="my-tests" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <FileText className="h-5 w-5 text-[#0B3C5D]" />
                Test Workflow Status
              </CardTitle>
              <CardDescription>
                Tests follow: Draft → Submit for Review → Approved/Rejected → Assigned
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-5 gap-4 text-center">
                <div className="p-3 bg-gray-50 rounded-lg">
                  <div className="text-2xl font-bold text-gray-600">
                    {tests.filter(t => t.workflowStatus === 'Draft').length}
                  </div>
                  <div className="text-xs text-muted-foreground">Draft</div>
                </div>
                <div className="p-3 bg-yellow-50 rounded-lg">
                  <div className="text-2xl font-bold text-yellow-600">
                    {tests.filter(t => t.workflowStatus === 'Pending Review').length}
                  </div>
                  <div className="text-xs text-muted-foreground">Pending Review</div>
                </div>
                <div className="p-3 bg-teal-50 rounded-lg">
                  <div className="text-2xl font-bold text-teal-600">
                    {tests.filter(t => t.workflowStatus === 'Approved').length}
                  </div>
                  <div className="text-xs text-muted-foreground">Approved</div>
                </div>
                <div className="p-3 bg-red-50 rounded-lg">
                  <div className="text-2xl font-bold text-red-600">
                    {tests.filter(t => t.workflowStatus === 'Rejected').length}
                  </div>
                  <div className="text-xs text-muted-foreground">Rejected</div>
                </div>
                <div className="p-3 bg-blue-50 rounded-lg">
                  <div className="text-2xl font-bold text-blue-600">
                    {tests.filter(t => t.workflowStatus === 'Assigned').length}
                  </div>
                  <div className="text-xs text-muted-foreground">Assigned</div>
                </div>
              </div>
            </CardContent>
          </Card>
          
          <ScrollArea className="h-[400px]">
            <div className="space-y-3">
              {tests.length === 0 ? (
                <Card className="border-dashed">
                  <CardContent className="py-8 text-center text-muted-foreground">
                    <FileText className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                    <p>No tests created yet. Create your first test to get started!</p>
                  </CardContent>
                </Card>
              ) : (
                tests.map(test => (
                  <Card key={test.id} className="hover:shadow-md transition-shadow" data-testid={`test-workflow-card-${test.id}`}>
                    <CardContent className="py-4">
                      <div className="flex items-start justify-between">
                        <div>
                          <div className="flex items-center gap-2">
                            <h4 className="font-medium">{test.testName}</h4>
                            {getStatusBadge(test.workflowStatus)}
                          </div>
                          <p className="text-sm text-muted-foreground mt-1">Code: {test.testCode}</p>
                          <div className="flex gap-2 mt-2">
                            <Badge variant="outline" className="text-xs">{test.testType}</Badge>
                            <Badge variant="outline" className="text-xs">
                              <Clock className="h-3 w-3 mr-1" />{test.duration} min
                            </Badge>
                            <Badge variant="outline" className="text-xs">
                              <Target className="h-3 w-3 mr-1" />{test.totalMarks} marks
                            </Badge>
                          </div>
                        </div>
                        <div className="flex gap-2">
                          {test.workflowStatus === 'Draft' && (
                            <Button 
                              size="sm" 
                              variant="outline"
                              onClick={() => submitForReview(test.id)}
                              disabled={processing}
                              data-testid={`btn-submit-review-${test.id}`}
                            >
                              <Send className="h-4 w-4 mr-1" />
                              Submit for Review
                            </Button>
                          )}
                          {test.workflowStatus === 'Approved' && (
                            <Button 
                              size="sm" 
                              className="bg-[#4ECDC4] hover:bg-[#4ECDC4]/90"
                              onClick={() => {
                                setSelectedTest(test);
                                setIsAssignOpen(true);
                              }}
                              data-testid={`btn-assign-${test.id}`}
                            >
                              <Users className="h-4 w-4 mr-1" />
                              Assign
                            </Button>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          </ScrollArea>
        </TabsContent>
        
        {canApprove && (
          <TabsContent value="pending-approval" className="space-y-4 mt-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <AlertCircle className="h-5 w-5 text-yellow-500" />
                  Tests Awaiting Your Approval
                </CardTitle>
                <CardDescription>
                  Review and approve/reject tests submitted by teachers
                </CardDescription>
              </CardHeader>
            </Card>
            
            <ScrollArea className="h-[400px]">
              <div className="space-y-3">
                {pendingApprovalTests.length === 0 ? (
                  <Card className="border-dashed">
                    <CardContent className="py-8 text-center text-muted-foreground">
                      <CheckCircle className="h-12 w-12 mx-auto mb-4 text-teal-300" />
                      <p>No tests pending approval. All caught up!</p>
                    </CardContent>
                  </Card>
                ) : (
                  pendingApprovalTests.map(test => (
                    <Card key={test.id} className="hover:shadow-md transition-shadow border-yellow-200" data-testid={`pending-test-${test.id}`}>
                      <CardContent className="py-4">
                        <div className="flex items-start justify-between">
                          <div>
                            <div className="flex items-center gap-2">
                              <h4 className="font-medium">{test.testName}</h4>
                              <Badge variant="outline" className="bg-yellow-100 text-yellow-700">
                                Pending Review
                              </Badge>
                            </div>
                            <p className="text-sm text-muted-foreground mt-1">
                              Code: {test.testCode} | Created: {new Date(test.createdAt).toLocaleDateString()}
                            </p>
                            <div className="flex gap-2 mt-2">
                              <Badge variant="outline" className="text-xs">{test.testType}</Badge>
                              <Badge variant="outline" className="text-xs">
                                {test.totalMarks} marks | Pass: {test.passingMarks}
                              </Badge>
                            </div>
                          </div>
                          <div className="flex gap-2">
                            <Button 
                              size="sm" 
                              variant="outline"
                              onClick={() => {
                                setSelectedTest(test);
                                setIsReviewOpen(true);
                              }}
                              data-testid={`btn-review-${test.id}`}
                            >
                              <Eye className="h-4 w-4 mr-1" />
                              Review
                            </Button>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))
                )}
              </div>
            </ScrollArea>
          </TabsContent>
        )}
      </Tabs>
      
      <Dialog open={isReviewOpen} onOpenChange={setIsReviewOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Review Test</DialogTitle>
            <DialogDescription>
              {selectedTest?.testName}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="bg-gray-50 p-4 rounded-lg space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Test Type:</span>
                <span className="font-medium">{selectedTest?.testType}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Duration:</span>
                <span className="font-medium">{selectedTest?.duration} minutes</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Total Marks:</span>
                <span className="font-medium">{selectedTest?.totalMarks}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Passing Marks:</span>
                <span className="font-medium">{selectedTest?.passingMarks}</span>
              </div>
            </div>
            
            <div className="space-y-2">
              <Label>Review Comments</Label>
              <Textarea 
                value={reviewComments}
                onChange={(e) => setReviewComments(e.target.value)}
                placeholder="Add comments for approval/rejection..."
                data-testid="input-review-comments"
              />
            </div>
          </div>
          <DialogFooter className="flex gap-2">
            <Button 
              variant="outline" 
              onClick={rejectTest}
              disabled={processing}
              className="border-red-300 text-red-600 hover:bg-red-50"
              data-testid="btn-reject-test"
            >
              <ThumbsDown className="h-4 w-4 mr-1" />
              Reject
            </Button>
            <Button 
              onClick={approveTest}
              disabled={processing}
              className="bg-teal-600 hover:bg-teal-700"
              data-testid="btn-approve-test"
            >
              <ThumbsUp className="h-4 w-4 mr-1" />
              Approve
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      
      <Dialog open={isAssignOpen} onOpenChange={setIsAssignOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Assign Test</DialogTitle>
            <DialogDescription>
              Assign "{selectedTest?.testName}" to students
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Select Batch (Optional)</Label>
              <Select value={selectedBatch} onValueChange={setSelectedBatch}>
                <SelectTrigger data-testid="select-batch">
                  <SelectValue placeholder="All students or select batch" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Students</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Start Date</Label>
                <Input 
                  type="date"
                  value={assignStartDate}
                  onChange={(e) => setAssignStartDate(e.target.value)}
                  data-testid="input-start-date"
                />
              </div>
              <div className="space-y-2">
                <Label>End Date</Label>
                <Input 
                  type="date"
                  value={assignEndDate}
                  onChange={(e) => setAssignEndDate(e.target.value)}
                  data-testid="input-end-date"
                />
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsAssignOpen(false)}>Cancel</Button>
            <Button 
              onClick={assignTest}
              disabled={processing}
              className="bg-[#4ECDC4] hover:bg-[#4ECDC4]/90"
              data-testid="btn-confirm-assign"
            >
              {processing ? 'Assigning...' : 'Assign Test'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
