import { BRAND_NAVY as BRAND } from '@/design-system/tokens';
import { useState } from 'react';
import { FileText, Download, TrendingUp, AlertCircle, CheckCircle, Sparkles, ChevronDown, ChevronUp } from 'lucide-react';

interface DigestData {
  childName: string;
  weekLabel: string;
  examsCompleted: number;
  avgScore: number;
  scoreChange: number;
  tasksCompleted: number;
  tasksPending: number;
  topSubject: string;
  weakSubject: string;
  lbiInsight?: string;
  nextSteps: string[];
  mentorSessions: number;
}

interface Props {
  data: DigestData;
}



export function WeeklyInsightDigest({ data }: Props) {
  const [expanded, setExpanded] = useState(false);

  const handleDownload = () => {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Weekly Insight Digest – ${data.childName}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 680px; margin: 40px auto; padding: 0 20px; color: #1e293b; }
  .header { background: #0B3C5D; color: white; border-radius: 16px; padding: 28px 32px; margin-bottom: 24px; }
  .header h1 { margin: 0 0 4px; font-size: 22px; }
  .header p  { margin: 0; opacity: 0.8; font-size: 14px; }
  .grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 16px; margin-bottom: 24px; }
  .kpi { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; text-align: center; }
  .kpi .val { font-size: 28px; font-weight: 700; color: #0B3C5D; }
  .kpi .lbl { font-size: 11px; color: #64748b; margin-top: 4px; }
  .section { margin-bottom: 20px; }
  .section h3 { font-size: 14px; font-weight: 600; color: #0B3C5D; margin: 0 0 10px; border-bottom: 2px solid #4ECDC4; padding-bottom: 6px; }
  .tag { display: inline-block; background: rgba(11,60,93,0.1); color: #0B3C5D; border-radius: 20px; padding: 3px 10px; font-size: 11px; margin: 3px; }
  .tag.teal { background: rgba(78,205,196,0.15); color: #4ECDC4; }
  .step { padding: 8px 0; border-bottom: 1px solid #f1f5f9; font-size: 13px; color: #475569; }
  .step:before { content: "→ "; color: #4ECDC4; font-weight: bold; }
  .footer { text-align: center; font-size: 11px; color: #94a3b8; margin-top: 32px; }
</style>
</head>
<body>
<div class="header">
  <h1>Weekly Insight Digest</h1>
  <p>${data.childName} · ${data.weekLabel}</p>
</div>
<div class="grid">
  <div class="kpi"><div class="val">${data.examsCompleted}</div><div class="lbl">Assessments Done</div></div>
  <div class="kpi"><div class="val">${data.avgScore}%</div><div class="lbl">Average Score</div></div>
  <div class="kpi"><div class="val">${data.mentorSessions}</div><div class="lbl">Mentor Sessions</div></div>
</div>
<div class="section">
  <h3>Academic Summary</h3>
  <span class="tag">Top: ${data.topSubject}</span>
  <span class="tag" style="background:rgba(239,68,68,0.1);color:#DC2626">Needs Work: ${data.weakSubject}</span>
  <span class="tag teal">Tasks Done: ${data.tasksCompleted}</span>
  <span class="tag">Pending: ${data.tasksPending}</span>
  ${data.scoreChange !== 0 ? `<span class="tag" style="background:${data.scoreChange > 0 ? 'rgba(78,205,196,0.1)' : 'rgba(239,68,68,0.1)'};color:${data.scoreChange > 0 ? '#4ECDC4' : '#DC2626'}">${data.scoreChange > 0 ? '▲' : '▼'} ${Math.abs(data.scoreChange)}% vs last week</span>` : ''}
</div>
${data.lbiInsight ? `<div class="section"><h3>Behavioral Insight</h3><p style="font-size:13px;color:#475569;line-height:1.6">${data.lbiInsight}</p></div>` : ''}
<div class="section">
  <h3>Next Steps</h3>
  ${data.nextSteps.map(s => `<div class="step">${s}</div>`).join('')}
</div>
<div class="footer">Generated by MetryxOne · Behavioral Intelligence Platform · ${new Date().toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MetryxOne_Digest_${data.childName.replace(/\s+/g, '_')}_${data.weekLabel.replace(/\s+/g, '_')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-2xl border shadow-sm overflow-hidden" style={{ borderColor: 'rgba(11,60,93,0.12)' }}>
      <div
        className="px-5 py-3.5 flex items-center gap-2 cursor-pointer select-none"
        style={{ background: 'rgba(11,60,93,0.06) 100%)', borderBottom: expanded ? '1px solid rgba(11,60,93,0.08)' : 'none' }}
        onClick={() => setExpanded(e => !e)}
      >
        <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: BRAND.primary }}>
          <FileText size={13} className="text-white" />
        </div>
        <div className="flex-1">
          <span className="text-sm font-semibold" style={{ color: BRAND.primary }}>Weekly Insight Digest</span>
          <span className="text-[10px] text-gray-400 ml-2">{data.weekLabel}</span>
        </div>
        <button
          onClick={e => { e.stopPropagation(); handleDownload(); }}
          className="flex items-center gap-1 text-[10px] font-semibold px-2.5 py-1 rounded-lg text-white mr-2 hover:opacity-80 transition-opacity"
          style={{ background: BRAND.teal }}
        >
          <Download size={10} /> Download
        </button>
        {expanded ? <ChevronUp size={14} className="text-gray-400" /> : <ChevronDown size={14} className="text-gray-400" />}
      </div>

      {expanded && (
        <div className="p-5">
          {/* KPI row */}
          <div className="grid grid-cols-3 gap-3 mb-4">
            {[
              { val: data.examsCompleted, lbl: 'Assessments', icon: <CheckCircle size={13} style={{ color: BRAND.teal }} /> },
              { val: `${data.avgScore}%`, lbl: 'Avg Score', icon: <TrendingUp size={13} style={{ color: BRAND.primary }} /> },
              { val: data.mentorSessions, lbl: 'Mentor Sessions', icon: <Sparkles size={13} style={{ color: BRAND.primary }} /> },
            ].map((k, i) => (
              <div key={i} className="rounded-xl p-3 text-center" style={{ background: 'rgba(11,60,93,0.04)', border: '1px solid rgba(11,60,93,0.08)' }}>
                <div className="flex justify-center mb-1">{k.icon}</div>
                <div className="text-lg font-bold" style={{ color: BRAND.primary }}>{k.val}</div>
                <div className="text-[9px] text-gray-400">{k.lbl}</div>
              </div>
            ))}
          </div>

          {/* Score change */}
          {data.scoreChange !== 0 && (
            <div className="flex items-center gap-2 mb-3 px-3 py-2 rounded-xl" style={{ background: data.scoreChange > 0 ? 'rgba(78,205,196,0.08)' : 'rgba(11,60,93,0.06)' }}>
              {data.scoreChange > 0
                ? <TrendingUp size={13} style={{ color: BRAND.teal }} />
                : <AlertCircle size={13} style={{ color: BRAND.primary }} />}
              <span className="text-xs" style={{ color: BRAND.primary }}>
                Score {data.scoreChange > 0 ? 'improved' : 'dipped'} by {Math.abs(data.scoreChange)}% vs last week
              </span>
            </div>
          )}

          {/* Subjects */}
          <div className="flex flex-wrap gap-2 mb-4">
            <span className="text-[10px] px-2.5 py-1 rounded-full font-medium text-white" style={{ background: BRAND.teal }}>Top: {data.topSubject}</span>
            <span className="text-[10px] px-2.5 py-1 rounded-full font-medium" style={{ background: 'rgba(11,60,93,0.1)', color: BRAND.primary }}>Focus: {data.weakSubject}</span>
            <span className="text-[10px] px-2.5 py-1 rounded-full font-medium" style={{ background: 'rgba(11,60,93,0.06)', color: '#64748B' }}>{data.tasksCompleted} tasks done</span>
            {data.tasksPending > 0 && <span className="text-[10px] px-2.5 py-1 rounded-full font-medium" style={{ background: 'rgba(11,60,93,0.06)', color: '#64748B' }}>{data.tasksPending} pending</span>}
          </div>

          {/* LBI insight */}
          {data.lbiInsight && (
            <div className="mb-4 px-3 py-2.5 rounded-xl" style={{ background: 'rgba(78,205,196,0.06)', border: '1px solid rgba(78,205,196,0.2)' }}>
              <div className="flex items-center gap-1.5 mb-1">
                <Sparkles size={11} style={{ color: BRAND.teal }} />
                <span className="text-[10px] font-semibold" style={{ color: BRAND.teal }}>Behavioral Insight</span>
              </div>
              <p className="text-xs text-gray-600 leading-relaxed">{data.lbiInsight}</p>
            </div>
          )}

          {/* Next steps */}
          <div>
            <div className="text-[10px] font-semibold uppercase tracking-wider mb-2" style={{ color: BRAND.primary }}>Next Steps</div>
            <div className="space-y-1.5">
              {data.nextSteps.map((step, i) => (
                <div key={i} className="flex items-start gap-2 text-xs text-gray-600">
                  <span className="mt-0.5 text-[10px] font-bold" style={{ color: BRAND.teal }}>→</span>
                  {step}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export function buildDigestData(child: any, completedExams: any[], studyTasks: any[], bookedSessions: any[]): DigestData {
  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);

  const thisWeekExams = completedExams.filter(e => new Date(e.completedAt || e.created_at || 0) >= weekAgo);
  const lastWeekExams = completedExams.filter(e => {
    const d = new Date(e.completedAt || e.created_at || 0);
    return d >= twoWeeksAgo && d < weekAgo;
  });

  const avgThis = thisWeekExams.length ? Math.round(thisWeekExams.reduce((s, e) => s + (e.score || 0), 0) / thisWeekExams.length) : 0;
  const avgLast = lastWeekExams.length ? Math.round(lastWeekExams.reduce((s, e) => s + (e.score || 0), 0) / lastWeekExams.length) : 0;

  const subjectScores: Record<string, number[]> = {};
  completedExams.forEach(e => {
    if (e.subject) {
      if (!subjectScores[e.subject]) subjectScores[e.subject] = [];
      subjectScores[e.subject].push(e.score || 0);
    }
  });
  const subjectAvgs = Object.entries(subjectScores).map(([s, scores]) => ({ subject: s, avg: scores.reduce((a, b) => a + b, 0) / scores.length }));
  subjectAvgs.sort((a, b) => b.avg - a.avg);

  const done = studyTasks.filter(t => t.status === 'completed').length;
  const pending = studyTasks.filter(t => t.status !== 'completed').length;

  const weekLabel = now.toLocaleDateString('en-IN', { month: 'short', day: 'numeric' }) + ' Week';

  const nextSteps: string[] = [];
  if (pending > 0) nextSteps.push(`Complete ${pending} pending study task${pending > 1 ? 's' : ''} this week`);
  if (subjectAvgs.length > 1) nextSteps.push(`Focus extra sessions on ${subjectAvgs[subjectAvgs.length - 1]?.subject || 'weaker subjects'}`);
  if (bookedSessions.filter(s => s.status === 'upcoming').length === 0) nextSteps.push('Book a mentor session to keep momentum going');
  nextSteps.push('Review LBI insights to align study strategies with learning style');

  return {
    childName: child?.name || 'Child',
    weekLabel,
    examsCompleted: thisWeekExams.length || completedExams.length,
    avgScore: avgThis || Math.round(completedExams.reduce((s, e) => s + (e.score || 0), 0) / Math.max(completedExams.length, 1)),
    scoreChange: avgThis - avgLast,
    tasksCompleted: done,
    tasksPending: pending,
    topSubject: subjectAvgs[0]?.subject || (child?.favoriteSubjects?.[0]) || 'Mathematics',
    weakSubject: subjectAvgs[subjectAvgs.length - 1]?.subject || (child?.weakSubjects?.[0]) || 'Science',
    lbiInsight: child?.lbiConsent ? 'Behavioral data shows strong visual processing and analytical reasoning. Schedule structured revision sessions in the morning for peak retention.' : undefined,
    nextSteps: nextSteps.slice(0, 4),
    mentorSessions: bookedSessions.filter(s => {
      const d = new Date(s.scheduledAt || s.date || 0);
      return d >= weekAgo && d <= now;
    }).length,
  };
}
