/**
 * mx301-report-pack.ts — MX-301 Phase 3 (Option C, Enhanced Hybrid Enterprise
 * Validation): build a presentation-quality ENTERPRISE PACK of 16 reports for the
 * demonstration candidate Sarah Johnson, persist them into the live Report Factory
 * tables (so the super-admin Reports Console surfaces them), and export every report
 * in FOUR formats (PDF + HTML + JSON + CSV) under backend/audit/mx-301/report-pack/.
 *
 *   Provision candidate first: npx tsx backend/scripts/mx301-demo-candidate.ts
 *   Build the pack:            npx tsx backend/scripts/mx301-report-pack.ts
 *   Roll the pack back:        npx tsx backend/scripts/mx301-report-pack.ts --rollback
 *
 * Honesty / safety contract (same as the rest of MX-301):
 *   - REUSES existing engines + renderers only. No new/rebuilt engine. The composer
 *     (services/report-pack.ts) runs every engine ONCE and composes the fixed
 *     9-section enterprise layout; where an engine has no measurable input for Sarah
 *     the report renders a professional "Insufficient validated data" state — NEVER a
 *     blank chart, empty table, or fabricated number.
 *   - Coverage (measurable input) ⟂ Confidence (trustworthiness) ⟂ Activation (the
 *     report generated) are kept separate; null is never coerced to 0.
 *   - The no-empty guard (validatePack) FAILS the run if any report is structurally
 *     incomplete — the pack is never emitted half-built.
 *   - Every row is tagged `mx301` / tenant `mx301` and is fully purgeable via
 *     --rollback. No production data is touched. The candidate's email is masked to an
 *     irreversible pseudonym in every committed deliverable.
 *   - Interview enrichment is BEST-EFFORT demonstration INPUT (a real interview with
 *     real panel scores, tagged + purgeable); if the employer substrate cannot be
 *     provisioned the Interview Readiness report stays honestly empty — never forced.
 */
import { copyFileSync, mkdirSync, statSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { pathToFileURL, fileURLToPath } from 'url';

import pg from 'pg';

import {
  buildPackSnapshot,
  composePack,
  validatePack,
  maskSubject,
  MX301_ROLE_TITLE,
  MX301_DEMO_JOB_ID,
  type ComposedReport,
} from '../services/report-pack.js';
import {
  renderReportToPDF,
  renderReportToHTML,
  renderReportToCSV,
  renderReportToJSON,
  type WhiteLabelConfig,
} from '../services/pdf-renderer.js';
import { ensureReportFactorySchema } from '../services/report-factory-schema.js';
import { scheduleInterview, ensureInterviewSchema } from '../services/interview-engine.js';
import { recordScore, ensureScoreSchema, candidateEvaluation } from '../services/evaluation-engine.js';
import { buildEiProfile } from '../services/ei-profile-engine.js';
import {
  persistEiProfile,
  listEiProfileHistory,
  ensureEiProfileHistorySchema,
} from '../services/ei-profile-history.js';

import { MX301_SUBJECT } from './mx301-demo-candidate.js';

const { Pool } = pg;

const TENANT_ID = 'mx301';
const TEMPLATE_PREFIX = 'MX-301';

// MetryxOne enterprise white-label — deep navy primary, teal accent.
const WHITE_LABEL: WhiteLabelConfig = {
  org_name: 'MetryxOne',
  logo_url: null,
  primary_color: '#0B2447',
  secondary_color: '#19376D',
  accent_color: '#2E8B8B',
  text_color: '#111827',
  font_family: 'Inter, system-ui, sans-serif',
  report_header: 'MetryxOne — Behavioural Intelligence Platform',
  report_footer:
    'This report is a developmental tool generated by the MetryxOne Behavioural Intelligence Platform. ' +
    'It reports developmental signals only and is NOT for use in hiring, promotion, or suitability decisions.',
};

// ── small DB helpers ────────────────────────────────────────────────────────
async function tableExists(pool: pg.Pool, table: string): Promise<boolean> {
  const r = await pool.query(`SELECT to_regclass($1) AS reg`, [table]);
  return r.rows[0]?.reg != null;
}
async function columnExists(pool: pg.Pool, table: string, col: string): Promise<boolean> {
  const r = await pool.query(
    `SELECT 1 FROM information_schema.columns WHERE table_name = $1 AND column_name = $2 LIMIT 1`,
    [table, col],
  );
  return (r.rowCount ?? 0) > 0;
}

// ── rollback — purge every mx301-tagged Report Factory + enrichment row ──────
const RF_PURGE: { table: string; col: string; like: string }[] = [
  { table: 'rf_export_jobs', col: 'report_id', like: '' }, // handled via FK cascade; left for clarity
  { table: 'rf_generated_reports', col: 'tenant_id', like: TENANT_ID },
  { table: 'rf_generated_reports', col: 'user_id', like: `%${TENANT_ID}%` },
  { table: 'rf_templates', col: 'name', like: `${TEMPLATE_PREFIX}%` },
  { table: 'rf_white_label_configs', col: 'tenant_id', like: TENANT_ID },
  // interview enrichment (demonstration input)
  { table: 'interview_scores', col: 'candidate_id', like: `%${TENANT_ID}%` },
  { table: 'interview_schedules', col: 'candidate_id', like: `%${TENANT_ID}%` },
  { table: 'employer_candidates', col: 'id', like: `%${TENANT_ID}%` },
  { table: 'employer_jobs', col: 'id', like: `%${TENANT_ID}%` },
  // EI snapshot enrichment (demonstration input; tagged via captured_by)
  { table: 'ei_profile_snapshots', col: 'captured_by', like: TENANT_ID },
];

async function rollback(pool: pg.Pool): Promise<number> {
  let total = 0;
  for (const t of RF_PURGE) {
    if (t.table === 'rf_export_jobs') continue; // cascades from rf_generated_reports
    if (!(await tableExists(pool, t.table))) continue;
    if (!(await columnExists(pool, t.table, t.col))) continue;
    try {
      const op = t.like.includes('%') ? 'LIKE' : '=';
      const r = await pool.query(`DELETE FROM ${t.table} WHERE ${t.col}::text ${op} $1`, [t.like]);
      if (r.rowCount) {
        total += r.rowCount;
        console.log(`  purged ${r.rowCount} from ${t.table}.${t.col}`);
      }
    } catch (e: any) {
      console.log(`  [skip] ${t.table}.${t.col}: ${String(e?.message ?? e).slice(0, 80)}`);
    }
  }
  return total;
}

// ── white-label config (upsert) ─────────────────────────────────────────────
async function seedWhiteLabel(pool: pg.Pool): Promise<void> {
  await pool.query(
    `INSERT INTO rf_white_label_configs
       (tenant_id, org_name, logo_url, primary_color, secondary_color, accent_color,
        text_color, font_family, report_header, report_footer, is_active)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true)
     ON CONFLICT (tenant_id) DO UPDATE SET
       org_name=EXCLUDED.org_name, primary_color=EXCLUDED.primary_color,
       secondary_color=EXCLUDED.secondary_color, accent_color=EXCLUDED.accent_color,
       text_color=EXCLUDED.text_color, font_family=EXCLUDED.font_family,
       report_header=EXCLUDED.report_header, report_footer=EXCLUDED.report_footer,
       is_active=true, updated_at=now()`,
    [
      TENANT_ID, WHITE_LABEL.org_name, WHITE_LABEL.logo_url ?? null,
      WHITE_LABEL.primary_color, WHITE_LABEL.secondary_color, WHITE_LABEL.accent_color,
      WHITE_LABEL.text_color, WHITE_LABEL.font_family,
      WHITE_LABEL.report_header, WHITE_LABEL.report_footer,
    ],
  );
}

// ── 16 templates, one per report_type → return report_type→template_id map ───
async function seedTemplates(pool: pg.Pool, reports: ComposedReport[]): Promise<Map<string, number>> {
  const map = new Map<string, number>();
  for (const r of reports) {
    const { rows } = await pool.query<{ id: number }>(
      `INSERT INTO rf_templates (name, report_type, description, is_default)
       VALUES ($1,$2,$3,false) RETURNING id`,
      [`${TEMPLATE_PREFIX} ${r.title}`, r.report_type, `MX-301 enterprise pack template for ${r.title}.`],
    );
    map.set(r.report_type, rows[0].id);
  }
  return map;
}

// ── derive narrative_texts + insights from the composed sections ────────────
function deriveNarrativeTexts(report: ComposedReport): Record<string, string> {
  const out: Record<string, string> = {};
  for (const s of report.generated_content.sections ?? []) {
    if (s && s.type === 'narrative' && s.text) out[String(s.key ?? s.title)] = String(s.text);
  }
  return out;
}
function deriveInsights(report: ComposedReport): any[] {
  for (const s of report.generated_content.sections ?? []) {
    if (s && s.type === 'insight' && Array.isArray(s.insights)) return s.insights;
  }
  return [];
}

// ── persist ONE composed report into rf_generated_reports ────────────────────
async function persistReport(pool: pg.Pool, report: ComposedReport, templateId: number | null): Promise<any> {
  const { rows } = await pool.query(
    `INSERT INTO rf_generated_reports
       (template_id, user_id, session_id, report_type, data_snapshot, generated_content,
        narrative_texts, insights, language, tenant_id, status, metadata, completed_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'en',$9,'complete',$10,NOW())
     RETURNING *`,
    [
      templateId,
      MX301_SUBJECT,
      null,
      report.report_type,
      JSON.stringify({ pack_version: report.metadata.pack_version, axes: report.generated_content.axes }),
      JSON.stringify(report.generated_content),
      JSON.stringify(deriveNarrativeTexts(report)),
      JSON.stringify(deriveInsights(report)),
      TENANT_ID,
      JSON.stringify(report.metadata),
    ],
  );
  return rows[0];
}

// ── export ONE persisted report row to 4 formats in outDir ───────────────────
async function exportReport(row: any, outDir: string): Promise<{ format: string; bytes: number }[]> {
  const base = String(row.report_type);
  const written: { format: string; bytes: number }[] = [];

  // PDF — renderer writes to /tmp then we copy into the audit dir.
  const pdfTmp = await renderReportToPDF(row, WHITE_LABEL);
  const pdfDest = resolve(outDir, `${base}.pdf`);
  copyFileSync(pdfTmp, pdfDest);

  const html = renderReportToHTML(row, WHITE_LABEL);
  writeFileSync(resolve(outDir, `${base}.html`), html);

  const json = renderReportToJSON(row);
  writeFileSync(resolve(outDir, `${base}.json`), json);

  const csv = renderReportToCSV(row);
  writeFileSync(resolve(outDir, `${base}.csv`), csv);

  written.push(
    { format: 'pdf', bytes: statSync(pdfDest).size },
    { format: 'html', bytes: Buffer.byteLength(html) },
    { format: 'json', bytes: Buffer.byteLength(json) },
    { format: 'csv', bytes: Buffer.byteLength(csv) },
  );
  return written;
}

// ── BEST-EFFORT interview enrichment (demonstration input; never forced) ─────
async function enrichInterview(pool: pg.Pool): Promise<{ enriched: boolean; detail: string }> {
  try {
    // 1. Ensure a job row resolves for MX301_DEMO_JOB_ID (employer_jobs is canonical).
    if (await tableExists(pool, 'employer_jobs')) {
      const hasType = await columnExists(pool, 'employer_jobs', 'type');
      const cols = ['id', 'title', 'status'];
      const vals: any[] = [MX301_DEMO_JOB_ID, MX301_ROLE_TITLE, 'open'];
      if (await columnExists(pool, 'employer_jobs', 'employer_id')) { cols.push('employer_id'); vals.push(`${TENANT_ID}_employer`); }
      if (hasType) { cols.push('type'); vals.push('full_time'); }
      const ph = vals.map((_, i) => `$${i + 1}`).join(',');
      await pool.query(
        `INSERT INTO employer_jobs (${cols.join(',')}) VALUES (${ph}) ON CONFLICT (id) DO NOTHING`,
        vals,
      );
    } else {
      return { enriched: false, detail: 'employer_jobs substrate absent — Interview Readiness stays honestly empty' };
    }

    // 2. Ensure the candidate row exists and is job-scoped (IDOR contract).
    if (!(await tableExists(pool, 'employer_candidates'))) {
      return { enriched: false, detail: 'employer_candidates substrate absent — Interview Readiness stays honestly empty' };
    }
    const cCols = ['id', 'job_id', 'name', 'email'];
    const cVals: any[] = [MX301_SUBJECT, MX301_DEMO_JOB_ID, 'Sarah Johnson', MX301_SUBJECT];
    if (await columnExists(pool, 'employer_candidates', 'employer_id')) { cCols.push('employer_id'); cVals.push(`${TENANT_ID}_employer`); }
    const cph = cVals.map((_, i) => `$${i + 1}`).join(',');
    await pool.query(
      `INSERT INTO employer_candidates (${cCols.join(',')}) VALUES (${cph}) ON CONFLICT (id) DO NOTHING`,
      cVals,
    );

    // 3. Schedule a real interview + record real panel scores (engines, not raw SQL).
    await ensureInterviewSchema(pool);
    await ensureScoreSchema(pool);
    const sch: any = await scheduleInterview(pool, {
      jobId: MX301_DEMO_JOB_ID,
      candidateId: MX301_SUBJECT,
      roundName: 'Final Panel',
      roundSeq: 1,
      mode: 'remote',
      scheduledAt: new Date().toISOString(),
      durationMins: 60,
      actor: 'mx301',
    });
    const interviewId = sch?.data?.id ?? sch?.id;
    if (sch?.ok === false || interviewId == null) {
      return { enriched: false, detail: `interview not scheduled (${sch?.message ?? sch?.code ?? 'unknown'}) — honest empty` };
    }
    const scores: { panelist: string; criterion: string; score: number }[] = [
      { panelist: 'panelist_a@mx301', criterion: 'Product Strategy', score: 4 },
      { panelist: 'panelist_a@mx301', criterion: 'Stakeholder Communication', score: 4 },
      { panelist: 'panelist_b@mx301', criterion: 'Analytical Depth', score: 3 },
      { panelist: 'panelist_b@mx301', criterion: 'Leadership', score: 4 },
    ];
    let recorded = 0;
    for (const s of scores) {
      const r: any = await recordScore(pool, {
        interviewId: String(interviewId), panelist: s.panelist, criterion: s.criterion,
        score: s.score, maxScore: 5, actor: 'mx301',
      });
      if (r?.ok !== false) recorded++;
    }
    return { enriched: recorded > 0, detail: `interview scheduled + ${recorded}/${scores.length} panel scores recorded` };
  } catch (e: any) {
    return { enriched: false, detail: `enrichment skipped (${String(e?.message ?? e).slice(0, 90)}) — honest empty` };
  }
}

// Best-effort EI snapshot enrichment — symmetric with the interview enrichment, but
// HONESTY-BOUNDED. It persists AT MOST ONE genuine current EI snapshot when the
// candidate's profile is measurable and none has been recorded yet. It deliberately
// NEVER manufactures a second, coincident duplicate to force Promotion Readiness
// (which needs ≥2 snapshots OVER TIME) to "ready" — that would fabricate a trend from
// non-time-separated data. Promotion Readiness reaching "measurable" must come from
// genuinely time-separated snapshots (repeat assessments / the activation journey),
// not from this script duplicating one capture. Captures are tagged captured_by=TENANT_ID
// and purged by rollback().
async function enrichEiSnapshots(pool: pg.Pool): Promise<{ enriched: boolean; detail: string; measured_snapshots: number }> {
  try {
    await ensureEiProfileHistorySchema(pool);
    const existing = await listEiProfileHistory(pool, MX301_SUBJECT, 200);
    const measured = existing.filter((r) => r.measurable).length;
    if (measured >= 1) {
      return {
        enriched: false,
        detail:
          `already ${measured} measured EI snapshot(s) on record — no capture needed; ` +
          'Promotion Readiness renders only when ≥2 genuinely time-separated snapshots exist',
        measured_snapshots: measured,
      };
    }
    const profile = await buildEiProfile(pool, MX301_SUBJECT);
    if (!profile?.measurable) {
      return {
        enriched: false,
        detail: 'EI profile is not measurable (no scored competencies) — Promotion Readiness stays honestly empty',
        measured_snapshots: measured,
      };
    }
    await persistEiProfile(pool, profile, TENANT_ID);
    return {
      enriched: true,
      detail:
        `captured 1 genuine measured EI snapshot (tagged ${TENANT_ID}); ` +
        'Promotion Readiness stays honestly empty until a second, time-separated snapshot is recorded (never duplicated to force "ready")',
      measured_snapshots: 1,
    };
  } catch (e: any) {
    return {
      enriched: false,
      detail: `EI enrichment skipped (${String(e?.message ?? e).slice(0, 90)}) — honest empty`,
      measured_snapshots: 0,
    };
  }
}

// ── main ─────────────────────────────────────────────────────────────────────
async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error('DATABASE_URL not set');
    process.exit(1);
  }
  const pool = new Pool({ connectionString: url });
  const isRollback = process.argv.includes('--rollback');

  try {
    if (isRollback) {
      console.log('MX-301 report pack ROLLBACK…');
      const n = await rollback(pool);
      console.log(`Rollback complete: ${n} rows removed.`);
      return;
    }

    await ensureReportFactorySchema(pool);

    // Idempotent: purge any prior pack first.
    console.log('Purging any prior MX-301 report pack…');
    await rollback(pool);

    // Best-effort interview enrichment (demonstration input; honest if unavailable).
    const enrich = await enrichInterview(pool);
    console.log(`Interview enrichment: ${enrich.enriched ? 'OK' : 'skipped'} — ${enrich.detail}`);

    // Best-effort EI snapshot enrichment so Promotion Readiness can render a trend
    // when the EI profile is genuinely measurable (never fabricates otherwise).
    const eiEnrich = await enrichEiSnapshots(pool);
    console.log(`EI enrichment: ${eiEnrich.enriched ? 'OK' : 'skipped'} — ${eiEnrich.detail}`);

    // Confirm what the Interview Readiness engine actually sees post-enrichment.
    let interviewScoresSeen = 0;
    try {
      const ev: any = await candidateEvaluation(pool, MX301_DEMO_JOB_ID, MX301_SUBJECT);
      interviewScoresSeen = Number(ev?.data?.total_scores ?? ev?.total_scores ?? 0) || 0;
    } catch { /* honest 0 */ }

    // ── Compose the 16-report pack from live engines ──────────────────────────
    console.log('Building pack snapshot (every engine runs once)…');
    const snapshot = await buildPackSnapshot(pool, MX301_SUBJECT);
    const reports = composePack(snapshot);

    // No-empty guard — refuse to emit a half-built pack.
    const violations = validatePack(reports);
    if (violations.length > 0) {
      throw new Error(
        `MX-301 no-empty guard FAILED (${violations.length}):\n` + violations.map((v) => `  - ${v}`).join('\n'),
      );
    }
    console.log(`No-empty guard PASSED — ${reports.length} reports, 9 sections each, no blank charts/tables.`);

    // ── Persist + export ──────────────────────────────────────────────────────
    await seedWhiteLabel(pool);
    const templateMap = await seedTemplates(pool, reports);

    const outDir = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'audit', 'mx-301', 'report-pack');
    mkdirSync(outDir, { recursive: true });

    const manifestReports: any[] = [];
    let fileCount = 0;
    for (const report of reports) {
      const templateId = templateMap.get(report.report_type) ?? null;
      const row = await persistReport(pool, report, templateId);
      const files = await exportReport(row, outDir);
      fileCount += files.length;
      manifestReports.push({
        report_type: report.report_type,
        title: report.title,
        report_uuid: row.report_uuid,
        measurable: report.metadata.measurable,
        coverage_pct: report.generated_content.axes.coverage.pct,
        confidence_band: report.generated_content.axes.confidence.band,
        activation: report.generated_content.axes.activation,
        honest_state: report.metadata.honest_state ? report.metadata.honest_state.why : null,
        files: files.map((f) => ({ format: f.format, bytes: f.bytes, path: `${report.report_type}.${f.format}` })),
      });
    }
    console.log(`Persisted ${reports.length} reports + exported ${fileCount} files → ${outDir}`);

    // ── Dashboard-sync verification (what the super-admin console reads) ───────
    const dbReports = await pool.query(
      `SELECT count(*)::int AS n FROM rf_generated_reports WHERE tenant_id = $1 AND status = 'complete'`,
      [TENANT_ID],
    );
    const dbTemplates = await pool.query(
      `SELECT count(*)::int AS n FROM rf_templates WHERE name LIKE $1`,
      [`${TEMPLATE_PREFIX}%`],
    );
    const dbWl = await pool.query(
      `SELECT count(*)::int AS n FROM rf_white_label_configs WHERE tenant_id = $1`,
      [TENANT_ID],
    );
    const dashboardSync = {
      generated_reports_in_db: dbReports.rows[0].n,
      templates_in_db: dbTemplates.rows[0].n,
      white_label_configs_in_db: dbWl.rows[0].n,
      in_sync: dbReports.rows[0].n === reports.length && dbTemplates.rows[0].n === reports.length && dbWl.rows[0].n === 1,
    };

    // ── Deliverables (PII-masked) ─────────────────────────────────────────────
    const masked = maskSubject(MX301_SUBJECT);
    const generatedAt = new Date().toISOString();
    const measurableCount = reports.filter((r) => r.metadata.measurable).length;

    const manifest = {
      phase: 'MX-301 Phase 3 — Enterprise Report Pack (Option C, Enhanced Hybrid)',
      candidate: 'Sarah Johnson — Senior Product Manager (Technology, 8 yrs, MBA, Bangalore) [demonstration]',
      subject_masked: masked,
      tenant_id: TENANT_ID,
      white_label: { org_name: WHITE_LABEL.org_name, primary_color: WHITE_LABEL.primary_color, accent_color: WHITE_LABEL.accent_color },
      generated_at: generatedAt,
      report_count: reports.length,
      file_count: fileCount,
      formats: ['pdf', 'html', 'json', 'csv'],
      preview_format: 'html',
      fixed_layout: [
        'Executive Summary', 'Candidate Information', 'Assessment Summary', 'Visualizations',
        'Interpretation', 'Recommendations', 'Confidence Level', 'Data Source', 'Generated Timestamp',
      ],
      measurable_reports: measurableCount,
      interview_enrichment: { enriched: enrich.enriched, detail: enrich.detail, scores_seen_by_engine: interviewScoresSeen },
      ei_enrichment: { enriched: eiEnrich.enriched, detail: eiEnrich.detail, measured_snapshots: eiEnrich.measured_snapshots },
      dashboard_sync: dashboardSync,
      axes_note:
        'Coverage (measurable input) ⟂ Confidence (trustworthiness) ⟂ Activation (report generated) are separate; null is never coerced to 0. ' +
        'Reports without measurable input render a professional "Insufficient validated data" state — never a blank chart, empty table, or fabricated number.',
      reports: manifestReports,
    };
    writeFileSync(resolve(outDir, 'manifest.json'), JSON.stringify(manifest, null, 2));

    const measRow = (r: ComposedReport) => {
      const cov = r.generated_content.axes.coverage.pct;
      const conf = r.generated_content.axes.confidence.band;
      const state = r.metadata.measurable ? 'measured' : 'insufficient data (honest)';
      return `| ${r.title} | ${r.metadata.measurable ? 'YES' : 'empty'} | ${cov == null ? 'n/a' : cov + '%'} | ${conf ?? 'n/a'} | ${state} |`;
    };
    const md = `# MX-301 Phase 3 — Enterprise Report Pack

**Option C (Enhanced Hybrid Enterprise Validation).** A presentation-quality enterprise pack of
**${reports.length} reports** for one realistic, fully removable demonstration candidate, persisted into the
live Report Factory and exported in **four formats each (${fileCount} files total)**.

- **Candidate**: Sarah Johnson — Senior Product Manager, Technology, 8 yrs, MBA, Bangalore (demonstration data, purgeable).
- **Subject (masked)**: \`${masked}\`
- **White-label**: ${WHITE_LABEL.org_name} (primary \`${WHITE_LABEL.primary_color}\`, accent \`${WHITE_LABEL.accent_color}\`)
- **Generated**: ${generatedAt}
- **Build / rollback**: \`npx tsx backend/scripts/mx301-report-pack.ts [--rollback]\`
- **Provision candidate first**: \`npx tsx backend/scripts/mx301-demo-candidate.ts\`

## Every report ships the SAME fixed enterprise layout (9 sections)

Executive Summary · Candidate Information · Assessment Summary · Visualizations · Interpretation ·
Recommendations · Confidence Level · Data Source · Generated Timestamp.

Formats: **PDF + HTML + JSON + CSV** (preview = HTML). The no-empty guard refuses to emit the pack if any
report is structurally incomplete — **${reports.length}/${reports.length} reports passed** with no blank charts or empty tables.

## Three separate axes (never composited)

- **Activation** — the report generated and persisted. All ${reports.length} reports activate.
- **Coverage** — the candidate has measurable input for that report. **${measurableCount}/${reports.length}** are measured;
  the rest render a professional *"Insufficient validated data"* state — honest, not a failure, not fabricated.
- **Confidence** — trustworthiness of the produced value (calibration / domain-proxy vs direct), reported per report.

\`null\` is never coerced to \`0\`.

## Per-report state

| Report | Measurable | Coverage | Confidence | State |
| --- | --- | --- | --- | --- |
${reports.map(measRow).join('\n')}

## Interview enrichment (demonstration input)

${enrich.enriched
  ? `A real interview was scheduled and **${interviewScoresSeen} panel scores** were recorded for the demonstration ` +
    `candidate (tagged \`mx301\`, fully purgeable), so the Interview Readiness report renders measured data rather than an empty state.`
  : `Interview substrate was not provisioned in this environment (${enrich.detail}); the Interview Readiness report ` +
    `renders an honest *"Insufficient validated data"* state — never forced.`}

## Dashboard sync (super-admin Reports Console)

The pack is persisted into the live \`rf_generated_reports\` table the super-admin console reads:

| Surface | Rows |
| --- | --- |
| Generated reports (tenant \`${TENANT_ID}\`, complete) | ${dashboardSync.generated_reports_in_db} |
| Pack templates | ${dashboardSync.templates_in_db} |
| White-label config | ${dashboardSync.white_label_configs_in_db} |

**In sync:** ${dashboardSync.in_sync ? 'YES — DB rows match the generated pack.' : 'NO — see manifest.json.'}

## Reversibility & safety

Every row is tagged \`mx301\` / tenant \`mx301\` and removed by \`--rollback\`. Engines are driven in-process
(the same functions the HTTP routes call) behind \`FF_REPORT_FACTORY\`; the build is additive and reversible and
touches no production data. The candidate email is masked to an irreversible pseudonym in every committed file.

## Scope

This validates the report **product** (composition, fixed layout, four-format export, honest empty states,
dashboard persistence) for one demonstration candidate. Route-level auth / feature-flag gating is validated per
phase elsewhere and is intentionally out of scope here.
`;
    writeFileSync(resolve(outDir, 'FOUNDER-REPORT.md'), md);
    console.log(`Deliverables written: ${outDir}/manifest.json + FOUNDER-REPORT.md`);
    console.log(
      `SUMMARY: reports=${reports.length} files=${fileCount} measurable=${measurableCount}/${reports.length} ` +
        `dashboard_in_sync=${dashboardSync.in_sync} interview_enriched=${enrich.enriched}`,
    );

    if (!dashboardSync.in_sync) process.exitCode = 1;
  } finally {
    await pool.end();
  }
}

const isDirectRun = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isDirectRun) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
