-- ============================================================
-- CAPADEX SAMPLE SEED — All Personas
-- concern_area_id references:
--   1=Short attention span, 2=Easily distracted, 21=Procrastination
--   191=Leadership Effectiveness, 192=Classroom Engagement
--   193=Workplace Distraction, 194=Interview Confidence, 195=Employability Gap
-- ============================================================

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM concern_areas WHERE id=191) THEN
    RAISE EXCEPTION 'concern_areas seed not applied yet — run concern area inserts first';
  END IF;
END $$;

-- Standard Likert options JSON (reused inline for each question)
-- Never=0, Rarely=25, Sometimes=50, Often=75, Always=100

INSERT INTO short_assessment_questions
  (concern_area_id, question_code, stage, dimension, question_text, polarity, weight,
   is_anchor, sort_order, target_personas, is_active, options)
VALUES

-- ═══════════════════════════════════════════════════════════════
-- SHORT ATTENTION SPAN (concern_area_id=1) — student,parent,teacher,campus
-- ═══════════════════════════════════════════════════════════════
-- Curiosity
(1,'SAP_CUR_01','Curiosity','Focus Awareness',    'How often do you struggle to stay focused on a single task for more than 10 minutes?',  'negative','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_CUR_02','Curiosity','Focus Awareness',    'How frequently does your mind drift while reading or studying?',                          'negative','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_CUR_03','Curiosity','Focus Awareness',    'How often do you leave tasks unfinished and jump to something else?',                    'negative','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_CUR_04','Curiosity','Attention Duration', 'How regularly does your attention drop during long lectures or study sessions?',          'negative','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_CUR_05','Curiosity','Attention Duration', 'How often do you need to re-read the same content because focus was lost?',              'negative','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_CUR_06','Curiosity','Social Feedback',    'How frequently do others point out that you seem distracted or unfocused?',              'negative','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
-- Insight
(1,'SAP_INS_01','Insight','Self-Awareness',       'How clearly can you identify the specific times when your attention is weakest?',         'positive','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_INS_02','Insight','Self-Awareness',       'Do you understand what triggers your attention to drift suddenly?',                       'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_INS_03','Insight','Pattern Recognition',  'How well do you recognise patterns in which tasks you struggle to focus on?',             'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_INS_04','Insight','Pattern Recognition',  'Do you notice how your emotional state affects your ability to sustain attention?',       'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_INS_05','Insight','Environmental Insight','How clearly do you understand how your environment impacts your concentration?',           'positive','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_INS_06','Insight','Impact Awareness',     'Can you see the connection between your attention gaps and your results?',                'positive','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
-- Growth
(1,'SAP_GRW_01','Growth','Strategy Use',          'How often do you use timed focus techniques such as 25-minute work sessions to sustain attention?','positive','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_GRW_02','Growth','Strategy Use',          'How regularly do you plan tasks in short focused bursts to manage your attention?',        'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_GRW_03','Growth','Habit Formation',       'How consistently do you remove distractions before beginning an important task?',          'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_GRW_04','Growth','Mindfulness',           'How often do you use mindfulness or breathing exercises to reset your focus?',             'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_GRW_05','Growth','Self-Monitoring',       'How regularly do you track your focus patterns to find peak concentration windows?',       'positive','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_GRW_06','Growth','Reward Systems',        'How often do you reward yourself for successfully completing focused work sessions?',       'positive','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
-- Mastery
(1,'SAP_MAS_01','Mastery','Sustained Focus',      'How consistently are you able to complete tasks without losing focus part-way through?',   'positive','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_MAS_02','Mastery','Sustained Focus',      'How well do you maintain concentration even in noisy or busy environments?',               'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_MAS_03','Mastery','Recovery',             'How effectively can you re-engage with a task immediately after an interruption?',         'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_MAS_04','Mastery','Independence',         'How reliably do you complete tasks without needing reminders or external prompting?',       'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_MAS_05','Mastery','Social Recognition',   'How often do others comment positively on your improved ability to stay focused?',          'positive','0.9',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(1,'SAP_MAS_06','Mastery','Pressure Performance', 'How confidently do you manage your own attention even in high-pressure situations?',        'positive','1.0',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),

-- ═══════════════════════════════════════════════════════════════
-- EASILY DISTRACTED (concern_area_id=2) — all personas
-- ═══════════════════════════════════════════════════════════════
(2,'EAD_CUR_01','Curiosity','External Distraction','How often do nearby sounds, movements or notifications pull you away from your work?',     'negative','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_CUR_02','Curiosity','Digital Distraction', 'How frequently do you check your phone while studying or working?',                       'negative','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_CUR_03','Curiosity','Digital Distraction', 'How often do you end up on social media when you intended to be working?',                'negative','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_CUR_04','Curiosity','Internal Distraction','How easily do random thoughts or worries pull you off task mid-activity?',                'negative','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_CUR_05','Curiosity','Social Distraction',  'How frequently do conversations around you derail your concentration?',                   'negative','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_CUR_06','Curiosity','Time Cost',           'How often does a small interruption cause you to lose significant work time?',             'negative','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_INS_01','Insight','Trigger Awareness',     'Do you clearly understand which types of distraction affect you most strongly?',           'positive','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_INS_02','Insight','Environmental Insight', 'How clearly can you identify the environments where you get most easily distracted?',       'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_INS_03','Insight','Emotional Insight',     'Do you recognise the emotional states that make you actively seek distraction?',           'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_INS_04','Insight','Boredom Cycle',         'How well do you understand the link between boredom and your distraction behaviour?',       'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_INS_05','Insight','Impact Awareness',      'Can you clearly see how your distraction habits have affected your results over time?',     'positive','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_INS_06','Insight','Lifestyle Link',        'Do you notice how your sleep, diet or mood affects your susceptibility to distraction?',    'positive','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_GRW_01','Growth','Environment Design',     'How often do you actively set up a distraction-free space before starting important work?', 'positive','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_GRW_02','Growth','Digital Control',        'How regularly do you use apps or settings to block distracting content during work time?',  'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_GRW_03','Growth','Intention Setting',      'How consistently do you set a clear intention before starting a task to stay on course?',   'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_GRW_04','Growth','Focus Technique',        'How often do you use structured focus methods to prevent distraction during work?',          'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_GRW_05','Growth','Routine Building',       'How consistently have you built a daily routine that helps you transition into focused work?','positive','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_GRW_06','Growth','Reflection',             'How regularly do you review your distraction episodes to understand and fix the root cause?','positive','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_MAS_01','Mastery','Extended Focus',        'How well can you sustain focused work for 60 minutes or more even in a stimulating environment?','positive','1.2',true,1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_MAS_02','Mastery','Shared Spaces',         'How consistently do you maintain productivity when working with others nearby?',            'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_MAS_03','Mastery','Habit Integration',     'How thoroughly have you integrated distraction management into your everyday routine?',      'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_MAS_04','Mastery','Output Quality',        'How often do you complete your planned work without losing significant time to distractions?','positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_MAS_05','Mastery','Interruption Handling', 'How confidently do you handle unexpected interruptions without losing your entire workflow?','positive','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(2,'EAD_MAS_06','Mastery','Pressure Performance',  'How reliably do you stay on task during high-stakes or time-pressured situations?',         'positive','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),

-- ═══════════════════════════════════════════════════════════════
-- PROCRASTINATION (concern_area_id=21) — all personas
-- ═══════════════════════════════════════════════════════════════
(21,'PRO_CUR_01','Curiosity','Delay Frequency',    'How often do you delay starting tasks even when you know they are important?',             'negative','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_CUR_02','Curiosity','Deadline Crunch',    'How frequently do you wait until the last minute before seriously starting work?',          'negative','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_CUR_03','Curiosity','Avoidance',          'How often do you feel a strong urge to do something else when you should be working?',      'negative','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_CUR_04','Curiosity','Overwhelm',          'How regularly do you feel overwhelmed and freeze rather than just beginning a task?',        'negative','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_CUR_05','Curiosity','Accumulation',       'How often do incomplete tasks pile up despite your genuine intention to finish them?',       'negative','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_CUR_06','Curiosity','Task Avoidance',     'How frequently do you do low-priority tasks to avoid the important ones?',                  'negative','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_INS_01','Insight','Emotional Root',       'Do you clearly understand which emotions or fears drive your procrastination?',              'positive','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_INS_02','Insight','Task Pattern',         'How clearly can you identify the types of tasks you most often procrastinate on?',           'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_INS_03','Insight','Cost Awareness',       'Do you recognise the long-term cost of procrastination versus the short-term relief it brings?','positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_INS_04','Insight','Perfectionism Link',   'How well do you understand the connection between perfectionism and your delay patterns?',   'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_INS_05','Insight','Thought Patterns',     'Can you identify the specific thoughts that tell you it is acceptable to do this later?',   'positive','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_INS_06','Insight','Impact Awareness',     'Do you understand how your procrastination affects the people who depend on you?',           'positive','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_GRW_01','Growth','Task Breakdown',        'How often do you break large tasks into small actionable steps to overcome starting resistance?','positive','1.2',true,1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_GRW_02','Growth','Scheduling',            'How regularly do you schedule and commit to specific start times for important tasks?',      'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_GRW_03','Growth','Accountability',        'How consistently do you use accountability partners or commitment devices to stay on track?', 'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_GRW_04','Growth','Emotional Management',  'How often do you identify and address the emotional triggers behind your delays?',           'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_GRW_05','Growth','Two-Minute Rule',       'How regularly do you use quick-start strategies to beat initial resistance on tasks?',       'positive','1.0',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_GRW_06','Growth','Buffer Deadlines',      'How often do you set personal deadlines ahead of real deadlines to manage your workload?',   'positive','0.9',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_MAS_01','Mastery','Proactive Start',      'How consistently do you begin important tasks well ahead of their deadlines?',               'positive','1.2',true, 1,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_MAS_02','Mastery','Habit Change',         'How effectively have you reduced your procrastination through deliberate habit changes?',    'positive','1.1',false,2,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_MAS_03','Mastery','Discomfort Tolerance', 'How well do you push through discomfort or boredom to complete difficult tasks?',            'positive','1.1',false,3,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_MAS_04','Mastery','Self-Direction',       'How reliably do you meet your own self-set goals without needing external pressure?',        'positive','1.0',false,4,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_MAS_05','Mastery','Initiative',           'How often do you proactively identify and start tasks others have not yet thought about?',   'positive','0.9',false,5,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(21,'PRO_MAS_06','Mastery','Reputation',           'How consistently would others describe you as someone who genuinely gets things done on time?','positive','1.0',false,6,'{}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),

-- ═══════════════════════════════════════════════════════════════
-- CLASSROOM ENGAGEMENT (concern_area_id=192) — teacher
-- ═══════════════════════════════════════════════════════════════
(192,'CLE_CUR_01','Curiosity','Student Attention', 'How often do your students appear disengaged or mentally absent during lessons?',            'negative','1.2',true, 1,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_CUR_02','Curiosity','Passive Behaviour', 'How frequently do you notice blank expressions or passive behaviour across your class?',      'negative','1.1',false,2,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_CUR_03','Curiosity','Response Gap',      'How often do students fail to respond meaningfully to questions you ask during teaching?',   'negative','1.1',false,3,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_CUR_04','Curiosity','Comprehension Gap', 'How regularly do students ask for clarification on content you have already fully explained?','negative','1.0',false,4,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_CUR_05','Curiosity','Early Drop-Off',    'How often do students visibly disengage within the first 10 minutes of your lesson?',        'negative','1.0',false,5,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_CUR_06','Curiosity','Sustained Attention','How frequently do students struggle to maintain attention across an entire class period?',   'negative','0.9',false,6,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_INS_01','Insight','Method Awareness',    'Do you understand which teaching approaches tend to lose student engagement most quickly?',   'positive','1.2',true, 1,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_INS_02','Insight','Student Profiling',   'How clearly can you identify which students are at greatest risk of consistent disengagement?','positive','1.1',false,2,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_INS_03','Insight','Environment Impact',  'Do you recognise how classroom layout and environment affect student attention levels?',      'positive','1.1',false,3,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_INS_04','Insight','Emotional Needs',     'How well do you understand the emotional needs behind disruptive or disengaged behaviour?',   'positive','1.0',false,4,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_INS_05','Insight','Engagement Pattern',  'Can you identify clear patterns in when and why engagement drops in your classroom?',        'positive','1.0',false,5,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_INS_06','Insight','Relevance Link',      'Do you recognise how lesson relevance connects directly to student motivation and attention?','positive','0.9',false,6,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_GRW_01','Growth','Method Variation',     'How often do you deliberately vary your teaching methods to sustain student engagement?',    'positive','1.2',true, 1,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_GRW_02','Growth','Collaborative Learning','How regularly do you use collaborative activities to re-energise disengaged students?',    'positive','1.1',false,2,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_GRW_03','Growth','Formative Checks',     'How consistently do you use quick formative assessments to gauge attention and understanding?','positive','1.1',false,3,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_GRW_04','Growth','Contextualisation',    'How often do you link lesson content to student interests or real-world examples?',          'positive','1.0',false,4,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_GRW_05','Growth','Inclusive Questioning','How regularly do you use wait time and differentiated questioning to include all students?', 'positive','1.0',false,5,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_GRW_06','Growth','Adaptation',           'How often do you reflect on observed engagement levels and adapt your lessons accordingly?', 'positive','0.9',false,6,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_MAS_01','Mastery','Full Engagement',     'How consistently do all students remain actively engaged throughout your entire lesson?',    'positive','1.2',true, 1,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_MAS_02','Mastery','Energy Management',   'How effectively do you manage the energy and attention level of your whole class?',          'positive','1.1',false,2,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_MAS_03','Mastery','Difficult Content',   'How reliably do you maintain engagement even during complex or less interesting topics?',    'positive','1.1',false,3,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_MAS_04','Mastery','Psychological Safety','How well do you create an environment where all students feel safe and motivated to participate?','positive','1.0',false,4,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_MAS_05','Mastery','In-Moment Adaptation','How confidently do you adapt your delivery on the spot when engagement is visibly dropping?','positive','1.0',false,5,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(192,'CLE_MAS_06','Mastery','Student Outcome',     'How consistently do students leave your lessons feeling genuinely motivated and understood?', 'positive','0.9',false,6,'{teacher}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),

-- ═══════════════════════════════════════════════════════════════
-- WORKPLACE DISTRACTION (concern_area_id=193) — professional,campus,jobseeker
-- ═══════════════════════════════════════════════════════════════
(193,'WKD_CUR_01','Curiosity','Digital Interruption','How often do email, messaging apps or notifications break your deep focus during work?',   'negative','1.2',true, 1,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_CUR_02','Curiosity','Off-Task Behaviour', 'How frequently do you find yourself on non-work tasks during dedicated work hours?',       'negative','1.1',false,2,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_CUR_03','Curiosity','Context Switching',  'How often do you switch between tasks so frequently that you lose all momentum?',          'negative','1.1',false,3,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_CUR_04','Curiosity','Meeting Disruption', 'How regularly do meetings or drop-in conversations disrupt your planned focus time?',       'negative','1.0',false,4,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_CUR_05','Curiosity','Incomplete Work',    'How often does your work day end with important tasks unstarted or unfinished?',            'negative','1.0',false,5,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_CUR_06','Curiosity','Mental State',       'How frequently do you feel mentally scattered rather than sharp and focused at work?',       'negative','0.9',false,6,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_INS_01','Insight','Trigger Mapping',      'Do you clearly understand which work environments trigger your most distracted states?',     'positive','1.2',true, 1,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_INS_02','Insight','Digital Pattern',      'How clearly can you identify the types of notifications that derail you most at work?',      'positive','1.1',false,2,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_INS_03','Insight','Energy Awareness',     'Do you recognise how your energy levels across the day shape your distraction patterns?',   'positive','1.1',false,3,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_INS_04','Insight','Cost Awareness',       'How well do you understand the productivity cost of each distraction you allow at work?',   'positive','1.0',false,4,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_INS_05','Insight','Distraction Types',    'Can you distinguish between necessary work interruptions and self-created distractions?',   'positive','1.0',false,5,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_INS_06','Insight','Team Impact',          'Do you recognise how your distraction habits impact the performance of your team or peers?','positive','0.9',false,6,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_GRW_01','Growth','Time Blocking',         'How often do you block dedicated deep-work windows in your calendar?',                       'positive','1.2',true, 1,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_GRW_02','Growth','Notification Management','How consistently do you manage notifications and interruptions during focused work time?', 'positive','1.1',false,2,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_GRW_03','Growth','Task Batching',         'How regularly do you batch similar tasks to reduce mental switching costs?',                 'positive','1.1',false,3,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_GRW_04','Growth','Environment Design',    'How consistently do you optimise your workspace for maximum concentration?',                 'positive','1.0',false,4,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_GRW_05','Growth','Async Communication',   'How often do you batch messages and use async communication to protect focused time?',       'positive','1.0',false,5,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_GRW_06','Growth','Day Debrief',           'How regularly do you review distracted work sessions to identify and fix the root causes?', 'positive','0.9',false,6,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_MAS_01','Mastery','Deep Work',            'How consistently do you complete your highest-priority work within your planned focus windows?','positive','1.2',true,1,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_MAS_02','Mastery','Environment Independence','How effectively do you maintain focus even in open-plan or hybrid work environments?',  'positive','1.1',false,2,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_MAS_03','Mastery','Complex Work',         'How reliably can you sustain concentration through complex, multi-hour analytical tasks?',   'positive','1.1',false,3,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_MAS_04','Mastery','Habit Embedding',      'How thoroughly have you embedded distraction management into your professional habits?',     'positive','1.0',false,4,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_MAS_05','Mastery','Peer Recognition',     'How often do colleagues see you as someone who delivers focused, high-quality work?',        'positive','0.9',false,5,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(193,'WKD_MAS_06','Mastery','Priority Protection',  'How confidently do you protect your best attention hours from low-value interruptions?',     'positive','1.0',false,6,'{professional,campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),

-- ═══════════════════════════════════════════════════════════════
-- INTERVIEW CONFIDENCE (concern_area_id=194) — jobseeker,campus
-- ═══════════════════════════════════════════════════════════════
(194,'INC_CUR_01','Curiosity','Pre-Interview Anxiety','How often do you feel nervous or anxious before and during job interviews?',              'negative','1.2',true, 1,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_CUR_02','Curiosity','Communication Gap',   'How frequently do you struggle to communicate your strengths confidently in interviews?',  'negative','1.1',false,2,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_CUR_03','Curiosity','Question Handling',   'How often do unexpected interview questions completely throw off your composure?',          'negative','1.1',false,3,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_CUR_04','Curiosity','Performance Gap',     'How regularly do you feel your interview performance does not reflect your actual ability?','negative','1.0',false,4,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_CUR_05','Curiosity','Post-Interview Regret','How often do you leave an interview wishing you had expressed yourself differently?',     'negative','1.0',false,5,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_CUR_06','Curiosity','Non-Verbal Signals',  'How frequently does your body language or voice betray nervousness during interviews?',    'negative','0.9',false,6,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_INS_01','Insight','Anxiety Triggers',      'Do you understand which specific interview scenarios trigger your greatest anxiety?',       'positive','1.2',true, 1,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_INS_02','Insight','Performance Gap',       'How clearly can you identify the gap between how nervous you feel and how you actually perform?','positive','1.1',false,2,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_INS_03','Insight','Story Strength',        'Do you recognise which of your experiences are most compelling to interviewers?',           'positive','1.1',false,3,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_INS_04','Insight','Non-Verbal Awareness',  'How well do you understand how interviewers read body language and non-verbal cues?',       'positive','1.0',false,4,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_INS_05','Insight','Interview Patterns',    'Can you identify clear patterns in the interviews where you have performed your best?',     'positive','1.0',false,5,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_INS_06','Insight','Preparation Link',      'Do you understand how your preparation quality directly drives your confidence in interviews?','positive','0.9',false,6,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_GRW_01','Growth','Mock Practice',          'How often do you practise mock interviews before applying for or attending real interviews?','positive','1.2',true, 1,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_GRW_02','Growth','Company Research',       'How thoroughly do you research the company and role to speak with genuine confidence?',     'positive','1.1',false,2,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_GRW_03','Growth','Answer Preparation',     'How consistently do you prepare and refine answers to common and tough interview questions?','positive','1.1',false,3,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_GRW_04','Growth','Presence Training',      'How regularly do you work on your body language, tone and vocal presence for interviews?',  'positive','1.0',false,4,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_GRW_05','Growth','Feedback Integration',   'How often do you seek and use feedback from past interviews to improve specific weak areas?','positive','1.0',false,5,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_GRW_06','Growth','Self-Review',            'How regularly do you record and review your own mock interview performance?',                'positive','0.9',false,6,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_MAS_01','Mastery','Calm Confidence',       'How consistently do you enter interviews feeling genuinely prepared, calm and confident?',  'positive','1.2',true, 1,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_MAS_02','Mastery','Adaptability',          'How effectively can you handle unexpected or challenging questions in the moment?',          'positive','1.1',false,2,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_MAS_03','Mastery','Value Communication',   'How reliably do you communicate your value proposition concisely and compellingly?',        'positive','1.1',false,3,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_MAS_04','Mastery','Nerve Management',      'How well do you manage nerves so they enhance rather than hinder your interview performance?','positive','1.0',false,4,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_MAS_05','Mastery','Interviewer Impact',    'How often do interviewers express a strong positive response to your answers?',             'positive','0.9',false,5,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(194,'INC_MAS_06','Mastery','Professional Close',    'How confidently do you follow up, negotiate and close interview conversations professionally?','positive','1.0',false,6,'{jobseeker,campus}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),

-- ═══════════════════════════════════════════════════════════════
-- EMPLOYABILITY GAP (concern_area_id=195) — campus,jobseeker
-- ═══════════════════════════════════════════════════════════════
(195,'EMP_CUR_01','Curiosity','Skills Uncertainty', 'How often do you feel unsure about whether your skills match what employers expect?',        'negative','1.2',true, 1,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_CUR_02','Curiosity','Value Articulation', 'How frequently do you struggle to clearly explain your professional value to a potential employer?','negative','1.1',false,2,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_CUR_03','Curiosity','Peer Comparison',    'How often do you feel behind your peers in professional skills or industry knowledge?',       'negative','1.1',false,3,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_CUR_04','Curiosity','JD Mismatch',        'How regularly do job descriptions list requirements you feel you do not yet fully meet?',    'negative','1.0',false,4,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_CUR_05','Curiosity','Role Readiness',     'How often do you feel underprepared for the real demands of your target role?',              'negative','1.0',false,5,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_CUR_06','Curiosity','Profile Confidence', 'How frequently do you feel your resume or portfolio does not reflect your true potential?',  'negative','0.9',false,6,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_INS_01','Insight','Skills Gap Clarity',   'Do you clearly understand which skill gaps are most critical for your target career path?',  'positive','1.2',true, 1,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_INS_02','Insight','Market Alignment',     'How well can you distinguish between the skills you have and those employers value most?',   'positive','1.1',false,2,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_INS_03','Insight','Network Awareness',    'Do you recognise how networking and personal branding affect your employability?',            'positive','1.1',false,3,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_INS_04','Insight','Differentiator Insight','How clearly do you understand what differentiates top candidates from average ones in your field?','positive','1.0',false,4,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_INS_05','Insight','Profile Gap',          'Can you identify the specific experiences or credentials missing from your professional profile?','positive','1.0',false,5,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_INS_06','Insight','Recruiter Insight',    'Do you understand how recruiters and hiring managers evaluate candidates like you?',          'positive','0.9',false,6,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_GRW_01','Growth','Active Skilling',       'How actively are you building new skills through courses, projects or internships?',          'positive','1.2',true, 1,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_GRW_02','Growth','Profile Maintenance',   'How regularly do you update your resume, LinkedIn and portfolio with your latest skills?',    'positive','1.1',false,2,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_GRW_03','Growth','Mentorship',            'How consistently do you seek mentors or industry professionals for career guidance?',          'positive','1.1',false,3,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_GRW_04','Growth','Experience Building',   'How often do you apply for roles, competitions or projects to build real-world experience?',  'positive','1.0',false,4,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_GRW_05','Growth','Value Communication',   'How regularly do you practise communicating your professional value in conversations?',        'positive','1.0',false,5,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_GRW_06','Growth','Industry Awareness',    'How consistently do you track industry trends to keep your skill set relevant?',               'positive','0.9',false,6,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_MAS_01','Mastery','Value Proposition',    'How confidently can you articulate your unique professional value to any employer?',           'positive','1.2',true, 1,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_MAS_02','Mastery','Role Matching',        'How effectively do you match your skills and experience to target role requirements?',         'positive','1.1',false,2,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_MAS_03','Mastery','Application Success',  'How reliably do you receive positive responses and callbacks from job applications?',           'positive','1.1',false,3,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_MAS_04','Mastery','Network Quality',      'How well have you built a professional network that actively supports your career growth?',    'positive','1.0',false,4,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_MAS_05','Mastery','Continuous Growth',    'How consistently do you continue developing your skills even after securing a position?',      'positive','0.9',false,5,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(195,'EMP_MAS_06','Mastery','Market Reputation',    'How often do recruiters or employers proactively seek you out for career opportunities?',      'positive','1.0',false,6,'{campus,jobseeker}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),

-- ═══════════════════════════════════════════════════════════════
-- LEADERSHIP EFFECTIVENESS (concern_area_id=191) — professional
-- ═══════════════════════════════════════════════════════════════
(191,'LEA_CUR_01','Curiosity','Team Motivation',    'How often do you find it difficult to motivate your team to consistently perform at their best?','negative','1.2',true,1,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_CUR_02','Curiosity','Conflict Resolution','How frequently do team conflicts or tensions go unresolved under your leadership?',           'negative','1.1',false,2,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_CUR_03','Curiosity','Dependency Dynamic', 'How often do team members come to you with problems rather than with solutions?',              'negative','1.1',false,3,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_CUR_04','Curiosity','Direction Clarity',  'How regularly do projects stall due to unclear direction or delayed decision-making?',          'negative','1.0',false,4,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_CUR_05','Curiosity','Style Mismatch',     'How often do you feel your leadership style is mismatched with what your team needs?',          'negative','1.0',false,5,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_CUR_06','Curiosity','Performance Gap',    'How frequently do you notice a clear gap between your team potential and their actual output?','negative','0.9',false,6,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_INS_01','Insight','Style Awareness',      'Do you clearly understand your dominant leadership style and its real impact on your team?',   'positive','1.2',true, 1,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_INS_02','Insight','Blind Spots',          'How clearly can you identify the specific blind spots in your own leadership approach?',        'positive','1.1',false,2,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_INS_03','Insight','Communication Impact', 'Do you recognise how your communication style directly affects team morale and engagement?',   'positive','1.1',false,3,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_INS_04','Insight','Individual Needs',     'How clearly can you identify what each of your highest-performing team members needs from you?','positive','1.0',false,4,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_INS_05','Insight','Delegation Insight',   'Can you distinguish between tasks you should delegate and those you must personally own?',     'positive','1.0',false,5,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_INS_06','Insight','Psychological Safety', 'Do you understand how psychological safety shapes your team willingness to contribute?',       'positive','0.9',false,6,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_GRW_01','Growth','Feedback Seeking',      'How regularly do you actively seek structured feedback from your team on your leadership?',    'positive','1.2',true, 1,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_GRW_02','Growth','Development Investment','How consistently do you invest in specific leadership development activities?',                 'positive','1.1',false,2,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_GRW_03','Growth','Structured Reviews',    'How often do you hold structured one-on-ones and team reviews to drive alignment?',            'positive','1.1',false,3,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_GRW_04','Growth','Feedback Quality',      'How deliberately do you practise giving clear, timely and constructive feedback to your team?','positive','1.0',false,4,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_GRW_05','Growth','Talent Development',    'How regularly do you identify and actively develop the next leaders within your team?',        'positive','1.0',false,5,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_GRW_06','Growth','Data Reflection',       'How often do you track metrics connecting your leadership actions to team performance outcomes?','positive','0.9',false,6,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_MAS_01','Mastery','Autonomous Performance','How consistently does your team perform at a high level without constant direction from you?','positive','1.2',true,1,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_MAS_02','Mastery','Adaptive Style',       'How effectively do you adapt your leadership style to meet different team member needs?',      'positive','1.1',false,2,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_MAS_03','Mastery','Conflict Mastery',     'How reliably do you resolve team conflicts in ways that strengthen rather than divide the team?','positive','1.1',false,3,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_MAS_04','Mastery','Culture Building',     'How well have you built a culture where accountability and high performance are self-sustaining?','positive','1.0',false,4,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_MAS_05','Mastery','Innovation Culture',   'How often do team members proactively bring innovative ideas and solutions to you?',            'positive','0.9',false,5,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]'),
(191,'LEA_MAS_06','Mastery','Executive Reputation', 'How consistently would senior stakeholders describe your leadership as exemplary and inspiring?','positive','1.0',false,6,'{professional}',true,'[{"option_text":"Never","score_value":0,"display_order":1},{"option_text":"Rarely","score_value":25,"display_order":2},{"option_text":"Sometimes","score_value":50,"display_order":3},{"option_text":"Often","score_value":75,"display_order":4},{"option_text":"Always","score_value":100,"display_order":5}]')

ON CONFLICT (question_code) DO UPDATE
  SET question_text = EXCLUDED.question_text,
      dimension     = EXCLUDED.dimension,
      polarity      = EXCLUDED.polarity,
      weight        = EXCLUDED.weight,
      is_anchor     = EXCLUDED.is_anchor,
      sort_order    = EXCLUDED.sort_order,
      target_personas = EXCLUDED.target_personas,
      options       = EXCLUDED.options,
      is_active     = EXCLUDED.is_active,
      updated_at    = now();
