-- CAPADEX Concern → Clarity-question precise mapping (2026-06-01).
--
-- WHY: clarity questions (`capadex_clarity_questions`) are linked to master
-- concerns ONLY through the coarse `relational_bridge_tag` (~56 buckets). A single
-- tag like ACADEMIC_COGNITIVE pools ~618 questions spanning many distinct concerns
-- (focus, procrastination, exam strategy, conceptual gaps…), so a specific concern
-- such as "Academic Focus" drew generic family questions. The clarity rows DO carry
-- a finer curated sub-topic label in their `concern` column ("Lack of Academic
-- Focus", "Poor Concentration During Studies", …), but the master table has no link
-- to it. This table stores that precise link, computed once and reviewable, so the
-- runtime picker can restrict to the actually-relevant clarity sub-concern(s)
-- instead of guessing relevance from question text per request.
--
-- One row per (master concern, matched clarity `concern` text). Concerns whose
-- bridge-tag pool yields no topical match are recorded as a single explicit
-- `orphan` marker row (match_method='orphan', clarity_concern='__orphan__') — never
-- fabricated; the picker treats orphans as "no mapping" and falls back to the whole
-- bridge tag (prior behaviour).
--
-- Mirrors the lazy `ensureConcernClarityMapSchema()` bootstrap in
-- `backend/services/concern-clarity-mapping-engine.ts`. Generated by
-- `backend/scripts/seed-concern-clarity-map.ts`.

CREATE TABLE IF NOT EXISTS capadex_concern_clarity_map (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  concern_pk            INTEGER NOT NULL,
  master_concern_id     TEXT,
  relational_bridge_tag TEXT,
  clarity_concern       TEXT NOT NULL,
  match_method          VARCHAR(24) NOT NULL,
  score                 NUMERIC(8,4) NOT NULL DEFAULT 0,
  question_count        INTEGER NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_concern_clarity_map
  ON capadex_concern_clarity_map (concern_pk, clarity_concern);
CREATE INDEX IF NOT EXISTS idx_concern_clarity_map_concern_id
  ON capadex_concern_clarity_map (master_concern_id);
CREATE INDEX IF NOT EXISTS idx_concern_clarity_map_bridge
  ON capadex_concern_clarity_map (relational_bridge_tag);
CREATE INDEX IF NOT EXISTS idx_concern_clarity_map_method
  ON capadex_concern_clarity_map (match_method);
