-- CAPADEX Intervention Runtime (Phase 4 — Part B).
--
-- Final node of the behavioural lineage chain:
--   Evidence → Signal → Composite → Pattern → Intervention
--
-- Stores the ranked, library-backed interventions generated by
-- backend/services/capadex-intervention-engine.ts. Canonical mirror of the lazy
-- ensureInterventionSchema() bootstrap (this repo has no migration runner) — kept
-- in lockstep so a fresh database and a running process converge on the same DDL.
--
-- Distinct from the user-scoped enterprise `capadex_interventions` table
-- (20260506_capadex_enterprise.sql) — this one is session-scoped and recomputed
-- idempotently on every /respond (absolute upsert + set reconciliation).

CREATE TABLE IF NOT EXISTS capadex_session_interventions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id       UUID NOT NULL,
  intervention_key VARCHAR(120) NOT NULL,
  construct_key    VARCHAR(120) NOT NULL,
  title            TEXT,
  description      TEXT,
  rationale        TEXT,
  effort           VARCHAR(20),
  duration         VARCHAR(40),
  expected_impact  NUMERIC(5,4) NOT NULL DEFAULT 0,
  confidence       NUMERIC(5,4) NOT NULL DEFAULT 0,
  review_window    VARCHAR(40),
  safety_level     VARCHAR(20),
  severity         NUMERIC(5,4) NOT NULL DEFAULT 0,
  signal_refs      JSONB NOT NULL DEFAULT '[]',
  pattern_refs     JSONB NOT NULL DEFAULT '[]',
  rank             INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_capadex_interventions_session
  ON capadex_session_interventions (session_id);

-- One intervention per construct per session; the runtime upserts on this key.
CREATE UNIQUE INDEX IF NOT EXISTS uq_capadex_interventions_session_key
  ON capadex_session_interventions (session_id, intervention_key);
