/**
 * CAPADEX PIL — Phase 5 Intervention Intelligence API (read-only).
 *
 * Surfaces the persisted Phase-5 tables (pil_intervention_library,
 * pil_intervention_quality_scores, pil_intervention_outcomes, pil_growth_pathways,
 * pil_action_plan_templates) to the SuperAdmin "Intervention Intelligence" panel.
 * Pure reads: SELECTs only; the deterministic content is authored + regenerated by
 * the runner (`scripts/pil/run-intervention-intelligence.ts`), never mutated here.
 *
 * Endpoints (all requireAuth + requireSuperAdmin), base /api/admin/pil/intervention:
 *   GET /stats          — distributions, quality averages, validators, Transformation Readiness Score
 *   GET /interventions  — paginated interventions + scores + outcomes (filter archetype/stakeholder/type)
 *   GET /pathways       — archetype × stakeholder growth pathways
 *   GET /plans          — archetype × stakeholder action-plan templates
 *   GET /duplicates     — duplicate review (filter kind, redundant)
 *   GET /interventions.csv | /pathways.csv | /plans.csv | /duplicates.csv  — exports [literal BEFORE /:key]
 *   GET /:key           — one archetype: interventions grouped + pathways + plans  [param LAST]
 */
import type { Express, Request, Response, RequestHandler } from 'express';
import type { Pool } from 'pg';
import {
  STAKEHOLDERS, INTERVENTION_TYPES, INTERVENTION_VALIDATION_TARGETS,
  auditDuplicates,
  type GeneratedIntervention, type DuplicateRow,
} from '../services/pil/intervention-intelligence-engine.js';

const STAKES = new Set<string>(STAKEHOLDERS);
const TYPES = new Set<string>(INTERVENTION_TYPES);
const DUP_KINDS = new Set(['identical', 'semantic', 'stakeholder']);

/**
 * Duplicate review is NOT a persisted table — the Phase-5 spec writes ONLY 5
 * tables, none a duplicate-review table. We re-derive it read-only at request
 * time from the persisted `pil_intervention_library` using the SAME engine
 * `auditDuplicates` the runner reports against → byte-identical, deterministic,
 * cached 60s. `dup_id` is a stable 1-based index over the ordered review rows.
 */
interface DuplicateReviewRow extends DuplicateRow { dup_id: number }
let _dupCache: { at: number; rows: DuplicateReviewRow[] } | null = null;

async function loadDuplicateReview(pool: Pool, force = false): Promise<DuplicateReviewRow[]> {
  if (!force && _dupCache && Date.now() - _dupCache.at < CACHE_TTL_MS) return _dupCache.rows;
  const lib = (await pool.query(`
    SELECT archetype_key, intervention_type, stakeholder_type, intervention_text
    FROM pil_intervention_library
    ORDER BY archetype_key, intervention_type, stakeholder_type, intervention_id`)).rows;
  const items = lib.map((r) => ({
    archetype_key: r.archetype_key,
    archetype_name: r.archetype_key,
    problem_id: 0,
    stakeholder: r.stakeholder_type,
    intervention_type: r.intervention_type,
    text: r.intervention_text,
  })) as unknown as GeneratedIntervention[];
  const { rows } = auditDuplicates(items);
  const sorted = rows
    .slice()
    .sort((a, b) => Number(b.redundant) - Number(a.redundant) || b.overlap - a.overlap);
  const withId = sorted.map((r, i) => ({ ...r, dup_id: i + 1 }));
  _dupCache = { at: Date.now(), rows: withId };
  return withId;
}

function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return '';
  let s = String(v);
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`; // neutralise spreadsheet formula injection
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function sendCsv(res: Response, file: string, header: string[], rows: any[]): void {
  const lines = [header.join(',')];
  for (const r of rows) lines.push(header.map((h) => csvEscape(r[h])).join(','));
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${file}"`);
  res.send(lines.join('\n'));
}

interface StatsShape {
  generated_at: string;
  totals: { interventions: number; pathways: number; plans: number; duplicate_reviews: number; archetypes: number };
  coverage: { complete_pathways: number; pathways: number };
  type_distribution: Record<string, number>;
  stakeholder_distribution: Record<string, number>;
  quality_averages: { practicality: number; actionability: number; outcome_clarity: number; stakeholder_relevance: number; archetype_alignment: number; composite: number };
  outcome_averages: { confidence_impact: number; risk_reduction_impact: number };
  duplicate_breakdown: { identical: number; semantic: number; stakeholder: number; redundant: number; variants: number };
  link_integrity: { linked: number; orphans: number };
  validation: {
    practicality: { rate: number; target: number; pass: boolean };
    actionability: { rate: number; target: number; pass: boolean };
    archetype_alignment: { rate: number; target: number; pass: boolean };
    duplicate_rate: { rate: number; target: number; pass: boolean };
    coverage: { rate: number; target: number; pass: boolean };
  };
  transformation_readiness_score: number;
}

const CACHE_TTL_MS = 60_000;
let _statsCache: { at: number; data: StatsShape } | null = null;

function r4(n: number): number { return Math.round(n * 10000) / 10000; }
function r2(n: number): number { return Math.round(n * 100) / 100; }

async function computeStats(pool: Pool, force = false): Promise<StatsShape> {
  const expectedTotal = STAKEHOLDERS.length * INTERVENTION_TYPES.length; // per archetype
  const [agg, typeDist, stakeDist, qAvg, oAvg, dupReview, pathCov, archCount, orphan, planN] = await Promise.all([
    pool.query(`SELECT count(*)::int n,
        count(*) FILTER (WHERE realism_pass)::int practical,
        count(*) FILTER (WHERE aligned)::int aligned,
        count(*) FILTER (WHERE is_duplicate)::int dup,
        count(DISTINCT archetype_key)::int ak FROM pil_intervention_library`),
    pool.query(`SELECT intervention_type k, count(*)::int n FROM pil_intervention_library GROUP BY intervention_type`),
    pool.query(`SELECT stakeholder_type k, count(*)::int n FROM pil_intervention_library GROUP BY stakeholder_type`),
    pool.query(`SELECT avg(practicality)::float pr, avg(actionability)::float ac, avg(outcome_clarity)::float oc, avg(stakeholder_relevance)::float sr, avg(archetype_alignment)::float aa, avg(composite)::float cp FROM pil_intervention_quality_scores`),
    pool.query(`SELECT count(*) FILTER (WHERE expected_outcome <> '' AND success_indicator <> '' AND progress_indicator <> '')::int full, avg(confidence_impact)::float ci, avg(risk_reduction_impact)::float rr, count(*)::int n FROM pil_intervention_outcomes`),
    loadDuplicateReview(pool, force),
    pool.query(`SELECT count(*)::int n, count(*) FILTER (WHERE complete)::int complete FROM pil_growth_pathways`),
    pool.query(`SELECT count(*)::int n FROM archetype_library`),
    pool.query(`SELECT count(*)::int n FROM pil_intervention_library il LEFT JOIN human_problem_library h ON il.problem_id = h.problem_id WHERE h.problem_id IS NULL`),
    pool.query(`SELECT count(*)::int n FROM pil_action_plan_templates`),
  ]);

  const a = agg.rows[0];
  const total = a.n || 0;
  const practicalRate = total ? a.practical / total : 0;
  const alignRate = total ? a.aligned / total : 0;
  const dupRate = total ? a.dup / total : 0;

  // actionability rate needs the score table (practicality flag lives on the library row)
  const actAgg = (await pool.query(`SELECT count(*) FILTER (WHERE actionability >= 4)::int ok, count(*)::int n FROM pil_intervention_quality_scores`)).rows[0];
  const actionableRate = actAgg?.n ? actAgg.ok / actAgg.n : 0;

  const dist = (rows: any[], keys: readonly string[]): Record<string, number> => {
    const o: Record<string, number> = {};
    for (const k of keys) o[k] = 0;
    for (const row of rows) o[row.k] = Number(row.n);
    return o;
  };
  const dupBy: Record<string, { n: number; redundant: number }> = { identical: { n: 0, redundant: 0 }, semantic: { n: 0, redundant: 0 }, stakeholder: { n: 0, redundant: 0 } };
  for (const row of dupReview) { const b = dupBy[row.kind]; b.n++; if (row.redundant) b.redundant++; }
  const redundant = dupBy.identical.redundant + dupBy.semantic.redundant + dupBy.stakeholder.redundant;
  const dupReviews = dupReview.length;
  const variants = dupReviews - redundant;

  const completePathways = Number(pathCov.rows[0]?.complete ?? 0);
  const pathwaysN = Number(pathCov.rows[0]?.n ?? 0);
  const archetypes = Number(archCount.rows[0]?.n ?? 0);
  const coverageRate = (archetypes * expectedTotal) ? total / (archetypes * expectedTotal) : 0;
  const orphans = Number(orphan.rows[0]?.n ?? 0);
  const linkRate = total ? (total - orphans) / total : 0;

  const trs = r4(practicalRate * 0.25 + actionableRate * 0.20 + alignRate * 0.15 + (1 - dupRate) * 0.15 + coverageRate * 0.15 + linkRate * 0.10) * 100;

  const q = qAvg.rows[0] || {};
  const o = oAvg.rows[0] || {};
  return {
    generated_at: new Date().toISOString(),
    totals: { interventions: total, pathways: pathwaysN, plans: Number(planN.rows[0]?.n ?? 0), duplicate_reviews: dupReviews, archetypes: a.ak || 0 },
    coverage: { complete_pathways: completePathways, pathways: pathwaysN },
    type_distribution: dist(typeDist.rows, INTERVENTION_TYPES),
    stakeholder_distribution: dist(stakeDist.rows, STAKEHOLDERS),
    quality_averages: {
      practicality: r2(Number(q.pr ?? 0)), actionability: r2(Number(q.ac ?? 0)),
      outcome_clarity: r2(Number(q.oc ?? 0)), stakeholder_relevance: r2(Number(q.sr ?? 0)),
      archetype_alignment: r2(Number(q.aa ?? 0)), composite: r2(Number(q.cp ?? 0)),
    },
    outcome_averages: { confidence_impact: r4(Number(o.ci ?? 0)), risk_reduction_impact: r4(Number(o.rr ?? 0)) },
    duplicate_breakdown: { identical: dupBy.identical.n, semantic: dupBy.semantic.n, stakeholder: dupBy.stakeholder.n, redundant, variants },
    link_integrity: { linked: total - orphans, orphans },
    validation: {
      practicality: { rate: r4(practicalRate), target: INTERVENTION_VALIDATION_TARGETS.practicality, pass: practicalRate >= INTERVENTION_VALIDATION_TARGETS.practicality },
      actionability: { rate: r4(actionableRate), target: INTERVENTION_VALIDATION_TARGETS.actionability, pass: actionableRate >= INTERVENTION_VALIDATION_TARGETS.actionability },
      archetype_alignment: { rate: r4(alignRate), target: INTERVENTION_VALIDATION_TARGETS.archetype_alignment, pass: alignRate >= INTERVENTION_VALIDATION_TARGETS.archetype_alignment },
      duplicate_rate: { rate: r4(dupRate), target: INTERVENTION_VALIDATION_TARGETS.duplicate_rate_max, pass: dupRate <= INTERVENTION_VALIDATION_TARGETS.duplicate_rate_max },
      coverage: { rate: r4(coverageRate), target: INTERVENTION_VALIDATION_TARGETS.coverage, pass: coverageRate >= INTERVENTION_VALIDATION_TARGETS.coverage },
    },
    transformation_readiness_score: Math.round(trs * 10) / 10,
  };
}

async function getStats(pool: Pool, force = false): Promise<StatsShape> {
  if (!force && _statsCache && Date.now() - _statsCache.at < CACHE_TTL_MS) return _statsCache.data;
  const data = await computeStats(pool, force);
  _statsCache = { at: Date.now(), data };
  return data;
}

export function registerPilInterventionRoutes(
  app: Express,
  pool: Pool,
  requireAuth: RequestHandler,
  requireSuperAdmin: RequestHandler,
): void {
  const base = '/api/admin/pil/intervention';

  // GET /stats
  app.get(`${base}/stats`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const stats = await getStats(pool, req.query.refresh === '1');
      res.json({ ok: true, stats });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'intervention stats failed' });
    }
  });

  // GET /interventions — paginated (filters: archetype, stakeholder, intervention_type)
  app.get(`${base}/interventions`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const limit = Math.min(Math.max(Number(req.query.limit) || 100, 1), 1000);
      const offset = Math.max(Number(req.query.offset) || 0, 0);
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`il.archetype_key = $${params.length}`); }
      const stake = String(req.query.stakeholder || '').trim();
      if (STAKES.has(stake)) { params.push(stake); where.push(`il.stakeholder_type = $${params.length}`); }
      const it = String(req.query.intervention_type || '').trim();
      if (TYPES.has(it)) { params.push(it); where.push(`il.intervention_type = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const total = Number((await pool.query(`SELECT count(*)::int n FROM pil_intervention_library il ${whereSql}`, params)).rows[0]?.n ?? 0);
      params.push(limit); params.push(offset);
      const rows = (await pool.query(`
        SELECT il.intervention_id, il.archetype_id, il.archetype_key, il.archetype_name, il.problem_id, il.stakeholder_type, il.intervention_type, il.intervention_text,
               il.realism_pass, il.aligned, il.is_duplicate,
               q.practicality, q.actionability, q.outcome_clarity, q.stakeholder_relevance, q.archetype_alignment, q.composite,
               o.expected_outcome, o.success_indicator, o.progress_indicator, o.confidence_impact, o.risk_reduction_impact
        FROM pil_intervention_library il
        LEFT JOIN pil_intervention_quality_scores q ON q.intervention_id = il.intervention_id
        LEFT JOIN pil_intervention_outcomes o ON o.intervention_id = il.intervention_id
        ${whereSql}
        ORDER BY il.archetype_key, il.intervention_type, il.stakeholder_type, il.intervention_id
        LIMIT $${params.length - 1} OFFSET $${params.length}`, params)).rows;
      res.json({ ok: true, total, limit, offset, count: rows.length, interventions: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'interventions failed' });
    }
  });

  // GET /pathways — archetype × stakeholder growth pathways (filter archetype, stakeholder)
  app.get(`${base}/pathways`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`archetype_key = $${params.length}`); }
      const stake = String(req.query.stakeholder || '').trim();
      if (STAKES.has(stake)) { params.push(stake); where.push(`stakeholder_type = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const rows = (await pool.query(`
        SELECT pathway_key, archetype_key, archetype_name, stakeholder_type, problem_id, stage_count, complete, stages, avg_composite, avg_confidence_impact, avg_risk_reduction, summary
        FROM pil_growth_pathways ${whereSql}
        ORDER BY archetype_key, stakeholder_type`, params)).rows;
      res.json({ ok: true, count: rows.length, pathways: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'pathways failed' });
    }
  });

  // GET /plans — archetype × stakeholder action-plan templates (filter archetype, stakeholder)
  app.get(`${base}/plans`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`archetype_key = $${params.length}`); }
      const stake = String(req.query.stakeholder || '').trim();
      if (STAKES.has(stake)) { params.push(stake); where.push(`stakeholder_type = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const rows = (await pool.query(`
        SELECT template_key, archetype_key, archetype_name, stakeholder_type, problem_id, plan_title, step_immediate, step_week, step_month, step_quarter, total_days, avg_composite, is_duplicate
        FROM pil_action_plan_templates ${whereSql}
        ORDER BY archetype_key, stakeholder_type`, params)).rows;
      res.json({ ok: true, count: rows.length, plans: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'plans failed' });
    }
  });

  // GET /duplicates — duplicate review (filters: kind, redundant); derived read-only from the library
  app.get(`${base}/duplicates`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const limit = Math.min(Math.max(Number(req.query.limit) || 200, 1), 2000);
      const offset = Math.max(Number(req.query.offset) || 0, 0);
      const kind = String(req.query.kind || '').trim();
      const redundant = String(req.query.redundant || '').trim();
      let review = await loadDuplicateReview(pool, req.query.refresh === '1');
      if (DUP_KINDS.has(kind)) review = review.filter((r) => r.kind === kind);
      if (redundant === 'true' || redundant === 'false') review = review.filter((r) => r.redundant === (redundant === 'true'));
      const total = review.length;
      const rows = review.slice(offset, offset + limit);
      res.json({ ok: true, total, limit, offset, count: rows.length, duplicates: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'duplicates failed' });
    }
  });

  // ── CSV exports — literal routes BEFORE param /:key ─────────────────────────
  app.get(`${base}/interventions.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`
        SELECT il.archetype_id, il.archetype_key, il.archetype_name, il.problem_id, il.stakeholder_type, il.intervention_type, il.intervention_text,
               o.expected_outcome, o.success_indicator, o.progress_indicator, o.confidence_impact, o.risk_reduction_impact,
               il.realism_pass, il.aligned, il.is_duplicate,
               q.practicality, q.actionability, q.outcome_clarity, q.stakeholder_relevance, q.archetype_alignment, q.composite
        FROM pil_intervention_library il
        LEFT JOIN pil_intervention_quality_scores q ON q.intervention_id = il.intervention_id
        LEFT JOIN pil_intervention_outcomes o ON o.intervention_id = il.intervention_id
        ORDER BY il.archetype_key, il.intervention_type, il.stakeholder_type, il.intervention_id`)).rows;
      sendCsv(res, 'pil_interventions.csv',
        ['archetype_id', 'archetype_key', 'archetype_name', 'problem_id', 'stakeholder_type', 'intervention_type', 'intervention_text', 'expected_outcome', 'success_indicator', 'progress_indicator', 'confidence_impact', 'risk_reduction_impact', 'realism_pass', 'aligned', 'is_duplicate', 'practicality', 'actionability', 'outcome_clarity', 'stakeholder_relevance', 'archetype_alignment', 'composite'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'interventions csv failed' });
    }
  });
  app.get(`${base}/pathways.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`SELECT pathway_key, archetype_key, archetype_name, stakeholder_type, problem_id, stage_count, complete, avg_composite, avg_confidence_impact, avg_risk_reduction, summary FROM pil_growth_pathways ORDER BY archetype_key, stakeholder_type`)).rows;
      sendCsv(res, 'pil_growth_pathways.csv', ['pathway_key', 'archetype_key', 'archetype_name', 'stakeholder_type', 'problem_id', 'stage_count', 'complete', 'avg_composite', 'avg_confidence_impact', 'avg_risk_reduction', 'summary'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'pathways csv failed' });
    }
  });
  app.get(`${base}/plans.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`SELECT template_key, archetype_key, archetype_name, stakeholder_type, problem_id, plan_title, step_immediate, step_week, step_month, step_quarter, total_days, avg_composite, is_duplicate FROM pil_action_plan_templates ORDER BY archetype_key, stakeholder_type`)).rows;
      sendCsv(res, 'pil_action_plan_templates.csv', ['template_key', 'archetype_key', 'archetype_name', 'stakeholder_type', 'problem_id', 'plan_title', 'step_immediate', 'step_week', 'step_month', 'step_quarter', 'total_days', 'avg_composite', 'is_duplicate'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'plans csv failed' });
    }
  });
  app.get(`${base}/duplicates.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = await loadDuplicateReview(pool);
      sendCsv(res, 'pil_intervention_duplicate_review.csv', ['dup_id', 'kind', 'redundant', 'text_a', 'text_b', 'overlap', 'archetype_a', 'archetype_b', 'stakeholder_a', 'stakeholder_b'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'duplicates csv failed' });
    }
  });

  // GET /:key — one archetype: interventions grouped + pathways + plans (param route LAST)
  app.get(`${base}/:key`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const key = String(req.params.key || '').trim();
      const [interventions, pathways, plans] = await Promise.all([
        pool.query(`
          SELECT il.intervention_id, il.archetype_name, il.problem_id, il.stakeholder_type, il.intervention_type, il.intervention_text,
                 il.realism_pass, il.aligned, il.is_duplicate,
                 q.practicality, q.actionability, q.outcome_clarity, q.stakeholder_relevance, q.archetype_alignment, q.composite,
                 o.expected_outcome, o.success_indicator, o.progress_indicator, o.confidence_impact, o.risk_reduction_impact
          FROM pil_intervention_library il
          LEFT JOIN pil_intervention_quality_scores q ON q.intervention_id = il.intervention_id
          LEFT JOIN pil_intervention_outcomes o ON o.intervention_id = il.intervention_id
          WHERE il.archetype_key = $1
          ORDER BY il.intervention_type, il.stakeholder_type, il.intervention_id`, [key]),
        pool.query(`SELECT pathway_key, stakeholder_type, stage_count, complete, stages, avg_composite, avg_confidence_impact, avg_risk_reduction, summary FROM pil_growth_pathways WHERE archetype_key = $1 ORDER BY stakeholder_type`, [key]),
        pool.query(`SELECT template_key, stakeholder_type, plan_title, step_immediate, step_week, step_month, step_quarter, total_days, avg_composite, is_duplicate FROM pil_action_plan_templates WHERE archetype_key = $1 ORDER BY stakeholder_type`, [key]),
      ]);
      if (!interventions.rows.length) return res.status(404).json({ ok: false, error: 'archetype has no interventions' });
      res.json({
        ok: true, archetype_key: key, archetype_name: interventions.rows[0].archetype_name || key,
        count: interventions.rows.length,
        interventions: interventions.rows, pathways: pathways.rows, plans: plans.rows,
      });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'intervention detail failed' });
    }
  });
}
