/**
 * CAPADEX PIL — Phase 3 Human Intelligence API (read-only).
 *
 * Surfaces the persisted Phase-3 tables (human_problem_library, human_emotion_library,
 * stakeholder_narratives) to the SuperAdmin "Human Intelligence" panel. Pure reads:
 * SELECTs only; the deterministic content is authored + regenerated by the runner
 * (`scripts/pil/run-human-intelligence.ts`), never mutated here.
 *
 * Endpoints (all requireAuth + requireSuperAdmin), base /api/admin/pil/human:
 *   GET /stats          — coverage + the three honest validators (realism/dup/alignment)
 *   GET /problems       — paginated problem library (filter archetype/voice)
 *   GET /emotions       — paginated emotion library (filter archetype/type)
 *   GET /narratives     — paginated stakeholder narratives (filter archetype/stakeholder)
 *   GET /problems.csv | /emotions.csv | /narratives.csv  — exports [literal BEFORE /:key]
 *   GET /:key           — one archetype: problems + emotions + narratives  [param LAST]
 */
import type { Express, Request, Response, RequestHandler } from 'express';
import type { Pool } from 'pg';
import {
  STAKEHOLDERS, EMOTION_TYPES, PROBLEM_VOICES, MIN_PROBLEMS, VALIDATION_TARGETS,
} from '../services/pil/human-intelligence-engine.js';

const VOICES = new Set<string>(PROBLEM_VOICES);
const EMO_TYPES = new Set<string>(EMOTION_TYPES);
const STAKES = new Set<string>(STAKEHOLDERS);

function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return '';
  let s = String(v);
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`; // neutralise spreadsheet formula injection
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function sendCsv(res: Response, file: string, header: string[], rows: any[]): void {
  const lines = [header.join(',')];
  for (const r of rows) lines.push(header.map((h) => csvEscape(r[h])).join(','));
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${file}"`);
  res.send(lines.join('\n'));
}

interface StatsShape {
  generated_at: string;
  totals: { problems: number; emotions: number; narratives: number; archetypes: number };
  coverage: { problems_ok: number; stakeholders_ok: number; emotions_ok: number; archetypes: number };
  emotion_distribution: Record<string, number>;
  stakeholder_distribution: Record<string, number>;
  voice_distribution: Record<string, number>;
  validation: {
    human_realism: { rate: number; target: number; pass: boolean };
    duplicate_rate: { rate: number; target: number; pass: boolean };
    archetype_alignment: { rate: number; target: number; pass: boolean };
  };
}

const CACHE_TTL_MS = 60_000;
let _statsCache: { at: number; data: StatsShape } | null = null;

async function computeStats(pool: Pool): Promise<StatsShape> {
  const [pAgg, eAgg, nAgg, cov] = await Promise.all([
    pool.query(`SELECT count(*)::int n, count(*) FILTER (WHERE realism_pass)::int realism, count(*) FILTER (WHERE aligned)::int aligned, count(*) FILTER (WHERE is_duplicate)::int dup, count(DISTINCT archetype_key)::int ak FROM human_problem_library`),
    pool.query(`SELECT count(*)::int n, count(*) FILTER (WHERE realism_pass)::int realism, count(*) FILTER (WHERE aligned)::int aligned, count(*) FILTER (WHERE is_duplicate)::int dup, count(DISTINCT archetype_key)::int ak FROM human_emotion_library`),
    pool.query(`SELECT count(*)::int n, count(*) FILTER (WHERE realism_pass)::int realism, count(*) FILTER (WHERE aligned)::int aligned, count(*) FILTER (WHERE is_duplicate)::int dup, count(DISTINCT archetype_key)::int ak FROM stakeholder_narratives`),
    pool.query(`
      WITH per AS (
        SELECT archetype_key,
               (SELECT count(*) FROM human_problem_library p WHERE p.archetype_key = a.archetype_key) AS problems,
               (SELECT count(DISTINCT stakeholder) FROM stakeholder_narratives s WHERE s.archetype_key = a.archetype_key) AS stakeholders,
               (SELECT count(DISTINCT emotion_type) FROM human_emotion_library e WHERE e.archetype_key = a.archetype_key) AS emotions
        FROM (SELECT DISTINCT archetype_key FROM human_problem_library
              UNION SELECT DISTINCT archetype_key FROM human_emotion_library
              UNION SELECT DISTINCT archetype_key FROM stakeholder_narratives) a
      )
      SELECT count(*)::int archetypes,
             count(*) FILTER (WHERE problems >= ${MIN_PROBLEMS})::int problems_ok,
             count(*) FILTER (WHERE stakeholders >= ${STAKEHOLDERS.length})::int stakeholders_ok,
             count(*) FILTER (WHERE emotions >= ${EMOTION_TYPES.length})::int emotions_ok
      FROM per`),
  ]);
  const [emoDist, stakeDist, voiceDist] = await Promise.all([
    pool.query(`SELECT emotion_type k, count(*)::int n FROM human_emotion_library GROUP BY emotion_type`),
    pool.query(`SELECT stakeholder k, count(*)::int n FROM stakeholder_narratives GROUP BY stakeholder`),
    pool.query(`SELECT voice k, count(*)::int n FROM human_problem_library GROUP BY voice`),
  ]);

  const p = pAgg.rows[0], e = eAgg.rows[0], n = nAgg.rows[0], c = cov.rows[0];
  const total = p.n + e.n + n.n;
  const realismOk = p.realism + e.realism + n.realism;
  const alignedOk = p.aligned + e.aligned + n.aligned;
  const dupCount = p.dup + e.dup + n.dup;
  const realismRate = total ? realismOk / total : 0;
  const alignRate = total ? alignedOk / total : 0;
  const dupRate = total ? dupCount / total : 0;

  const dist = (rows: any[], keys: readonly string[]): Record<string, number> => {
    const o: Record<string, number> = {};
    for (const k of keys) o[k] = 0;
    for (const r of rows) o[r.k] = Number(r.n);
    return o;
  };

  return {
    generated_at: new Date().toISOString(),
    totals: { problems: p.n, emotions: e.n, narratives: n.n, archetypes: Number(c?.archetypes ?? 0) },
    coverage: {
      problems_ok: Number(c?.problems_ok ?? 0),
      stakeholders_ok: Number(c?.stakeholders_ok ?? 0),
      emotions_ok: Number(c?.emotions_ok ?? 0),
      archetypes: Number(c?.archetypes ?? 0),
    },
    emotion_distribution: dist(emoDist.rows, EMOTION_TYPES),
    stakeholder_distribution: dist(stakeDist.rows, STAKEHOLDERS),
    voice_distribution: dist(voiceDist.rows, PROBLEM_VOICES),
    validation: {
      human_realism: { rate: Math.round(realismRate * 10000) / 10000, target: VALIDATION_TARGETS.human_realism, pass: realismRate >= VALIDATION_TARGETS.human_realism },
      duplicate_rate: { rate: Math.round(dupRate * 10000) / 10000, target: VALIDATION_TARGETS.duplicate_rate_max, pass: dupRate <= VALIDATION_TARGETS.duplicate_rate_max },
      archetype_alignment: { rate: Math.round(alignRate * 10000) / 10000, target: VALIDATION_TARGETS.archetype_alignment, pass: alignRate >= VALIDATION_TARGETS.archetype_alignment },
    },
  };
}

async function getStats(pool: Pool, force = false): Promise<StatsShape> {
  if (!force && _statsCache && Date.now() - _statsCache.at < CACHE_TTL_MS) return _statsCache.data;
  const data = await computeStats(pool);
  _statsCache = { at: Date.now(), data };
  return data;
}

export function registerPilHumanIntelligenceRoutes(
  app: Express,
  pool: Pool,
  requireAuth: RequestHandler,
  requireSuperAdmin: RequestHandler,
): void {
  const base = '/api/admin/pil/human';

  // GET /stats — coverage + validators
  app.get(`${base}/stats`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const stats = await getStats(pool, req.query.refresh === '1');
      res.json({ ok: true, stats });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'human stats failed' });
    }
  });

  // GET /problems — paginated (filters: archetype, voice)
  app.get(`${base}/problems`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const limit = Math.min(Math.max(Number(req.query.limit) || 100, 1), 1000);
      const offset = Math.max(Number(req.query.offset) || 0, 0);
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`archetype_key = $${params.length}`); }
      const voice = String(req.query.voice || '').trim();
      if (VOICES.has(voice)) { params.push(voice); where.push(`voice = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const total = Number((await pool.query(`SELECT count(*)::int n FROM human_problem_library ${whereSql}`, params)).rows[0]?.n ?? 0);
      params.push(limit); params.push(offset);
      const rows = (await pool.query(`
        SELECT problem_id, archetype_key, archetype_name, voice, problem_statement, realism_pass, aligned, is_duplicate
        FROM human_problem_library ${whereSql}
        ORDER BY archetype_key, problem_id
        LIMIT $${params.length - 1} OFFSET $${params.length}`, params)).rows;
      res.json({ ok: true, total, limit, offset, count: rows.length, problems: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'human problems failed' });
    }
  });

  // GET /emotions — paginated (filters: archetype, type)
  app.get(`${base}/emotions`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const limit = Math.min(Math.max(Number(req.query.limit) || 100, 1), 1000);
      const offset = Math.max(Number(req.query.offset) || 0, 0);
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`archetype_key = $${params.length}`); }
      const type = String(req.query.type || '').trim();
      if (EMO_TYPES.has(type)) { params.push(type); where.push(`emotion_type = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const total = Number((await pool.query(`SELECT count(*)::int n FROM human_emotion_library ${whereSql}`, params)).rows[0]?.n ?? 0);
      params.push(limit); params.push(offset);
      const rows = (await pool.query(`
        SELECT emotion_id, archetype_key, archetype_name, emotion_type, statement, realism_pass, aligned, is_duplicate
        FROM human_emotion_library ${whereSql}
        ORDER BY archetype_key, emotion_type, emotion_id
        LIMIT $${params.length - 1} OFFSET $${params.length}`, params)).rows;
      res.json({ ok: true, total, limit, offset, count: rows.length, emotions: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'human emotions failed' });
    }
  });

  // GET /narratives — paginated (filters: archetype, stakeholder)
  app.get(`${base}/narratives`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const limit = Math.min(Math.max(Number(req.query.limit) || 100, 1), 1000);
      const offset = Math.max(Number(req.query.offset) || 0, 0);
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`archetype_key = $${params.length}`); }
      const stake = String(req.query.stakeholder || '').trim();
      if (STAKES.has(stake)) { params.push(stake); where.push(`stakeholder = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const total = Number((await pool.query(`SELECT count(*)::int n FROM stakeholder_narratives ${whereSql}`, params)).rows[0]?.n ?? 0);
      params.push(limit); params.push(offset);
      const rows = (await pool.query(`
        SELECT narrative_id, archetype_key, archetype_name, stakeholder, narrative, realism_pass, aligned, is_duplicate
        FROM stakeholder_narratives ${whereSql}
        ORDER BY archetype_key, stakeholder, narrative_id
        LIMIT $${params.length - 1} OFFSET $${params.length}`, params)).rows;
      res.json({ ok: true, total, limit, offset, count: rows.length, narratives: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'human narratives failed' });
    }
  });

  // ── CSV exports — literal routes BEFORE param /:key ─────────────────────────
  app.get(`${base}/problems.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`SELECT archetype_key, archetype_name, voice, problem_statement, realism_pass, aligned, is_duplicate FROM human_problem_library ORDER BY archetype_key, problem_id`)).rows;
      sendCsv(res, 'human_problem_library.csv', ['archetype_key', 'archetype_name', 'voice', 'problem_statement', 'realism_pass', 'aligned', 'is_duplicate'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'problems csv failed' });
    }
  });
  app.get(`${base}/emotions.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`SELECT archetype_key, archetype_name, emotion_type, statement, realism_pass, aligned, is_duplicate FROM human_emotion_library ORDER BY archetype_key, emotion_type, emotion_id`)).rows;
      sendCsv(res, 'human_emotion_library.csv', ['archetype_key', 'archetype_name', 'emotion_type', 'statement', 'realism_pass', 'aligned', 'is_duplicate'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'emotions csv failed' });
    }
  });
  app.get(`${base}/narratives.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`SELECT archetype_key, archetype_name, stakeholder, narrative, realism_pass, aligned, is_duplicate FROM stakeholder_narratives ORDER BY archetype_key, stakeholder, narrative_id`)).rows;
      sendCsv(res, 'stakeholder_narratives.csv', ['archetype_key', 'archetype_name', 'stakeholder', 'narrative', 'realism_pass', 'aligned', 'is_duplicate'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'narratives csv failed' });
    }
  });

  // GET /:key — one archetype: full human content (param route LAST among GETs)
  app.get(`${base}/:key`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const key = String(req.params.key || '').trim();
      const [problems, emotions, narratives] = await Promise.all([
        pool.query(`SELECT problem_id, archetype_name, voice, problem_statement, realism_pass, aligned, is_duplicate FROM human_problem_library WHERE archetype_key = $1 ORDER BY problem_id`, [key]),
        pool.query(`SELECT emotion_id, archetype_name, emotion_type, statement, realism_pass, aligned, is_duplicate FROM human_emotion_library WHERE archetype_key = $1 ORDER BY emotion_type, emotion_id`, [key]),
        pool.query(`SELECT narrative_id, archetype_name, stakeholder, narrative, realism_pass, aligned, is_duplicate FROM stakeholder_narratives WHERE archetype_key = $1 ORDER BY stakeholder, narrative_id`, [key]),
      ]);
      if (!problems.rows.length && !emotions.rows.length && !narratives.rows.length) {
        return res.status(404).json({ ok: false, error: 'archetype has no human content' });
      }
      const name = problems.rows[0]?.archetype_name || emotions.rows[0]?.archetype_name || narratives.rows[0]?.archetype_name || key;
      res.json({ ok: true, archetype_key: key, archetype_name: name, problems: problems.rows, emotions: emotions.rows, narratives: narratives.rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'human detail failed' });
    }
  });
}
