/**
 * CAPADEX PIL — Phase 4 Search Intent API (read-only).
 *
 * Surfaces the persisted Phase-4 tables (search_intents, search_intent_quality_scores,
 * search_intent_duplicate_review, search_intent_clusters) to the SuperAdmin
 * "Search Intent" panel. Pure reads: SELECTs only; the deterministic content is
 * authored + regenerated by the runner (`scripts/pil/run-search-intent.ts`),
 * never mutated here.
 *
 * Endpoints (all requireAuth + requireSuperAdmin), base /api/admin/pil/search:
 *   GET /stats        — distributions, quality averages, validators, Discovery Readiness Score
 *   GET /intents      — paginated intents + scores (filter archetype/stakeholder/intent_type)
 *   GET /clusters     — archetype × intent-type demand clusters
 *   GET /duplicates   — duplicate review (filter kind, redundant)
 *   GET /intents.csv | /clusters.csv | /duplicates.csv  — exports [literal BEFORE /:key]
 *   GET /:key         — one archetype: intents + scores grouped  [param LAST]
 */
import type { Express, Request, Response, RequestHandler } from 'express';
import type { Pool } from 'pg';
import {
  STAKEHOLDERS, INTENT_TYPES, SEARCH_VALIDATION_TARGETS,
} from '../services/pil/search-intent-engine.js';

const STAKES = new Set<string>(STAKEHOLDERS);
const INTENTS = new Set<string>(INTENT_TYPES);
const DUP_KINDS = new Set(['identical', 'semantic', 'stakeholder']);

function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return '';
  let s = String(v);
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`; // neutralise spreadsheet formula injection
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function sendCsv(res: Response, file: string, header: string[], rows: any[]): void {
  const lines = [header.join(',')];
  for (const r of rows) lines.push(header.map((h) => csvEscape(r[h])).join(','));
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${file}"`);
  res.send(lines.join('\n'));
}

interface StatsShape {
  generated_at: string;
  totals: { intents: number; clusters: number; duplicate_reviews: number; archetypes: number };
  coverage: { fully_covered: number; archetypes: number };
  intent_distribution: Record<string, number>;
  stakeholder_distribution: Record<string, number>;
  quality_averages: { search_realism: number; human_language: number; archetype_alignment: number; intent_clarity: number; composite: number };
  duplicate_breakdown: { identical: number; semantic: number; stakeholder: number; redundant: number; variants: number };
  link_integrity: { linked: number; orphans: number };
  validation: {
    search_realism: { rate: number; target: number; pass: boolean };
    archetype_alignment: { rate: number; target: number; pass: boolean };
    duplicate_rate: { rate: number; target: number; pass: boolean };
    intent_clarity: { rate: number };
  };
  discovery_readiness_score: number;
}

const CACHE_TTL_MS = 60_000;
let _statsCache: { at: number; data: StatsShape } | null = null;

function r4(n: number): number { return Math.round(n * 10000) / 10000; }
function r2(n: number): number { return Math.round(n * 100) / 100; }

async function computeStats(pool: Pool): Promise<StatsShape> {
  const [agg, intentDist, stakeDist, qAvg, dupAgg, cov, archCount, orphan, clusterN, dupN] = await Promise.all([
    pool.query(`SELECT count(*)::int n,
        count(*) FILTER (WHERE realism_pass)::int realism,
        count(*) FILTER (WHERE aligned)::int aligned,
        count(*) FILTER (WHERE intent_clear)::int clear,
        count(*) FILTER (WHERE is_duplicate)::int dup,
        count(DISTINCT archetype_key)::int ak FROM search_intents`),
    pool.query(`SELECT intent_type k, count(*)::int n FROM search_intents GROUP BY intent_type`),
    pool.query(`SELECT stakeholder_type k, count(*)::int n FROM search_intents GROUP BY stakeholder_type`),
    pool.query(`SELECT avg(search_realism)::float sr, avg(human_language)::float hl, avg(archetype_alignment)::float aa, avg(intent_clarity)::float ic, avg(composite)::float cp FROM search_intent_quality_scores`),
    pool.query(`SELECT kind, count(*)::int n, count(*) FILTER (WHERE redundant)::int redundant FROM search_intent_duplicate_review GROUP BY kind`),
    pool.query(`WITH per AS (SELECT archetype_key, count(*) c FROM search_intents GROUP BY archetype_key)
                SELECT count(*)::int archetypes, count(*) FILTER (WHERE c = ${STAKEHOLDERS.length * INTENT_TYPES.length})::int fully FROM per`),
    pool.query(`SELECT count(*)::int n FROM archetype_library`),
    pool.query(`SELECT count(*)::int n FROM search_intents si LEFT JOIN human_problem_library h ON si.problem_id = h.problem_id WHERE h.problem_id IS NULL`),
    pool.query(`SELECT count(*)::int n FROM search_intent_clusters`),
    pool.query(`SELECT count(*)::int n FROM search_intent_duplicate_review`),
  ]);

  const a = agg.rows[0];
  const total = a.n || 0;
  const realismRate = total ? a.realism / total : 0;
  const alignRate = total ? a.aligned / total : 0;
  const clarityRate = total ? a.clear / total : 0;
  const dupRate = total ? a.dup / total : 0;

  const dist = (rows: any[], keys: readonly string[]): Record<string, number> => {
    const o: Record<string, number> = {};
    for (const k of keys) o[k] = 0;
    for (const row of rows) o[row.k] = Number(row.n);
    return o;
  };
  const dupBy: Record<string, { n: number; redundant: number }> = { identical: { n: 0, redundant: 0 }, semantic: { n: 0, redundant: 0 }, stakeholder: { n: 0, redundant: 0 } };
  for (const row of dupAgg.rows) dupBy[row.kind] = { n: Number(row.n), redundant: Number(row.redundant) };
  const redundant = dupBy.identical.redundant + dupBy.semantic.redundant + dupBy.stakeholder.redundant;
  const variants = (Number(dupN.rows[0]?.n ?? 0)) - redundant;

  const fully = Number(cov.rows[0]?.fully ?? 0);
  const archetypes = Number(archCount.rows[0]?.n ?? 0);
  const coverageRate = archetypes ? fully / archetypes : 0;
  const orphans = Number(orphan.rows[0]?.n ?? 0);
  const linkRate = total ? (total - orphans) / total : 0;

  const drs = r4(realismRate * 0.25 + alignRate * 0.20 + clarityRate * 0.15 + (1 - dupRate) * 0.15 + coverageRate * 0.15 + linkRate * 0.10) * 100;

  const q = qAvg.rows[0] || {};
  return {
    generated_at: new Date().toISOString(),
    totals: { intents: total, clusters: Number(clusterN.rows[0]?.n ?? 0), duplicate_reviews: Number(dupN.rows[0]?.n ?? 0), archetypes: a.ak || 0 },
    coverage: { fully_covered: fully, archetypes },
    intent_distribution: dist(intentDist.rows, INTENT_TYPES),
    stakeholder_distribution: dist(stakeDist.rows, STAKEHOLDERS),
    quality_averages: {
      search_realism: r2(Number(q.sr ?? 0)), human_language: r2(Number(q.hl ?? 0)),
      archetype_alignment: r2(Number(q.aa ?? 0)), intent_clarity: r2(Number(q.ic ?? 0)), composite: r2(Number(q.cp ?? 0)),
    },
    duplicate_breakdown: { identical: dupBy.identical.n, semantic: dupBy.semantic.n, stakeholder: dupBy.stakeholder.n, redundant, variants },
    link_integrity: { linked: total - orphans, orphans },
    validation: {
      search_realism: { rate: r4(realismRate), target: SEARCH_VALIDATION_TARGETS.search_realism, pass: realismRate >= SEARCH_VALIDATION_TARGETS.search_realism },
      archetype_alignment: { rate: r4(alignRate), target: SEARCH_VALIDATION_TARGETS.archetype_alignment, pass: alignRate >= SEARCH_VALIDATION_TARGETS.archetype_alignment },
      duplicate_rate: { rate: r4(dupRate), target: SEARCH_VALIDATION_TARGETS.duplicate_rate_max, pass: dupRate <= SEARCH_VALIDATION_TARGETS.duplicate_rate_max },
      intent_clarity: { rate: r4(clarityRate) },
    },
    discovery_readiness_score: Math.round(drs * 10) / 10,
  };
}

async function getStats(pool: Pool, force = false): Promise<StatsShape> {
  if (!force && _statsCache && Date.now() - _statsCache.at < CACHE_TTL_MS) return _statsCache.data;
  const data = await computeStats(pool);
  _statsCache = { at: Date.now(), data };
  return data;
}

export function registerPilSearchIntentRoutes(
  app: Express,
  pool: Pool,
  requireAuth: RequestHandler,
  requireSuperAdmin: RequestHandler,
): void {
  const base = '/api/admin/pil/search';

  // GET /stats
  app.get(`${base}/stats`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const stats = await getStats(pool, req.query.refresh === '1');
      res.json({ ok: true, stats });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'search stats failed' });
    }
  });

  // GET /intents — paginated (filters: archetype, stakeholder, intent_type)
  app.get(`${base}/intents`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const limit = Math.min(Math.max(Number(req.query.limit) || 100, 1), 1000);
      const offset = Math.max(Number(req.query.offset) || 0, 0);
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`si.archetype_key = $${params.length}`); }
      const stake = String(req.query.stakeholder || '').trim();
      if (STAKES.has(stake)) { params.push(stake); where.push(`si.stakeholder_type = $${params.length}`); }
      const it = String(req.query.intent_type || '').trim();
      if (INTENTS.has(it)) { params.push(it); where.push(`si.intent_type = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const total = Number((await pool.query(`SELECT count(*)::int n FROM search_intents si ${whereSql}`, params)).rows[0]?.n ?? 0);
      params.push(limit); params.push(offset);
      const rows = (await pool.query(`
        SELECT si.intent_id, si.archetype_key, si.archetype_name, si.problem_id, si.stakeholder_type, si.intent_type, si.search_phrase,
               si.realism_pass, si.aligned, si.intent_clear, si.is_duplicate,
               q.search_realism, q.human_language, q.archetype_alignment, q.intent_clarity, q.composite
        FROM search_intents si LEFT JOIN search_intent_quality_scores q ON q.intent_id = si.intent_id
        ${whereSql}
        ORDER BY si.archetype_key, si.intent_type, si.stakeholder_type, si.intent_id
        LIMIT $${params.length - 1} OFFSET $${params.length}`, params)).rows;
      res.json({ ok: true, total, limit, offset, count: rows.length, intents: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'search intents failed' });
    }
  });

  // GET /clusters — archetype × intent-type clusters (filter archetype)
  app.get(`${base}/clusters`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const where: string[] = []; const params: unknown[] = [];
      const ak = String(req.query.archetype || '').trim();
      if (ak) { params.push(ak); where.push(`archetype_key = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const rows = (await pool.query(`
        SELECT cluster_key, cluster_label, archetype_key, archetype_name, intent_type, member_count, avg_composite, sample_phrase
        FROM search_intent_clusters ${whereSql}
        ORDER BY avg_composite DESC, member_count DESC`, params)).rows;
      res.json({ ok: true, count: rows.length, clusters: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'search clusters failed' });
    }
  });

  // GET /duplicates — duplicate review (filters: kind, redundant)
  app.get(`${base}/duplicates`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const limit = Math.min(Math.max(Number(req.query.limit) || 200, 1), 2000);
      const offset = Math.max(Number(req.query.offset) || 0, 0);
      const where: string[] = []; const params: unknown[] = [];
      const kind = String(req.query.kind || '').trim();
      if (DUP_KINDS.has(kind)) { params.push(kind); where.push(`kind = $${params.length}`); }
      const redundant = String(req.query.redundant || '').trim();
      if (redundant === 'true' || redundant === 'false') { params.push(redundant === 'true'); where.push(`redundant = $${params.length}`); }
      const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';
      const total = Number((await pool.query(`SELECT count(*)::int n FROM search_intent_duplicate_review ${whereSql}`, params)).rows[0]?.n ?? 0);
      params.push(limit); params.push(offset);
      const rows = (await pool.query(`
        SELECT dup_id, kind, redundant, phrase_a, phrase_b, overlap, archetype_a, archetype_b, stakeholder_a, stakeholder_b
        FROM search_intent_duplicate_review ${whereSql}
        ORDER BY redundant DESC, overlap DESC, dup_id
        LIMIT $${params.length - 1} OFFSET $${params.length}`, params)).rows;
      res.json({ ok: true, total, limit, offset, count: rows.length, duplicates: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'search duplicates failed' });
    }
  });

  // ── CSV exports — literal routes BEFORE param /:key ─────────────────────────
  app.get(`${base}/intents.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`
        SELECT si.archetype_key, si.archetype_name, si.problem_id, si.stakeholder_type, si.intent_type, si.search_phrase,
               si.realism_pass, si.aligned, si.intent_clear, si.is_duplicate,
               q.search_realism, q.human_language, q.archetype_alignment, q.intent_clarity, q.composite
        FROM search_intents si LEFT JOIN search_intent_quality_scores q ON q.intent_id = si.intent_id
        ORDER BY si.archetype_key, si.intent_type, si.stakeholder_type, si.intent_id`)).rows;
      sendCsv(res, 'search_intents.csv',
        ['archetype_key', 'archetype_name', 'problem_id', 'stakeholder_type', 'intent_type', 'search_phrase', 'realism_pass', 'aligned', 'intent_clear', 'is_duplicate', 'search_realism', 'human_language', 'archetype_alignment', 'intent_clarity', 'composite'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'intents csv failed' });
    }
  });
  app.get(`${base}/clusters.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`SELECT cluster_key, cluster_label, archetype_key, intent_type, member_count, avg_composite, sample_phrase FROM search_intent_clusters ORDER BY avg_composite DESC`)).rows;
      sendCsv(res, 'search_intent_clusters.csv', ['cluster_key', 'cluster_label', 'archetype_key', 'intent_type', 'member_count', 'avg_composite', 'sample_phrase'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'clusters csv failed' });
    }
  });
  app.get(`${base}/duplicates.csv`, requireAuth, requireSuperAdmin, async (_req: Request, res: Response) => {
    try {
      const rows = (await pool.query(`SELECT kind, redundant, phrase_a, phrase_b, overlap, archetype_a, archetype_b, stakeholder_a, stakeholder_b FROM search_intent_duplicate_review ORDER BY redundant DESC, overlap DESC, dup_id`)).rows;
      sendCsv(res, 'search_intent_duplicate_review.csv', ['kind', 'redundant', 'phrase_a', 'phrase_b', 'overlap', 'archetype_a', 'archetype_b', 'stakeholder_a', 'stakeholder_b'], rows);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'duplicates csv failed' });
    }
  });

  // GET /:key — one archetype: intents grouped by intent type (param route LAST)
  app.get(`${base}/:key`, requireAuth, requireSuperAdmin, async (req: Request, res: Response) => {
    try {
      const key = String(req.params.key || '').trim();
      const rows = (await pool.query(`
        SELECT si.intent_id, si.archetype_name, si.problem_id, si.stakeholder_type, si.intent_type, si.search_phrase,
               si.realism_pass, si.aligned, si.intent_clear, si.is_duplicate,
               q.search_realism, q.human_language, q.archetype_alignment, q.intent_clarity, q.composite
        FROM search_intents si LEFT JOIN search_intent_quality_scores q ON q.intent_id = si.intent_id
        WHERE si.archetype_key = $1
        ORDER BY si.intent_type, si.stakeholder_type, si.intent_id`, [key])).rows;
      if (!rows.length) return res.status(404).json({ ok: false, error: 'archetype has no search intents' });
      res.json({ ok: true, archetype_key: key, archetype_name: rows[0].archetype_name || key, count: rows.length, intents: rows });
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err?.message || 'search detail failed' });
    }
  });
}
