// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chatbot-icons/AuroraSpark.tsx": () => import("../components/mockups/chatbot-icons/AuroraSpark.tsx"),
  "./components/mockups/chatbot-icons/CrystallineAI.tsx": () => import("../components/mockups/chatbot-icons/CrystallineAI.tsx"),
  "./components/mockups/chatbot-icons/NeuralPulse.tsx": () => import("../components/mockups/chatbot-icons/NeuralPulse.tsx"),
  "./components/mockups/chatbot-icons/QuantumOrb.tsx": () => import("../components/mockups/chatbot-icons/QuantumOrb.tsx"),
  "./components/mockups/tbh-landing/LandingPage.tsx": () => import("../components/mockups/tbh-landing/LandingPage.tsx")
};
