/**
 * Competency Maturity Layers
 * 5-level maturity model for each of the 24 competency domains.
 * Each level has a label, behavioural descriptor, and evidence signals.
 */

export interface MaturityLevel {
  level:       1 | 2 | 3 | 4 | 5;
  label:       string;
  descriptor:  string;
  evidenceSignals: string[];
}

export interface CompetencyMaturity {
  competencyId: string;
  levels: Record<1 | 2 | 3 | 4 | 5, MaturityLevel>;
}

const def = (
  competencyId: string,
  l1: [string, string, string[]],
  l2: [string, string, string[]],
  l3: [string, string, string[]],
  l4: [string, string, string[]],
  l5: [string, string, string[]],
): CompetencyMaturity => ({
  competencyId,
  levels: {
    1: { level: 1, label: l1[0], descriptor: l1[1], evidenceSignals: l1[2] },
    2: { level: 2, label: l2[0], descriptor: l2[1], evidenceSignals: l2[2] },
    3: { level: 3, label: l3[0], descriptor: l3[1], evidenceSignals: l3[2] },
    4: { level: 4, label: l4[0], descriptor: l4[1], evidenceSignals: l4[2] },
    5: { level: 5, label: l5[0], descriptor: l5[1], evidenceSignals: l5[2] },
  },
});

export const MATURITY_LAYERS: CompetencyMaturity[] = [
  def('programming',
    ['Aware',      'Can read code; writes simple scripts with guidance',            ['Completed a coding bootcamp', 'Built a "Hello World" project']],
    ['Practicing', 'Independently writes working code in 1 language',              ['Personal project on GitHub', '1–2 years of coding experience']],
    ['Proficient', 'Delivers production-quality features; code reviewed and merged',['Active in open source', 'Shipped features at work', 'Passes coding interviews']],
    ['Advanced',   'Designs APIs, refactors legacy systems, mentors teammates',     ['Tech lead on a product', 'Authored internal libraries', 'LeetCode Hard comfortable']],
    ['Expert',     'Sets coding standards; contributes to languages/frameworks',    ['Open source maintainer', 'Speaker at tech conferences', 'RFC authoring']],
  ),
  def('systems-design',
    ['Aware',      'Understands client-server model and basic databases',           ['Studied CS fundamentals']],
    ['Practicing', 'Can explain REST APIs, monoliths, and simple data models',     ['Designed simple services at work']],
    ['Proficient', 'Designs scalable services; handles load balancing, caching',   ['Led backend architecture for a product', 'Handled 10k+ req/s']],
    ['Advanced',   'Architects distributed systems; leads tech design reviews',    ['Designed microservices at scale', 'Authored tech design docs']],
    ['Expert',     'Shapes org-wide architecture; creates novel system patterns',  ['Principal/Staff engineer credits', 'Conference talks', 'Published design systems']],
  ),
  def('cloud',
    ['Aware',      'Knows what cloud providers are; used cloud storage or VMs',    ['Used AWS S3 or GCP console']],
    ['Practicing', 'Deploys apps to cloud; uses managed databases and VMs',        ['Deployed personal project on AWS/GCP/Azure']],
    ['Proficient', 'Manages IaC, CI/CD pipelines, container orchestration',       ['AWS/GCP certified', 'Kubernetes in production']],
    ['Advanced',   'Designs cloud-native systems; FinOps; multi-region strategies',['Cloud architect on 3+ projects', 'Cost-optimised cloud spend by >30%']],
    ['Expert',     'Sets cloud strategy for organisations; contributes to cloud OSS',['AWS Hero / GCP Champion', 'Cloud OS contributor']],
  ),
  def('data-engineering',
    ['Aware',      'Understands what data pipelines are; has used Excel/Sheets',   ['Completed a data engineering course']],
    ['Practicing', 'Writes ETL scripts; uses a data warehouse or lake',            ['Built pipelines in Airflow or dbt']],
    ['Proficient', 'Designs reliable pipelines; manages streaming and batch data', ['Production Kafka/Spark pipelines', 'Warehouse design at work']],
    ['Advanced',   'Architects data platforms; optimises cost and reliability',    ['Data platform lead', 'Reduced pipeline failures by >40%']],
    ['Expert',     'Shapes data platform strategy; contributes to OSS data tools', ['Committer to Airflow/Spark/dbt', 'Data platform at 1B+ event scale']],
  ),
  def('security',
    ['Aware',      'Knows basic security hygiene; aware of OWASP top 10',         ['Completed OWASP course or CEH intro']],
    ['Practicing', 'Implements auth, HTTPS, input validation in own code',         ['Added MFA or JWT auth to a project']],
    ['Proficient', 'Conducts threat modelling; performs security code reviews',    ['Passed OSCP or CEH', 'Found CVEs in internal audit']],
    ['Advanced',   'Leads red team exercises; designs zero-trust architectures',   ['Penetration testing engagements', 'Security architecture ownership']],
    ['Expert',     'Discovers novel attack vectors; shapes security posture',      ['CVE publications', 'Conference speaker', 'Security advisory roles']],
  ),
  def('data-analysis',
    ['Aware',      'Can read charts and understand basic metrics',                 ['Used GA4 or a dashboard tool']],
    ['Practicing', 'Writes SQL queries; builds dashboards in Tableau/Power BI',   ['Monthly reporting at work', 'SQL course completed']],
    ['Proficient', 'Designs analytical frameworks; drives decisions with data',    ['Owns a product analytics function', 'Built self-serve dashboards for teams']],
    ['Advanced',   'Builds predictive models; defines company KPI frameworks',    ['Led analytics for a P&L', 'Reduced churn via data insights by >20%']],
    ['Expert',     'Establishes data-driven culture; publishes analytical methods',['Chief Analytics Officer equivalent', 'Published analysis methodology']],
  ),
  def('statistics',
    ['Aware',      'Understands mean, median, correlation',                        ['High school/undergrad stats']],
    ['Practicing', 'Runs A/B tests, regression; interprets p-values',             ['A/B testing at work', 'Coursera ML or stats course']],
    ['Proficient', 'Applies advanced ML; designs experiments rigorously',          ['ML models in production', 'Kaggle competitions']],
    ['Advanced',   'Develops novel ML architectures; deep NLP/CV expertise',      ['PhD-level research or equivalent', 'Top-10 Kaggle rank']],
    ['Expert',     'Publishes novel research; shapes field-level ML direction',    ['NeurIPS / ICML papers', 'Top model benchmark positions']],
  ),
  def('business-acumen',
    ['Aware',      'Understands revenue, profit, and basic business model concepts',['MBA prep', 'Startup exposure']],
    ['Practicing', 'Frames work in terms of business impact; tracks OKRs',        ['Contributed to OKR planning', 'Read company financials']],
    ['Proficient', 'Analyses market opportunities; builds business cases',         ['Authored a business case that was approved', 'P&L ownership partial']],
    ['Advanced',   'Identifies strategic opportunities; understands competitive dynamics',['Full P&L ownership', 'Led market entry decisions']],
    ['Expert',     'Shapes industry direction; creates new market categories',     ['C-suite or board role', 'Series A+ fundraising', 'Market creation experience']],
  ),
  def('research',
    ['Aware',      'Can find and read relevant articles or papers',                ['Used Google Scholar', 'Literature review for a project']],
    ['Practicing', 'Conducts structured research; synthesises insights clearly',   ['User research interviews', 'Competitive analysis deliverable']],
    ['Proficient', 'Designs mixed-method research; translates into decisions',     ['Owns research function for a product', 'Usability studies with 20+ participants']],
    ['Advanced',   'Publishes or patents research; leads research programmes',     ['Published paper or patent', 'Led research team of 3+']],
    ['Expert',     'Defines research agenda; recognised domain authority',         ['Keynote at research conferences', 'Editorial board membership']],
  ),
  def('writing',
    ['Aware',      'Writes basic emails and messages clearly',                     ['Blog post or LinkedIn article']],
    ['Practicing', 'Produces structured documents: reports, specs, proposals',     ['Regular internal documentation', 'PRD or design brief written']],
    ['Proficient', 'Communicates complex ideas accessibly; adapts to audience',    ['Newsletter or published blog with 1k+ reads', 'Ghost-written exec content']],
    ['Advanced',   'Thought leadership writing; moves audiences to action',        ['Widely cited internal or external content', 'Published book chapter/column']],
    ['Expert',     'Sets written communication standards; published author',       ['Book publication', 'Regular columnist', '100k+ readers']],
  ),
  def('presentation',
    ['Aware',      'Can make a basic slideshow and present to small groups',       ['Gave a class or team presentation']],
    ['Practicing', 'Presents data-backed recommendations to 10–30 people',        ['All-hands or town hall presentation', 'Pitch to leadership']],
    ['Proficient', 'Delivers compelling narratives to mixed audiences; handles Q&A',['External client presentations', 'Conference speaking at 100+ audience']],
    ['Advanced',   'Keynote speaker; coaches others; influences through storytelling',['Conference keynote', 'TEDx talk', 'Executive coach for presentations']],
    ['Expert',     'Defines presentation culture; world-class speaker/communicator',['TED main stage', 'Media appearances', 'Published presentation frameworks']],
  ),
  def('stakeholder-mgmt',
    ['Aware',      'Knows who the stakeholders are; responds to their requests',   ['Worked cross-functionally on one project']],
    ['Practicing', 'Proactively communicates updates; manages expectations',       ['Regular stakeholder status reports', 'Navigated one conflict successfully']],
    ['Proficient', 'Builds trust across levels; aligns diverse stakeholders',      ['Managed 10+ stakeholders on a major project', 'Delivered with difficult constraints']],
    ['Advanced',   'Influences without authority at senior levels',                ['Drove exec alignment on contentious decision', 'Built coalition for major change']],
    ['Expert',     'Shapes stakeholder ecosystems; board-level influencer',        ['Board presentations', 'Shareholder/investor relations ownership']],
  ),
  def('people-mgmt',
    ['Aware',      'Has led informal groups or volunteered as team lead',          ['Led college club or volunteer team']],
    ['Practicing', 'Manages 1–3 direct reports; conducts 1:1s and reviews',      ['First-line manager experience', '360 feedback received']],
    ['Proficient', 'Leads teams of 5–10; hires, develops, and retains talent',    ['Promoted team members', 'Reduced attrition in team']],
    ['Advanced',   'Manages managers; shapes team culture and org design',        ['Led teams of 20+', 'Org restructure experience', 'Succession planning']],
    ['Expert',     'Leads thousands; defines people strategy at company level',   ['C-suite people leadership', 'Culture transformation at scale']],
  ),
  def('strategy',
    ['Aware',      'Can articulate what strategy means; reads strategic analyses', ['Completed strategy case study course']],
    ['Practicing', 'Contributes to team-level strategy and quarterly OKRs',       ['Authored team strategy section', 'Competitive analysis contribution']],
    ['Proficient', 'Owns product or function strategy; makes trade-off decisions', ['3-year product roadmap authored', 'Market entry decision made']],
    ['Advanced',   'Sets business unit strategy; drives transformation programmes',['P&L leader', 'M&A involvement', 'Org transformation ownership']],
    ['Expert',     'Shapes industry direction; creates blue ocean strategies',     ['CEO / Board-level strategy', 'Market category creation', 'Published frameworks']],
  ),
  def('mentoring',
    ['Aware',      'Shares knowledge informally with peers',                       ['Helped onboard a new colleague']],
    ['Practicing', 'Provides regular structured feedback to 1–2 people',          ['Formal mentoring relationship of 6+ months']],
    ['Proficient', 'Mentors 3–5 people; develops coaching skills',               ['Improved mentee promotion rate', 'Runs internal workshops']],
    ['Advanced',   'Builds mentoring culture; trains other mentors',             ['Mentoring programme leader', 'Coached 20+ professionals']],
    ['Expert',     'Recognised coach/mentor; published frameworks; transforms careers',['ICF certified', 'Published coaching methodology', 'Executive coaching practice']],
  ),
  def('design-thinking',
    ['Aware',      'Has heard of design thinking; knows empathise-define-ideate', ['Completed a DT intro workshop']],
    ['Practicing', 'Applies DT in sprints; creates personas and journey maps',    ['Led a design sprint', 'Created user journey map for a product']],
    ['Proficient', 'Facilitates DT workshops; embeds user research into decisions',['DT workshop facilitator for 20+ people', 'Shipped DT-informed features']],
    ['Advanced',   'Scales DT across organisations; defines innovation frameworks',['DT programme lead', 'Innovation lab head']],
    ['Expert',     'Recognised DT thought leader; shapes methodology evolution', ['IDEO-level practice', 'Published DT frameworks', 'Conference keynotes']],
  ),
  def('visual-design',
    ['Aware',      'Appreciates design; can make basic visuals in Canva/Slides',  ['Created a presentation deck visually']],
    ['Practicing', 'Uses Figma/Sketch; creates wireframes and basic UI',          ['Personal app or website designed', 'Internship design work']],
    ['Proficient', 'Designs pixel-perfect UIs; maintains design system components',['Product design shipped to 10k+ users', 'Design system contributor']],
    ['Advanced',   'Owns design system; defines visual identity and guidelines',  ['Design system creator', 'Brand redesign lead', 'Dribbble/Behance popular']],
    ['Expert',     'Shapes design culture; globally recognised visual craftsperson',['Design award winner', 'Agency creative director', 'Widely cited design work']],
  ),
  def('storytelling',
    ['Aware',      'Can sequence ideas logically',                                ['Structured one presentation using SCQA or pyramid']],
    ['Practicing', 'Frames problems as stories; uses data narratives',            ['Wrote a compelling case study', 'Pitched an idea successfully']],
    ['Proficient', 'Builds compelling narratives that move executive decisions',   ['Secured funding/approval through storytelling', 'Regular all-hands storyteller']],
    ['Advanced',   'Coaches teams on storytelling; builds narrative frameworks',  ['Internal storytelling coach', 'External brand narrative ownership']],
    ['Expert',     'Defines narrative culture; published storyteller',            ['Published book/podcast', 'Keynote at major event', '1M+ content reach']],
  ),
  def('project-mgmt',
    ['Aware',      'Has been a team member on a structured project',              ['Participated in Agile sprint', 'Used Jira or Trello']],
    ['Practicing', 'Independently runs small projects end-to-end',               ['Managed a 3-month project solo', 'PMP or Prince2 foundations']],
    ['Proficient', 'Manages complex multi-team programmes on time and budget',   ['Delivered ₹5Cr+ project', 'PMP certified', 'Led cross-functional team of 10+']],
    ['Advanced',   'Portfolio management; manages multiple programmes simultaneously',['Programme Director experience', 'Saved >20% cost through PM excellence']],
    ['Expert',     'Defines PM methodology for organisations; published frameworks',['PMO head', 'Industry standard PM method contributor']],
  ),
  def('process',
    ['Aware',      'Follows defined processes; understands SOP basics',           ['Worked in an ISO-certified org', 'Used a ticketing system']],
    ['Practicing', 'Identifies inefficiencies; documents improved processes',    ['Created an SOP that was adopted', 'Reduced manual steps in a workflow']],
    ['Proficient', 'Applies Lean/Six Sigma; drives measurable process improvements',['Six Sigma Green Belt', 'Reduced cycle time by >25%']],
    ['Advanced',   'Redesigns org-level processes; leads operational excellence',['Lean Six Sigma Black Belt', 'Enterprise-wide process transformation']],
    ['Expert',     'Shapes operational excellence culture; published frameworks', ['COO-level operational impact', 'Industry benchmark setter']],
  ),
  def('negotiation',
    ['Aware',      'Understands BATNA, positions vs interests basics',            ['Completed a negotiation module or book']],
    ['Practicing', 'Negotiates vendor contracts and internal resource trade-offs',['Secured a discount or better terms in procurement']],
    ['Proficient', 'Leads complex multi-party negotiations; builds lasting agreements',['Closed a major contract or partnership deal']],
    ['Advanced',   'High-stakes negotiation at exec level; crisis negotiation capable',['Negotiated M&A terms', 'Union or major regulatory negotiation']],
    ['Expert',     'Defines negotiation strategy for organisations; published approach',['Hostage negotiator equivalent', 'Published negotiation framework', 'Harvard PON equivalent']],
  ),
  def('drive',
    ['Aware',      'Completes assigned tasks; shows up consistently',             ['Positive performance reviews', 'Perfect attendance record']],
    ['Practicing', 'Proactively identifies and solves problems beyond own scope', ['Took ownership of an unassigned problem', 'Shipped extra feature on own initiative']],
    ['Proficient', 'Self-directed; consistently delivers beyond expectations',    ['Promoted ahead of cycle', 'Consistently exceeds OKRs']],
    ['Advanced',   'Creates urgency in teams; builds execution cultures',        ['Turnaround leader', 'Delivered impossible deadline reliably']],
    ['Expert',     'Inspirational force; legendary execution reputation',         ['Founder / serial entrepreneur', 'Industry-changing product shipped']],
  ),
  def('collaboration',
    ['Aware',      'Participates in team activities; shares information when asked',['Team sports or group projects experience']],
    ['Practicing', 'Actively contributes to cross-functional work; builds relationships',['Led cross-team meeting', 'Improved team rituals']],
    ['Proficient', 'Creates psychological safety; resolves conflicts constructively',['Team health score improved', 'Conflict resolved without escalation']],
    ['Advanced',   'Builds collaboration across org silos; creates partnership models',['Alliance or partnership programmes led', 'Org health award']],
    ['Expert',     'Collaboration culture architect; published collaborative methods',['Org design authority', 'Partnership ecosystem creator']],
  ),
  def('resilience',
    ['Aware',      'Manages personal stress with basic coping strategies',        ['Mindfulness course', 'Navigated a setback and continued']],
    ['Practicing', 'Maintains performance under pressure; recovers quickly from setbacks',['Delivered under tight deadline', 'Bounced back from a project failure']],
    ['Proficient', 'Sustains team performance in adversity; prevents burnout',   ['Led team through crisis successfully', 'Attrition stayed low in difficult quarter']],
    ['Advanced',   'Transforms organisational resilience; builds anti-fragile systems',['Led org through restructure', 'Built business continuity programmes']],
    ['Expert',     'Resilience thought leader; shapes wellbeing culture at scale',['Published resilience framework', 'Certified resilience programme designer']],
  ),
];

const MATURITY_MAP = new Map<string, CompetencyMaturity>(MATURITY_LAYERS.map(m => [m.competencyId, m]));

export function getMaturity(competencyId: string): CompetencyMaturity | undefined {
  return MATURITY_MAP.get(competencyId);
}

export function getLevelDescriptor(competencyId: string, level: number): MaturityLevel | null {
  const clamped = Math.max(1, Math.min(5, Math.round(level))) as 1 | 2 | 3 | 4 | 5;
  return MATURITY_MAP.get(competencyId)?.levels[clamped] ?? null;
}

export function getNextLevelDescriptor(competencyId: string, currentLevel: number): MaturityLevel | null {
  const next = Math.min(5, Math.floor(currentLevel) + 1) as 1 | 2 | 3 | 4 | 5;
  if (next <= currentLevel) return null;
  return MATURITY_MAP.get(competencyId)?.levels[next] ?? null;
}
