import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const EXPORT_DIR = '/tmp/rf_exports';

function ensureExportDir(): void {
  if (!fs.existsSync(EXPORT_DIR)) fs.mkdirSync(EXPORT_DIR, { recursive: true });
}

export interface WhiteLabelConfig {
  org_name?: string;
  primary_color?: string;
  secondary_color?: string;
  accent_color?: string;
  report_header?: string;
  report_footer?: string;
  logo_url?: string;
}

// ── PDF ────────────────────────────────────────────────────────────────────

export function renderReportToPDF(report: Record<string, unknown>, wl?: WhiteLabelConfig): Promise<string> {
  ensureExportDir();
  const uuid = (report.report_uuid as string) ?? String(report.id ?? Date.now());
  const filePath = path.join(EXPORT_DIR, `rf_${uuid}.pdf`);

  const primary    = wl?.primary_color ?? '#6366f1';
  const orgName    = wl?.org_name ?? 'MetryxOne';
  const footerText = wl?.report_footer ?? 'This report is a developmental tool generated by MetryxOne Behavioural Intelligence Platform. Not for use in hiring or promotion decisions.';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margins: { top: 60, bottom: 80, left: 60, right: 60 },
      size: 'A4',
      info: {
        Title: `${String(report.report_type ?? 'Report').toUpperCase()} Report`,
        Author: orgName,
        Creator: 'MetryxOne Report Factory',
      },
    });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const pageW = doc.page.width - 120; // usable width

    // ── Header band ──────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 90).fill(primary);
    doc.fontSize(20).fillColor('#ffffff')
       .text(`${String(report.report_type ?? 'custom').toUpperCase()} REPORT`, 60, 28, { width: pageW });
    doc.fontSize(10).fillColor('rgba(255,255,255,0.8)')
       .text(`Generated ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })} · ${orgName}`, 60, 56, { width: pageW });
    doc.y = 110;

    // ── Utility helpers ────────────────────────────────────────────────
    const hr = () => {
      doc.moveDown(0.4);
      doc.moveTo(60, doc.y).lineTo(60 + pageW, doc.y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
      doc.moveDown(0.6);
    };

    const sectionTitle = (title: string) => {
      if (doc.y > 700) doc.addPage();
      doc.moveDown(0.5);
      doc.fontSize(13).fillColor(primary).text(title, 60, doc.y, { width: pageW });
      doc.moveDown(0.3);
    };

    const bodyText = (text: string) => {
      doc.fontSize(10).fillColor('#374151').text(text, 60, doc.y, { width: pageW, lineGap: 3 });
      doc.moveDown(0.7);
    };

    const bullet = (text: string, color: string) => {
      if (doc.y > 720) doc.addPage();
      const bx = 72; const tx = 88;
      doc.circle(bx, doc.y + 4, 3).fill(color);
      doc.fontSize(9).fillColor('#374151').text(text, tx, doc.y, { width: pageW - 28, lineGap: 2 });
      doc.moveDown(0.4);
    };

    // ── Report sections ────────────────────────────────────────────────
    const sections: Record<string, unknown>[] = (report.generated_content as any)?.sections ?? [];

    for (const sec of sections) {
      if (!sec || typeof sec !== 'object') continue;
      const s = sec as Record<string, unknown>;
      const type = String(s.type ?? '');

      if (type === 'header' || type === 'footer') continue;

      if (s.title) sectionTitle(String(s.title));

      switch (type) {
        case 'narrative': {
          if (s.text) bodyText(String(s.text));
          hr();
          break;
        }
        case 'insight': {
          const insights = (s.insights as any[]) ?? [];
          const SEVERITY_COLORS: Record<string, string> = {
            positive: '#10b981', info: '#6366f1', warning: '#f59e0b', critical: '#ef4444',
          };
          for (const ins of insights) {
            bullet(String(ins.text ?? ''), SEVERITY_COLORS[String(ins.severity ?? 'info')] ?? '#6366f1');
          }
          if (insights.length === 0) {
            doc.fontSize(9).fillColor('#9ca3af').text('No insights fired for this report.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'chart': {
          const resolved = s.resolved_data as any;
          if (resolved?.labels?.length) {
            // Render as a simple data table inside the PDF
            const labels: string[] = resolved.labels ?? [];
            const values: number[] = resolved.datasets?.[0]?.data ?? [];
            const maxVal = Math.max(...values.filter(Number.isFinite), 1);
            const barMaxW = pageW - 160;

            doc.fontSize(9).fillColor('#6b7280')
               .text(`Chart: ${String(s.title ?? '')}  ·  Data source: ${String((s.visualization as any)?.data_source ?? '')}`, 60, doc.y, { width: pageW });
            doc.moveDown(0.4);

            for (let i = 0; i < Math.min(labels.length, 15); i++) {
              if (doc.y > 710) doc.addPage();
              const val = Number.isFinite(values[i]) ? values[i] : 0;
              const barW = (val / maxVal) * barMaxW;
              const rowY = doc.y;
              doc.fontSize(8).fillColor('#374151').text(String(labels[i]).substring(0, 28), 60, rowY + 2, { width: 130 });
              doc.rect(200, rowY, barW, 10).fill(`${primary}55`);
              doc.rect(200, rowY, barW, 10).stroke(primary);
              doc.fontSize(8).fillColor('#374151').text(String(val), 204 + barW, rowY + 2, { width: 50 });
              doc.y = rowY + 16;
            }
          } else {
            doc.fontSize(9).fillColor('#9ca3af')
               .text(`[Chart: ${String((s.visualization as any)?.title ?? 'data pending')} — view in web report for rendered chart]`, 60, doc.y, { width: pageW, oblique: true });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'benchmark': {
          const results = (s.benchmark_results as any[]) ?? [];
          if (results.length) {
            for (const r of results) {
              if (doc.y > 720) doc.addPage();
              if (r.suppressed) {
                doc.fontSize(9).fillColor('#9ca3af')
                   .text(`${r.metric}: insufficient cohort data (k < ${r.min_cohort_size ?? 30})`, 60, doc.y, { width: pageW });
              } else {
                const pctLabel = r.percentile != null ? ` · ${r.percentile}th percentile` : '';
                const medianLabel = r.peer_median != null ? ` · Peer median: ${r.peer_median}` : '';
                doc.fontSize(9).fillColor('#374151')
                   .text(`${r.metric}: Your score ${r.user_score ?? 'N/A'}${medianLabel}${pctLabel} (cohort n=${r.cohort_size ?? '—'})`, 60, doc.y, { width: pageW, lineGap: 2 });
              }
              doc.moveDown(0.4);
            }
          } else {
            doc.fontSize(9).fillColor('#9ca3af').text('No benchmark data available.', 60, doc.y, { width: pageW });
            doc.moveDown(0.5);
          }
          hr();
          break;
        }
        case 'score': {
          const scores = (s.scores as any[]) ?? [];
          for (const sc of scores) {
            if (doc.y > 720) doc.addPage();
            doc.fontSize(10).fillColor('#374151')
               .text(`${sc.score_type}: ${sc.score} (${sc.band ?? '—'})`, 60, doc.y, { width: pageW });
            doc.moveDown(0.3);
          }
          hr();
          break;
        }
      }
    }

    // ── Footer ─────────────────────────────────────────────────────────
    const footerY = doc.page.height - 60;
    doc.moveTo(60, footerY - 8).lineTo(60 + pageW, footerY - 8).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    doc.fontSize(7).fillColor('#9ca3af')
       .text(footerText, 60, footerY, { width: pageW, align: 'center', lineGap: 2 });

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

// ── CSV ────────────────────────────────────────────────────────────────────

export function renderReportToCSV(report: Record<string, unknown>): string {
  const rows: string[] = [
    'report_uuid,report_type,section_key,content_type,content,severity,metric,user_score,peer_median,percentile,cohort_size',
  ];
  const uuid = String(report.report_uuid ?? report.id ?? '');
  const rtype = String(report.report_type ?? '');
  const esc = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;

  const sections: Record<string, unknown>[] = (report.generated_content as any)?.sections ?? [];
  for (const sec of sections) {
    if (!sec || typeof sec !== 'object') continue;
    const s = sec as Record<string, unknown>;
    const key = String(s.key ?? s.section_key ?? s.type ?? '');
    const type = String(s.type ?? '');

    if (type === 'narrative' && s.text) {
      rows.push([esc(uuid), esc(rtype), esc(key), esc('narrative'), esc(s.text), '', '', '', '', '', ''].join(','));
    }
    if (type === 'insight') {
      for (const ins of (s.insights as any[]) ?? []) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('insight'), esc(ins.text ?? ''), esc(ins.severity ?? 'info'), '', '', '', '', ''].join(','));
      }
    }
    if (type === 'benchmark') {
      for (const r of (s.benchmark_results as any[]) ?? []) {
        if (!r.suppressed) {
          rows.push([esc(uuid), esc(rtype), esc(key), esc('benchmark'), '', '', esc(r.metric ?? ''), esc(r.user_score ?? ''), esc(r.peer_median ?? ''), esc(r.percentile ?? ''), esc(r.cohort_size ?? '')].join(','));
        }
      }
    }
    if (type === 'chart' && (s.resolved_data as any)?.labels) {
      const rd = s.resolved_data as any;
      const labels: string[] = rd.labels ?? [];
      const values: number[] = rd.datasets?.[0]?.data ?? [];
      for (let i = 0; i < labels.length; i++) {
        rows.push([esc(uuid), esc(rtype), esc(key), esc('chart_datapoint'), esc(labels[i]), '', esc(labels[i]), esc(values[i] ?? ''), '', '', ''].join(','));
      }
    }
  }
  return '\uFEFF' + rows.join('\n'); // UTF-8 BOM for Excel
}

// ── JSON ───────────────────────────────────────────────────────────────────

export function renderReportToJSON(report: Record<string, unknown>): string {
  return JSON.stringify({
    schema_version: '1.0',
    exported_at: new Date().toISOString(),
    report: {
      uuid: report.report_uuid,
      type: report.report_type,
      language: report.language,
      status: report.status,
      created_at: report.created_at,
      completed_at: report.completed_at,
      narrative_texts: report.narrative_texts ?? {},
      insights: report.insights ?? [],
      generated_content: report.generated_content ?? {},
      metadata: report.metadata ?? {},
    },
  }, null, 2);
}

// ── Utilities ──────────────────────────────────────────────────────────────

export function getExportFilePath(jobUuid: string, format: string): string {
  const ext = format === 'pdf' ? 'pdf' : format === 'csv' ? 'csv' : format === 'xlsx' ? 'csv' : 'json';
  return path.join(EXPORT_DIR, `rf_${jobUuid}.${ext}`);
}

export function getContentType(format: string): string {
  switch (format) {
    case 'pdf':  return 'application/pdf';
    case 'csv':  return 'text/csv; charset=utf-8';
    case 'json': return 'application/json';
    case 'xlsx': return 'text/csv; charset=utf-8'; // served as csv until xlsx lib added
    default:     return 'application/octet-stream';
  }
}
