-- /app/scripts/seed-concern-areas.sql
-- Auto-generated from /app/frontend/server/src/scripts/seed-concerns.ts
-- 160 concern areas across all categories
-- Idempotent: safe to re-run

CREATE TABLE IF NOT EXISTS concern_areas (
  id              SERIAL PRIMARY KEY,
  category        TEXT NOT NULL,
  concern_area    TEXT NOT NULL,
  parent_worry    TEXT NOT NULL,
  impact_on_child TEXT NOT NULL,
  assessment_type TEXT,
  search_keywords TEXT,
  services        JSONB NOT NULL DEFAULT '[]'::jsonb,
  roles           JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order      INTEGER NOT NULL DEFAULT 0,
  created_at      TIMESTAMP NOT NULL DEFAULT now(),
  updated_at      TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE (category, concern_area)
);
CREATE INDEX IF NOT EXISTS idx_concern_areas_category ON concern_areas(category);
CREATE INDEX IF NOT EXISTS idx_concern_areas_active ON concern_areas(is_active);

INSERT INTO concern_areas (category, concern_area, parent_worry, impact_on_child, assessment_type, search_keywords, sort_order) VALUES
  ('Focus', 'Short attention span', 'My child cannot sit and study', 'Poor learning', 'lbi', 'focus short attention span my child cannot sit and study poor learning', 1),
  ('Focus', 'Easily distracted', 'Gets distracted very quickly', 'Low productivity', 'lbi', 'focus easily distracted gets distracted very quickly low productivity', 2),
  ('Focus', 'Screen distraction', 'Always on phone/tablet', 'Reduced focus', 'lbi', 'focus screen distraction always on phone/tablet reduced focus', 3),
  ('Focus', 'Inconsistent concentration', 'Sometimes focused, mostly not', 'Unstable performance', 'lbi', 'focus inconsistent concentration sometimes focused, mostly not unstable performance', 4),
  ('Focus', 'Difficulty completing tasks', 'Leaves work halfway', 'Poor outcomes', 'lbi', 'focus difficulty completing tasks leaves work halfway poor outcomes', 5),
  ('Focus', 'Daydreaming', 'Lost in thoughts', 'Low engagement', 'lbi', 'focus daydreaming lost in thoughts low engagement', 6),
  ('Focus', 'Lack of mental stamina', 'Gets tired quickly while studying', 'Weak retention', 'lbi', 'focus lack of mental stamina gets tired quickly while studying weak retention', 7),
  ('Focus', 'Avoidance of difficult tasks', 'Avoids tough subjects', 'Skill gaps', 'lbi', 'focus avoidance of difficult tasks avoids tough subjects skill gaps', 8),
  ('Focus', 'No deep work ability', 'Cannot study for long hours', 'Low mastery', 'lbi', 'focus no deep work ability cannot study for long hours low mastery', 9),
  ('Focus', 'Over multitasking', 'Keeps switching tasks', 'Inefficiency', 'lbi', 'focus over multitasking keeps switching tasks inefficiency', 10),
  ('Academics', 'Low marks', 'Marks are very low', 'Academic risk', 'lbi', 'academics low marks marks are very low academic risk', 11),
  ('Academics', 'Sudden drop in performance', 'Marks have dropped recently', 'Concern trigger', 'lbi', 'academics sudden drop in performance marks have dropped recently concern trigger', 12),
  ('Academics', 'Inconsistent results', 'Sometimes good, sometimes bad', 'Unpredictability', 'lbi', 'academics inconsistent results sometimes good, sometimes bad unpredictability', 13),
  ('Academics', 'Exam fear', 'Panics during exams', 'Underperformance', 'lbi', 'academics exam fear panics during exams underperformance', 14),
  ('Academics', 'Poor writing skills', 'Cannot present answers well', 'Low scoring', 'lbi', 'academics poor writing skills cannot present answers well low scoring', 15),
  ('Academics', 'Slow writing speed', 'Cannot finish paper on time', 'Exam loss', 'lbi', 'academics slow writing speed cannot finish paper on time exam loss', 16),
  ('Academics', 'Weak subject foundation', 'Basics are not clear', 'Long-term gap', 'lbi', 'academics weak subject foundation basics are not clear long-term gap', 17),
  ('Academics', 'Difficulty in math/science', 'Struggles with concepts', 'Learning difficulty', 'lbi', 'academics difficulty in math/science struggles with concepts learning difficulty', 18),
  ('Academics', 'Rote learning dependency', 'Memorizes but doesn''t understand', 'Shallow learning', 'lbi', 'academics rote learning dependency memorizes but doesn''t understand shallow learning', 19),
  ('Academics', 'Homework resistance', 'Doesn''t want to do homework', 'Poor discipline', 'lbi', 'academics homework resistance doesn''t want to do homework poor discipline', 20),
  ('Behavior', 'Procrastination', 'Delays everything', 'Time loss', 'lbi', 'behavior procrastination delays everything time loss', 21),
  ('Behavior', 'Lack of discipline', 'No routine at all', 'Inconsistency', 'lbi', 'behavior lack of discipline no routine at all inconsistency', 22),
  ('Behavior', 'Irregular study habits', 'Studies randomly', 'Weak structure', 'lbi', 'behavior irregular study habits studies randomly weak structure', 23),
  ('Behavior', 'No goal setting', 'No aim in life', 'Directionless', 'lbi', 'behavior no goal setting no aim in life directionless', 24),
  ('Behavior', 'Easily gives up', 'Quits quickly', 'Low resilience', 'lbi', 'behavior easily gives up quits quickly low resilience', 25),
  ('Behavior', 'Dependency on parents', 'Needs constant push', 'No independence', 'lbi', 'behavior dependency on parents needs constant push no independence', 26),
  ('Behavior', 'Disorganized lifestyle', 'Very messy routine', 'Inefficiency', 'lbi', 'behavior disorganized lifestyle very messy routine inefficiency', 27),
  ('Behavior', 'Poor time management', 'Cannot manage time', 'Missed targets', 'lbi', 'behavior poor time management cannot manage time missed targets', 28),
  ('Behavior', 'Avoidance behavior', 'Escapes responsibilities', 'Weak accountability', 'lbi', 'behavior avoidance behavior escapes responsibilities weak accountability', 29),
  ('Behavior', 'Lack of responsibility', 'Doesn''t take things seriously', 'Immaturity', 'lbi', 'behavior lack of responsibility doesn''t take things seriously immaturity', 30),
  ('Emotional', 'Low confidence', 'Doesn''t believe in self', 'Poor performance', 'lbi', 'emotional low confidence doesn''t believe in self poor performance', 31),
  ('Emotional', 'Fear of failure', 'Afraid to try', 'Avoidance', 'lbi', 'emotional fear of failure afraid to try avoidance', 32),
  ('Emotional', 'Anxiety', 'Always worried', 'Mental stress', 'lbi', 'emotional anxiety always worried mental stress', 33),
  ('Emotional', 'Mood swings', 'Emotions change quickly', 'Instability', 'lbi', 'emotional mood swings emotions change quickly instability', 34),
  ('Emotional', 'Overthinking', 'Thinks too much', 'Mental fatigue', 'lbi', 'emotional overthinking thinks too much mental fatigue', 35),
  ('Emotional', 'Stress', 'Too much pressure', 'Burnout', 'lbi', 'emotional stress too much pressure burnout', 36),
  ('Emotional', 'Negative thinking', 'Always pessimistic', 'Low motivation', 'lbi', 'emotional negative thinking always pessimistic low motivation', 37),
  ('Emotional', 'Fear of judgment', 'Worried about others', 'Inhibition', 'lbi', 'emotional fear of judgment worried about others inhibition', 38),
  ('Emotional', 'Comparison stress', 'Compares with others', 'Low self-worth', 'lbi', 'emotional comparison stress compares with others low self-worth', 39),
  ('Emotional', 'Emotional sensitivity', 'Gets hurt easily', 'Fragility', 'lbi', 'emotional emotional sensitivity gets hurt easily fragility', 40),
  ('Mental Health', 'Test anxiety', 'Freezes in exams', 'Score drop', 'lbi', 'mental health test anxiety freezes in exams score drop', 41),
  ('Mental Health', 'Social anxiety', 'Avoids interaction', 'Isolation', 'lbi', 'mental health social anxiety avoids interaction isolation', 42),
  ('Mental Health', 'Lack of motivation', 'No interest in anything', 'Stagnation', 'lbi', 'mental health lack of motivation no interest in anything stagnation', 43),
  ('Mental Health', 'Burnout', 'Feels tired always', 'Withdrawal', 'lbi', 'mental health burnout feels tired always withdrawal', 44),
  ('Mental Health', 'Low self-esteem', 'Feels inferior', 'Confidence loss', 'lbi', 'mental health low self-esteem feels inferior confidence loss', 45),
  ('Mental Health', 'Emotional regulation issues', 'Cannot control emotions', 'Behavioral issues', 'lbi', 'mental health emotional regulation issues cannot control emotions behavioral issues', 46),
  ('Mental Health', 'Withdrawal behavior', 'Keeps to self', 'Isolation', 'lbi', 'mental health withdrawal behavior keeps to self isolation', 47),
  ('Mental Health', 'Fear of speaking', 'Afraid to talk', 'Communication gap', 'lbi', 'mental health fear of speaking afraid to talk communication gap', 48),
  ('Mental Health', 'Pressure from expectations', 'Feels burdened', 'Stress', 'lbi', 'mental health pressure from expectations feels burdened stress', 49),
  ('Mental Health', 'Lack of mental resilience', 'Cannot handle failure', 'Fragility', 'lbi', 'mental health lack of mental resilience cannot handle failure fragility', 50),
  ('Digital', 'Screen addiction', 'Always on screen', 'Focus loss', 'lbi', 'digital screen addiction always on screen focus loss', 51),
  ('Digital', 'Gaming addiction', 'Plays games excessively', 'Time waste', 'lbi', 'digital gaming addiction plays games excessively time waste', 52),
  ('Digital', 'Social media overuse', 'Always scrolling', 'Distraction', 'lbi', 'digital social media overuse always scrolling distraction', 53),
  ('Digital', 'YouTube addiction', 'Watches endlessly', 'Reduced productivity', 'lbi', 'digital youtube addiction watches endlessly reduced productivity', 54),
  ('Digital', 'Late-night phone use', 'Sleeps very late', 'Poor health', 'lbi', 'digital late-night phone use sleeps very late poor health', 55),
  ('Digital', 'Dopamine dependency', 'Needs constant stimulation', 'Low patience', 'lbi', 'digital dopamine dependency needs constant stimulation low patience', 56),
  ('Digital', 'Reduced offline engagement', 'Doesn''t play outside', 'Social impact', 'lbi', 'digital reduced offline engagement doesn''t play outside social impact', 57),
  ('Digital', 'Academic neglect due to phone', 'Studies less due to phone', 'Performance drop', 'lbi', 'digital academic neglect due to phone studies less due to phone performance drop', 58),
  ('Digital', 'Multitasking with devices', 'Studies + phone together', 'Inefficiency', 'lbi', 'digital multitasking with devices studies + phone together inefficiency', 59),
  ('Digital', 'Lack of digital discipline', 'No control over usage', 'Habit damage', 'lbi', 'digital lack of digital discipline no control over usage habit damage', 60),
  ('Social', 'Poor communication', 'Cannot express clearly', 'Weak interaction', 'lbi', 'social poor communication cannot express clearly weak interaction', 61),
  ('Social', 'Shyness', 'Too shy', 'Low participation', 'lbi', 'social shyness too shy low participation', 62),
  ('Social', 'Lack of friends', 'Doesn''t socialize', 'Isolation', 'lbi', 'social lack of friends doesn''t socialize isolation', 63),
  ('Social', 'Peer pressure', 'Easily influenced', 'Risk behavior', 'lbi', 'social peer pressure easily influenced risk behavior', 64),
  ('Social', 'Conflict with peers', 'Frequent fights', 'Social issues', 'lbi', 'social conflict with peers frequent fights social issues', 65),
  ('Social', 'Poor listening skills', 'Doesn''t listen', 'Miscommunication', 'lbi', 'social poor listening skills doesn''t listen miscommunication', 66),
  ('Social', 'Low participation in class', 'Doesn''t engage', 'Missed learning', 'lbi', 'social low participation in class doesn''t engage missed learning', 67),
  ('Social', 'Fear of public speaking', 'Avoids stage', 'Confidence gap', 'lbi', 'social fear of public speaking avoids stage confidence gap', 68),
  ('Social', 'Lack of teamwork', 'Cannot work in groups', 'Collaboration issue', 'lbi', 'social lack of teamwork cannot work in groups collaboration issue', 69),
  ('Social', 'Social comparison', 'Feels inferior to peers', 'Low confidence', 'lbi', 'social social comparison feels inferior to peers low confidence', 70),
  ('Habits', 'Poor sleep routine', 'Sleeps irregularly', 'Low energy', 'lbi', 'habits poor sleep routine sleeps irregularly low energy', 71),
  ('Habits', 'Lack of physical activity', 'No exercise', 'Health impact', 'lbi', 'habits lack of physical activity no exercise health impact', 72),
  ('Habits', 'Poor diet habits', 'Unhealthy eating', 'Low energy', 'lbi', 'habits poor diet habits unhealthy eating low energy', 73),
  ('Habits', 'No structured routine', 'Day is unplanned', 'Chaos', 'lbi', 'habits no structured routine day is unplanned chaos', 74),
  ('Habits', 'Lack of consistency', 'Cannot follow routine', 'Instability', 'lbi', 'habits lack of consistency cannot follow routine instability', 75),
  ('Habits', 'Low discipline', 'No control', 'Weak habits', 'lbi', 'habits low discipline no control weak habits', 76),
  ('Habits', 'Poor hygiene', 'Neglects self-care', 'Health risk', 'lbi', 'habits poor hygiene neglects self-care health risk', 77),
  ('Habits', 'Lack of productivity habits', 'Wastes time', 'Low output', 'lbi', 'habits lack of productivity habits wastes time low output', 78),
  ('Habits', 'No habit formation', 'Cannot build habits', 'No growth', 'lbi', 'habits no habit formation cannot build habits no growth', 79),
  ('Habits', 'Irregular energy cycles', 'Active at wrong times', 'Inefficiency', 'lbi', 'habits irregular energy cycles active at wrong times inefficiency', 80),
  ('Career', 'No career clarity', 'Doesn''t know what to do', 'Confusion', 'career', 'career no career clarity doesn''t know what to do confusion', 81),
  ('Career', 'Too many interests', 'Confused between options', 'Indecision', 'career', 'career too many interests confused between options indecision', 82),
  ('Career', 'External influence', 'Others deciding career', 'Misalignment', 'career', 'career external influence others deciding career misalignment', 83),
  ('Career', 'Lack of exposure', 'Doesn''t know options', 'Limited vision', 'career', 'career lack of exposure doesn''t know options limited vision', 84),
  ('Career', 'Unrealistic goals', 'Dreams not practical', 'Risk', 'career', 'career unrealistic goals dreams not practical risk', 85),
  ('Career', 'No long-term planning', 'No future plan', 'Uncertainty', 'career', 'career no long-term planning no future plan uncertainty', 86),
  ('Career', 'Fear of wrong choice', 'What if we choose wrong', 'Anxiety', 'career', 'career fear of wrong choice what if we choose wrong anxiety', 87),
  ('Career', 'Lack of skill awareness', 'Doesn''t know strengths', 'Misfit', 'career', 'career lack of skill awareness doesn''t know strengths misfit', 88),
  ('Career', 'No guidance', 'No proper advice', 'Confusion', 'career', 'career no guidance no proper advice confusion', 89),
  ('Career', 'Misalignment with abilities', 'Choosing wrong stream', 'Failure risk', 'career', 'career misalignment with abilities choosing wrong stream failure risk', 90),
  ('Family', 'Lack of communication', 'Doesn''t talk openly', 'Disconnect', 'lbi', 'family lack of communication doesn''t talk openly disconnect', 91),
  ('Family', 'Parent-child conflict', 'Frequent arguments', 'Stress', 'lbi', 'family parent-child conflict frequent arguments stress', 92),
  ('Family', 'Over-expectation', 'Pressure from parents', 'Anxiety', 'lbi', 'family over-expectation pressure from parents anxiety', 93),
  ('Family', 'Lack of guidance', 'We don''t know how to help', 'Confusion', 'lbi', 'family lack of guidance we don''t know how to help confusion', 94),
  ('Family', 'Comparison with siblings', 'Compared at home', 'Low self-worth', 'lbi', 'family comparison with siblings compared at home low self-worth', 95),
  ('Family', 'Lack of monitoring', 'We don''t track properly', 'Missed issues', 'lbi', 'family lack of monitoring we don''t track properly missed issues', 96),
  ('Family', 'Emotional disconnect', 'Not emotionally close', 'Isolation', 'lbi', 'family emotional disconnect not emotionally close isolation', 97),
  ('Family', 'Over-dependence on tuition', 'We rely only on coaching', 'Weak foundation', 'lbi', 'family over-dependence on tuition we rely only on coaching weak foundation', 98),
  ('Family', 'Confusion about child''s ability', 'Don''t understand child', 'Misjudgment', 'lbi', 'family confusion about child''s ability don''t understand child misjudgment', 99),
  ('Family', 'Fear about future', 'What will happen later', 'Anxiety', 'lbi', 'family fear about future what will happen later anxiety', 100),
  ('Learning', 'Learning disabilities (Dyslexia, ADHD, Dysgraphia)', 'Why is my child not learning like others?', 'Misdiagnosis, academic struggle', 'lbi', 'learning learning disabilities (dyslexia, adhd, dysgraphia) why is my child not learning like others? misdiagnosis, academic struggle', 101),
  ('Learning', 'Poor comprehension skills', 'Reads but doesn''t understand', 'Weak conceptual learning', 'lbi', 'learning poor comprehension skills reads but doesn''t understand weak conceptual learning', 102),
  ('Learning', 'Memory retention issues', 'Forgets whatever studied', 'Poor exam performance', 'lbi', 'learning memory retention issues forgets whatever studied poor exam performance', 103),
  ('Cognitive', 'Low problem-solving ability', 'Cannot think independently', 'Weak analytical skills', 'lbi', 'cognitive low problem-solving ability cannot think independently weak analytical skills', 104),
  ('Cognitive', 'Lack of critical thinking', 'Cannot apply knowledge', 'Surface-level learning', 'lbi', 'cognitive lack of critical thinking cannot apply knowledge surface-level learning', 105),
  ('Cognitive', 'Slow processing speed', 'Takes too long to understand', 'Academic delay', 'lbi', 'cognitive slow processing speed takes too long to understand academic delay', 106),
  ('Emotional', 'Anger issues', 'Gets angry very quickly', 'Relationship & behavior problems', 'lbi', 'emotional anger issues gets angry very quickly relationship & behavior problems', 107),
  ('Emotional', 'Lack of emotional intelligence', 'Cannot understand emotions', 'Social disconnect', 'lbi', 'emotional lack of emotional intelligence cannot understand emotions social disconnect', 108),
  ('Mental Health', 'Early signs of depression', 'Seems dull / uninterested', 'Serious mental health risk', 'lbi', 'mental health early signs of depression seems dull / uninterested serious mental health risk', 109),
  ('Mental Health', 'Panic attacks', 'Sudden fear episodes', 'Academic disruption', 'lbi', 'mental health panic attacks sudden fear episodes academic disruption', 110),
  ('Digital', 'Exposure to inappropriate content', 'What are they watching online?', 'Behavioral distortion', 'lbi', 'digital exposure to inappropriate content what are they watching online? behavioral distortion', 111),
  ('Digital', 'Cyberbullying', 'Someone is troubling online', 'Emotional trauma', 'lbi', 'digital cyberbullying someone is troubling online emotional trauma', 112),
  ('Social', 'Bullying (offline)', 'Child is being bullied in school', 'Fear, withdrawal', 'lbi', 'social bullying (offline) child is being bullied in school fear, withdrawal', 113),
  ('Social', 'Lack of assertiveness', 'Cannot say no', 'Peer pressure vulnerability', 'lbi', 'social lack of assertiveness cannot say no peer pressure vulnerability', 114),
  ('Social', 'Influence of wrong peer group', 'Bad friends influencing', 'Risky behaviors', 'lbi', 'social influence of wrong peer group bad friends influencing risky behaviors', 115),
  ('Habits', 'Addiction tendencies (beyond screens)', 'Getting addicted easily', 'Long-term dependency risk', 'lbi', 'habits addiction tendencies (beyond screens) getting addicted easily long-term dependency risk', 116),
  ('Habits', 'Lack of self-control', 'Cannot control impulses', 'Poor decisions', 'lbi', 'habits lack of self-control cannot control impulses poor decisions', 117),
  ('Career', 'Lack of real-world skills', 'Not ready for real life', 'Employability gap', 'career', 'career lack of real-world skills not ready for real life employability gap', 118),
  ('Career', 'Skill vs marks mismatch', 'Good marks but no skills', 'Future struggle', 'career', 'career skill vs marks mismatch good marks but no skills future struggle', 119),
  ('Career', 'Fear of competition', 'Cannot handle competition', 'Avoidance mindset', 'career', 'career fear of competition cannot handle competition avoidance mindset', 120),
  ('Parenting', 'Inconsistent parenting approach', 'We are not aligned as parents', 'Confusion in child', 'lbi', 'parenting inconsistent parenting approach we are not aligned as parents confusion in child', 121),
  ('Parenting', 'Lack of parenting skills', 'We don''t know how to guide properly', 'Wrong interventions', 'lbi', 'parenting lack of parenting skills we don''t know how to guide properly wrong interventions', 122),
  ('Parenting', 'Overprotection', 'We do everything for child', 'Dependency', 'lbi', 'parenting overprotection we do everything for child dependency', 123),
  ('Parenting', 'Lack of boundaries', 'Child doesn''t listen at all', 'Discipline issues', 'lbi', 'parenting lack of boundaries child doesn''t listen at all discipline issues', 124),
  ('Environment', 'School mismatch', 'School not suitable for child', 'Learning dissatisfaction', 'lbi', 'environment school mismatch school not suitable for child learning dissatisfaction', 125),
  ('Environment', 'Academic pressure from school', 'Too much syllabus pressure', 'Stress, burnout', 'lbi', 'environment academic pressure from school too much syllabus pressure stress, burnout', 126),
  ('Health', 'Frequent fatigue', 'Always tired', 'Low productivity', 'lbi', 'health frequent fatigue always tired low productivity', 127),
  ('Health', 'Hormonal/teen changes impact', 'Behavior changed suddenly', 'Emotional instability', 'lbi', 'health hormonal/teen changes impact behavior changed suddenly emotional instability', 128),
  ('Future Skills', 'Lack of creativity', 'No innovative thinking', 'Limited growth', 'lbi', 'future skills lack of creativity no innovative thinking limited growth', 129),
  ('Future Skills', 'Lack of curiosity', 'Doesn''t ask questions', 'Passive learning', 'lbi', 'future skills lack of curiosity doesn''t ask questions passive learning', 130),
  ('Board Exams', 'Failure in board exams', 'My child has failed in boards', 'Emotional breakdown, stigma', 'exam_ready', 'board exams failure in board exams my child has failed in boards emotional breakdown, stigma', 131),
  ('Board Exams', 'Compartment exam stress', 'How to clear compartment?', 'Anxiety, urgency pressure', 'exam_ready', 'board exams compartment exam stress how to clear compartment? anxiety, urgency pressure', 132),
  ('Board Exams', 'Low board percentage', 'Marks are too low for good college', 'Limited opportunities', 'exam_ready', 'board exams low board percentage marks are too low for good college limited opportunities', 133),
  ('Board Exams', 'Unexpected poor results', 'We expected more marks', 'Confidence loss', 'exam_ready', 'board exams unexpected poor results we expected more marks confidence loss', 134),
  ('Board Exams', 'Exam performance vs preparation mismatch', 'Studied well but marks are low', 'Frustration, confusion', 'exam_ready', 'board exams exam performance vs preparation mismatch studied well but marks are low frustration, confusion', 135),
  ('Board Exams', 'Time mismanagement in board exam', 'Couldn''t complete paper', 'Score loss', 'exam_ready', 'board exams time mismanagement in board exam couldn''t complete paper score loss', 136),
  ('Board Exams', 'Poor answer presentation', 'Knows answers but cannot write properly', 'Low evaluation score', 'exam_ready', 'board exams poor answer presentation knows answers but cannot write properly low evaluation score', 137),
  ('Board Exams', 'Weak exam strategy', 'Doesn''t know how to attempt paper', 'Inefficient scoring', 'exam_ready', 'board exams weak exam strategy doesn''t know how to attempt paper inefficient scoring', 138),
  ('Board Exams', 'Panic during board exam', 'Blank out in exam hall', 'Severe underperformance', 'exam_ready', 'board exams panic during board exam blank out in exam hall severe underperformance', 139),
  ('Board Exams', 'Lack of revision strategy', 'Didn''t revise properly', 'Poor retention', 'exam_ready', 'board exams lack of revision strategy didn''t revise properly poor retention', 140),
  ('Board Exams', 'Syllabus completion gaps', 'Portions left before exam', 'Low confidence', 'exam_ready', 'board exams syllabus completion gaps portions left before exam low confidence', 141),
  ('Board Exams', 'Overconfidence before exam', 'Thought it was easy', 'Poor results', 'exam_ready', 'board exams overconfidence before exam thought it was easy poor results', 142),
  ('Board Exams', 'Burnout before boards', 'Exhausted before exams started', 'Performance drop', 'exam_ready', 'board exams burnout before boards exhausted before exams started performance drop', 143),
  ('Board Exams', 'External pressure (family/society)', 'Too much pressure for marks', 'Anxiety, stress', 'exam_ready', 'board exams external pressure (family/society) too much pressure for marks anxiety, stress', 144),
  ('Board Exams', 'Comparison after results', 'Others scored more', 'Low self-esteem', 'exam_ready', 'board exams comparison after results others scored more low self-esteem', 145),
  ('Betterment', 'Lack of clarity about betterment exams', 'What is improvement exam process?', 'Confusion, delay', 'exam_ready', 'betterment lack of clarity about betterment exams what is improvement exam process? confusion, delay', 146),
  ('Betterment', 'Fear of repeating failure', 'What if marks don''t improve again?', 'Avoidance', 'exam_ready', 'betterment fear of repeating failure what if marks don''t improve again? avoidance', 147),
  ('Betterment', 'No strategy for improvement exam', 'How to improve marks now?', 'Ineffective preparation', 'exam_ready', 'betterment no strategy for improvement exam how to improve marks now? ineffective preparation', 148),
  ('Betterment', 'Time gap misuse', 'Wasting time after results', 'Lost opportunity', 'exam_ready', 'betterment time gap misuse wasting time after results lost opportunity', 149),
  ('Betterment', 'Lack of structured re-preparation', 'Doesn''t know where to restart', 'Same mistakes repeated', 'exam_ready', 'betterment lack of structured re-preparation doesn''t know where to restart same mistakes repeated', 150),
  ('Betterment', 'Concept gaps not fixed', 'Still weak in basics', 'No improvement', 'exam_ready', 'betterment concept gaps not fixed still weak in basics no improvement', 151),
  ('Betterment', 'Psychological setback after failure', 'Lost confidence completely', 'Withdrawal', 'exam_ready', 'betterment psychological setback after failure lost confidence completely withdrawal', 152),
  ('Betterment', 'Social stigma of failure', 'What will others say?', 'Shame, isolation', 'exam_ready', 'betterment social stigma of failure what will others say? shame, isolation', 153),
  ('Betterment', 'Lack of motivation to retry', 'Doesn''t want to attempt again', 'Dropout risk', 'exam_ready', 'betterment lack of motivation to retry doesn''t want to attempt again dropout risk', 154),
  ('Betterment', 'Wrong study strategy repetition', 'Repeating same mistakes', 'No score improvement', 'exam_ready', 'betterment wrong study strategy repetition repeating same mistakes no score improvement', 155),
  ('Betterment', 'Lack of mentorship/guidance', 'No one to guide for improvement', 'Directionless effort', 'exam_ready', 'betterment lack of mentorship/guidance no one to guide for improvement directionless effort', 156),
  ('Betterment', 'Fear of career delay', 'Will this delay future?', 'Anxiety', 'exam_ready', 'betterment fear of career delay will this delay future? anxiety', 157),
  ('Betterment', 'College admission uncertainty', 'Will colleges accept betterment scores?', 'Confusion', 'exam_ready', 'betterment college admission uncertainty will colleges accept betterment scores? confusion', 158),
  ('Betterment', 'Peer progression pressure', 'Friends moved ahead', 'Inferiority feeling', 'exam_ready', 'betterment peer progression pressure friends moved ahead inferiority feeling', 159),
  ('Betterment', 'Emotional recovery after failure', 'Child is mentally down', 'Long-term confidence impact', 'exam_ready', 'betterment emotional recovery after failure child is mentally down long-term confidence impact', 160)
ON CONFLICT (category, concern_area) DO UPDATE SET
  parent_worry = EXCLUDED.parent_worry,
  impact_on_child = EXCLUDED.impact_on_child,
  assessment_type = EXCLUDED.assessment_type,
  search_keywords = EXCLUDED.search_keywords,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
