-- /app/scripts/seed-competency-library.sql
-- Auto-generated from /app/frontend/attached_assets/Pasted--Domain-Subdomain-Micro-Competenc...
-- 12 Domains, 101 Subdomains, 317 Micro-Competencies
-- Idempotent: ON CONFLICT (competency_number) DO UPDATE

INSERT INTO competency_library (competency_number, competency_name, domain, sub_domain, status) VALUES
(1, 'Number sense', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(2, 'arithmetic accuracy', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(3, 'quantitative reasoning', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(4, 'estimation accuracy', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(5, 'proportional reasoning', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(6, 'financial numeracy', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(7, 'data sufficiency analysis', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(8, 'error detection', 'Cognitive & Analytical Intelligence', 'Numerical Aptitude', 'Active'),
(9, 'Deductive reasoning', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(10, 'inductive reasoning', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(11, 'abductive reasoning', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(12, 'syllogistic reasoning', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(13, 'analogy mapping', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(14, 'sequence logic', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(15, 'pattern recognition', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(16, 'conditional reasoning', 'Cognitive & Analytical Intelligence', 'Logical Reasoning', 'Active'),
(17, 'Assumption identification', 'Cognitive & Analytical Intelligence', 'Critical Thinking', 'Active'),
(18, 'argument evaluation', 'Cognitive & Analytical Intelligence', 'Critical Thinking', 'Active'),
(19, 'bias detection', 'Cognitive & Analytical Intelligence', 'Critical Thinking', 'Active'),
(20, 'logical consistency', 'Cognitive & Analytical Intelligence', 'Critical Thinking', 'Active'),
(21, 'evidence validation', 'Cognitive & Analytical Intelligence', 'Critical Thinking', 'Active'),
(22, 'fallacy detection', 'Cognitive & Analytical Intelligence', 'Critical Thinking', 'Active'),
(23, 'counterfactual reasoning', 'Cognitive & Analytical Intelligence', 'Critical Thinking', 'Active'),
(24, 'Problem decomposition', 'Cognitive & Analytical Intelligence', 'Analytical Thinking', 'Active'),
(25, 'root cause analysis', 'Cognitive & Analytical Intelligence', 'Analytical Thinking', 'Active'),
(26, 'variable isolation', 'Cognitive & Analytical Intelligence', 'Analytical Thinking', 'Active'),
(27, 'structured thinking', 'Cognitive & Analytical Intelligence', 'Analytical Thinking', 'Active'),
(28, 'prioritization', 'Cognitive & Analytical Intelligence', 'Analytical Thinking', 'Active'),
(29, 'causal analysis', 'Cognitive & Analytical Intelligence', 'Analytical Thinking', 'Active'),
(30, 'Problem identification', 'Cognitive & Analytical Intelligence', 'Problem Solving', 'Active'),
(31, 'hypothesis generation', 'Cognitive & Analytical Intelligence', 'Problem Solving', 'Active'),
(32, 'solution ideation', 'Cognitive & Analytical Intelligence', 'Problem Solving', 'Active'),
(33, 'alternative evaluation', 'Cognitive & Analytical Intelligence', 'Problem Solving', 'Active'),
(34, 'feasibility analysis', 'Cognitive & Analytical Intelligence', 'Problem Solving', 'Active'),
(35, 'iterative refinement', 'Cognitive & Analytical Intelligence', 'Problem Solving', 'Active'),
(36, 'Risk assessment', 'Cognitive & Analytical Intelligence', 'Decision Making', 'Active'),
(37, 'trade-off evaluation', 'Cognitive & Analytical Intelligence', 'Decision Making', 'Active'),
(38, 'cost-benefit analysis', 'Cognitive & Analytical Intelligence', 'Decision Making', 'Active'),
(39, 'probabilistic thinking', 'Cognitive & Analytical Intelligence', 'Decision Making', 'Active'),
(40, 'judgment accuracy', 'Cognitive & Analytical Intelligence', 'Decision Making', 'Active'),
(41, 'speed-quality balance', 'Cognitive & Analytical Intelligence', 'Decision Making', 'Active'),
(42, 'Interdependency mapping', 'Cognitive & Analytical Intelligence', 'Systems Thinking', 'Active'),
(43, 'feedback loop understanding', 'Cognitive & Analytical Intelligence', 'Systems Thinking', 'Active'),
(44, 'holistic reasoning', 'Cognitive & Analytical Intelligence', 'Systems Thinking', 'Active'),
(45, 'complexity handling', 'Cognitive & Analytical Intelligence', 'Systems Thinking', 'Active'),
(46, 'system dynamics', 'Cognitive & Analytical Intelligence', 'Systems Thinking', 'Active'),
(47, 'Abstraction', 'Cognitive & Analytical Intelligence', 'Conceptual Thinking', 'Active'),
(48, 'generalization', 'Cognitive & Analytical Intelligence', 'Conceptual Thinking', 'Active'),
(49, 'theoretical modeling', 'Cognitive & Analytical Intelligence', 'Conceptual Thinking', 'Active'),
(50, 'principle application', 'Cognitive & Analytical Intelligence', 'Conceptual Thinking', 'Active'),
(51, 'Data sourcing', 'Cognitive & Analytical Intelligence', 'Research & Data Analysis', 'Active'),
(52, 'hypothesis testing', 'Cognitive & Analytical Intelligence', 'Research & Data Analysis', 'Active'),
(53, 'statistical reasoning', 'Cognitive & Analytical Intelligence', 'Research & Data Analysis', 'Active'),
(54, 'data interpretation', 'Cognitive & Analytical Intelligence', 'Research & Data Analysis', 'Active'),
(55, 'synthesis', 'Cognitive & Analytical Intelligence', 'Research & Data Analysis', 'Active'),
(56, 'insight extraction', 'Cognitive & Analytical Intelligence', 'Research & Data Analysis', 'Active'),
(57, 'Idea fluency', 'Cognitive & Analytical Intelligence', 'Creativity & Innovation', 'Active'),
(58, 'originality', 'Cognitive & Analytical Intelligence', 'Creativity & Innovation', 'Active'),
(59, 'divergent thinking', 'Cognitive & Analytical Intelligence', 'Creativity & Innovation', 'Active'),
(60, 'lateral thinking', 'Cognitive & Analytical Intelligence', 'Creativity & Innovation', 'Active'),
(61, 'recombination ability', 'Cognitive & Analytical Intelligence', 'Creativity & Innovation', 'Active'),
(62, 'experimentation mindset', 'Cognitive & Analytical Intelligence', 'Creativity & Innovation', 'Active'),
(63, 'Visualization', 'Cognitive & Analytical Intelligence', 'Spatial Intelligence', 'Active'),
(64, 'mental rotation', 'Cognitive & Analytical Intelligence', 'Spatial Intelligence', 'Active'),
(65, 'spatial reasoning', 'Cognitive & Analytical Intelligence', 'Spatial Intelligence', 'Active'),
(66, 'diagrammatic interpretation', 'Cognitive & Analytical Intelligence', 'Spatial Intelligence', 'Active'),
(67, 'Cause-effect understanding', 'Cognitive & Analytical Intelligence', 'Mechanical Reasoning', 'Active'),
(68, 'system functionality', 'Cognitive & Analytical Intelligence', 'Mechanical Reasoning', 'Active'),
(69, 'physical reasoning', 'Cognitive & Analytical Intelligence', 'Mechanical Reasoning', 'Active'),
(70, 'troubleshooting', 'Cognitive & Analytical Intelligence', 'Mechanical Reasoning', 'Active'),
(71, 'Self-monitoring', 'Cognitive & Analytical Intelligence', 'Metacognition', 'Active'),
(72, 'strategy selection', 'Cognitive & Analytical Intelligence', 'Metacognition', 'Active'),
(73, 'cognitive flexibility', 'Cognitive & Analytical Intelligence', 'Metacognition', 'Active'),
(74, 'error awareness', 'Cognitive & Analytical Intelligence', 'Metacognition', 'Active'),
(75, 'learning regulation', 'Cognitive & Analytical Intelligence', 'Metacognition', 'Active'),
(76, 'Clarity', 'Communication & Expression', 'Verbal Communication', 'Active'),
(77, 'articulation', 'Communication & Expression', 'Verbal Communication', 'Active'),
(78, 'fluency', 'Communication & Expression', 'Verbal Communication', 'Active'),
(79, 'pronunciation', 'Communication & Expression', 'Verbal Communication', 'Active'),
(80, 'tone modulation', 'Communication & Expression', 'Verbal Communication', 'Active'),
(81, 'vocabulary depth', 'Communication & Expression', 'Verbal Communication', 'Active'),
(82, 'Grammar accuracy', 'Communication & Expression', 'Written Communication', 'Active'),
(83, 'syntax control', 'Communication & Expression', 'Written Communication', 'Active'),
(84, 'clarity', 'Communication & Expression', 'Written Communication', 'Active'),
(85, 'conciseness', 'Communication & Expression', 'Written Communication', 'Active'),
(86, 'coherence', 'Communication & Expression', 'Written Communication', 'Active'),
(87, 'structured writing', 'Communication & Expression', 'Written Communication', 'Active'),
(88, 'Email etiquette', 'Communication & Expression', 'Business Communication', 'Active'),
(89, 'formal writing', 'Communication & Expression', 'Business Communication', 'Active'),
(90, 'professional tone', 'Communication & Expression', 'Business Communication', 'Active'),
(91, 'structured documentation', 'Communication & Expression', 'Business Communication', 'Active'),
(92, 'clarity of intent', 'Communication & Expression', 'Business Communication', 'Active'),
(93, 'Structuring content', 'Communication & Expression', 'Presentation Skills', 'Active'),
(94, 'audience engagement', 'Communication & Expression', 'Presentation Skills', 'Active'),
(95, 'storytelling', 'Communication & Expression', 'Presentation Skills', 'Active'),
(96, 'visual communication', 'Communication & Expression', 'Presentation Skills', 'Active'),
(97, 'delivery confidence', 'Communication & Expression', 'Presentation Skills', 'Active'),
(98, 'Attention', 'Communication & Expression', 'Active Listening', 'Active'),
(99, 'interpretation', 'Communication & Expression', 'Active Listening', 'Active'),
(100, 'paraphrasing', 'Communication & Expression', 'Active Listening', 'Active'),
(101, 'questioning', 'Communication & Expression', 'Active Listening', 'Active'),
(102, 'response relevance', 'Communication & Expression', 'Active Listening', 'Active'),
(103, 'Argument framing', 'Communication & Expression', 'Persuasion & Influence', 'Active'),
(104, 'influencing strategies', 'Communication & Expression', 'Persuasion & Influence', 'Active'),
(105, 'objection handling', 'Communication & Expression', 'Persuasion & Influence', 'Active'),
(106, 'negotiation framing', 'Communication & Expression', 'Persuasion & Influence', 'Active'),
(107, 'Boundary setting', 'Communication & Expression', 'Assertiveness', 'Active'),
(108, 'confident communication', 'Communication & Expression', 'Assertiveness', 'Active'),
(109, 'respectful disagreement', 'Communication & Expression', 'Assertiveness', 'Active'),
(110, 'Stage presence', 'Communication & Expression', 'Public Speaking', 'Active'),
(111, 'voice control', 'Communication & Expression', 'Public Speaking', 'Active'),
(112, 'audience interaction', 'Communication & Expression', 'Public Speaking', 'Active'),
(113, 'confidence under pressure', 'Communication & Expression', 'Public Speaking', 'Active'),
(114, 'Narrative structuring', 'Communication & Expression', 'Storytelling', 'Active'),
(115, 'emotional appeal', 'Communication & Expression', 'Storytelling', 'Active'),
(116, 'audience connection', 'Communication & Expression', 'Storytelling', 'Active'),
(117, 'Adaptability across audiences', 'Communication & Expression', 'Cross-functional Communication', 'Active'),
(118, 'clarity in diverse teams', 'Communication & Expression', 'Cross-functional Communication', 'Active'),
(119, 'Constructive feedback delivery', 'Communication & Expression', 'Feedback Communication', 'Active'),
(120, 'receptiveness', 'Communication & Expression', 'Feedback Communication', 'Active'),
(121, 'feedback framing', 'Communication & Expression', 'Feedback Communication', 'Active'),
(122, 'Email/chat clarity', 'Communication & Expression', 'Digital Communication', 'Active'),
(123, 'asynchronous communication', 'Communication & Expression', 'Digital Communication', 'Active'),
(124, 'brevity', 'Communication & Expression', 'Digital Communication', 'Active'),
(125, 'tone appropriateness', 'Communication & Expression', 'Digital Communication', 'Active'),
(126, 'Initiative', 'Personal Effectiveness & Self-Management', 'Self-Motivation', 'Active'),
(127, 'drive', 'Personal Effectiveness & Self-Management', 'Self-Motivation', 'Active'),
(128, 'goal orientation', 'Personal Effectiveness & Self-Management', 'Self-Motivation', 'Active'),
(129, 'proactiveness', 'Personal Effectiveness & Self-Management', 'Self-Motivation', 'Active'),
(130, 'Consistency', 'Personal Effectiveness & Self-Management', 'Discipline', 'Active'),
(131, 'habit formation', 'Personal Effectiveness & Self-Management', 'Discipline', 'Active'),
(132, 'focus maintenance', 'Personal Effectiveness & Self-Management', 'Discipline', 'Active'),
(133, 'self-control', 'Personal Effectiveness & Self-Management', 'Discipline', 'Active'),
(134, 'Stress tolerance', 'Personal Effectiveness & Self-Management', 'Resilience', 'Active'),
(135, 'recovery ability', 'Personal Effectiveness & Self-Management', 'Resilience', 'Active'),
(136, 'persistence', 'Personal Effectiveness & Self-Management', 'Resilience', 'Active'),
(137, 'adversity handling', 'Personal Effectiveness & Self-Management', 'Resilience', 'Active'),
(138, 'Flexibility', 'Personal Effectiveness & Self-Management', 'Adaptability', 'Active'),
(139, 'openness to change', 'Personal Effectiveness & Self-Management', 'Adaptability', 'Active'),
(140, 'situational adjustment', 'Personal Effectiveness & Self-Management', 'Adaptability', 'Active'),
(141, 'Honesty', 'Personal Effectiveness & Self-Management', 'Integrity & Ethics', 'Active'),
(142, 'ethical reasoning', 'Personal Effectiveness & Self-Management', 'Integrity & Ethics', 'Active'),
(143, 'transparency', 'Personal Effectiveness & Self-Management', 'Integrity & Ethics', 'Active'),
(144, 'fairness', 'Personal Effectiveness & Self-Management', 'Integrity & Ethics', 'Active'),
(145, 'Ownership', 'Personal Effectiveness & Self-Management', 'Accountability', 'Active'),
(146, 'responsibility', 'Personal Effectiveness & Self-Management', 'Accountability', 'Active'),
(147, 'follow-through', 'Personal Effectiveness & Self-Management', 'Accountability', 'Active'),
(148, 'reliability', 'Personal Effectiveness & Self-Management', 'Accountability', 'Active'),
(149, 'Strength/weakness identification', 'Personal Effectiveness & Self-Management', 'Self-Awareness', 'Active'),
(150, 'reflective thinking', 'Personal Effectiveness & Self-Management', 'Self-Awareness', 'Active'),
(151, 'emotional awareness', 'Personal Effectiveness & Self-Management', 'Self-Awareness', 'Active'),
(152, 'Emotional control', 'Personal Effectiveness & Self-Management', 'Emotional Regulation', 'Active'),
(153, 'composure', 'Personal Effectiveness & Self-Management', 'Emotional Regulation', 'Active'),
(154, 'impulse management', 'Personal Effectiveness & Self-Management', 'Emotional Regulation', 'Active'),
(155, 'Curiosity', 'Personal Effectiveness & Self-Management', 'Learning Agility', 'Active'),
(156, 'speed of learning', 'Personal Effectiveness & Self-Management', 'Learning Agility', 'Active'),
(157, 'knowledge transfer', 'Personal Effectiveness & Self-Management', 'Learning Agility', 'Active'),
(158, 'experimentation', 'Personal Effectiveness & Self-Management', 'Learning Agility', 'Active'),
(159, 'Openness to feedback', 'Personal Effectiveness & Self-Management', 'Growth Mindset', 'Active'),
(160, 'continuous improvement orientation', 'Personal Effectiveness & Self-Management', 'Growth Mindset', 'Active'),
(161, 'Sustained performance', 'Personal Effectiveness & Self-Management', 'Energy Management', 'Active'),
(162, 'fatigue management', 'Personal Effectiveness & Self-Management', 'Energy Management', 'Active'),
(163, 'burnout prevention', 'Personal Effectiveness & Self-Management', 'Energy Management', 'Active'),
(164, 'Prioritization', 'Personal Effectiveness & Self-Management', 'Time Management', 'Active'),
(165, 'scheduling', 'Personal Effectiveness & Self-Management', 'Time Management', 'Active'),
(166, 'deadline adherence', 'Personal Effectiveness & Self-Management', 'Time Management', 'Active'),
(167, 'time estimation', 'Personal Effectiveness & Self-Management', 'Time Management', 'Active'),
(168, 'Performance under pressure', 'Personal Effectiveness & Self-Management', 'Stress Management', 'Active'),
(169, 'coping strategies', 'Personal Effectiveness & Self-Management', 'Stress Management', 'Active'),
(170, 'Rapport building', 'Social & Interpersonal Intelligence', 'Interpersonal Skills', 'Active'),
(171, 'relationship management', 'Social & Interpersonal Intelligence', 'Interpersonal Skills', 'Active'),
(172, 'empathy in interaction', 'Social & Interpersonal Intelligence', 'Interpersonal Skills', 'Active'),
(173, 'Empathy', 'Social & Interpersonal Intelligence', 'Emotional Intelligence', 'Active'),
(174, 'emotional awareness', 'Social & Interpersonal Intelligence', 'Emotional Intelligence', 'Active'),
(175, 'emotional regulation in social context', 'Social & Interpersonal Intelligence', 'Emotional Intelligence', 'Active'),
(176, 'Cooperation', 'Social & Interpersonal Intelligence', 'Teamwork & Collaboration', 'Active'),
(177, 'contribution', 'Social & Interpersonal Intelligence', 'Teamwork & Collaboration', 'Active'),
(178, 'coordination', 'Social & Interpersonal Intelligence', 'Teamwork & Collaboration', 'Active'),
(179, 'mutual support', 'Social & Interpersonal Intelligence', 'Teamwork & Collaboration', 'Active'),
(180, 'Mediation', 'Social & Interpersonal Intelligence', 'Conflict Resolution', 'Active'),
(181, 'negotiation', 'Social & Interpersonal Intelligence', 'Conflict Resolution', 'Active'),
(182, 'de-escalation strategies', 'Social & Interpersonal Intelligence', 'Conflict Resolution', 'Active'),
(183, 'Diversity sensitivity', 'Social & Interpersonal Intelligence', 'Cultural Intelligence', 'Active'),
(184, 'inclusion', 'Social & Interpersonal Intelligence', 'Cultural Intelligence', 'Active'),
(185, 'cross-cultural adaptability', 'Social & Interpersonal Intelligence', 'Cultural Intelligence', 'Active'),
(186, 'Relationship building', 'Social & Interpersonal Intelligence', 'Networking', 'Active'),
(187, 'maintaining professional networks', 'Social & Interpersonal Intelligence', 'Networking', 'Active'),
(188, 'Expectation alignment', 'Social & Interpersonal Intelligence', 'Stakeholder Management', 'Active'),
(189, 'communication clarity', 'Social & Interpersonal Intelligence', 'Stakeholder Management', 'Active'),
(190, 'influence management', 'Social & Interpersonal Intelligence', 'Stakeholder Management', 'Active'),
(191, 'Service mindset', 'Social & Interpersonal Intelligence', 'Customer Orientation', 'Active'),
(192, 'empathy', 'Social & Interpersonal Intelligence', 'Customer Orientation', 'Active'),
(193, 'responsiveness', 'Social & Interpersonal Intelligence', 'Customer Orientation', 'Active'),
(194, 'Credibility', 'Social & Interpersonal Intelligence', 'Trust Building', 'Active'),
(195, 'consistency', 'Social & Interpersonal Intelligence', 'Trust Building', 'Active'),
(196, 'transparency', 'Social & Interpersonal Intelligence', 'Trust Building', 'Active'),
(197, 'Group dynamics understanding', 'Social & Interpersonal Intelligence', 'Social Awareness', 'Active'),
(198, 'situational awareness', 'Social & Interpersonal Intelligence', 'Social Awareness', 'Active'),
(199, 'Persuasion', 'Social & Interpersonal Intelligence', 'Influence Without Authority', 'Active'),
(200, 'alignment building', 'Social & Interpersonal Intelligence', 'Influence Without Authority', 'Active'),
(201, 'Cross-functional coordination', 'Social & Interpersonal Intelligence', 'Collaboration Across Teams', 'Active'),
(202, 'integration', 'Social & Interpersonal Intelligence', 'Collaboration Across Teams', 'Active'),
(203, 'Vision setting', 'Leadership & Influence', 'Leadership Skills', 'Active'),
(204, 'direction', 'Leadership & Influence', 'Leadership Skills', 'Active'),
(205, 'alignment', 'Leadership & Influence', 'Leadership Skills', 'Active'),
(206, 'Delegation', 'Leadership & Influence', 'People Management', 'Active'),
(207, 'mentoring', 'Leadership & Influence', 'People Management', 'Active'),
(208, 'coaching', 'Leadership & Influence', 'People Management', 'Active'),
(209, 'performance management', 'Leadership & Influence', 'People Management', 'Active'),
(210, 'Long-term planning', 'Leadership & Influence', 'Strategic Thinking', 'Active'),
(211, 'foresight', 'Leadership & Influence', 'Strategic Thinking', 'Active'),
(212, 'scenario analysis', 'Leadership & Influence', 'Strategic Thinking', 'Active'),
(213, 'Decisiveness', 'Leadership & Influence', 'Decision Leadership', 'Active'),
(214, 'accountability in decisions', 'Leadership & Influence', 'Decision Leadership', 'Active'),
(215, 'Leading change', 'Leadership & Influence', 'Change Management', 'Active'),
(216, 'adaptability', 'Leadership & Influence', 'Change Management', 'Active'),
(217, 'transition management', 'Leadership & Influence', 'Change Management', 'Active'),
(218, 'Developing others', 'Leadership & Influence', 'Coaching & Mentoring', 'Active'),
(219, 'feedback guidance', 'Leadership & Influence', 'Coaching & Mentoring', 'Active'),
(220, 'Driving results', 'Leadership & Influence', 'Execution Leadership', 'Active'),
(221, 'ensuring outcomes', 'Leadership & Influence', 'Execution Leadership', 'Active'),
(222, 'Structuring teams', 'Leadership & Influence', 'Team Building', 'Active'),
(223, 'synergy creation', 'Leadership & Influence', 'Team Building', 'Active'),
(224, 'Motivation', 'Leadership & Influence', 'Inspirational Leadership', 'Active'),
(225, 'influence', 'Leadership & Influence', 'Inspirational Leadership', 'Active'),
(226, 'engagement', 'Leadership & Influence', 'Inspirational Leadership', 'Active'),
(227, 'Opportunity recognition', 'Leadership & Influence', 'Entrepreneurial Mindset', 'Active'),
(228, 'calculated risk-taking', 'Leadership & Influence', 'Entrepreneurial Mindset', 'Active'),
(229, 'Ownership', 'Execution, Operations & Productivity', 'Task Execution', 'Active'),
(230, 'closure', 'Execution, Operations & Productivity', 'Task Execution', 'Active'),
(231, 'quality of execution', 'Execution, Operations & Productivity', 'Task Execution', 'Active'),
(232, 'Planning', 'Execution, Operations & Productivity', 'Project Management', 'Active'),
(233, 'execution', 'Execution, Operations & Productivity', 'Project Management', 'Active'),
(234, 'monitoring', 'Execution, Operations & Productivity', 'Project Management', 'Active'),
(235, 'risk tracking', 'Execution, Operations & Productivity', 'Project Management', 'Active'),
(236, 'Workflow design', 'Execution, Operations & Productivity', 'Process Management', 'Active'),
(237, 'process optimization', 'Execution, Operations & Productivity', 'Process Management', 'Active'),
(238, 'Resource optimization', 'Execution, Operations & Productivity', 'Operational Efficiency', 'Active'),
(239, 'output maximization', 'Execution, Operations & Productivity', 'Operational Efficiency', 'Active'),
(240, 'Accuracy', 'Execution, Operations & Productivity', 'Attention to Detail', 'Active'),
(241, 'precision', 'Execution, Operations & Productivity', 'Attention to Detail', 'Active'),
(242, 'quality control', 'Execution, Operations & Productivity', 'Attention to Detail', 'Active'),
(243, 'Managing multiple priorities effectively', 'Execution, Operations & Productivity', 'Multitasking', 'Active'),
(244, 'Efficient utilization of time', 'Execution, Operations & Productivity', 'Resource Management', 'Active'),
(245, 'tools', 'Execution, Operations & Productivity', 'Resource Management', 'Active'),
(246, 'people', 'Execution, Operations & Productivity', 'Resource Management', 'Active'),
(247, 'Outcome delivery', 'Execution, Operations & Productivity', 'Goal Execution', 'Active'),
(248, 'milestone tracking', 'Execution, Operations & Productivity', 'Goal Execution', 'Active'),
(249, 'Monitoring metrics', 'Execution, Operations & Productivity', 'Performance Tracking', 'Active'),
(250, 'feedback loops', 'Execution, Operations & Productivity', 'Performance Tracking', 'Active'),
(251, 'Goal clarity', 'Career & Professional Readiness', 'Career Awareness', 'Active'),
(252, 'career mapping', 'Career & Professional Readiness', 'Career Awareness', 'Active'),
(253, 'Workplace etiquette', 'Career & Professional Readiness', 'Professionalism', 'Active'),
(254, 'behavior standards', 'Career & Professional Readiness', 'Professionalism', 'Active'),
(255, 'Readiness for job roles', 'Career & Professional Readiness', 'Employability Skills', 'Active'),
(256, 'workplace adaptability', 'Career & Professional Readiness', 'Employability Skills', 'Active'),
(257, 'Communication', 'Career & Professional Readiness', 'Interview Skills', 'Active'),
(258, 'confidence', 'Career & Professional Readiness', 'Interview Skills', 'Active'),
(259, 'structured responses', 'Career & Professional Readiness', 'Interview Skills', 'Active'),
(260, 'Achievement articulation', 'Career & Professional Readiness', 'Resume & Profile Building', 'Active'),
(261, 'structuring', 'Career & Professional Readiness', 'Resume & Profile Building', 'Active'),
(262, 'Self-positioning', 'Career & Professional Readiness', 'Personal Branding', 'Active'),
(263, 'visibility', 'Career & Professional Readiness', 'Personal Branding', 'Active'),
(264, 'Workplace structure', 'Career & Professional Readiness', 'Organizational Awareness', 'Active'),
(265, 'dynamics understanding', 'Career & Professional Readiness', 'Organizational Awareness', 'Active'),
(266, 'Market trends', 'Career & Professional Readiness', 'Industry Awareness', 'Active'),
(267, 'domain knowledge', 'Career & Professional Readiness', 'Industry Awareness', 'Active'),
(268, 'Basic computing', 'Digital, Data & Technology Skills', 'Digital Literacy', 'Active'),
(269, 'internet usage', 'Digital, Data & Technology Skills', 'Digital Literacy', 'Active'),
(270, 'Data interpretation', 'Digital, Data & Technology Skills', 'Data Literacy', 'Active'),
(271, 'visualization', 'Digital, Data & Technology Skills', 'Data Literacy', 'Active'),
(272, 'basic analytics', 'Digital, Data & Technology Skills', 'Data Literacy', 'Active'),
(273, 'Domain-specific technical knowledge', 'Digital, Data & Technology Skills', 'Technical Skills', 'Active'),
(274, 'Email', 'Digital, Data & Technology Skills', 'Digital Communication Tools', 'Active'),
(275, 'collaboration tools', 'Digital, Data & Technology Skills', 'Digital Communication Tools', 'Active'),
(276, 'remote work tools', 'Digital, Data & Technology Skills', 'Digital Communication Tools', 'Active'),
(277, 'Learning new tools', 'Digital, Data & Technology Skills', 'Technology Adaptability', 'Active'),
(278, 'tech agility', 'Digital, Data & Technology Skills', 'Technology Adaptability', 'Active'),
(279, 'Understanding tools for efficiency', 'Digital, Data & Technology Skills', 'Automation Awareness', 'Active'),
(280, 'Data privacy', 'Digital, Data & Technology Skills', 'Cyber Awareness', 'Active'),
(281, 'basic cybersecurity hygiene', 'Digital, Data & Technology Skills', 'Cyber Awareness', 'Active'),
(282, 'Idea validation', 'Innovation, Entrepreneurship & Value Creation', 'Innovation Skills', 'Active'),
(283, 'prototyping', 'Innovation, Entrepreneurship & Value Creation', 'Innovation Skills', 'Active'),
(284, 'experimentation', 'Innovation, Entrepreneurship & Value Creation', 'Innovation Skills', 'Active'),
(285, 'Opportunity spotting', 'Innovation, Entrepreneurship & Value Creation', 'Entrepreneurial Skills', 'Active'),
(286, 'resourcefulness', 'Innovation, Entrepreneurship & Value Creation', 'Entrepreneurial Skills', 'Active'),
(287, 'Market understanding', 'Innovation, Entrepreneurship & Value Creation', 'Business Acumen', 'Active'),
(288, 'value creation logic', 'Innovation, Entrepreneurship & Value Creation', 'Business Acumen', 'Active'),
(289, 'Budgeting', 'Innovation, Entrepreneurship & Value Creation', 'Financial Literacy', 'Active'),
(290, 'cost understanding', 'Innovation, Entrepreneurship & Value Creation', 'Financial Literacy', 'Active'),
(291, 'ROI thinking', 'Innovation, Entrepreneurship & Value Creation', 'Financial Literacy', 'Active'),
(292, 'User empathy', 'Innovation, Entrepreneurship & Value Creation', 'Design Thinking', 'Active'),
(293, 'ideation', 'Innovation, Entrepreneurship & Value Creation', 'Design Thinking', 'Active'),
(294, 'prototyping', 'Innovation, Entrepreneurship & Value Creation', 'Design Thinking', 'Active'),
(295, 'Moral judgment', 'Ethics, Governance & Responsibility', 'Ethical Reasoning', 'Active'),
(296, 'fairness', 'Ethics, Governance & Responsibility', 'Ethical Reasoning', 'Active'),
(297, 'integrity', 'Ethics, Governance & Responsibility', 'Ethical Reasoning', 'Active'),
(298, 'Rules', 'Ethics, Governance & Responsibility', 'Compliance Awareness', 'Active'),
(299, 'regulations understanding', 'Ethics, Governance & Responsibility', 'Compliance Awareness', 'Active'),
(300, 'Sustainability awareness', 'Ethics, Governance & Responsibility', 'Social Responsibility', 'Active'),
(301, 'ethical impact', 'Ethics, Governance & Responsibility', 'Social Responsibility', 'Active'),
(302, 'Transparency', 'Ethics, Governance & Responsibility', 'Accountability Systems', 'Active'),
(303, 'reporting responsibility', 'Ethics, Governance & Responsibility', 'Accountability Systems', 'Active'),
(304, 'Energy levels', 'Health, Wellbeing & Sustainability', 'Physical Wellbeing', 'Active'),
(305, 'health maintenance awareness', 'Health, Wellbeing & Sustainability', 'Physical Wellbeing', 'Active'),
(306, 'Stress balance', 'Health, Wellbeing & Sustainability', 'Mental Wellbeing', 'Active'),
(307, 'emotional health awareness', 'Health, Wellbeing & Sustainability', 'Mental Wellbeing', 'Active'),
(308, 'Balance management', 'Health, Wellbeing & Sustainability', 'Work-Life Balance', 'Active'),
(309, 'sustainability', 'Health, Wellbeing & Sustainability', 'Work-Life Balance', 'Active'),
(310, 'Safe work practices', 'Health, Wellbeing & Sustainability', 'Occupational Health Awareness', 'Active'),
(311, 'Geopolitical awareness', 'Global & Future Readiness', 'Global Awareness', 'Active'),
(312, 'global trends', 'Global & Future Readiness', 'Global Awareness', 'Active'),
(313, 'AI awareness', 'Global & Future Readiness', 'Future Skills Orientation', 'Active'),
(314, 'adaptability to future roles', 'Global & Future Readiness', 'Future Skills Orientation', 'Active'),
(315, 'Continuous upskilling mindset', 'Global & Future Readiness', 'Lifelong Learning Orientation', 'Active'),
(316, 'Virtual collaboration', 'Global & Future Readiness', 'Remote Work Readiness', 'Active'),
(317, 'self-management', 'Global & Future Readiness', 'Remote Work Readiness', 'Active')
ON CONFLICT (competency_number) DO UPDATE SET
  competency_name = EXCLUDED.competency_name,
  domain = EXCLUDED.domain,
  sub_domain = EXCLUDED.sub_domain,
  status = EXCLUDED.status;
