import { createContext, useContext } from 'react';
import type { UseMutationResult, UseQueryResult } from '@tanstack/react-query';
import type { QueryClient } from '@tanstack/react-query';
import type React from 'react';

// Shared brand configuration
export interface BrandConfig {
  primary: string;
  accent: string;
  cyan: string;
  lightBg: string;
  dark: string;
  success: string;
  warning: string;
  danger: string;
  purple: string;
  indigo: string;
}

// Common action dialog shape
export interface ActionDialog {
  open: boolean;
  type: string;
  item: unknown;
}

// Mentor dialog shape
export interface MentorDialog {
  open: boolean;
  type: string;
  mentor: unknown;
}

// Document request dialog shape
export interface DocumentRequestDialog {
  open: boolean;
  onboarding: unknown;
}

// Mentor profile modal shape
export interface MentorProfileModal {
  open: boolean;
  mentor: unknown | null;
}

// Template dialog shape
export interface TemplateDialog {
  open: boolean;
  mode: 'create' | 'edit';
  template: unknown | null;
}

// KYC feedback
export interface FeedbackResult {
  ok: boolean;
  msg: string;
}

// Stage check for capadex
export interface CapadexStageCheckData {
  completed: string[];
  has_prior_completion: boolean;
  next_stage_code: string | null;
  next_stage_label: string | null;
  next_stage_index: number;
  next_stage_color: string;
}

export interface AdminDashboardContextValue {
  // Auth
  isAuthenticated: boolean;
  setIsAuthenticated: React.Dispatch<React.SetStateAction<boolean>>;
  isCheckingAuth: boolean;
  // Navigation
  activeTab: string;
  setActiveTab: React.Dispatch<React.SetStateAction<string>>;
  crisisPending: number;
  // Assessment tools navigation
  psyActiveSection: 'frameworks' | 'domains' | 'items' | 'modules' | 'custom-modules' | 'competency-framework' | 'tools';
  setPsyActiveSection: React.Dispatch<React.SetStateAction<'frameworks' | 'domains' | 'items' | 'modules' | 'custom-modules' | 'competency-framework' | 'tools'>>;
  // Global search/filter
  searchQuery: string;
  setSearchQuery: React.Dispatch<React.SetStateAction<string>>;
  statusFilter: string;
  setStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  entityTypeFilter: string;
  setEntityTypeFilter: React.Dispatch<React.SetStateAction<string>>;
  // Dialogs
  actionDialog: ActionDialog;
  setActionDialog: React.Dispatch<React.SetStateAction<ActionDialog>>;
  actionNotes: string;
  setActionNotes: React.Dispatch<React.SetStateAction<string>>;
  // Layout
  sidebarCollapsed: boolean;
  setSidebarCollapsed: React.Dispatch<React.SetStateAction<boolean>>;
  // View modes
  userMgmtView: 'users' | 'onboarding';
  setUserMgmtView: React.Dispatch<React.SetStateAction<'users' | 'onboarding'>>;
  securityView: 'security' | 'audit' | 'access';
  setSecurityView: React.Dispatch<React.SetStateAction<'security' | 'audit' | 'access'>>;
  hrSubTab: 'jobs' | 'applicants' | 'mentors';
  setHrSubTab: React.Dispatch<React.SetStateAction<'jobs' | 'applicants' | 'mentors'>>;
  newJobData: unknown;
  setNewJobData: React.Dispatch<React.SetStateAction<unknown>>;
  selectedStudents: string[];
  setSelectedStudents: React.Dispatch<React.SetStateAction<string[]>>;
  instituteFilter: string;
  setInstituteFilter: React.Dispatch<React.SetStateAction<string>>;
  financialSubTab: 'overview' | 'recon' | 'flow' | 'payouts';
  setFinancialSubTab: React.Dispatch<React.SetStateAction<'overview' | 'recon' | 'flow' | 'payouts'>>;
  // Mentor state
  selectedMentor: unknown;
  setSelectedMentor: React.Dispatch<React.SetStateAction<unknown>>;
  mentorStatusFilter: string;
  setMentorStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  mentorSearchQuery: string;
  setMentorSearchQuery: React.Dispatch<React.SetStateAction<string>>;
  mentorTypeFilter: string;
  setMentorTypeFilter: React.Dispatch<React.SetStateAction<string>>;
  mentorAreaFilter: string;
  setMentorAreaFilter: React.Dispatch<React.SetStateAction<string>>;
  mentorDialog: MentorDialog;
  setMentorDialog: React.Dispatch<React.SetStateAction<MentorDialog>>;
  documentRequestDialog: DocumentRequestDialog;
  setDocumentRequestDialog: React.Dispatch<React.SetStateAction<DocumentRequestDialog>>;
  requestedDocs: string[];
  setRequestedDocs: React.Dispatch<React.SetStateAction<string[]>>;
  documentRequestMessage: string;
  setDocumentRequestMessage: React.Dispatch<React.SetStateAction<string>>;
  sendingDocRequest: boolean;
  setSendingDocRequest: React.Dispatch<React.SetStateAction<boolean>>;
  generatedUploadUrl: string;
  setGeneratedUploadUrl: React.Dispatch<React.SetStateAction<string>>;
  mentorDialogData: unknown;
  setMentorDialogData: React.Dispatch<React.SetStateAction<unknown>>;
  mentorDetailTab: 'overview' | 'kpis' | 'tasks' | 'payouts' | 'violations';
  setMentorDetailTab: React.Dispatch<React.SetStateAction<'overview' | 'kpis' | 'tasks' | 'payouts' | 'violations'>>;
  mentorSectionTab: 'roster' | 'operations';
  setMentorSectionTab: React.Dispatch<React.SetStateAction<'roster' | 'operations'>>;
  mentorViewMode: 'grid' | 'list';
  setMentorViewMode: React.Dispatch<React.SetStateAction<'grid' | 'list'>>;
  mentorSortBy: 'name' | 'rating' | 'sessions' | 'revenue' | 'phi' | 'joined';
  setMentorSortBy: React.Dispatch<React.SetStateAction<'name' | 'rating' | 'sessions' | 'revenue' | 'phi' | 'joined'>>;
  mentorSelectedIds: Set<number>;
  setMentorSelectedIds: React.Dispatch<React.SetStateAction<Set<number>>>;
  mentorBulkActionLoading: boolean;
  setMentorBulkActionLoading: React.Dispatch<React.SetStateAction<boolean>>;
  inviteMentorModal: boolean;
  setInviteMentorModal: React.Dispatch<React.SetStateAction<boolean>>;
  inviteForm: { fullName: string; email: string; mobile: string; mentorType: string };
  setInviteForm: React.Dispatch<React.SetStateAction<{ fullName: string; email: string; mobile: string; mentorType: string }>>;
  inviting: boolean;
  setInviting: React.Dispatch<React.SetStateAction<boolean>>;
  mentorNotifyModal: boolean;
  setMentorNotifyModal: React.Dispatch<React.SetStateAction<boolean>>;
  mentorNotifySubject: string;
  setMentorNotifySubject: React.Dispatch<React.SetStateAction<string>>;
  mentorNotifyMessage: string;
  setMentorNotifyMessage: React.Dispatch<React.SetStateAction<string>>;
  sendingMentorNotify: boolean;
  setSendingMentorNotify: React.Dispatch<React.SetStateAction<boolean>>;
  mentorAdjPhiModal: boolean;
  setMentorAdjPhiModal: React.Dispatch<React.SetStateAction<boolean>>;
  mentorPhiValue: number;
  setMentorPhiValue: React.Dispatch<React.SetStateAction<number>>;
  savingMentorPhi: boolean;
  setSavingMentorPhi: React.Dispatch<React.SetStateAction<boolean>>;
  mentorAssignTaskModal: boolean;
  setMentorAssignTaskModal: React.Dispatch<React.SetStateAction<boolean>>;
  mentorTaskForm: { title: string; taskType: string; description: string; scheduledDate: string };
  setMentorTaskForm: React.Dispatch<React.SetStateAction<{ title: string; taskType: string; description: string; scheduledDate: string }>>;
  savingMentorTask: boolean;
  setSavingMentorTask: React.Dispatch<React.SetStateAction<boolean>>;
  mentorReportViolationModal: boolean;
  setMentorReportViolationModal: React.Dispatch<React.SetStateAction<boolean>>;
  mentorViolationForm: { violationType: string; severity: string; description: string };
  setMentorViolationForm: React.Dispatch<React.SetStateAction<{ violationType: string; severity: string; description: string }>>;
  savingMentorViolation: boolean;
  setSavingMentorViolation: React.Dispatch<React.SetStateAction<boolean>>;
  mentorProfileSubTab: 'profile' | 'marketplace' | 'responsibilities' | 'bookings' | 'rating' | 'tasks' | 'kpis' | 'agreement' | 'onboarding';
  setMentorProfileSubTab: React.Dispatch<React.SetStateAction<'profile' | 'marketplace' | 'responsibilities' | 'bookings' | 'rating' | 'tasks' | 'kpis' | 'agreement' | 'onboarding'>>;
  mentorProfileModal: MentorProfileModal;
  setMentorProfileModal: React.Dispatch<React.SetStateAction<MentorProfileModal>>;
  mentorProfileForm: unknown;
  setMentorProfileForm: React.Dispatch<React.SetStateAction<unknown>>;
  savingMentorProfile: boolean;
  setSavingMentorProfile: React.Dispatch<React.SetStateAction<boolean>>;
  // Parent state
  selectedParent: unknown;
  setSelectedParent: React.Dispatch<React.SetStateAction<unknown>>;
  parentSearch: string;
  setParentSearch: React.Dispatch<React.SetStateAction<string>>;
  parentSubFilter: string;
  setParentSubFilter: React.Dispatch<React.SetStateAction<string>>;
  parentDetailTab: 'profile' | 'children' | 'bookings' | 'subscription' | 'briefings' | 'activity' | 'consent' | 'kyc';
  setParentDetailTab: React.Dispatch<React.SetStateAction<'profile' | 'children' | 'bookings' | 'subscription' | 'briefings' | 'activity' | 'consent' | 'kyc'>>;
  kycAdminAction: 'verify' | 'reject' | null;
  setKycAdminAction: React.Dispatch<React.SetStateAction<'verify' | 'reject' | null>>;
  kycRejectionReason: string;
  setKycRejectionReason: React.Dispatch<React.SetStateAction<string>>;
  kycAdminNotes: string;
  setKycAdminNotes: React.Dispatch<React.SetStateAction<string>>;
  kycActionLoading: boolean;
  setKycActionLoading: React.Dispatch<React.SetStateAction<boolean>>;
  kycActionFeedback: FeedbackResult | null;
  setKycActionFeedback: React.Dispatch<React.SetStateAction<FeedbackResult | null>>;
  consentEmailSending: boolean;
  setConsentEmailSending: React.Dispatch<React.SetStateAction<boolean>>;
  consentEmailResult: FeedbackResult | null;
  setConsentEmailResult: React.Dispatch<React.SetStateAction<FeedbackResult | null>>;
  parentActionLoading: string | null;
  setParentActionLoading: React.Dispatch<React.SetStateAction<string | null>>;
  parentActionFeedback: FeedbackResult | null;
  setParentActionFeedback: React.Dispatch<React.SetStateAction<FeedbackResult | null>>;
  parentResetPwdOpen: boolean;
  setParentResetPwdOpen: React.Dispatch<React.SetStateAction<boolean>>;
  parentResetPwdValue: string;
  setParentResetPwdValue: React.Dispatch<React.SetStateAction<string>>;
  parentNotifOpen: boolean;
  setParentNotifOpen: React.Dispatch<React.SetStateAction<boolean>>;
  parentNotifMessage: string;
  setParentNotifMessage: React.Dispatch<React.SetStateAction<string>>;
  // Student state
  selectedStudent: unknown;
  setSelectedStudent: React.Dispatch<React.SetStateAction<unknown>>;
  studentSearch: string;
  setStudentSearch: React.Dispatch<React.SetStateAction<string>>;
  studentGradeFilter: string;
  setStudentGradeFilter: React.Dispatch<React.SetStateAction<string>>;
  studentDetailTab: string;
  setStudentDetailTab: React.Dispatch<React.SetStateAction<string>>;
  studentActionFeedback: FeedbackResult | null;
  setStudentActionFeedback: React.Dispatch<React.SetStateAction<FeedbackResult | null>>;
  studentActionLoading: string | null;
  setStudentActionLoading: React.Dispatch<React.SetStateAction<string | null>>;
  studentResetPwdOpen: boolean;
  setStudentResetPwdOpen: React.Dispatch<React.SetStateAction<boolean>>;
  studentResetPwdValue: string;
  setStudentResetPwdValue: React.Dispatch<React.SetStateAction<string>>;
  studentNotifOpen: boolean;
  setStudentNotifOpen: React.Dispatch<React.SetStateAction<boolean>>;
  studentNotifMessage: string;
  setStudentNotifMessage: React.Dispatch<React.SetStateAction<string>>;
  studentRegistryExportOpen: boolean;
  setStudentRegistryExportOpen: React.Dispatch<React.SetStateAction<boolean>>;
  studentsView: string;
  setStudentsView: React.Dispatch<React.SetStateAction<string>>;
  rosterSchoolFilter: string;
  setRosterSchoolFilter: React.Dispatch<React.SetStateAction<string>>;
  rosterGradeFilter: string;
  setRosterGradeFilter: React.Dispatch<React.SetStateAction<string>>;
  rosterSearch: string;
  setRosterSearch: React.Dispatch<React.SetStateAction<string>>;
  rosterGroupBy: string;
  setRosterGroupBy: React.Dispatch<React.SetStateAction<string>>;
  rosterExportOpen: boolean;
  setRosterExportOpen: React.Dispatch<React.SetStateAction<boolean>>;
  // Institution state
  selectedInstitution: unknown;
  setSelectedInstitution: React.Dispatch<React.SetStateAction<unknown>>;
  institutionSearch: string;
  setInstitutionSearch: React.Dispatch<React.SetStateAction<string>>;
  institutionTypeFilter: string;
  setInstitutionTypeFilter: React.Dispatch<React.SetStateAction<string>>;
  institutionDetailTab: string;
  setInstitutionDetailTab: React.Dispatch<React.SetStateAction<string>>;
  assigningInstCode: string | null;
  setAssigningInstCode: React.Dispatch<React.SetStateAction<string | null>>;
  instStudentsSearch: string;
  setInstStudentsSearch: React.Dispatch<React.SetStateAction<string>>;
  instStudentsGroupBy: string;
  setInstStudentsGroupBy: React.Dispatch<React.SetStateAction<string>>;
  instAssignPlanModal: boolean;
  setInstAssignPlanModal: React.Dispatch<React.SetStateAction<boolean>>;
  instAssignMentorModal: boolean;
  setInstAssignMentorModal: React.Dispatch<React.SetStateAction<boolean>>;
  instSelectedPlanId: string | null;
  setInstSelectedPlanId: React.Dispatch<React.SetStateAction<string | null>>;
  instSelectedMentorId: number | null;
  setInstSelectedMentorId: React.Dispatch<React.SetStateAction<number | null>>;
  instMentorSlotDate: string;
  setInstMentorSlotDate: React.Dispatch<React.SetStateAction<string>>;
  // Onboarding state
  selectedOnboarding: unknown;
  setSelectedOnboarding: React.Dispatch<React.SetStateAction<unknown>>;
  onboardingSearch: string;
  setOnboardingSearch: React.Dispatch<React.SetStateAction<string>>;
  onboardingSubTab: string;
  setOnboardingSubTab: React.Dispatch<React.SetStateAction<string>>;
  selectedEnrollmentKyc: unknown;
  setSelectedEnrollmentKyc: React.Dispatch<React.SetStateAction<unknown>>;
  enrollmentKycSearchQuery: string;
  setEnrollmentKycSearchQuery: React.Dispatch<React.SetStateAction<string>>;
  kycStatusFilter: string;
  setKycStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  // Notifications state
  broadcastCategory: string;
  setBroadcastCategory: React.Dispatch<React.SetStateAction<string>>;
  broadcastTitle: string;
  setBroadcastTitle: React.Dispatch<React.SetStateAction<string>>;
  broadcastMessage: string;
  setBroadcastMessage: React.Dispatch<React.SetStateAction<string>>;
  broadcastPriority: string;
  setBroadcastPriority: React.Dispatch<React.SetStateAction<string>>;
  broadcastTargetRoles: string[];
  setBroadcastTargetRoles: React.Dispatch<React.SetStateAction<string[]>>;
  broadcastActionUrl: string;
  setBroadcastActionUrl: React.Dispatch<React.SetStateAction<string>>;
  broadcastSendEmail: boolean;
  setBroadcastSendEmail: React.Dispatch<React.SetStateAction<boolean>>;
  notifSubTab: 'broadcasts' | 'templates' | 'quicksend' | 'analytics' | 'auditlogs' | 'scenarios' | 'scheduled';
  setNotifSubTab: React.Dispatch<React.SetStateAction<'broadcasts' | 'templates' | 'quicksend' | 'analytics' | 'auditlogs' | 'scenarios' | 'scheduled'>>;
  pauseFrom: string;
  setPauseFrom: React.Dispatch<React.SetStateAction<string>>;
  pauseTo: string;
  setPauseTo: React.Dispatch<React.SetStateAction<string>>;
  templateSearch: string;
  setTemplateSearch: React.Dispatch<React.SetStateAction<string>>;
  templateCategoryFilter: string;
  setTemplateCategoryFilter: React.Dispatch<React.SetStateAction<string>>;
  templateExpandedId: number | null;
  setTemplateExpandedId: React.Dispatch<React.SetStateAction<number | null>>;
  templateDialog: TemplateDialog;
  setTemplateDialog: React.Dispatch<React.SetStateAction<TemplateDialog>>;
  templateFormData: { title: string; category: string; bodyTemplate: string; type: string; priority: string; roles: string; variables: string; actionLabel: string };
  setTemplateFormData: React.Dispatch<React.SetStateAction<{ title: string; category: string; bodyTemplate: string; type: string; priority: string; roles: string; variables: string; actionLabel: string }>>;
  templateSaving: boolean;
  setTemplateSaving: React.Dispatch<React.SetStateAction<boolean>>;
  quickSendTemplateId: string;
  setQuickSendTemplateId: React.Dispatch<React.SetStateAction<string>>;
  quickSendRecipientId: string;
  setQuickSendRecipientId: React.Dispatch<React.SetStateAction<string>>;
  quickSendContext: Record<string, string>;
  setQuickSendContext: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  quickSendSending: boolean;
  setQuickSendSending: React.Dispatch<React.SetStateAction<boolean>>;
  notifLogCategoryFilter: string;
  setNotifLogCategoryFilter: React.Dispatch<React.SetStateAction<string>>;
  notifLogTypeFilter: string;
  setNotifLogTypeFilter: React.Dispatch<React.SetStateAction<string>>;
  notifLogPriorityFilter: string;
  setNotifLogPriorityFilter: React.Dispatch<React.SetStateAction<string>>;
  notifLogExpandedId: number | null;
  setNotifLogExpandedId: React.Dispatch<React.SetStateAction<number | null>>;
  reportIncidentDialog: boolean;
  setReportIncidentDialog: React.Dispatch<React.SetStateAction<boolean>>;
  newIncidentData: { title: string; description: string; severity: string; incidentType: string };
  setNewIncidentData: React.Dispatch<React.SetStateAction<{ title: string; description: string; severity: string; incidentType: string }>>;
  // Package state
  editPackageDialog: boolean;
  setEditPackageDialog: React.Dispatch<React.SetStateAction<boolean>>;
  createPackageDialog: boolean;
  setCreatePackageDialog: React.Dispatch<React.SetStateAction<boolean>>;
  pkgWizardStep: number;
  setPkgWizardStep: React.Dispatch<React.SetStateAction<number>>;
  editPackageData: unknown;
  setEditPackageData: React.Dispatch<React.SetStateAction<unknown>>;
  deleteConfirmId: string | null;
  setDeleteConfirmId: React.Dispatch<React.SetStateAction<string | null>>;
  newPackageData: unknown;
  setNewPackageData: React.Dispatch<React.SetStateAction<unknown>>;
  newPkgCatMode: boolean;
  setNewPkgCatMode: React.Dispatch<React.SetStateAction<boolean>>;
  editPkgCatMode: boolean;
  setEditPkgCatMode: React.Dispatch<React.SetStateAction<boolean>>;
  newPkgSubCatMode: boolean;
  setNewPkgSubCatMode: React.Dispatch<React.SetStateAction<boolean>>;
  editPkgSubCatMode: boolean;
  setEditPkgSubCatMode: React.Dispatch<React.SetStateAction<boolean>>;
  // Question bank state
  psychoQuestionFilter: string;
  setPsychoQuestionFilter: React.Dispatch<React.SetStateAction<string>>;
  lbiQuestionFilter: string;
  setLbiQuestionFilter: React.Dispatch<React.SetStateAction<string>>;
  qbSubTab: 'questions' | 'blueprints';
  setQbSubTab: React.Dispatch<React.SetStateAction<'questions' | 'blueprints'>>;
  qbBoardFilter: string;
  setQbBoardFilter: React.Dispatch<React.SetStateAction<string>>;
  qbClassFilter: string;
  setQbClassFilter: React.Dispatch<React.SetStateAction<string>>;
  qbSubjectFilter: string;
  setQbSubjectFilter: React.Dispatch<React.SetStateAction<string>>;
  blueprintData: any;
  setBlueprintData: React.Dispatch<React.SetStateAction<any>>;
  generatingPaper: boolean;
  setGeneratingPaper: React.Dispatch<React.SetStateAction<boolean>>;
  generatedPaper: any;
  setGeneratedPaper: React.Dispatch<React.SetStateAction<any>>;
  questionBankQuestions: unknown[];
  refetchQuestions: () => void;
  // Booking/assignment state
  bookingSearch: string;
  setBookingSearch: React.Dispatch<React.SetStateAction<string>>;
  bookingStatusFilter: string;
  setBookingStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  showAssignDialog: boolean;
  setShowAssignDialog: React.Dispatch<React.SetStateAction<boolean>>;
  assignChildId: string | null;
  setAssignChildId: React.Dispatch<React.SetStateAction<string | null>>;
  assignPackageId: string | null;
  setAssignPackageId: React.Dispatch<React.SetStateAction<string | null>>;
  assignAgeBandFilter: string;
  setAssignAgeBandFilter: React.Dispatch<React.SetStateAction<string>>;
  assignSubTypeFilter: string;
  setAssignSubTypeFilter: React.Dispatch<React.SetStateAction<string>>;
  assignInstitutionFilter: string;
  setAssignInstitutionFilter: React.Dispatch<React.SetStateAction<string>>;
  assignStartDate: string;
  setAssignStartDate: React.Dispatch<React.SetStateAction<string>>;
  assignNotes: string;
  setAssignNotes: React.Dispatch<React.SetStateAction<string>>;
  assignSubmitting: boolean;
  setAssignSubmitting: React.Dispatch<React.SetStateAction<boolean>>;
  assignSuccess: boolean;
  setAssignSuccess: React.Dispatch<React.SetStateAction<boolean>>;
  assignConflict: string | null;
  setAssignConflict: React.Dispatch<React.SetStateAction<string | null>>;
  assignPkgSearch: string;
  setAssignPkgSearch: React.Dispatch<React.SetStateAction<string>>;
  assignMode: string;
  setAssignMode: React.Dispatch<React.SetStateAction<string>>;
  assignChildSearch: string;
  setAssignChildSearch: React.Dispatch<React.SetStateAction<string>>;
  assignPkgSort: string;
  setAssignPkgSort: React.Dispatch<React.SetStateAction<string>>;
  seedingPackages: boolean;
  setSeedingPackages: React.Dispatch<React.SetStateAction<boolean>>;
  seedingEducation: boolean;
  setSeedingEducation: React.Dispatch<React.SetStateAction<boolean>>;
  // Scoring state
  scoringSubTab: string;
  setScoringSubTab: React.Dispatch<React.SetStateAction<string>>;
  calcModule: string;
  setCalcModule: React.Dispatch<React.SetStateAction<string>>;
  calcInputs: Record<string, unknown>;
  setCalcInputs: React.Dispatch<React.SetStateAction<Record<string, unknown>>>;
  calcResult: unknown;
  setCalcResult: React.Dispatch<React.SetStateAction<unknown>>;
  expandedModule: string | null;
  setExpandedModule: React.Dispatch<React.SetStateAction<string | null>>;
  publishModalOpen: boolean;
  setPublishModalOpen: React.Dispatch<React.SetStateAction<boolean>>;
  publishChoice: string;
  setPublishChoice: React.Dispatch<React.SetStateAction<string>>;
  publishStatus: unknown;
  setPublishStatus: React.Dispatch<React.SetStateAction<unknown>>;
  configVersion: unknown;
  configApproval: unknown;
  setConfigApproval: React.Dispatch<React.SetStateAction<unknown>>;
  auditLog: unknown[];
  setAuditLog: React.Dispatch<React.SetStateAction<unknown[]>>;
  versionHistory: unknown;
  auditFilter: string;
  setAuditFilter: React.Dispatch<React.SetStateAction<string>>;
  moduleHealth: unknown;
  domainRows: unknown[];
  setDomainRows: React.Dispatch<React.SetStateAction<unknown[]>>;
  selectedProductId: string | null;
  setSelectedProductId: React.Dispatch<React.SetStateAction<string | null>>;
  productWeightConfig: unknown;
  setProductWeightConfig: React.Dispatch<React.SetStateAction<unknown>>;
  domainSaveStatus: string | null;
  setDomainSaveStatus: React.Dispatch<React.SetStateAction<string | null>>;
  normRows: unknown[];
  setNormRows: React.Dispatch<React.SetStateAction<unknown[]>>;
  normLocked: boolean;
  setNormLocked: React.Dispatch<React.SetStateAction<boolean>>;
  batchMode: boolean;
  setBatchMode: React.Dispatch<React.SetStateAction<boolean>>;
  batchCsv: string;
  setBatchCsv: React.Dispatch<React.SetStateAction<string>>;
  batchResults: unknown[];
  setBatchResults: React.Dispatch<React.SetStateAction<unknown[]>>;
  diffExpanded: boolean;
  setDiffExpanded: React.Dispatch<React.SetStateAction<boolean>>;
  importPreviewOpen: boolean;
  setImportPreviewOpen: React.Dispatch<React.SetStateAction<boolean>>;
  importPreviewData: unknown;
  setImportPreviewData: React.Dispatch<React.SetStateAction<unknown>>;
  alertRules: unknown[];
  setAlertRules: React.Dispatch<React.SetStateAction<unknown[]>>;
  formulaRows: unknown[];
  setFormulaRows: React.Dispatch<React.SetStateAction<unknown[]>>;
  scoringParams: unknown;
  setScoringParams: React.Dispatch<React.SetStateAction<unknown>>;
  scoringConfigLoaded: boolean;
  setScoringConfigLoaded: React.Dispatch<React.SetStateAction<boolean>>;
  // User management state
  studentsPage: number;
  setStudentsPage: React.Dispatch<React.SetStateAction<number>>;
  studentsRoleFilter: string;
  setStudentsRoleFilter: React.Dispatch<React.SetStateAction<string>>;
  studentsActiveFilter: string;
  setStudentsActiveFilter: React.Dispatch<React.SetStateAction<string>>;
  editUserDialog: boolean;
  setEditUserDialog: React.Dispatch<React.SetStateAction<boolean>>;
  editUserData: unknown;
  setEditUserData: React.Dispatch<React.SetStateAction<unknown>>;
  umPage: number;
  setUmPage: React.Dispatch<React.SetStateAction<number>>;
  umRoleFilter: string;
  setUmRoleFilter: React.Dispatch<React.SetStateAction<string>>;
  umStatusFilter: string;
  setUmStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  umSearch: string;
  setUmSearch: React.Dispatch<React.SetStateAction<string>>;
  umResetPwDialog: boolean;
  setUmResetPwDialog: React.Dispatch<React.SetStateAction<boolean>>;
  umNewPassword: string;
  setUmNewPassword: React.Dispatch<React.SetStateAction<string>>;
  scheduledJobStatusFilter: string;
  setScheduledJobStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  // Document state
  documentSearch: string;
  setDocumentSearch: React.Dispatch<React.SetStateAction<string>>;
  documentStatusFilter: string;
  setDocumentStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  documentEntityFilter: string;
  setDocumentEntityFilter: React.Dispatch<React.SetStateAction<string>>;
  // Settings state
  settingsSubTab: 'general' | 'security' | 'notifications' | 'integrations' | 'compliance';
  setSettingsSubTab: React.Dispatch<React.SetStateAction<'general' | 'security' | 'notifications' | 'integrations' | 'compliance'>>;
  // Query data
  stats: unknown;
  statsLoading: boolean;
  refetchStats: () => void;
  platformSettingsData: unknown[];
  refetchSettings: () => void;
  onboardingApprovals: unknown[];
  refetchOnboarding: () => void;
  entityCodes: unknown[];
  refetchCodes: () => void;
  consents: unknown[];
  refetchConsents: () => void;
  documentsData: unknown[];
  documentsLoading: boolean;
  refetchDocuments: () => void;
  auditLogs: unknown[];
  refetchAuditLogs: () => void;
  securityConfig: unknown[];
  refetchSecurityConfig: () => void;
  securityIncidents: unknown[];
  refetchSecurityIncidents: () => void;
  retentionPolicies: unknown[];
  refetchRetentionPolicies: () => void;
  accessPolicies: unknown[];
  refetchAccessPolicies: () => void;
  reconciliations: unknown[];
  refetchReconciliations: () => void;
  learningPlans: unknown[];
  refetchLearningPlans: () => void;
  behaviorData: unknown;
  refetchBehaviorData: () => void;
  psychoAgeBands: unknown[];
  refetchAgeBands: () => void;
  psychoDomains: unknown[];
  refetchDomains: () => void;
  psychoConfigs: unknown[];
  refetchConfigs: () => void;
  psychoQuestions: unknown[];
  refetchPsychoQuestions: () => void;
  lbiDomains: unknown[];
  refetchLbiDomains: () => void;
  competencyDomains: unknown[];
  refetchCompetencyDomains: () => void;
  lbiAgeBands: unknown[];
  refetchLbiAgeBands: () => void;
  lbiQuestions: unknown[];
  refetchLbiQuestions: () => void;
  lbiAdminQuestions: unknown[];
  refetchLbiAdminQ: () => void;
  lbiAdminQLoading: boolean;
  customAssessmentModules: unknown[];
  refetchCustomModules: () => void;
  lbiAdminSubdomains: unknown[];
  refetchLbiSubdomains: () => void;
  sdiDomains: unknown[];
  lbiAdminStats: unknown;
  refetchLbiStats: () => void;
  erqData: unknown;
  refetchErqData: () => void;
  examReadyData: unknown;
  refetchExamReadyData: () => void;
  subscriptionPackages: unknown[];
  refetchSubscriptionPackages: () => void;
  subscriptionStats: unknown;
  refetchSubscriptionStats: () => void;
  lbiCatalog: unknown;
  moduleScoringCatalog: unknown;
  engineStats: unknown;
  assessmentProducts: unknown[];
  refetchProducts: () => void;
  adminSubscriptions: unknown[];
  refetchAdminSubscriptions: () => void;
  childrenList: unknown[];
  assignChildActiveSubs: unknown[];
  jobs: unknown[];
  refetchJobs: () => void;
  mentors: unknown[];
  refetchMentors: () => void;
  mentorKpis: unknown;
  mentorTasks: unknown[];
  refetchMentorTasks: () => void;
  mentorPayouts: unknown[];
  mentorViolations: unknown[];
  refetchMentorViolations: () => void;
  mentorBookings: unknown[];
  refetchMentorBookings: () => void;
  mentorReviewsData: unknown;
  refetchMentorReviews: () => void;
  mentorOnboarding: unknown[];
  refetchMentorOnboarding: () => void;
  mentorPlatformStats: unknown;
  refetchMentorPlatformStats: () => void;
  mentorAllSessions: unknown[];
  refetchMentorAllSessions: () => void;
  mentorLeaderboard: unknown[];
  refetchMentorLeaderboard: () => void;
  parents: unknown[];
  refetchParents: () => void;
  loadingParents: boolean;
  parentChildren: unknown[];
  refetchParentChildren: () => void;
  parentBriefings: unknown[];
  refetchParentBriefings: () => void;
  parentSubscription: unknown;
  refetchParentSubscription: () => void;
  parentActivity: unknown[];
  refetchParentActivity: () => void;
  parentBookings: unknown[];
  refetchParentBookings: () => void;
  parentKyc: unknown;
  refetchParentKyc: () => void;
  studentsList: unknown[];
  refetchStudents: () => void;
  loadingStudents: boolean;
  classRosterRaw: unknown[];
  refetchClassRoster: () => void;
  loadingClassRoster: boolean;
  studentWellness: unknown;
  refetchStudentWellness: () => void;
  studentLbi: unknown;
  refetchStudentLbi: () => void;
  studentBookings: unknown[];
  refetchStudentBookings: () => void;
  studentSubscription: unknown;
  refetchStudentSub: () => void;
  selectedStudentDetail: unknown;
  institutionsList: unknown[];
  refetchInstitutions: () => void;
  loadingInstitutions: boolean;
  instStudentsData: unknown[];
  refetchInstStudents: () => void;
  instMentorsList: unknown[];
  instPlansList: unknown[];
  applications: unknown[];
  refetchApplications: () => void;
  transactions: unknown[];
  refetchTransactions: () => void;
  financialStats: unknown;
  institutes: unknown[];
  usersData: unknown[];
  studentsData: unknown[];
  studentsLoading: boolean;
  refetchStudentsLegacy: () => void;
  umData: unknown[];
  umLoading: boolean;
  refetchUm: () => void;
  onboardingStats: unknown;
  kycDocuments: unknown[];
  refetchKyc: () => void;
  studentEnrollments: unknown[];
  refetchEnrollments: () => void;
  enrollmentKycList: unknown[];
  refetchEnrollmentKyc: () => void;
  mentorPipelineList: unknown[];
  refetchMentorPipeline: () => void;
  // Mutations
  approveOnboardingMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  makerVerifyKycMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  checkerApproveKycMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  rejectKycMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  rejectOnboardingMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  verifyDocumentsMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  verifyKycMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  suspendOnboardingMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  reinstateOnboardingMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  generateCodeMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  revokeCodeMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  activateMentorMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  suspendMentorMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  warnMentorMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  reactivateMentorMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  advanceOnboardingStageMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  assignTaskMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  reportViolationMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  updatePhiMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  approveJobMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  createJobMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  submitJobMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  approveJobStageMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  publishJobMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  closeJobMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  rejectJobMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  shortlistApplicationMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  rejectApplicationMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  advanceApplicationMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  processPayoutMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  toggleScenarioMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  deleteScenarioMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  cancelScheduledJobMutation: UseMutationResult<unknown, unknown, unknown, unknown>;
  // Utilities
  toast: (opts: { title: string; description?: string; variant?: string }) => void;
  queryClient: QueryClient;
  saveScoringDomains: () => void;
  saveScoringNorms: () => void;
  saveScoringParams: () => void;
  saveScoringModules: () => void;
  updateSetting: (key: string, value: string, type?: string, category?: string, description?: string) => Promise<void>;
  seedDefaultSettings: () => Promise<void>;
  handleLogout: () => Promise<void>;
  getSettingValue: (key: string, defaultValue?: string) => string;
  getSettingBool: (key: string, defaultValue?: boolean) => boolean;
  BRAND: BrandConfig;
  formatDate: (d?: string | null) => string;
  formatDateTime: (d?: string | null) => string;
  formatCurrency: (amount: number | string | null) => string;
  getStatusBadge: (status: string) => React.ReactElement;
  formatEntityType: (type?: string) => string;
  // Navigation
  navGroups: { label: string | null; items: { id: string; icon: React.ElementType; label: string; external?: boolean; badge?: number; badgeColor?: string }[]; isLabs?: boolean }[];
  menuItems: { id: string; icon: React.ElementType; label: string; external?: boolean; badge?: number; badgeColor?: string }[];
  labsOpen: boolean;
  setLabsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  // Dialog state (used by AdminDialogs)
  domainFormData: { domain_code: string; domain_name: string; description: string; sort_order: number; is_active: boolean };
  setDomainFormData: React.Dispatch<React.SetStateAction<{ domain_code: string; domain_name: string; description: string; sort_order: number; is_active: boolean }>>;
  domainSaving: boolean;
  setDomainSaving: React.Dispatch<React.SetStateAction<boolean>>;
  domainDeleting: boolean;
  setDomainDeleting: React.Dispatch<React.SetStateAction<boolean>>;
  compDomainFormData: { name: string; description: string; sort_order: number; is_active: boolean };
  setCompDomainFormData: React.Dispatch<React.SetStateAction<{ name: string; description: string; sort_order: number; is_active: boolean }>>;
  compDomainSaving: boolean;
  setCompDomainSaving: React.Dispatch<React.SetStateAction<boolean>>;
  compDomainDeleting: boolean;
  setCompDomainDeleting: React.Dispatch<React.SetStateAction<boolean>>;
  lbiQFormData: Record<string, unknown>;
  setLbiQFormData: React.Dispatch<React.SetStateAction<Record<string, unknown>>>;
  lbiQSaving: boolean;
  setLbiQSaving: React.Dispatch<React.SetStateAction<boolean>>;
  sendingDocRequest: boolean;
  setSendingDocRequest: React.Dispatch<React.SetStateAction<boolean>>;
  importDialog: boolean;
  setImportDialog: React.Dispatch<React.SetStateAction<boolean>>;
  importFile: File | null;
  setImportFile: React.Dispatch<React.SetStateAction<File | null>>;
  importLoading: boolean;
  setImportLoading: React.Dispatch<React.SetStateAction<boolean>>;
  importResult: Record<string, unknown> | null;
  setImportResult: React.Dispatch<React.SetStateAction<Record<string, unknown> | null>>;
}

export const AdminDashboardContext = createContext<AdminDashboardContextValue | null>(null);

export function useAdminDashboard(): AdminDashboardContextValue {
  const ctx = useContext(AdminDashboardContext);
  if (!ctx) throw new Error('useAdminDashboard must be used within AdminDashboardContext.Provider');
  return ctx;
}
